import { ContentFlag, EditorialReference, EditorialSectionValue, VetSpecies } from './common';

export interface DiseaseRecord extends ContentFlag {
  id: string;
  slug: string;
  title: string;
  synonyms: string[];
  species: VetSpecies[];
  category: string;
  tags: string[];
  quickSummary: string;
  thirtySecondView?: string[];
  doNotForget?: string[];
  whenToSuspect?: string[];
  initialConduct?: string[];
  highYieldTests?: string[];
  dogVsCatDifferences?: string[];
  commonMistakes?: string[];
  redFlags: string[];
  clinicalPearls: string[];
  introduction: EditorialSectionValue;
  etiology: EditorialSectionValue;
  transmission: EditorialSectionValue;
  pathophysiology: EditorialSectionValue;
  epidemiology: EditorialSectionValue;
  clinicalPresentation: EditorialSectionValue;
  physicalExam: EditorialSectionValue;
  differentialDiagnoses: EditorialSectionValue;
  diagnostics: EditorialSectionValue;
  diagnosticApproach: EditorialSectionValue;
  treatment: EditorialSectionValue;
  prognosis: EditorialSectionValue;
  complications: EditorialSectionValue;
  prevention: EditorialSectionValue;
  relatedConsensusSlugs: string[];
  relatedMedicationSlugs: string[];
  references?: EditorialReference[];
  isPublished?: boolean;
  createdAt?: string;
  updatedAt?: string;
}
