export const DOG_BREEDS_BR = [
  'Akita Inu',
  'American Bully',
  'Australian Shepherd',
  'Basset Hound',
  'Beagle',
  'Border Collie',
  'Boston Terrier',
  'Boxer',
  'Bulldog Francês',
  'Bulldog Inglês',
  'Cane Corso',
  'Chihuahua',
  'Cocker Spaniel Inglês',
  'Collie',
  'Dachshund',
  'Dobermann',
  'Golden Retriever',
  'Husky Siberiano',
  'Jack Russell Terrier',
  'Labrador Retriever',
  'Lhasa Apso',
  'Maltês',
  'Pastor Alemão',
  'Pinscher',
  'Pit Bull Terrier Americano',
  'Poodle',
  'Pug',
  'Rottweiler',
  'Samoieda',
  'Schnauzer Miniatura',
  'Shih Tzu',
  'Spitz Alemão',
  'SRD (Vira-lata)',
  'Weimaraner',
  'Yorkshire Terrier',
];

export const CAT_BREEDS_BR = [
  'Abissínio',
  'Angorá',
  'Bengal',
  'Birmanês',
  'British Shorthair',
  'Burmese',
  'Devon Rex',
  'Exótico',
  'Himalaio',
  'Maine Coon',
  'Norueguês da Floresta',
  'Oriental Shorthair',
  'Persa',
  'Ragdoll',
  'Russian Blue',
  'Savannah',
  'Scottish Fold',
  'Siamês',
  'Sphynx',
  'SRD (Sem raça definida)',
];
