/**
 * Ordem sugerida para subseções de diagnóstico: raciocínio e plano antes;
 * exames da triagem aos mais confirmatórios; recursos limitados por último.
 */
export const DIAGNOSTIC_SUBSECTION_PRIORITY: string[] = [
  'drcAlertaEstadiamentoIRIS',
  'drcFiguraIrisStaging',
  'drcCronicoVersusAgudo',
  'drcPacoteInvestigacao',
  'drcTabelaComparativaEspecies',
  'drcPressaoSubstadiamento',
  'drcEstadiamentoPassos',
  'drcExamesLaboratoriaisContexto',
  'tabelaClassificacaoExposicaoInfeccao',
  'fundamentosDiagnosticoLCan',
  'citologiaFormasAmastigotas',
  'testesMolecularesPcr',
  'sorologiaEInterpretacao',
  'cmeSuspeitaClinica',
  'cmeTabelaFasesSinaisLab',
  'cmeEsfregacoSangue',
  'cmeSorologiaInterpretacao',
  'cmePcrSangueMedula',
  'cmeDiagnosticoIntegrado',
  'tcHistoriaEFisico',
  'tcBancoMinimo',
  'tcRadiografia',
  'tcFluoroscopia',
  'tcTraqueoBroncoscopia',
  'tcTomografia',
  'tcLavadoCultura',
  'tcTabelaGrauACVS',
  'tcTabelaComplicacoesStent2024',
  'tcDiagnosticosDiferenciais',
  'hemoSuspeitaContexto',
  'hemoHemogramaEsfregaco',
  'hemoPcrPreferido',
  'hemoCoinfeccoesBase',
  'hemoPadraoOuroResumo',
  'hemoTabelaDoxiciclinaGatoAlerta',
  'teachingOverview',
  'diagnosticReasoning',
  'conceitosTestes',
  'tabelaDesempenho',
  'aplicacaoPratica',
  'planoDiagnostico',
  'pathophysiologyExplanation',
  'clinicalSuspicion',
  'summary',
  'overview',
  'description',
  'background',
  'definition',
  'diagnosticPlanStepByStep',
  'firstLineTests',
  'idealTests',
  'mostSensitiveTests',
  'mostSpecificTests',
  'confirmatoryTests',
  'interpretation',
  'limitations',
  'falsePositiveConsiderations',
  'falseNegativeConsiderations',
  'ancillaryTests',
  'laboratoryFindings',
  'laboratory',
  'laboratoryTests',
  'examesLaboratoriais',
  'imagingFindings',
  'imaging',
  'imagingStudies',
  'examesDeImagem',
  'advancedImaging',
  'endoscopy',
  'biopsy',
  'cytology',
  'histopathology',
  'microbiology',
  'molecularTests',
  'serology',
  'culture',
  'monitoringLabs',
  'minimumDatabase',
  'workup',
  'diagnosticPlanIfLimitedResources',
  'drugProtocolExamples',
  'abordagemDiagnostica',
  'examesEConfirmacao',
  /* DMVD / MMVD — plano → ausculta → eco → estádio → B2 → RX → ECG → laboratório → tosse → diferenciais → seguimento */
  'dmvdClinicaAusculta',
  'dmvdEcocardiografiaPadraoOuro',
  'dmvdEstadiamentoAcvimTabela',
  'tabelaLeituraRapidaECG',
  'figuraNaoTrateEcg',
  'holterIndicacoes',
  'figuraHolterGatosSaudaveis',
  'arrAtualizacao2026Gatos',
  /* Giardíase — apresentação → plano → métodos → diferenciais */
  'apresentacaoClinicaTabela',
  'figuraApresentacaoClinica',
  'algoritmoDiagnostico',
  'figuraFluxogramaDiagnostico',
  'tabelaDiagnosticosCompleta',
  'tabelaDesempenhoBarrera2024',
  'tabelaComparacaoGiardiaTritrichomonas',
  'sensibilidadeEspecificidadeDidatica',
  'giardiaVsTritrichomonasGatos',
  /* Cistoisosporose — gravidade → interpretação → morfologia → diferenciais → figuras */
  'classificacaoGravidadeOperacional',
  'matrizInterpretacaoCopro',
  'tabelaMorfologiaOocistos',
  'tabelaComparacaoEimeria',
  'diferenciaisCao',
  'diferenciaisGato',
  'figuraAttia2024',
  'figuraFerreira2019',
  'figuraFluxogramaTerapeutico',
  /* Hiperparatireoidismo — classificação → laboratório → imagem */
  'matrizInterpretacaoPth',
  'figuraCardInterpretacaoPth',
  'figuraFluxogramaPrincipal',
  'figuraFluxogramaHipercalcemia',
  'tabelaPadroesLaboratoriais',
  'tabelaAlvosFosforoIrisCao',
  'tabelaAlvosFosforoIrisGato',
  'jornadaDiagnosticaPhpt',
  'ultrassomParatireoides',
  'ctParatireoides',
  'figuraRubberJaw',
  'diferenciaisHipercalcemiaCao',
  'diferenciaisHipercalcemiaGato',
  'tabelaJornadaDiagnostica',
  /* Insulinoma — decisão → alertas → estadiamento → imagem */
  'tabelaDecisaoClinicaRapida',
  'alertaRelacaoInsulinaGlicose',
  'alertaInsulinaNormalHipoglicemia',
  'alertaInsulinaAbsolutaEstadiamento',
  'seloEvidenciaFelinaLimitada',
  'limitacaoTomografia',
  'tabelaEstadiamentoTNM',
  'figuraSinaisClinicos',
  'figuraPredisposicaoRacial',
  'diferenciaisHipoglicemia',
  /* CAD — classificação → alertas BHB → plano → gatilhos */
  'tabelaComparativaEntidades',
  'alertaEdkaSglT2_2026',
  'alertaBhbPreferencial',
  'alertaCetonuriaArmadilha',
  'tabelaBhbCutoffs',
  'jornadaDiagnostica',
  'ecgQualidade',
  'dmvdCriteriosB2Tabela',
  'dmvdRadiografiaTorax',
  'dmvdRadiografiaToraxNormalVsCardiomegalia',
  'dmvdEletrocardiograma',
  'dmvdBiomarcadoresLaboratorio',
  'dmvdTosseCardiacaVsRespiratoria',
  'dmvdDiferenciaisDiagnosticos',
  'dmvdSeguimentoMonitorizacao',
];

export function sortDiagnosticSubsectionEntries(entries: [string, unknown][]): [string, unknown][] {
  return [...entries].sort(([a], [b]) => {
    const ia = DIAGNOSTIC_SUBSECTION_PRIORITY.indexOf(a);
    const ib = DIAGNOSTIC_SUBSECTION_PRIORITY.indexOf(b);
    if (ia === -1 && ib === -1) return a.localeCompare(b);
    if (ia === -1) return 1;
    if (ib === -1) return -1;
    return ia - ib;
  });
}
