/**
 * Tradução de chaves técnicas em inglês (JSON editorial) para títulos em português na interface.
 */

const FULL_KEY_LABELS: Record<string, string> = {
  consequenciasSistemicas: 'Consequências sistêmicas',
  classificacaoAnatomica: 'Mapa anatômico e dinâmica respiratória',
  fatoresAgravantes: 'Fatores que agravam ou precipitam sinais',
  limitesDoConceito: 'O que não deve ser confundido',
  perfilClassico: 'Perfil mais frequente',
  evidenciaRecente: 'O que os estudos recentes acrescentam',
  notaSobreGatos: 'Nota sobre gatos',
  cascataMecanica: 'Ciclo mecânico tosse–inflamação–colapso',
  pontoChave: 'Ponto-chave',
  mecanicaRespiratoria: 'Mecânica respiratória',
  gatilhosComuns: 'Gatilhos comuns',
  diagnosticosDiferenciais: 'Diagnósticos diferenciais',
  graduacaoEndoscopica: 'Graduação anatômica tradicional',
  interpretacaoIntegrada: 'Como interpretar o grau',
  terapiaFarmacologica: 'Princípios da terapia farmacológica',
  protocolosCriseObstrutiva: 'Crise obstrutiva — estabilização medicamentosa',
  protocolosAmbulatoriais: 'Tosse e inflamação — protocolos ambulatoriais',
  adjuvantesViasAereasInferiores: 'Doença de vias aéreas inferiores — adjuvantes selecionados',
  planoDeReavaliacao: 'Quando reavaliar',
  evidenciaCorticoideInalatorio: 'Evidência para corticosteroide inalatório',
  criteriosIntervencao: 'Quando discutir intervenção',
  oQueEvitar: 'Condutas a evitar',
  doencaNatural: 'Complicações da doença',
  aposStent: 'Complicações após stent',
  leituraDaEvidencia: 'Como interpretar as estimativas',
  prevencaoPrimaria: 'O que é possível prevenir',
  planoDomiciliar: 'Plano domiciliar',
  sinaisDeUrgencia: 'Quando procurar emergência',
  felinaIatrogenica: 'Hipotireoidismo iatrogênico felino',
  cmdControversa: 'Associação com CMD — controversa',
  notaCaudaRato: 'Cauda de rato (alopecia caudal)',
  tabelaCombinacaoDiagnostica: 'Combinação TT4 / fT4ED / cTSH',
  evidenciaBeierCMD: 'Evidência — hipotireoidismo e CMD',
  sdmaRenal: 'SDMA e função renal',
  giGori: 'Manifestações gastrointestinais',
  levotiroxinaCao: 'Levotiroxina — cão',
  levotiroxinaGato: 'Levotiroxina — gato',
  iatrogenicaFelina: 'Prevenção iatrogênica felina',
  goitrosoVsNaoGoitroso: 'Goitroso vs não goitroso',
  figuraGoitroso: 'Formas goitrosa e não goitrosa',
  evidenciaAbitbolRottweiler: 'Evidência genética — Rottweiler 2026',
  vanPouckeFelino: 'Mutações TPO em gatos',
  cretinismoHistorico: 'Sinônimo histórico (cretinismo)',
  tabelaNanismoHipofisario: 'Nanismo hipofisário vs hipotireoidismo congênito',
  tabelaDiferencialNanismo: 'Diagnósticos diferenciais de nanismo',
  tabelaRadiografia: 'Achados radiográficos',
  golinelliNota: 'Nota sobre dose de cohort (Golinelli)',
  perfil: 'Perfil do paciente',
  racas: 'Raças e particularidades',
  felinos: 'Particularidades em gatos',
  primaria: 'Forma primária',
  secundaria: 'Causas secundárias',
  rara: 'Causas raras',
  eixo: 'Eixo tireoidiano e efeitos sistêmicos',
  ntis: 'Síndrome da doença não tireoidiana (NTIS)',
  principio: 'Princípio diagnóstico',
  testes: 'Como interpretar os exames',
  desempenho: 'Desempenho diagnóstico publicado',
  conceitosTestes: 'Sensibilidade, especificidade e valores preditivos',
  tabelaDesempenho: 'Desempenho publicado dos testes na PIF',
  aplicacaoPratica: 'Probabilidade pré-teste e pós-teste na prática',
  valorPreditivoPositivo: 'Valor preditivo positivo (VPP)',
  valorPreditivoNegativo: 'Valor preditivo negativo (VPN)',
  probabilidadePreTeste: 'Probabilidade pré-teste',
  tabelaTLICao: 'Interpretação do cTLI (cão)',
  tabelaTLIGato: 'Interpretação do fTLI (gato)',
  tabelaSinaisFelinos: 'Sinais clínicos felinos (150 casos)',
  paa: 'Atrofia acinar pancreática (PAA)',
  pancreatiteCronicaTerminal: 'Pancreatite crônica terminal',
  reservaFuncional: 'Reserva funcional pancreática',
  fatorIntrinseco: 'Fator intrínseco e cobalamina',
  disbiose: 'Disbiose intestinal',
  cobalamin: 'Cobalamina (vitamina B12)',
  pert: 'Reposição enzimática (PERT)',
  algoritmoFalha: 'Algoritmo de falha terapêutica',
  antibioticoRefratario: 'Antibiótico em casos refratários',
  omeprazolRefratario: 'Omeprazol em refratários',
  ipeDiabetes: 'IPE + diabetes mellitus',
  paaBreeding: 'Reprodução e raças predispostas',
  subclinicoNoAutoPert: 'IPE subclínica — conduta',
  aaHaCategorias: 'Decisão clínica por cenário',
  interferentes: 'Doenças e medicamentos interferentes',
  imagem: 'Quando utilizar exames de imagem',
  levotiroxina: 'Levotiroxina: dose e administração',
  resposta: 'Resposta esperada ao tratamento',
  comaMixedematoso: 'Coma mixedematoso: emergência',
  iatrogenica: 'Prevenção de causas iatrogênicas',
  sobrediagnostico: 'Como evitar o sobrediagnóstico',
  fatoresAmbientais: 'Fatores ambientais e dietéticos',
  imunomodulacao: 'Imunomodulação de base',
  especifica: 'Terapia específica',
  figurasHemorragicas: 'Figuras — sinais hemorrágicos',
  passosDiagnosticos: 'Plano diagnóstico passo a passo',
  portador: 'Portador assintomático',
  maligna: 'Forma maligna',
  mecanismoImune: 'Mecanismo imunomediado',
  genetica: 'Predisposição genética',
  dieta: 'Dieta e causas nutricionais',
  caes: 'Particularidades em cães',
  gatos: 'Particularidades em gatos',
  prognostico: 'Fatores prognósticos',
  preclinica: 'Doença pré-clínica',
  aguda: 'Descompensação aguda',
  cronica: 'Tratamento de longo prazo',
  manutencao: 'Manutenção e prevenção',
  nutricional: 'Prevenção nutricional',
  hormonal: 'Influência hormonal',
  molecular: 'Alterações moleculares',
  localizacao: 'Distribuição das lesões',
  especie: 'Diferenças entre cães e gatos',
  exameClinico: 'Exame clínico e mapeamento das massas',
  citologia: 'Citologia: utilidade e limites',
  histopatologia: 'Histopatologia: diagnóstico definitivo',
  estadiamentoTnm: 'Estadiamento TNM',
  linfonodoSentinela: 'Linfonodo sentinela',
  padraoOuro: 'Padrão ouro diagnóstico',
  cirurgia: 'Planejamento cirúrgico',
  quimioterapia: 'Quimioterapia adjuvante',
  carcinomaInflamatorio: 'Carcinoma mamário inflamatório',
  suporte: 'Tratamento de suporte',
  novidades: 'Evidências e estratégias recentes',
  castracao: 'Castragem e redução de risco',
  manejo: 'Manejo preventivo',
  deteccao: 'Detecção precoce',
  agentes: 'Agentes bacterianos mais prováveis',
  vias: 'Como a infecção alcança a glândula',
  culturaNormal: 'Bactérias no leite de animais saudáveis',
  periodo: 'Período de maior risco',
  risco: 'Fatores de risco',
  recorrencia: 'Risco de recorrência',
  neonatos: 'Impacto sobre os filhotes',
  contagio: 'Risco de transmissão',
  suporteLocal: 'Cuidados locais e drenagem',
  analgesia: 'Controle da dor',
  lactacao: 'Manejo da lactação e dos filhotes',
  antibiotico: 'Uso responsável de antimicrobianos',
  hipoteses: 'Mecanismos propostos',
  classificacao: 'Classificação do fenótipo',
  apresentacao: 'Forma de apresentação',
  mecanismo: 'Mecanismo hemodinâmico',
  congestao: 'Controle da congestão',
  trombose: 'Prevenção de tromboembolismo',
  arritmia: 'Controle de arritmias',
  obstrucao: 'Obstrução dinâmica da via de saída',
  desfechos: 'Complicações e desfechos',
  prioridades: 'Prioridades terapêuticas',
  alertas: 'Alertas de segurança',
  tutor: 'Orientações ao tutor',
  visaoGeral: 'Visão geral',
  fatores: 'Fatores participantes',
  especiePrincipal: 'Espécie principal',
  notaFelinos: 'Nota sobre felinos',
  contextoGeografico: 'Contexto geográfico',
  patogenese: 'Patogênese',
  infiltrado: 'Infiltrado inflamatório',
  transmissao: 'Transmissão',
  ordemDePrioridade: 'Ordem de prioridade',
  ordemDePrioridadeEstruturada: 'Ordem de prioridade',
  protocoloTerapeutico: 'Protocolo terapêutico — doses de referência',
  farmacos: 'Fármacos — tabela de referência (DMVD / ICC)',
  conceitoEixoHPA: 'Conceito: eixo HPA',
  comparacaoTiposHAC: 'Comparação dos tipos de hiperadrenocorticismo',
  formasNoCaes: 'Formas no cão',
  formasNosGatos: 'Formas no gato',
  especiesCaes: 'Cães',
  especiesGatos: 'Gatos',
  patogenesePDH: 'Patogênese — PDH',
  patogeneseADH: 'Patogênese — ADH',
  patogeneseIatrogenica: 'Patogênese — iatrogênica',
  decisaoInicial: 'Decisão: tratar, operar ou encaminhar',
  trilostanoNoCao: 'Trilostano (cão)',
  mitotanoNoCao: 'Mitotano (cão)',
  cetoconazolNoCao: 'Cetoconazol (cão)',
  cirurgiaEspecializada: 'Cirurgia e terapias especializadas',
  tratamentoFelino: 'Tratamento no gato',
  iatrogenicoManejo: 'Hiperadrenocorticismo iatrogênico',
  prognosticoResumo: 'Prognóstico',
  cushDiagnosticoAbordagem: 'Abordagem Diagnóstica do Cushing',
  cushDiagnosticoTriagem: 'Testes de Triagem (LDDST, ACTH, UCCR)',
  cushDiagnosticoDiferenciacao: 'Testes de Diferenciação (PDH vs. ADH)',
  cushFiguraFrenchieAbdomen: 'Abdômen Penduloso',
  cushFiguraAlopeciaAbdomen: 'Abdômen Penduloso e Alopecia Simétrica Bilateral',
  cushFiguraAdrenalNormal: 'Ultrassonografia — adrenal normal de cão',
  cushFiguraAdrenalAumentada: 'Ultrassonografia — adrenal aumentada (Cushing)',
  figuraEixoHPA: 'Eixo hipotálamo–hipófise–adrenal (HPA)',
  figuraHipofisectomia: 'MRI — planejamento de hipofisectomia',
  figuraPeleFragil: 'Fragilidade cutânea felina',
  figuraCtPituitaria: 'TC — massa hipofisária',
  figuraLaceracaoExtensa: 'Laceração extensa por pele frágil',
  classificacaoALIVE: 'Classificação ALIVE — formas de Síndrome de Cushing',
  eixoHPA: 'Eixo hipotálamo–hipófise–adrenal (HPA)',
  mucoceleAssociacao: 'Associação com mucocele biliar',
  renalProteinuria: 'Proteinúria glomerular',
  coagulacao: 'Hipercoagulabilidade',
  tabelaCushingClinicalScore: 'Cushing Clinical Score (ALIVE)',
  washout: 'Período de washout de glicocorticoides',
  selegilinaCetoconazol: 'Selegilina e cetoconazol — não rotina',
  metaAnalise2025: 'Meta-análise 2025 — trilostano vs mitotano',
  deteccaoPrecoce: 'Detecção precoce e triagem',
  abordagem: 'Abordagem diagnóstica',
  trilostano: 'Trilostano',
  mitotano: 'Mitotano',
  iatrogenico: 'Síndrome de Cushing iatrogênica',
  tabelaComparacaoCaoGato: 'Comparação cão vs gato',
  progesterona: 'Secreção de progesterona e esteroides atípicos',
  peleFragil: 'Fragilidade cutânea',
  subdiagnostico: 'Síndrome de Cushing subdiagnóstica',
  raridade: 'Frequência e raridade',
  coorteMiceli: 'Coorte Miceli et al. (2022) — 43 gatos',
  farmacovigilancia: 'Farmacovigilância emergente',
  radioterapia: 'Radioterapia de macroadenoma',
  adrenalectomia: 'Adrenalectomia',
  hepatico: 'Alterações hepáticas',
  dermatologico: 'Manifestações dermatológicas',
  renal: 'Alterações renais e urinárias',
  diabetes: 'Diabetes mellitus concomitante',
  cushFiguraCarcinomaAdrenal: 'Ultrassonografia — carcinoma de adrenal',
  sinaisPorSistema: 'Manifestações Clínicas por Sistemas',
  hiperFiguraFollicularCell: 'Fisiologia: Síntese e Liberação de T3 e T4 na Célula Folicular',
  hiperFiguraPalpacaoTireoide: 'Exame Físico: Palpação da Tireoide (Bócio Felino)',
  cmeTecnicaNorsworthy: 'Técnica de Palpação de Norsworthy',
  hiperFiguraNorsworthy: 'Técnica de Norsworthy (Exame Físico)',
  hiperFiguraScintigraphy: 'Cintilografia Tireoidiana: Padrões de Hipertireoidismo',
  hiperFiguraScintigraphyEctopic: 'Cintilografia Tireoidiana: Hiperplasia vs. Tecido Ectópico',

  tcFiguraCirurgiaImplante: 'Implante Traqueal Extraluminal (Transoperatório e Pós-operatório)',
  notaCaninos: 'Nota sobre cães',
  visaoGeralFenotipoFinal: 'Visão geral — fenótipo histológico final',
  causasEmCaes: 'Causas em cães',
  causasEmGatos: 'Causas em gatos',
  principaisCausasCaes: 'Principais causas de HAS em cães',
  principaisCausasGatos: 'Principais causas de HAS em gatos',
  perfilFelino: 'Perfil felino',
  perfilCanino: 'Perfil canino',
  naoContagiosa: 'Não contagiosa',
  duracaoMinima: 'Duração mínima (critério de cronicidade)',
  perdaNefronsHiperfiltracao: 'Perda de néfrons e hiperfiltração',
  perdaConcentracaoUrina: 'Perda da concentração urinária',
  retencaoUremica: 'Retenção de solutos urêmicos',
  fosforoMineralBone: 'Fósforo e metabolismo mineral ósseo',
  acidoseAnemiaHipertensao: 'Acidose, anemia e hipertensão',
  drcAlertaEstadiamentoIRIS: 'Estadiamento IRIS — só com paciente estável',
  drcFiguraIrisStaging: 'Imagem clínica — ultrassom contrastado em DRC felina',
  drcCronicoVersusAgudo: 'Crônico versus agudo — indícios rápidos',
  drcPacoteInvestigacao: 'Pacote inicial de investigação',
  drcTabelaComparativaEspecies: 'Comparação cão versus gato (destaques)',
  drcPressaoSubstadiamento: 'Pressão arterial e substadiamento IRIS',
  drcEstadiamentoPassos: 'Passos práticos de estadiamento',
  drcExamesLaboratoriaisContexto: 'Laboratório e urinálise — contexto',
  drcAlertaEstadiamentoInstavel: 'Antes de tratar: estabilidade e volume',
  drcDietaRenal: 'Dieta renal',
  drcFosforoQuelantes: 'Quelantes de fósforo — doses de referência',
  drcMetasFosforoIRIS: 'Metas de fósforo por estádio',
  drcCondutaPraticaPorEstagioEspecie: 'Conduta prática por estágio e espécie',
  drcProteinuriaRaas: 'Proteinúria — IECA e ARB',
  drcHipertensao: 'Hipertensão sistêmica',
  drcSintomasUremicos: 'Sintomas urêmicos e apetite',
  drcHipocalemiaAcidose: 'Potássio e acidose metabólica',
  drcAnemia: 'Anemia da DRC — eritropoiese',
  drcSuplementacaoFerro: 'Suplementação de ferro',
  drcFluidoterapiaSc: 'Fluidoterapia subcutânea',
  drcNutricaoAssistida: 'Nutrição assistida e sondas',
  drcCalcitriol: 'Calcitriol — nota por espécie',
  drcUtiOculta: 'Infecção urinária subclínica',
  drcTabelaPrognosticoFelino: 'Prognóstico — dados em gatos (exemplo publicado)',
  especiesNasAmericas: 'Espécies nas Américas',
  focoCaninoEgatos: 'Foco da diretriz e nota felina',
  distribuicaoAmericas: 'Distribuição nas Américas',
  magnitudesEVariacao: 'Magnitudes e variação regional',
  saudePublicaInterface: 'Saúde pública e One Health',
  cicloVetorEMacrófago: 'Ciclo no vetor e no hospedeiro',
  viasSecundariasTransmissao: 'Vias secundárias de transmissão',
  patogeneseParasitaEImunidade: 'Patogênese: parasita + imunidade',
  principiosFarmacologicosLCan: 'Classes terapêuticas (Brasileish)',
  objetivoTerapeuticoLCan: 'Objetivo terapêutico realista',
  miltefosina: 'Miltefosina',
  marbofloxacina: 'Marbofloxacina',
  alopurinol: 'Alopurinol',
  domperidona: 'Domperidona',
  estadiamentoClinicoBrasileish: 'Estadiamento clínico (I–VI)',
  tabelaClassificacaoExposicaoInfeccao: 'Tabela 1 — Classificação (exposição, infecção, doença)',
  fundamentosDiagnosticoLCan: 'Fundamentos do diagnóstico',
  citologiaFormasAmastigotas: 'Citologia (amastigotas)',
  testesMolecularesPcr: 'PCR e testes moleculares',
  sorologiaEInterpretacao: 'Sorologia e interpretação de títulos',
  visaoGeralLeishmanioses: 'Leishmaniose visceral e formas clínicas',
  especiesAgentesAmericas: 'Espécies de Leishmania nas Américas',
  cicloVetorialFlebotomineos: 'Ciclo no vetor (flebotomíneos)',
  transmissaoSecundariaCaes: 'Transmissão secundária em cães',
  distribuicaoMundialEAmericas: 'Distribuição nas Américas e no mundo',
  leishmanioseNoBrasil: 'Situação no Brasil',
  prevalenciaIncidencia: 'Prevalência e incidência',
  imunopatogeneseEOrganos: 'Imunopatogênese e órgãos-alvo',
  formasClinicasDidaticas: 'Formas clínicas (didática)',
  transmissaoResumo: 'Vias de transmissão (resumo)',
  arquiteturaTerapeuticaTresClasses: 'Classes terapêuticas (leishmanicida, estático, imunomodulador)',
  farmacosRegistradosBrasil: 'Fármacos registrados no Brasil (ANVISA)',
  tabelaFarmacosBrasil2025: 'Tabela 2 — Doses e efeitos adversos (Brasil)',
  alopurinolImunomoduladoresECorticoides: 'Alopurinol, imunomoduladores e corticoides',
  notasRodapeEstadiamento: 'Notas ao estadiamento (RPC, IRIS, confirmação)',
  tabelaMonitoramentoBrasileish4: 'Tabela 4 — Monitoramento (doente vs. infectado sadio)',
  notasMonitoramento: 'Monitoramento por imagem e urinálise',
  principiosPrevencao: 'Princípios de prevenção',
  produtosRegistradosEvidenciaCampo: 'Produtos e evidência de campo',
  tabelaProdutosRepelentes2025: 'Tabela 5 — Repelência / inseticida / estudos',
  notasRodapeTabela5: 'Legenda da tabela de produtos',
  gatosEManejo: 'Gatos, reprodução, sangue e vacina',
  controleAbrigosEAmbiental: 'Abrigos e controle ambiental',
  conceitoIntracelular: 'Conceito: bactéria intracelular',
  agentePrincipalEOutros: 'Agente principal e agentes relacionados',
  distribuicaoEVetor: 'Distribuição e vetor',
  transfusaoEComunidade: 'Transfusão e vigilância em comunidade',
  gravidadeECoinfecao: 'Gravidade e coinfecções',
  disseminacaoEVasculite: 'Disseminação e vasculite',
  trombocitopeniaMultifatorial: 'Por que a trombocitopenia?',
  sangramentoSemPlaquetasMuitoBaixas: 'Sangramento desproporcional à contagem',
  rimOlhoImunocomplexos: 'Rim, olho e imunocomplexos',
  medulaOssea: 'Medula óssea nas fases',
  cmeSuspeitaClinica: 'Suspeita clínica',
  cmeTabelaFasesSinaisLab: 'Tabela — fases (clínica e laboratório)',
  cmeEsfregacoSangue: 'Esfregaço sanguíneo e mórulas',
  cmeSorologiaInterpretacao: 'Sorologia e interpretação temporal',
  cmePcrSangueMedula: 'PCR (sangue / medula)',
  cmeDiagnosticoIntegrado: 'Diagnóstico integrado (conceito prático)',
  cmeDoxiciclinaPrimeiraLinha: 'Doxiciclina — primeira linha',
  cmeTabelaAntimicrobianos: 'Tabela — antimicrobianos e adjuvantes',
  cmeSuporteTransfusaoFluidos: 'Transfusão, fluidos e suporte',
  cmeMedulaDeprimida: 'Medula deprimida e expectativas',
  cmeControleCarrapato: 'Prevenção: controle de carrapatos',
  cmeDoadoresSangue: 'Doadores de sangue',
  cmeZoonose: 'Zoonose e sentinela',
  figuraCicloCarrapato: 'Ciclo do carrapato-marrom',
  figuraCarrapato: 'Vetor: Rhipicephalus sanguineus',
  desenvolvimentoCelular: 'Desenvolvimento intracelular de E. canis',
  tabelaSinaisClinicos: 'Sinais clínicos em tabela',
  sinaisHemorragicosCutaneoMucosos: 'Sinais hemorrágicos cutâneo-mucosos',
  sinaisCavidadesEOculares: 'Sinais hemorrágicos oculares e de cavidades',
  petequiasAbdominais: 'Petéquias cutâneas',
  petequiasMucosas: 'Petéquias em mucosa',
  epistaxe: 'Epistaxe',
  hifema: 'Hifema',
  hemorragiaEscleral: 'Hemorragia escleral',
  planoDiagnostico: 'Plano diagnóstico passo a passo',
  fasesELaboratorio: 'Fases e laboratório',
  morulaTvmdl: 'Mórula em esfregaço sanguíneo',
  morulaDetalhada: 'Mórulas e cultura celular',
  mielossupressao: 'Mielossupressão crônica',
  pontosChave: 'O que não pode ser esquecido',
  consultaRapidaTable: 'Consulta rápida',
  fenotiposAnatomicos: 'Fenótipos anatômicos',
  figuraWShaped: 'Figura — colapso tradicional vs malformação em W',
  colapsoWShaped: 'Malformação em W',
  etiologiaMultifatorial: 'Etiologia multifatorial',
  geneticaZfyve16: 'Genética — ZFYVE16 (evidência emergente)',
  anatomiaNormal: 'Anatomia normal da traqueia',
  alteracoesCartilagem: 'Alterações da cartilagem',
  gatoRaro: 'Colapso traqueal em gatos',
  cicloAutoperpetuante: 'Ciclo autoperpetuante da tosse',
  fisiologiaPoiseuille: 'Física da via aérea (Poiseuille)',
  figuraPressoes: 'Dinâmica inspiratória/expiratória',
  figuraCicloAutoperpetuante: 'Figura — ciclo autoperpetuante',
  tabelaGrauI_IV: 'Gradação ACVS I–IV',
  alertaRxNormal: 'Alerta — radiografia normal',
  tabelaDiferenciais: 'Diagnósticos diferenciais',
  figuraGraus: 'Figura — graus de colapso',
  figuraFluoroscopiaKim: 'Fluoroscopia dinâmica',
  kim2024: 'Evidência — Kim et al., 2024',
  suematsu2025: 'Evidência — Suematsu et al., 2025 (radiografia)',
  robin2024: 'Evidência — Robin et al., 2024 (meta-análise stent)',
  congiusta2021: 'Evidência — Congiusta et al., 2021 (médico vs stent)',
  weisse2026: 'Evidência — Weisse et al., 2026 (Yorkshire)',
  talavera2023: 'Evidência — Talavera-López et al., 2023 (fluticasona)',
  fenotiposCards: 'Fenótipos clínicos (tosse vs obstrução)',
  tabelaFarmacologica: 'Tabela farmacológica completa',
  notaDexametasona: 'Nota — discrepância de dexametasona na crise',
  figuraComplicacoesStent: 'Figura — complicações pós-stent',
  principiosAnestesia: 'Anestesia e recuperação',
  escoreControleConsultaVet: 'Escore de controle ConsultaVET',
  pesoPeitoralAmbiente: 'Prevenção — peso, peitoral e ambiente',
  tcWeisse2026: 'Prevalência em Yorkshire Terriers (2026)',
  tcObesidade: 'Obesidade como fator agravante',
  tcAnatomiaMembranaDorsal: 'Anatomia e membrana dorsal',
  tcPrimariaSecundaria: 'Forma primária vs secundária',
  tcFatoresAgravantes: 'Fatores agravantes',
  tcPerfilRacas: 'Perfil epidemiológico',
  tcBroncomalacia: 'Broncomalácia associada',
  tcFisiologiaDinamica: 'Fisiologia dinâmica (inspiração / expiração)',
  tcComplicacoesGraves: 'Complicações graves',
  tcHistoriaEFisico: 'História e exame físico',
  tcBancoMinimo: 'Banco mínimo de dados',
  tcRadiografia: 'Radiografia: papel e limites',
  tcFluoroscopia: 'Fluoroscopia',
  tcTraqueoBroncoscopia: 'Traqueoscopia / broncoscopia',
  tcTomografia: 'Tomografia computadorizada',
  tcLavadoCultura: 'Lavado traqueal / BAL e cultura',
  tcTabelaGrauACVS: 'Gradação ACVS (I–IV)',
  tcTabelaComplicacoesStent2024: 'Complicações após stent (meta-análise)',
  tcDiagnosticosDiferenciais: 'Diagnósticos diferenciais',
  tcPrincipioConservador: 'Princípio do manejo conservador',
  tcMedidasNaoFarmacologicas: 'Medidas não farmacológicas',
  tcAntitussigenosTabela: 'Antitussígenos (doses)',
  tcCorticosteroides: 'Corticosteroides',
  tcBroncodilatadores: 'Broncodilatadores',
  tcAntibioticos: 'Antibióticos (uso racional)',
  tcCriseAguda: 'Crise respiratória aguda',
  tcAnéisExtraluminais: 'Anéis extraluminais',
  tcStentIntraluminal: 'Stent intraluminal',
  tcPrevencaoDescompensacao: 'Prevenção de descompensação',
  tcMecanismoImune: 'Mecanismo imune',
  tcGatilhosComuns: 'Gatilhos comuns',
  tcRemodelamento: 'Remodelamento brônquico',
  tcPerfilPopulacional: 'Perfil populacional',
  tcAmbiente: 'Ambiente e fatores de risco',
  tcCascataInflamatoria: 'Cascata inflamatória',
  tcConsequenciasFuncionais: 'Consequências funcionais',
  tcTransmissao: 'Transmissão',
  tcDiferenciaisObrigatorios: 'Diferenciais obrigatórios',
  tcLavadoBroncoalveolar: 'Lavado broncoalveolar',
  tcExamesComplementares: 'Exames complementares',
  tcTabelaDiferenciais: 'Tabela de diferenciais',
  tcDefinicaoOperacional: 'Definição operacional',
  tcFatoresPredisponentes: 'Fatores predisponentes',
  tcDiferencaAsma: 'Diferença em relação à asma felina',
  tcPerfilCanino: 'Perfil no cão',
  tcPerfilFelino: 'Perfil no gato',
  tcCicloInflamatorio: 'Ciclo inflamatório',
  tcBronquiectasia: 'Bronquiectasia',
  tcBroncoscopiaLavado: 'Broncoscopia e lavado broncoalveolar',
  tcAntitussigenos: 'Antitussígenos',
  tcMedidasAmbientais: 'Medidas ambientais',
  tcReducaoDeProgressao: 'Redução de progressão',
  tcPadraoDeReacao: 'Padrão de reação',
  tcCausasSubjacentes: 'Causas subjacentes',
  tcApresentacaoOral: 'Apresentação oral',
  tcAutotraumatismo: 'Autotraumatismo',
  tcInspecaoMorfologica: 'Inspeção morfológica',
  tcCitologia: 'Citologia da lesão',
  tcBiopsia: 'Biópsia',
  tcInvestigacaoCausaBase: 'Investigação da causa de base',
  tcControleDePulgas: 'Controle de pulgas',
  tcGlicocorticoides: 'Glicocorticoides',
  tcCiclosporina: 'Ciclosporina',
  tcDietaDeEliminacao: 'Dieta de eliminação',
  tcCasosRefratarios: 'Casos refratários',
  tcGranulomaOralExtenso: 'Granuloma oral extenso',
  tcPrevencaoDeRecidiva: 'Prevenção de recidiva',
  tcReducaoDeCrises: 'Redução de crises',
  hemoConceito: 'Conceito (hemoplasmas)',
  hemoEspeciesFelinas: 'Espécies em gatos',
  hemoEspeciesCaninas: 'Espécies em cães',
  hemoGatos: 'Epidemiologia em gatos',
  hemoCaes: 'Epidemiologia em cães',
  hemoImunohemolise: 'Imunohemólise e ciclo',
  hemoCiclico: 'Parasitemia cíclica',
  hemoTransmissao: 'Transmissão (sangue, vetores, contexto)',
  hemoSuspeitaContexto: 'Suspeita no contexto certo',
  hemoHemogramaEsfregaco: 'Hemograma e esfregaço',
  hemoPcrPreferido: 'PCR (método preferido)',
  hemoCoinfeccoesBase: 'Coinfecções e doenças de base',
  hemoPadraoOuroResumo: 'Padrão ouro prático',
  hemoTabelaDoxiciclinaGatoAlerta: 'Alerta — doxiciclina em gatos',
  hemoEstabilizar: 'Estabilização e suporte',
  hemoDoxiciclina: 'Doxiciclina (doses por espécie)',
  hemoAlternativasAbcd: 'Alternativas e esquemas ABCD / Plumb’s',
  hemoCorticoides: 'Corticosteroides na hemoplasmose',
  hemoPrevencaoPortador: 'Portador assintomático — quando não tratar',
  hemoDoadoresPcr: 'Doadores e PCR',
  hemoIatrogeniaVetores: 'Iatrogenia e controle de vetores',
  hemoMicoplasmaFelisRespiratorio: 'M. felis — vias aéreas e olho',
  terapiasInternacionaisComplemento: 'Acervo internacional (complemento)',
  teachingOverview: 'Visão didática',
  pathophysiologyExplanation: 'Entendendo a fisiopatologia',
  diagnosticReasoning: 'Raciocínio clínico',
  diagnosticPlanStepByStep: 'Plano diagnóstico passo a passo',
  diagnosticPlanIfLimitedResources: 'Conduta com recursos limitados',
  treatmentReasoning: 'Lógica do tratamento',
  treatmentByScenario: 'Tratamento por cenário',
  drugProtocolExamples: 'Protocolos medicamentosos',
  monitoringPlan: 'Plano de monitoramento',
  ownerGuidance: 'Orientação ao tutor',
  commonClinicalMistakesExpanded: 'Erros clínicos frequentes',
  causes: 'Principais causas',
  riskFactors: 'Fatores de risco',
  clinicalSuspicion: 'Quando suspeitar',
  firstLineTests: 'Exames mínimos',
  idealTests: 'Exames ideais',
  confirmatoryTests: 'Exames confirmatórios',
  mostSensitiveTests: 'Exames mais sensíveis',
  mostSpecificTests: 'Exames mais específicos',
  falsePositiveConsiderations: 'Falsos positivos',
  falseNegativeConsiderations: 'Falsos negativos',
  limitations: 'Limitações',
  interpretation: 'Interpretação prática',
  supportiveCare: 'Tratamento de suporte',
  emergencyCare: 'Tratamento emergencial',
  longTermCare: 'Tratamento de longo prazo',
  specificTherapy: 'Tratamento específico',
  description: 'Visão geral',
  outcomes: 'Desfechos esperados',
  tissueDamage: 'Lesão tecidual',
  immuneInteraction: 'Interação inflamatória',
  possibleSystemsAffected: 'Sistemas afetados',
  agePredisposition: 'Faixa etária mais afetada',
  populationFactors: 'Perfil do paciente',
  immunologicFactors: 'Fatores biológicos',
  environmentalFactors: 'Fatores ambientais',
  susceptibleGroups: 'Pacientes mais expostos',
  mainClinicalSigns: 'Principais sinais',
  summaryDifferentials: 'Diferenciais principais',
  affectedHosts: 'Espécies afetadas',
  overview: 'Visão geral',
  cause: 'Causa',
  causesCombined: 'Causas',
  infectiousRole: 'Papel das infecções',
  microbiotaAndDiet: 'Microbiota e alimentação',
  microbiota: 'Microbiota',
  dietAndNutrition: 'Dieta e nutrição',
  nutrition: 'Nutrição',
  immuneMediated: 'Mecanismo imunomediado',
  pathogenesis: 'Patogênese',
  mechanisms: 'Mecanismos',
  clinicalSpectrum: 'Espectro clínico',
  signalment: 'Sinal clínico inicial',
  breedPredisposition: 'Predisposição por raça',
  historyComplaints: 'Queixas no histórico',
  chiefComplaints: 'Queixa principal',
  respiratorySigns: 'Sinais respiratórios',
  digestiveSigns: 'Sinais digestivos',
  neurologicSigns: 'Sinais neurológicos',
  dermatologicSigns: 'Sinais dermatológicos',
  generalSigns: 'Sinais gerais',
  ocularSigns: 'Sinais oculares',
  systemicSigns: 'Sinais sistêmicos',
  urinarySigns: 'Sinais urinários',
  musculoskeletalSigns: 'Sinais músculo-esqueléticos',
  perianalSigns: 'Sinais perianais',
  onsetAndCourse: 'Início e evolução',
  advancedDisease: 'Quadro avançado',
  typicalSignalment: 'Perfil típico do paciente',
  defecationRelatedSigns: 'Sinais relacionados à defecação',
  analSacs: 'Sacos anais',
  palpation: 'Palpação',
  inspection: 'Inspeção',
  digitalRectalExam: 'Toque retal',
  abordagemDiagnostica: 'Abordagem e raciocínio diagnóstico',
  examesEConfirmacao: 'Exames e confirmação',
  examesLaboratoriais: 'Exames laboratoriais',
  examesDeImagem: 'Exames de imagem',
  respiratoryForm: 'Forma respiratória',
  cardiovascularForm: 'Forma cardiovascular',
  avoidMistakes: 'Erros a evitar',
  keyPoints: 'Pontos-chave',
  summary: 'Resumo',
  background: 'Contexto',
  mecanismoAutoimune: 'Mecanismo autoimune',
  timo: 'Papel do timo',
  associacoes: 'Associações e comorbidades',
  cmsRelacionada: 'Síndromes miastênicas congênitas (relacionadas)',
  notaClinica: 'Nota clínica epidemiológica',
  formasClinicas: 'Formas clínicas',
  viaAscendente: 'Via ascendente',
  viaHematogena: 'Via hematógena',
  microbiologia: 'Micro-organismos',
  brucella: 'Brucella canis',
  relacaoBph: 'Relação com hiperplasia prostática benigna (BPH)',
  anatomiaCanina: 'Anatomia prostática canina',
  barreiraSangueProstata: 'Barreira sangue–próstata',
  figuraHistopatologia: 'Citologia e histopatologia',
  tabelaAgudaCronica: 'Aguda × crônica',
  tabelaPenetracao: 'Penetração antimicrobiana',
  cpse: 'Esterase prostática específica canina (CPSE)',
  mineralizacao: 'Mineralização prostática',
  tabelaDiferencial: 'BPH × prostatite × neoplasia',
  tabelaAntimicrobianos: 'Antimicrobianos e doses',
  duracao: 'Duração do tratamento',
  abscesso: 'Abscesso prostático',
  suporteAguda: 'Suporte na prostatite aguda',
  manejoReprodutor: 'Manejo do reprodutor',
  ituRecorrente: 'Infecção urinária recorrente',
  sintomatico: 'Tratamento sintomático',
  criseColinergica: 'Crise colinérgica',
  suporteEsofagico: 'Manejo do megaesôfago',
  pneumoniaAspirativa: 'Pneumonia aspirativa',
  drogasCautela: 'Fármacos e anestesia — cautela',
  redFlagsInternacao: 'Red flags — internação',
  diagnosticoPrecoce: 'Diagnóstico precoce',
  aspiracao: 'Prevenção de aspiração',
  cms: 'CMS — prevenção reprodutiva',
  mgFiguraBloqueioJnm: 'Ilustração — bloqueio da junção neuromuscular',
  margemDeSeguranca: 'Margem de segurança da transmissão',
  fatigabilidade: 'Fisiologia da fatigabilidade',
  megaesofago: 'Megaesôfago na miastenia gravis',
  subtipos: 'Subtipos moleculares',
  heranca: 'Herança genética',
  individualizado: 'Tratamento individualizado',
  reproducao: 'Aconselhamento reprodutivo',
  felvExogenoEndogeno: 'FeLV exógeno e endógeno (enFeLV)',
  subgruposVirais: 'Subgrupos virais (A, B, C, T)',
  zoonose: 'Potencial zoonótico',
  figuraPatogenese: 'Patogênese da infecção',
  figuraDesfechos: 'Desfechos da infecção',
  figuraRespostaImune: 'Resposta imune e desfechos',
  desfechosInfeccao: 'Quatro desfechos da infecção',
  imunopatogenese: 'Imunopatogênese',
  oncogenese: 'Oncogenese',
  transmissaoIatrogenica: 'Transmissão iatrogênica',
  sobrevivenciaAmbiente: 'Sobrevivência no ambiente',
  distribuicao: 'Distribuição',
  fatoresRisco: 'Fatores de risco',
  principios: 'Princípios do tratamento',
  assintomatico: 'Gato FeLV+ assintomático',
  infeccoesSecundarias: 'Infecções secundárias',
  linfoma: 'Linfoma associado ao FeLV',
  diferencaGengivite: 'FCGS × gengivite × periodontite',
  fatoresAssociados: 'Fatores associados',
  cascata: 'Patogênese — cascata imunológica',
  porQueExtracaoFunciona: 'Por que a extração dentária funciona',
  figuraFenotipos: 'Fenótipos clínicos (ulcerativo × proliferativo)',
  figuraImunologia: 'Imuno-histoquímica da mucosa oral',
  tabelaPMEFME: 'Extração parcial (PME) × boca inteira (FME)',
  tabelaDesfechoExtracao: 'Desfecho após extrações dentárias',
  tabelaHierarquiaTerapeutica: 'Hierarquia terapêutica e evidência',
  sdaI: 'Índice de atividade da estomatite (SDAI)',
  dor: 'Dor oral — fisiopatologia',
  extracaoDentaria: 'Extrações dentárias — primeira linha',
  tabelaAnalgesia: 'Analgesia multimodal',
  antimicrobianos: 'Antimicrobianos — quando usar',
  corticoides: 'Corticosteroides — limitações',
  ciclosporina: 'Ciclosporina — refratários pós-extração',
  interferonOmega: 'Interferon-ω felino recombinante',
  msc: 'Células mesenquimais estromais (MSC)',
  experimental: 'Terapias experimentais e adjuvantes',
  retrovirus: 'Retrovírus e prognóstico',
  odontologiaPreventiva: 'Odontologia preventiva',
  orientacaoTutor: 'Orientação ao tutor',
  geneticaFGF4: 'Genética discal — O retrogene 12-FGF4RG (CDDY)',
  classificacaoHansenEFormasEspeciais: 'Classificação moderna — Hansen I, II, ANNPE e HNPE',
  graduacaoNeurologicaToracolombar: 'Graduação neurológica toracolombar (Graus 1 a 5)',
  testeDeNocicepcaoProfunda: 'Teste de nocicepção profunda (dor consciente ≠ reflexo)',
  imagemAvançadaRMvsTC: 'Imagem avançada — Ressonância Magnética × Tomografia',
  diferencasEpidemiologicasEGenetica: 'Epidemiologia e genética na espécie felina',
  classificacaoFelina: 'Classificação das lesões discais felinas',
  diferenciacaoRM: 'Diferenciação por RM de mimetizadores felinos (Linfoma, PIF, FCE)',
  disfunçãoBarreira: 'Disfunção da barreira epidérmica',
  imunopatogeneseIL31: 'Imunopatogênese e o eixo IL-31 / JAK-STAT',
  microbiomaEDisbiose: 'Microbioma cutâneo e disbiose secundária',
  criteriosDeFavrot: 'Critérios diagnósticos de Favrot',
  testesAlergicosIDTIgE: 'Testes alérgicos (IDT e IgE sérica) — função real',
  imunopatogeneseFelina: 'Imunopatogênese da reação alérgica felina',
  osQuatroPadroesReacionais: 'Os quatro padrões reacionais felinos clássicos',
  dietaDeEliminacaoFelina: 'Dieta de eliminação felina e desafio',
  testesAlergicosFelinos: 'Testes alérgicos felinos e indicações da ASIT',
  placasEosinofilicasRecorrentes: 'Placas eosinofílicas recorrentes',
  dermatofitoseSecundaria: 'Dermatofitose secundária',
  toxoplasmoseDisseminada: 'Toxoplasmose disseminada',
  fivFelv: 'Associação com retroviroses (FIV / FeLV)',
  associacaoDRC: 'Associação com doença renal crônica (DRC)',
  diferenciacaoTerapeutica: 'Diferenciação terapêutica (Periodontite vs TR vs FCGS)',
  terapiasEmergentesAdjuvantes: 'Terapias emergentes e adjuvantes',
  homeCareFelino: 'Cuidados domiciliares em felinos',
  homeCareDiario: 'Escovação diária',
  produtosVOHC: 'Produtos aceitos pelo VOHC',
  consultasRegulares: 'Acompanhamento e profilaxia periódica',
  homeCareHigiene: 'Higiene oral domiciliar',
  exameDentalPrecoce: 'Exame radiográfico precoce em gatos',
  mecanismosDestruicaoBeta: 'Mecanismos de destruição das células β',
  resistênciaInsulínicaAgregada: 'Resistência insulínica agregada',
  diestroMecanismo: 'Mecanismo do diestro e GH mamário',
  triadeDiagnostica: 'Tríade diagnóstica',
  examesIniciais: 'Exames laboratoriais iniciais',
  frutosamina: 'Frutosamina sérica',
  urocultura: 'Urocultura e avaliação urinária',
  glicotoxicidadeERemissao: 'Glicotoxicidade e remissão diabética',
  fatoresDeResistência: 'Fatores de resistência insulínica',
  escoreAliveDcs: 'Escore clínico ALIVE DCS (iCatCare)',
  catarata: 'Catarata diabética canina',
  dka: 'Cetoacidose diabética (DKA)',
  hhs: 'Estado hiperglicêmico hiperosmolar (HHS)',
  edka: 'Cetoacidose diabética euglicêmica (eDKA)',
  neuropatia: 'Neuropatia diabética felina (postura plantígrada)',
  acromegalia: 'Hipersomatotropismo (acromegalia felina)',
  tabelaInsulinas: 'Tabela de insulinas e antidiabéticos',
  fluxogramaResistencia: 'Fluxograma de resistência insulínica',
  remissaoPreservacao: 'Preservação de células β e remissão',
  vigilanciaComplicacoes: 'Vigilância de complicações',
  calculoPesoIdeal: 'Cálculo do peso corporal ideal para dose de insulina',
  tabelaPesoIdealEcc: 'Estimativa do peso ideal pelo ECC (9 pontos)',
  exemploCalculoInsulina: 'Passo a passo — dose pela massa ideal',
  definicao: 'Definição',
  lesaoPredominante: 'Lesão tireoidiana predominante',
  naoGraves: 'Não é doença de Graves',
  distribuicaoAnatomica: 'Distribuição unilateral × bilateral × ectópica',
  fatoresPropostos: 'Fatores etiológicos propostos',
  progressao: 'Doença progressiva',
  prevalencia: 'Prevalência',
  raca: 'Predisposição racial',
  caoNota: 'Hipertireoidismo no cão — nota',
  eixoHPT: 'Eixo hipotálamo–hipófise–tireoide',
  metabolismo: 'Efeitos metabólicos do excesso de T3/T4',
  mascaramentoDRC: 'Mascaramento da DRC',
  tabelaFrequenciaSinais: 'Frequência dos sinais clínicos',
  hipertireoidismoApatico: 'Hipertireoidismo apático',
  figuraFisiologia: 'Fisiologia tireoidiana',
  figuraCintilografia: 'Cintilografia tireoidiana',
  tabelaComparacaoTratamentos: 'Comparação das modalidades terapêuticas',
  tt4: 'T4 total (TT4)',
  ft4: 'T4 livre (fT4)',
  tsh: 'TSH — interpretação',
  cintilografia: 'Cintilografia tireoidiana',
  tabelaGruposAAHA: 'Grupos diagnósticos AAHA 2023',
  figuraPalpacao: 'Palpação da tireoide',
  objetivos: 'Objetivos do tratamento',
  iodoRadioativo: 'Iodo radioativo (^131I)',
  metimazol: 'Metimazol',
  tabelaMetimazol: 'Metimazol — doses e monitoramento',
  carbimazol: 'Carbimazol',
  dietaIodo: 'Dieta restrita em iodo',
  tireoidectomia: 'Tireoidectomia',
  betabloqueadores: 'Betabloqueadores — terapia sintomática',
  tempestadeTireotoxica: 'Tempestade tireotóxica',
  drcConcomitante: 'Hipertireoidismo + DRC',
  rastreio: 'Rastreio preventivo',
  redFlags: 'Sinais de alerta',
  antiviraisEvidencia: 'Antivirais — evidência',
  glicocorticoides: 'Glicocorticoides',
  monitoramento: 'Monitoramento',
  testagemVacinacao: 'Testagem e vacinação',
  manejoMulticat: 'Domicílio multicat',
  criadores: 'Criadores e gatis',
  hospital: 'FeLV no hospital veterinário',
  eutanasia: 'Eutanásia — quando considerar',
  fcovEntéricoVsPIF: 'FCoV entérico versus PIF',
  transmissaoFCoV: 'Transmissão do FCoV entérico',
  transmissaoPIF: 'Transmissão da PIF',
  idade: 'Faixa etária',
  sexo: 'Sexo',
  figuraUveite: 'Resposta ocular ao antiviral',
  tabelaDosesGS: 'Doses de GS-441524',
  tabelaTesteAmostra: 'Teste certo para amostra certa',
  efusao: 'Fisiopatologia da efusão',
  granulomas: 'Granulomas e vasculite',
  imunidade: 'Papel da imunidade',
  caveatADE: 'Antibody-dependent enhancement (ADE)',
  ocularNeurologica: 'PIF ocular e neurológica',
  remdesivir: 'Remdesivir',
  molnupiravir: 'Molnupiravir',
  corticoide: 'Corticoides — indicações adjuvantes',
  controleFCoV: 'Controle do FCoV em gatil',
  vacina: 'Vacina contra PIF',
  biossegurancaProdutos: 'Qualidade de produtos antivirais',
  biologiaLentivirus: 'Biologia do lentivírus',
  subtiposClados: 'Subtipos e clados virais (A–F)',
  brasil: 'Epidemiologia brasileira',
  mundial: 'Epidemiologia mundial',
  transmissaoMordida: 'Transmissão por mordida',
  transmissaoConvivencia: 'Convivência pacífica',
  transmissaoVertical: 'Transmissão vertical',
  transmissaoSanguinea: 'Transmissão sanguínea e iatrogênica',
  figuraEstagios: 'Estágios da infecção',
  figuraCd4Cd8: 'Depleção CD4+ e CD4:CD8',
  figuraGingivoestomatite: 'Gengivoestomatite',
  figuraAlgoritmo: 'Algoritmo diagnóstico',
  tabelaTestesPOC: 'Desempenho dos testes POC',
  tabelaHemograma: 'Achados hematológicos',
  hiperglobulinemia: 'Hiperglobulinemia policlonal',
  tratamentoSuporte: '7.1 Tratamento de suporte',
  tratamentoDeSuporte: '7.1 Tratamento de suporte',
  tratamentoDoencasAssociadas: '7.2 Tratamento de doenças associadas ao vírus da FIV',
  tratamentoDeDoencasAssociadas: '7.2 Tratamento de doenças associadas ao vírus da FIV',
  tratamentoMonitoramento: '7.3 Monitoramento (como fazer)',
  zidovudinaIndicacoes: 'Indicações de zidovudina (AZT)',
  lamivudina: 'Lamivudina — evidência limitada',
  interferon: 'Interferon — evidência limitada',
  gengivoestomatite: 'Gengivoestomatite crônica',
  controleBrigas: 'Prevenção de brigas e acesso externo',
  testagem: 'Testagem e introdução de gatos',
  doadores: 'Triagem de doadores de sangue',
  convivenciaFivMaisFivMenos: 'Convivência FIV+ com FIV−',
  errosComuns: 'Erros a evitar',
  notes: 'Notas',
  commentary: 'Comentários',
  evidence: 'Evidências',
  controversies: 'Controvérsias',
  differentialConsiderations: 'Considerações diferenciais',
  staging: 'Estadiamento',
  classification: 'Classificação',
  prognosticFactors: 'Fatores prognósticos',
  qualityOfLife: 'Qualidade de vida',
  clientCommunication: 'Comunicação com o tutor',
  dischargeInstructions: 'Orientações de alta',
  hospitalizationCriteria: 'Critérios de internação',
  outpatientCare: 'Manejo ambulatorial',
  inpatientCare: 'Manejo hospitalar',
  surgicalOptions: 'Opções cirúrgicas',
  medicalManagement: 'Tratamento medicamentoso',
  adjunctTherapy: 'Terapia adjuvante',
  firstAid: 'Primeiros socorros',
  chronicManagement: 'Manejo crônico',
  acuteManagement: 'Manejo agudo',
  preventiveCare: 'Cuidados preventivos',
  vaccination: 'Vacinação',
  parasiteControl: 'Controle de parasitas',
  zoonoticConsiderations: 'Aspectos zoonóticos',
  publicHealth: 'Saúde pública',
  oneHealth: 'Uma só saúde',
  differentialDiagnosis: 'Diagnóstico diferencial',
  dmvdAnlodipinoHipertensao: 'Amlodipino — hipertensão e vasodilatação',
  dmvdAnatomiaMixomatose: 'O que muda na valva (endocardiose mixomatosa)',
  dmvdArrhythmiasFrequenciaCardiaca: 'Arritmias e controle da frequência',
  dmvdBiomarcadoresLaboratorio: 'Biomarcadores e laboratório (papel auxiliar)',
  dmvdCirculacaoPulmonarEdema: 'Circulação pulmonar e congestão',
  dmvdCicloHemodinamico: 'Ciclo hemodinâmico: regurgitação, volume e remodelação',
  dmvdCriteriosB2Tabela: 'Critérios de B2 — usar em conjunto',
  dmvdEletrocardiograma: 'Eletrocardiograma e ritmo',
  dmvdFuncaoSistolicaDescompensacao: 'Função sistólica e descompensação',
  dmvdSobrecargaVolumeRemodelacao: 'Sobrecarga de volume e remodelação excêntrica',
  dmvdClinicaAusculta: 'Clínica e ausculta',
  dmvdComplicacoesEletro: 'Complicação elétrica: fibrilação atrial',
  dmvdDiferenciaisDiagnosticos: 'Diagnósticos diferenciais essenciais',
  dmvdEspironolactonaBloqueioNefron: 'Espironolactona e bloqueio sequencial do néfron',
  dmvdEcocardiografiaPadraoOuro: 'Ecocardiografia (padrão ouro)',
  dmvdEstadiamentoAcvimTabela: 'Estadiamento ACVIM (A–D) — o que muda na conduta',
  dmvdFurosemidaAgudaCronicaTorasemida: 'Furosemida, torasemida e transição oral',
  dmvdEstrategiaPorEstagioAcvim: 'Mapa terapêutico por estágio ACVIM',
  dmvdIccAgudaHospitalar: 'ICC aguda — ordem hospitalar',
  dmvdIecaBenazeprilEnalapril: 'IECA: benazepril e enalapril',
  dmvdIsosorbidaVasodilatadorOral: 'Isosorbida (vasodilatador oral)',
  dmvdNeurohumoralIcc: 'Ativação neuro-humoral na ICC',
  dmvdNotaCirurgicaValvar: 'Cirurgia valvar — realidade de referência',
  dmvdPimobendanFormaJeJumMarcas: 'Pimobendan — formulação, jejum e titulação',
  dmvdPredisposicaoRacial: 'Predisposição racial',
  dmvdPrevalenciaEIdade: 'Prevalência e idade',
  dmvdPrognosticoLongitudinal: 'Prognóstico ao longo do tempo',
  dmvdRadiografiaTorax: 'Radiografia de tórax — papel e limites',
  dmvdRadiografiaToraxNormalVsCardiomegalia: 'Radiografia — tórax normal versus cardiomegalia',
  dmvdTosseCardiacaVsRespiratoria: 'Tosse cardíaca versus respiratória',
  historiaNatural: 'História natural',
  pesoExercicio: 'Peso e exercício',
  figuraRxPadraoBronquial: 'Radiografia — padrão brônquico (Donuts e Tramlines)',
  figuraTcBronquiteCronica: 'Tomografia computadorizada do tórax',
  figuraCitologiaCurschmann: 'Citologia — espirais de Curschmann',
  figuraRxTcAsmaFelina: 'Radiografia e TC — colapso do lobo médio e brônquios espessados',
  figuraRxPrePosToracocentese: 'Radiografia — pré e pós-toracocentese',
  dmvdSeguimentoMonitorizacao: 'Seguimento ambulatorial e reestadiamento',
  dmvdUrgenciaHospitalarVasodilatadoresInotropicos:
    'Urgência hospitalar: nitroprussiato, dobutamina e monitorização',
  dmvdValvaTricuspideNota: 'Valva tricúspide e circulação direita',
  conceitoFundamental: 'Conceito fundamental — antes do antiarrítmico',
  arritmiaNaoSignificaCardiopatia: 'Arritmia não implica cardiopatia primária',
  ecgCurtoPodePerder: 'ECG curto pode perder arritmias paroxísticas',
  repercussaoHemodinamica: 'Repercussão hemodinâmica da taqui/bradicardia',
  antiarritmicosProarritmicos: 'Antiarrítmicos também podem causar arritmias',
  fisiologiaEletrica: 'Fisiologia elétrica normal',
  mecanismosArritmia: 'Como as arritmias surgem',
  taquicardiaHemodinamica: 'Por que taquicardia causa síncope ou choque',
  bradicardiaHemodinamica: 'Por que bradicardia reduz débito',
  classificacaoPratica: 'Classificação prática das arritmias',
  tabelaLeituraRapidaECG: 'Leitura rápida do ECG',
  tabelaJornadaDiagnostica: 'Jornada diagnóstica completa',
  figuraNaoTrateEcg: 'Não trate apenas o ECG',
  holterIndicacoes: 'Holter — quando indicar',
  ecgQualidade: 'Como realizar ECG com qualidade',
  figuraHolterGatosSaudaveis: 'Ectopia ventricular em gatos saudáveis (Holter 24 h)',
  arrAtualizacao2026Gatos: 'Atualização científica 2026 — gatos saudáveis',
  figuraEstratificacaoUrgencia: 'Estratificação de urgência ConsultaVet',
  arrNotaEstratificacao: 'Nota sobre estratificação (não estadiamento consensual)',
  /* Giardíase */
  alertaPositivoNaoCausa: 'POSITIVO ≠ CAUSA COMPROVADA DA DIARREIA',
  figuraAlertaPositivoNaoCausa: 'Alerta — positivo não fecha etiologia',
  taxonomiaAssemblages: 'Assemblages A–H de *Giardia duodenalis*',
  figuraCicloBiologico: 'Ciclo biológico do parasita',
  atualizacaoBrasil2026: 'Giardia no Brasil — evidência One Health 2026',
  figuraPatogenia: 'Patogenia — da adesão à diarreia',
  tabelaDiagnosticosCompleta: 'Métodos diagnósticos — comparativo prático',
  tabelaDesempenhoBarrera2024: 'Desempenho diagnóstico — Barrera et al., 2024',
  tabelaComparacaoGiardiaTritrichomonas: 'Giardia vs *Tritrichomonas foetus* — gatos',
  sensibilidadeEspecificidadeDidatica: 'Sensibilidade, especificidade, VPP e VPN',
  figuraFluxogramaDiagnostico: 'Fluxograma diagnóstico integrado',
  giardiaVsTritrichomonasGatos: 'Diferencial felino — *Tritrichomonas*',
  algoritmoDiagnostico: 'Algoritmo diagnóstico resumido',
  apresentacaoClinicaTabela: 'Apresentação clínica (não estadiamento)',
  figuraApresentacaoClinica: 'Espectro clínico da giardíase',
  figuraHigieneAmbiental: 'Higiene ambiental — parte do tratamento',
  fenbendazolCaesGatos: 'Fenbendazol — primeira linha (cães e gatos)',
  metronidazolAlerta: 'Metronidazol — alternativa, não rotina',
  tratarAssintomatico: 'Tratar assintomático positivo?',
  monitoramentoPosTratamento: 'Monitoramento pós-tratamento',
  falhaReinfecaoAlgoritmo: 'Falha terapêutica ou reinfecção — algoritmo',
  figuraCiuca2021: 'Eficácia fenbendazol × metronidazol (Ciuca et al., 2021)',
  perolasClinicas: 'Pérolas clínicas',
  zoonoseCard: 'Potencial zoonótico — baixo, mas não zero',
  vacinaNota: 'Vacina anti-Giardia — não rotina',
  /* Cistoisosporose */
  alertaCoccidioidomicose: 'Cistoisosporose ≠ coccidioidomicose',
  especiesImportantes: 'Espécies de *Cystoisospora* — cães e gatos',
  brasil2023: 'Prevalência em clínica brasileira (Jataí-GO, 2023)',
  destruicaoEpitelial: 'Destruição epitelial intracelular',
  diarreiaMalabsortiva: 'Diarreia malabsortiva/osmótica',
  desidratacaoFilhotes: 'Desidratação desproporcional em filhotes',
  imunossupressao: 'Imunossupressão e excreção prolongada',
  figuraFisiopatologia: 'Fisiopatologia — vilosidades e diarreia',
  classificacaoGravidadeOperacional: 'Classificação operacional de gravidade (não estadiamento)',
  matrizInterpretacaoCopro: 'Matriz de interpretação coproparasitológica',
  tabelaMorfologiaOocistos: 'Morfologia de oocistos — guia prático',
  tabelaComparacaoEimeria: '*Cystoisospora* vs *Eimeria* (passagem espúria)',
  diferenciaisCao: 'Diagnósticos diferenciais — cão',
  diferenciaisGato: 'Diagnósticos diferenciais — gato',
  figuraFluxogramaTerapeutico: 'Fluxograma terapêutico integrado',
  figuraAttia2024: 'Oocistos de *C. felis* — Attia et al., 2024 (CC BY 4.0)',
  figuraFerreira2019: 'Cistos tissulares monozoicos — Ferreira et al., 2019 (CC BY 4.0)',
  ponazurilEsquemaTresDias: 'Ponazuril 50 mg/kg × 3 dias — primeira linha',
  ponazurilDoseUnicaAlerta: 'Ponazuril dose única — não equivalente a 3 dias',
  toltrazurilPorFonte: 'Toltrazuril — protocolos por fonte',
  diclazurilDivergenciaAlerta: 'Diclazuril — divergência de dose (2,5–5 vs 25 mg/kg)',
  sulfadimetoxina: 'Sulfadimetoxina — alternativa clássica',
  controleAmbiental: 'Controle ambiental — parte do tratamento',
  falhaTratamento: 'Falha aparente — checklist antes de “resistência”',
  criacaoCanil: 'Criação e canis — metafilaxia e higiene',
  triagemFilhotes: 'Triagem de filhotes em abrigos e pet shops',
  /* Hiperparatireoidismo */
  alertaNaoUsarCalcioCorrigido: 'Não usar cálcio corrigido por albumina',
  figuraCardInterpretacaoPth: 'Card de ouro — interpretação PTH × iCa',
  cardInterpretacaoPth: 'Matriz iCa × PTH',
  tresFenotipos: 'Três fenótipos — resumo',
  figuraTresMecanismos: 'Comparação dos três mecanismos',
  figuraEixoPth: 'Eixo fisiológico Ca–P–PTH–calcitriol',
  fisiologiaPth: 'Fisiologia normal do PTH',
  fgf23Ckd: 'FGF23 na doença renal',
  anatomiaParatireoides: 'Anatomia das paratireoides',
  tabelaComparacaoTresMecanismos: 'PHPT × CKD-MBD × NSHP',
  matrizInterpretacaoPth: 'Matriz de interpretação laboratorial',
  tabelaPadroesLaboratoriais: 'Padrões laboratoriais por fenótipo',
  tabelaAlvosFosforoIrisCao: 'Metas de fósforo IRIS 2026 — cão',
  tabelaAlvosFosforoIrisGato: 'Metas de fósforo IRIS 2026 — gato',
  jornadaDiagnosticaPhpt: 'Jornada diagnóstica — PHPT',
  ultrassomParatireoides: 'Ultrassonografia cervical',
  ctParatireoides: 'Tomografia das paratireoides',
  figuraFluxogramaPrincipal: 'Fluxograma principal — classificar mecanismo',
  figuraFluxogramaHipercalcemia: 'Fluxograma — hipercalcemia',
  figuraFluxogramaCkdMbd: 'Fluxograma — CKD-MBD (IRIS 2026)',
  figuraFluxogramaNshp: 'Fluxograma — NSHP',
  figuraFluxogramaPosCirurgia: 'Fluxograma — pós-paratireoidectomia',
  figuraRubberJaw: 'Osteodistrofia renal — “floating teeth”',
  diferenciaisHipercalcemiaCao: 'Hipercalcemia — diferenciais (cão)',
  diferenciaisHipercalcemiaGato: 'Hipercalcemia — diferenciais (gato)',
  phptParatireoidectomia: 'PHPT — paratireoidectomia',
  hipercalcemiaGrave: 'Hipercalcemia grave — estabilização',
  hipocalcemiaPosOp: 'Hipocalcemia pós-operatória',
  atualizacaoPth2025: 'Atualização 2025 — PTH pré-operatório e hipocalcemia',
  ckdMbdDietaQuelante: 'CKD-MBD — dieta e quelantes',
  fgf23IrisGato: 'FGF23 felino — IRIS 2026',
  calcitriolNota: 'Calcitriol no CKD-MBD — não rotina',
  cinacalceteNota: 'Cinacalcete — terapia experimental',
  nshpTratamento: 'NSHP — correção dietética',
  tabelaCaoVsGato: 'Comparativo cão × gato',
  hiperparatireoidismoTerciarioNota: 'Hiperparatireoidismo terciário — nota avançada',
  tabelaDecisaoClinicaRapida: 'Decisão clínica rápida',
  alertaRelacaoInsulinaGlicose: 'Alerta — não usar relação insulina:glicose',
  alertaInsulinaNormalHipoglicemia: 'Alerta — insulina “normal” na hipoglicemia',
  alertaInsulinaAbsolutaEstadiamento: 'Evidência — insulina absoluta não estadia',
  seloEvidenciaFelinaLimitada: 'Evidência felina limitada',
  limitacaoTomografia: 'Limitação importante da tomografia',
  tabelaEstadiamentoTNM: 'Estadiamento TNM',
  figuraSinaisClinicos: 'Sinais clínicos — VetCompass 2026 (CC BY 4.0)',
  figuraPredisposicaoRacial: 'Predisposição racial — VetCompass 2025 (CC BY 4.0)',
  diferenciaisHipoglicemia: 'Diagnósticos diferenciais da hipoglicemia',
  cascataFisiologiaBeta: 'Fisiologia da célula beta',
  cascataPatogenia: 'Patogenia do insulinoma',
  infograficoFisiologiaBeta: 'Infográfico — secreção de insulina',
  infograficoPatogeniaSinais: 'Infográfico — patogenia dos sinais',
  neuroglicopeniaVsAdrenergica: 'Neuroglicopenia × resposta adrenérgica',
  polineuropatiaAssociada: 'Polineuropatia associada',
  condutaImediataCrise: 'Conduta imediata — crise hipoglicêmica',
  alertaEdkaSglT2_2026: 'Alerta 2026 — eDKA em gatos com SGLT2',
  alertaBhbPreferencial: 'BHB sanguíneo preferencial à cetonúria',
  alertaCetonuriaArmadilha: 'Armadilha da cetonúria durante tratamento',
  tabelaBhbCutoffs: 'Cutoffs de β-hidroxibutirato (BHB)',
  tabelaPotassioAaha2024: 'Suplementação de K⁺ — AAHA Fluid 2024',
  paradoxoPotassio: 'Paradoxo do potássio na CAD',
  tabelaComparativaEntidades: 'CAD × DK × eDKA × EHH',
  condutaImediata: 'Conduta imediata — primeiros 15–60 minutos',
  potassioFundamental: 'Potássio — pilar do tratamento',
  bicarbonatoNaoRotina: 'Bicarbonato — não rotineiro',
  antibioticosNaoAutomaticos: 'Antibióticos — não automáticos',
  nutricaoPrecoceFelino: 'Nutrição enteral precoce (felino)',
  protocoloEdkaSglT2Aaha2026: 'Protocolo eDKA/SGLT2 — AAHA 2026',
  protocoloFelinoRegularIM: 'Insulina regular IM — gato (AAHA 2026)',
  protocoloFelinoGlargina: 'Glargina — alternativa felina',
  protocoloCaninoRegularIM: 'Insulina regular IM — cão',
  protocoloCaninoCRI: 'CRI insulina regular — cão',
  protocoloCaninoLisproAlternativa: 'Lispro IM — alternativa canina (Malerba)',
  errosQueMatam: 'Erros que matam',
  tabelaDefinicoes: 'Definições — CAD × DK × eDKA × EHH',
  fluxoFisiologico: 'Cascata fisiopatológica',
  cascataMetabolica: 'Cascata metabólica da CAD',
  estreptozotocinaOncologia: 'Estreptozotocina — oncologia especializada',
  toceranibTerapiaAlvo: 'Toceranibe — terapia alvo',
  orientacaoTutorCrise: 'Orientação ao tutor — crise em casa',
  evidenciaPublicada: 'Evidência publicada',
  tabelaFarmacos: 'Medicamentos — doses práticas',
  tabelaRelacaoGlicoseInsulina: 'Interpretação — glicemia × insulina',
  figuraFluxogramaArritmiasPrincipal: 'Fluxograma principal — ritmo anormal',
  figuraFluxogramaFAOrca: 'FA canina — controle de frequência (adaptado ORCA)',
  figuraVtComSemPulso: 'VT com pulso × VF/VT sem pulso',
  arrFaCaninaOrca: 'FA canina — evidência ORCA e ORCA II',
  arrAdenosinaAlerta: 'Adenosina — alerta importante',
  arrVtAgudaCao: 'VT aguda com pulso — cão',
  arrVtAgudaGato: 'Lidocaína em gatos — alerta vermelho',
  arrAivr: 'Ritmo idioventricular acelerado (AIVR)',
  arrBradiarritmias: 'Bradiarritmias — abordagem',
  arrSss: 'Sick sinus syndrome (SSS)',
  arrBloqueiosAv: 'Bloqueios AV',
  arrAvrtPreexcitacao: 'Vias acessórias, preexcitação e AVRT',
  arrAblationAvrt: 'Ablação por radiofrequência em AVRT canina',
  arrTorsades: 'Torsades de pointes',
  arrVfVtSemPulso: 'VF e VT sem pulso — parada cardiorrespiratória',
  tabelaClassesAntiarritmicos: 'Classes antiarrítmicas (Vaughan-Williams)',
  arrInteracoesAltoRisco: 'Antes de combinar antiarrítmicos',
  alertasSeguranca: 'Avisos de segurança',
  arrParticularidadesCaes: 'Particularidades em cães',
  arrParticularidadesGatos: 'Particularidades em gatos',
  figuraSistemaEletrico: 'Sistema elétrico cardíaco',
  figuraBloqueiosAv: 'Bloqueios AV — painel didático',
  figuraHipercalemia: 'Hipercalemia — progressão no ECG',
  workup: 'Investigação complementar',
  therapeuticGoals: 'Objetivos terapêuticos',
  followUp: 'Seguimento',
  recurrence: 'Recidiva',
  relapse: 'Recaída',
  remission: 'Remissão',
  epidemiologicContext: 'Contexto epidemiológico',
  hostFactors: 'Fatores do hospedeiro',
  environmentalTriggers: 'Gatilhos ambientais',
  comorbidities: 'Comorbidades',
  predisposingFactors: 'Fatores predisponentes',
  clinicalCourse: 'Evolução clínica',
  naturalHistory: 'História natural',
  pathologicFindings: 'Achados anatomopatológicos',
  laboratoryFindings: 'Achados laboratoriais',
  imagingFindings: 'Achados de imagem',
  cytology: 'Citologia',
  histopathology: 'Histopatologia',
  microbiology: 'Microbiologia',
  serology: 'Sorologia',
  molecularTests: 'Testes moleculares',
  ancillaryTests: 'Exames auxiliares',
  monitoring: 'Monitoramento',
  reassessment: 'Reavaliação',
  prognosisFactors: 'Fatores de prognóstico',
  survival: 'Sobrevida',
  mortality: 'Mortalidade',
  morbidity: 'Morbidade',
  economicConsiderations: 'Considerações econômicas',
  ethicalConsiderations: 'Considerações éticas',
  legalConsiderations: 'Considerações legais',
  reporting: 'Notificação',
  biosecurity: 'Biossegurança',
  quarantine: 'Quarentena',
  disinfection: 'Desinfecção',
  vectorControl: 'Controle de vetores',
  reservoirHosts: 'Hospedeiros reservatório',
  transmissionRoutes: 'Vias de transmissão',
  incubationPeriod: 'Período de incubação',
  carrierState: 'Estado de portador',
  subclinical: 'Subclínico',
  clinicalManifestations: 'Manifestações clínicas',
  paraclinical: 'Paraclínico',
  definitiveDiagnosis: 'Diagnóstico definitivo',
  presumptiveDiagnosis: 'Diagnóstico presuntivo',
  ruleOuts: 'Exclusões',
  minimumDatabase: 'Banco mínimo de dados',
  advancedImaging: 'Imagem avançada',
  endoscopy: 'Endoscopia',
  biopsy: 'Biópsia',
  fineNeedleAspiration: 'Aspiração por agulha fina',
  culture: 'Cultura',
  sensitivityTesting: 'Teste de sensibilidade',
  antimicrobialStewardship: 'Uso racional de antimicrobianos',
  sourceControl: 'Controle do foco',
  fluidTherapy: 'Fluidoterapia',
  anesthesiaConsiderations: 'Considerações anestésicas',
  perioperative: 'Perioperatório',
  postoperative: 'Pós-operatório',
  rehabilitation: 'Reabilitação',
  nutritionSupport: 'Suporte nutricional',
  transfusion: 'Transfusão',
  oxygenTherapy: 'Oxigenoterapia',
  mechanicalVentilation: 'Ventilação mecânica',
  euthanasiaConsiderations: 'Considerações sobre eutanásia',
  palliativeCare: 'Cuidados paliativos',
  homeCare: 'Cuidados domiciliares',
  nursingCare: 'Cuidados de enfermagem',
  woundManagement: 'Manejo de feridas',
  bandaging: 'Curativos',
  physicalTherapy: 'Fisioterapia',
  environmentalModification: 'Modificação ambiental',
  behavioralModification: 'Modificação comportamental',
  enrichment: 'Enriquecimento ambiental',
  exerciseRestriction: 'Restrição de exercício',
  dietaryModification: 'Modificação dietética',
  allergenAvoidance: 'Evitação de alérgenos',
  immunotherapy: 'Imunoterapia',
  desensitization: 'Dessensibilização',
  vaccineResponse: 'Resposta vacinal',
  maternalNeonatal: 'Matriz e neonatal',
  pediatricConsiderations: 'Considerações pediátricas',
  geriatricConsiderations: 'Considerações geriátricas',
  breedSpecific: 'Específico da raça',
  speciesSpecific: 'Específico da espécie',
  felineSpecific: 'Específico felino',
  canineSpecific: 'Específico canino',
  zoonosisRisk: 'Risco zoonótico',
  occupationalRisk: 'Risco ocupacional',
  outbreakManagement: 'Manejo de surtos',
  herdHealth: 'Saúde de rebanho',
  shelterMedicine: 'Medicina de abrigos',
  travelMedicine: 'Medicina de viagem',
  importExport: 'Importação e exportação',
  regulatory: 'Aspectos regulatórios',
  pharmacokinetics: 'Farmacocinética',
  pharmacodynamics: 'Farmacodinâmica',
  drugInteractions: 'Interações medicamentosas',
  adverseReactions: 'Reações adversas',
  overdose: 'Superdose',
  toxicity: 'Toxicidade',
  antidote: 'Antídoto',
  decontamination: 'Descontaminação',
  emesisInduction: 'Indução de êmese',
  activatedCharcoal: 'Carvão ativado',
  gastricLavage: 'Lavagem gástrica',
  anticonvulsants: 'Anticonvulsivantes',
  cardiovascularSupport: 'Suporte cardiovascular',
  renalSupport: 'Suporte renal',
  hepaticSupport: 'Suporte hepático',
  hematologicSupport: 'Suporte hematológico',
  coagulopathy: 'Coagulopatia',
  sepsisManagement: 'Manejo da sepse',
  shock: 'Choque',
  acidBase: 'Equilíbrio ácido-base',
  electrolytes: 'Eletrólitos',
  bloodGas: 'Gasometria',
  acidosis: 'Acidose',
  alkalosis: 'Alcalose',
  dehydration: 'Desidratação',
  hypovolemia: 'Hipovolemia',
  anemia: 'Anemia',
  polycythemia: 'Policitemia',
  thrombocytopenia: 'Trombocitopenia',
  leukogram: 'Leucograma',
  inflammatoryMarkers: 'Marcadores inflamatórios',
  acutePhaseProteins: 'Proteínas de fase aguda',
  biomarkers: 'Biomarcadores',
  geneticTesting: 'Testes genéticos',
  pedigreeRisk: 'Risco familiar',
  heritability: 'Hereditariedade',
  multifactorial: 'Multifatorial',
  idiopathic: 'Idiopático',
  iatrogenic: 'Iatrogênico',
  traumatic: 'Traumático',
  neoplastic: 'Neoplásico',
  degenerative: 'Degenerativo',
  developmental: 'Desenvolvimental',
  congenital: 'Congênito',
  acquired: 'Adquirido',
  primary: 'Primário',
  secondary: 'Secundário',
  tertiary: 'Terciário',
  localized: 'Localizado',
  generalized: 'Generalizado',
  focal: 'Focal',
  multifocal: 'Multifocal',
  diffuse: 'Difuso',
  chronic: 'Crônico',
  acute: 'Agudo',
  subacute: 'Subagudo',
  peracute: 'Peragudo',
  intermittent: 'Intermitente',
  recurrent: 'Recorrente',
  refractory: 'Refratário',
  responsive: 'Responsivo',
  partialResponse: 'Resposta parcial',
  completeResponse: 'Resposta completa',
  treatmentFailure: 'Falha terapêutica',
  resistance: 'Resistência',
  sensitivity: 'Sensibilidade',
  specificity: 'Especificidade',
  predictiveValue: 'Valor preditivo',
  likelihoodRatios: 'Razões de verossimilhança',
  bayesian: 'Abordagem bayesiana',
  clinicalDecision: 'Decisão clínica',
  algorithms: 'Algoritmos',
  flowcharts: 'Fluxogramas',
  checklists: 'Listas de verificação',
  redFlagsSection: 'Sinais de alerta',
  pearls: 'Pérolas clínicas',
  pitfalls: 'Armadilhas',
  mimics: 'Mimetizadores',
  lookAlike: 'Semelhantes',
  ruleIns: 'Critérios de inclusão',
  ruleOutsCriteria: 'Critérios de exclusão',
  goldStandard: 'Padrão ouro',
  screening: 'Rastreamento',
  confirmation: 'Confirmação',
  monitoringLabs: 'Laboratório de monitoramento',
  imagingFollowUp: 'Seguimento por imagem',
  clinicalScoring: 'Escores clínicos',
  severityScores: 'Escores de gravidade',
  stagingSystems: 'Sistemas de estadiamento',
  responseCriteria: 'Critérios de resposta',
  dischargeCriteria: 'Critérios de alta',
  readmission: 'Reinternação',
  complicationsWatch: 'Vigilância de complicações',
  longTermOutlook: 'Perspectiva em longo prazo',
  caregiverEducation: 'Educação do cuidador',
  compliance: 'Adesão',
  recheckIntervals: 'Intervalos de reavaliação',
  telemedicine: 'Telemedicina',
  referralCriteria: 'Critérios de encaminhamento',
  specialistConsult: 'Consulta especializada',
  multidisciplinary: 'Multidisciplinar',
  evidenceBased: 'Baseado em evidências',
  consensusStatements: 'Declarações de consenso',
  guidelines: 'Diretrizes',
  offLabel: 'Uso fora da bula',
  compassionateUse: 'Uso compassivo',
  clinicalTrials: 'Ensaios clínicos',
  emergingTherapies: 'Terapias emergentes',
  futureDirections: 'Direções futuras',
  knowledgeGaps: 'Lacunas de conhecimento',
  researchNeeds: 'Necessidades de pesquisa',
};

/** Partes de chaves camelCase em inglês → português (minúsculas, exceto nomes próprios). */
const CAMEL_PARTS_PT: Record<string, string> = {
  and: 'e',
  or: 'ou',
  of: 'de',
  in: 'em',
  for: 'para',
  with: 'com',
  without: 'sem',
  from: 'de',
  to: 'a',
  on: 'em',
  at: 'em',
  by: 'por',
  vs: 'versus',
  per: 'por',
  pre: 'pré',
  post: 'pós',
  non: 'não',
  anti: 'anti',
  co: 'co',
  sub: 'sub',
  over: 'super',
  under: 'sub',
  intra: 'intra',
  inter: 'inter',
  multi: 'multi',
  overview: 'visão geral',
  infectious: 'infeccioso',
  role: 'papel',
  microbiota: 'microbiota',
  diet: 'dieta',
  immune: 'imune',
  mediated: 'mediado',
  host: 'hospedeiro',
  vector: 'vetor',
  risk: 'risco',
  factor: 'fator',
  factors: 'fatores',
  clinical: 'clínico',
  presentation: 'apresentação',
  sign: 'sinal',
  signs: 'sinais',
  symptom: 'sintoma',
  symptoms: 'sintomas',
  history: 'história',
  physical: 'físico',
  exam: 'exame',
  diagnostic: 'diagnóstico',
  diagnostics: 'diagnósticos',
  differential: 'diferencial',
  treatment: 'tratamento',
  therapy: 'terapia',
  management: 'manejo',
  prognosis: 'prognóstico',
  prevention: 'prevenção',
  control: 'controle',
  transmission: 'transmissão',
  epidemiology: 'epidemiologia',
  etiology: 'etiologia',
  pathophysiology: 'fisiopatologia',
  pathology: 'patologia',
  laboratory: 'laboratorial',
  imaging: 'imagem',
  surgical: 'cirúrgico',
  medical: 'médico',
  emergency: 'emergência',
  chronic: 'crônico',
  acute: 'agudo',
  general: 'geral',
  specific: 'específico',
  common: 'comum',
  rare: 'raro',
  severe: 'grave',
  mild: 'leve',
  moderate: 'moderado',
  early: 'precoce',
  late: 'tardio',
  primary: 'primário',
  secondary: 'secundário',
  local: 'local',
  systemic: 'sistêmico',
  regional: 'regional',
  bilateral: 'bilateral',
  unilateral: 'unilateral',
  upper: 'superior',
  lower: 'inferior',
  distal: 'distal',
  proximal: 'proximal',
  respiratory: 'respiratório',
  cardiovascular: 'cardiovascular',
  gastrointestinal: 'gastrointestinal',
  neurologic: 'neurológico',
  neurological: 'neurológico',
  dermatologic: 'dermatológico',
  dermatological: 'dermatológico',
  renal: 'renal',
  hepatic: 'hepático',
  ocular: 'ocular',
  orthopedic: 'ortopédico',
  orthopaedic: 'ortopédico',
  musculoskeletal: 'músculo-esquelético',
  reproductive: 'reprodutivo',
  endocrine: 'endócrino',
  hematologic: 'hematológico',
  haematological: 'hematológico',
  immunologic: 'imunológico',
  immunological: 'imunológico',
  metabolic: 'metabólico',
  nutritional: 'nutricional',
  behavioral: 'comportamental',
  behavioural: 'comportamental',
  urinary: 'urinário',
  lymphatic: 'linfático',
  oral: 'oral',
  dental: 'dental',
  environmental: 'ambiental',
  genetic: 'genético',
  breed: 'raça',
  age: 'idade',
  sex: 'sexo',
  weight: 'peso',
  body: 'corpo',
  condition: 'condição',
  score: 'escore',
  scale: 'escala',
  stage: 'estágio',
  grade: 'grau',
  type: 'tipo',
  class: 'classe',
  category: 'categoria',
  form: 'forma',
  pattern: 'padrão',
  course: 'evolução',
  onset: 'início',
  duration: 'duração',
  frequency: 'frequência',
  severity: 'gravidade',
  outcome: 'desfecho',
  outcomes: 'desfechos',
  survival: 'sobrevida',
  mortality: 'mortalidade',
  morbidity: 'morbidade',
  incidence: 'incidência',
  prevalence: 'prevalência',
  exposure: 'exposição',
  vaccine: 'vacina',
  vaccination: 'vacinação',
  parasite: 'parasita',
  bacterial: 'bacteriano',
  viral: 'viral',
  fungal: 'fúngico',
  protozoal: 'protozoário',
  rickettsial: 'rickettsial',
  zoonotic: 'zoonótico',
  public: 'pública',
  health: 'saúde',
  safety: 'segurança',
  welfare: 'bem-estar',
  quality: 'qualidade',
  life: 'vida',
  pain: 'dor',
  distress: 'sofrimento',
  comfort: 'conforto',
  care: 'cuidado',
  nursing: 'enfermagem',
  owner: 'tutor',
  client: 'cliente',
  patient: 'paciente',
  animal: 'animal',
  canine: 'canino',
  feline: 'felino',
  dog: 'cão',
  cat: 'gato',
  puppy: 'filhote',
  kitten: 'filhote',
  adult: 'adulto',
  geriatric: 'geriátrico',
  pediatric: 'pediátrico',
  juvenile: 'juvenil',
  neonatal: 'neonatal',
  maternal: 'materno',
  fetal: 'fetal',
  placental: 'placentário',
  congenital: 'congênito',
  hereditary: 'hereditário',
  familial: 'familiar',
  idiopathic: 'idiopático',
  iatrogenic: 'iatrogênico',
  traumatic: 'traumático',
  toxic: 'tóxico',
  neoplastic: 'neoplásico',
  inflammatory: 'inflamatório',
  degenerative: 'degenerativo',
  developmental: 'desenvolvimental',
  autoimmune: 'autoimune',
  allergic: 'alérgico',
  hypersensitivity: 'hipersensibilidade',
  deficiency: 'deficiência',
  excess: 'excesso',
  imbalance: 'desequilíbrio',
  dysfunction: 'disfunção',
  failure: 'falência',
  insufficiency: 'insuficiência',
  obstruction: 'obstrução',
  stenosis: 'estenose',
  dilation: 'dilatação',
  rupture: 'ruptura',
  perforation: 'perfuração',
  ulcer: 'úlcera',
  erosion: 'erosão',
  necrosis: 'necrose',
  fibrosis: 'fibrose',
  edema: 'edema',
  hemorrhage: 'hemorragia',
  effusion: 'derrame',
  effusions: 'derrames',
  mass: 'massa',
  lesion: 'lesão',
  lesions: 'lesões',
  tumor: 'tumor',
  cyst: 'cisto',
  abscess: 'abscesso',
  granuloma: 'granuloma',
  plaque: 'placa',
  nodule: 'nódulo',
  papule: 'pápula',
  vesicle: 'vesícula',
  pustule: 'pústula',
  skinScale: 'escama',
  crust: 'crosta',
  alopecia: 'alopecia',
  pruritus: 'prurido',
  erythema: 'eritema',
  hyperpigmentation: 'hiperpigmentação',
  hypopigmentation: 'hipopigmentação',
  discharge: 'secreção',
  secretion: 'secreção',
  exudate: 'exsudato',
  drainage: 'drenagem',
  wound: 'ferida',
  trauma: 'trauma',
  injury: 'lesão',
  burn: 'queimadura',
  bite: 'mordedura',
  sting: 'picada',
  foreign: 'estranho',
  intussusception: 'intussuscepção',
  volvulus: 'vólvulo',
  torsion: 'torção',
  distension: 'distensão',
  ileus: 'íleo',
  vomiting: 'vômito',
  diarrhea: 'diarreia',
  constipation: 'constipação',
  inappetence: 'inapetência',
  anorexia: 'anorexia',
  polyphagia: 'polifagia',
  polydipsia: 'polidipsia',
  polyuria: 'poliúria',
  oliguria: 'oligúria',
  anuria: 'anúria',
  dysuria: 'disúria',
  stranguria: 'estrangúria',
  hematuria: 'hematúria',
  proteinuria: 'proteinúria',
  glucosuria: 'glicosúria',
  ketonuria: 'cetonúria',
  bilirubinuria: 'bilirrubinúria',
  azotemia: 'azotemia',
  uremia: 'uremia',
  acidosis: 'acidose',
  alkalosis: 'alcalose',
  dehydration: 'desidratação',
  shock: 'choque',
  sepsis: 'sepse',
  fever: 'febre',
  hypothermia: 'hipotermia',
  hyperthermia: 'hipertermia',
  lethargy: 'letargia',
  weakness: 'fraqueza',
  collapse: 'colapso',
  syncope: 'síncope',
  seizure: 'convulsão',
  seizures: 'convulsões',
  tremor: 'tremor',
  ataxia: 'ataxia',
  paresis: 'paresia',
  paralysis: 'paralisia',
  lameness: 'claudicação',
  stiffness: 'rigidez',
  cough: 'tosse',
  sneeze: 'espirro',
  nasal: 'nasal',
  aural: 'auricular',
  gingival: 'gengival',
  periodontal: 'periodontal',
  stomatitis: 'estomatite',
  glossitis: 'glossite',
  esophageal: 'esofágico',
  gastric: 'gástrico',
  intestinal: 'intestinal',
  colonic: 'cólico',
  pancreatic: 'pancreático',
  biliary: 'biliar',
  splenic: 'esplênico',
  ureteral: 'ureteral',
  bladder: 'bexiga',
  urethral: 'uretral',
  prostatic: 'prostático',
  uterine: 'uterino',
  ovarian: 'ovariano',
  testicular: 'testicular',
  mammary: 'mamário',
  thoracic: 'torácico',
  pulmonary: 'pulmonar',
  pleural: 'pleural',
  mediastinal: 'mediastinal',
  cardiac: 'cardíaco',
  pericardial: 'pericárdico',
  vascular: 'vascular',
  arterial: 'arterial',
  venous: 'venoso',
  lymph: 'linfático',
  node: 'linfonodo',
  bone: 'ósseo',
  joint: 'articular',
  muscle: 'muscular',
  tendon: 'tendíneo',
  ligament: 'ligamentar',
  cartilage: 'cartilaginoso',
  skin: 'pele',
  hair: 'pelo',
  coat: 'pelagem',
  nail: 'unha',
  claw: 'garra',
  pad: 'coixinha',
  foot: 'pata',
  limb: 'membro',
  spine: 'coluna',
  spinal: 'espinal',
  brain: 'encéfalo',
  peripheral: 'periférico',
  central: 'central',
  autonomic: 'autonômico',
  sensory: 'sensorial',
  motor: 'motor',
  reflex: 'reflexo',
  cognition: 'cognição',
  behavior: 'comportamento',
  aggression: 'agressividade',
  anxiety: 'ansiedade',
  fear: 'medo',
  stress: 'estresse',
  enrichment: 'enriquecimento',
  training: 'treinamento',
  medication: 'medicamento',
  drug: 'fármaco',
  dose: 'dose',
  dosing: 'posologia',
  route: 'via',
  taper: 'desmame',
  grooming: 'auto-lambeção',
  flare: 'exacerbação',
  attainment: 'atingimento',
  target: 'alvo',
  threshold: 'limiar',
  itch: 'prurido',
  offlabel: 'fora da bula',
  titration: 'titulação',
  loading: 'ataque',
  maintenance: 'manutenção',
  breakthrough: 'escape',
  rescue: 'resgate',
  adjunct: 'adjuvante',
  alternative: 'alternativa',
  first: 'primeira',
  line: 'linha',
  second: 'segunda',
  third: 'terceira',
  off: 'fora',
  label: 'bula',
  contraindication: 'contraindicação',
  precaution: 'precaução',
  warning: 'aviso',
  interaction: 'interação',
  adverse: 'adverso',
  effect: 'efeito',
  toxicity: 'toxicidade',
  overdose: 'superdose',
  withdrawal: 'suspensão',
  rebound: 'rebote',
  resistance: 'resistência',
  sensitivity: 'sensibilidade',
  culture: 'cultura',
  sensitivityTesting: 'teste de sensibilidade',
  gram: 'Gram',
  stain: 'coloração',
  cytology: 'citologia',
  histology: 'histologia',
  biopsy: 'biópsia',
  aspirate: 'aspirado',
  fluid: 'fluido',
  analysis: 'análise',
  chemistry: 'bioquímica',
  panel: 'painel',
  profile: 'perfil',
  count: 'contagem',
  smear: 'esfregaço',
  coagulation: 'coagulação',
  crossmatch: 'crossmatch',
  typing: 'tipagem',
  cross: 'cruzado',
  match: 'compatibilidade',
  transfusion: 'transfusão',
  whole: 'total',
  blood: 'sangue',
  plasma: 'plasma',
  platelet: 'plaqueta',
  erythrocyte: 'eritrócito',
  leukocyte: 'leucócito',
  radiograph: 'radiografia',
  radiography: 'radiografia',
  ultrasound: 'ultrassom',
  ct: 'tomografia',
  mri: 'ressonância',
  scan: 'exame',
  contrast: 'contraste',
  fluoroscopy: 'fluoroscopia',
  endoscopy: 'endoscopia',
  bronchoscopy: 'broncoscopia',
  rhinoscopy: 'rinoscopia',
  cystoscopy: 'cistoscopia',
  laparoscopy: 'laparoscopia',
  thoracoscopy: 'toracoscopia',
  arthroscopy: 'artroscopia',
  electrocardiogram: 'eletrocardiograma',
  echocardiogram: 'ecocardiograma',
  bloodPressure: 'pressão arterial',
  monitoring: 'monitorização',
  telemetry: 'telemetria',
  ambulatory: 'ambulatorial',
  holter: 'Holter',
  protocol: 'protocolo',
  guideline: 'diretriz',
  consensus: 'consenso',
  statement: 'declaração',
  recommendation: 'recomendação',
  level: 'nível',
  evidence: 'evidência',
  study: 'estudo',
  trial: 'ensaio',
  cohort: 'coorte',
  case: 'caso',
  series: 'série',
  report: 'relato',
  review: 'revisão',
  meta: 'meta',
  systematic: 'sistemática',
  randomized: 'randomizado',
  controlled: 'controlado',
  blinded: 'cego',
  placebo: 'placebo',
  comparator: 'comparador',
  endpoint: 'desfecho',
  surrogate: 'substituto',
  biomarker: 'biomarcador',
  validation: 'validação',
  reproducibility: 'reprodutibilidade',
  accuracy: 'acurácia',
  precision: 'precisão',
  bias: 'viés',
  confounding: 'confusão',
  limitation: 'limitação',
  caveat: 'ressalva',
  uncertainty: 'incerteza',
  gap: 'lacuna',
  need: 'necessidade',
  future: 'futuro',
  direction: 'direção',
  emerging: 'emergente',
  novel: 'novo',
  experimental: 'experimental',
  investigational: 'investigacional',
  compassionate: 'compassivo',
  use: 'uso',
  expanded: 'expandido',
  access: 'acesso',
  named: 'nomeado',
  import: 'importação',
  export: 'exportação',
  regulatory: 'regulatório',
  approval: 'aprovação',
  registration: 'registro',
  marketWithdrawal: 'retirada',
  recall: 'recall',
  event: 'evento',
  reporting: 'notificação',
  pharmacovigilance: 'farmacovigilância',
  mecanismo: 'mecanismo',
  imune: 'imune',
  gatilhos: 'gatilhos',
  comuns: 'comuns',
  remodelamento: 'remodelamento',
  populacional: 'populacional',
  ambiente: 'ambiente',
  cascata: 'cascata',
  inflamatoria: 'inflamatória',
  inflamatorio: 'inflamatório',
  consequencias: 'consequências',
  consequencia: 'consequência',
  sistemicas: 'sistêmicas',
  sistemica: 'sistêmica',
  sistemicos: 'sistêmicos',
  sistemico: 'sistêmico',
  funcionais: 'funcionais',
  historia: 'história',
  fisico: 'físico',
  diferenciais: 'diferenciais',
  obrigatorios: 'obrigatórios',
  obrigatorias: 'obrigatórias',
  obrigatorio: 'obrigatório',
  obrigatoria: 'obrigatória',
  exames: 'exames',
  complementares: 'complementares',
  lavado: 'lavado',
  broncoalveolar: 'broncoalveolar',
  tabela: 'tabela',
  definicao: 'definição',
  operacional: 'operacional',
  predisponentes: 'predisponentes',
  diferenca: 'diferença',
  asma: 'asma',
  ciclo: 'ciclo',
  biologico: 'biológico',
  diagnostico: 'diagnóstico',
  cronica: 'crônica',
  fisiologico: 'fisiológico',
  orgao: 'órgão',
  patogenese: 'patogênese',
  prognostico: 'prognóstico',
  sinonimia: 'sinonímia',
  clinica: 'clínica',
  padroes: 'padrões',
  cao: 'cão',
  phpt: 'PHPT',
  ckd: 'CKD',
  mbd: 'MBD',
  nshp: 'NSHP',
  bronquiectasia: 'bronquiectasia',
  broncoscopia: 'broncoscopia',
  canino: 'canino',
  felino: 'felino',
  padrao: 'padrão',
  reacao: 'reação',
  causas: 'causas',
  subjacentes: 'subjacentes',
  apresentacao: 'apresentação',
  autotraumatismo: 'autotraumatismo',
  inspecao: 'inspeção',
  morfologica: 'morfológica',
  investigacao: 'investigação',
  biopsia: 'biópsia',
  pulgas: 'pulgas',
  glicocorticoides: 'glicocorticoides',
  ciclosporina: 'ciclosporina',
  eliminacao: 'eliminação',
  refratarios: 'refratários',
  extenso: 'extenso',
  prevencao: 'prevenção',
  recidiva: 'recidiva',
  reducao: 'redução',
  crises: 'crises',
  progressao: 'progressão',
  medidas: 'medidas',
  ambientais: 'ambientais',
  antitussigenos: 'antitussígenos',
  antibioticos: 'antibióticos',
  broncodilatadores: 'broncodilatadores',
  corticosteroides: 'corticosteroides',
  crise: 'crise',
  transmissao: 'transmissão',
  anatomia: 'anatomia',
  membrana: 'membrana',
  dorsal: 'dorsal',
  primaria: 'primária',
  secundaria: 'secundária',
  agravantes: 'agravantes',
  racas: 'raças',
  broncomalacia: 'broncomalácia',
  fisiologia: 'fisiologia',
  dinamica: 'dinâmica',
  complicacoes: 'complicações',
  graves: 'graves',
  banco: 'banco',
  minimo: 'mínimo',
  traqueo: 'traqueo',
  cultura: 'cultura',
  grau: 'grau',
  diagnosticos: 'diagnósticos',
  principio: 'princípio',
  conservador: 'conservador',
  farmacologicas: 'farmacológicas',
  nao: 'não',
  aneis: 'anéis',
  extraluminais: 'extraluminais',
  stent: 'stent',
  intraluminal: 'intraluminal',
  descompensacao: 'descompensação',
  tc: '',
};

function splitCamelCaseKey(key: string): string[] {
  return key
    .replace(/([a-z0-9])([A-ZÀ-ÖØ-Ý])/g, '$1 $2')
    .replace(/([A-ZÀ-ÖØ-Ý]+)([A-ZÀ-ÖØ-Ý][a-zà-öø-ÿ])/g, '$1 $2')
    .split(/\s+/)
    .filter(Boolean);
}

/** Remove prefixos editoriais internos (tc, hemo, cme, drc…) antes de montar título legível. */
export function stripEditorialSubsectionPrefix(key: string): string {
  const prefixes = ['tc', 'hemo', 'cme', 'drc', 'cush', 'hiper'] as const;
  for (const prefix of prefixes) {
    if (!key.startsWith(prefix) || key.length <= prefix.length) continue;
    const next = key.charAt(prefix.length);
    if (!/[A-ZÀ-ÖØ-ÞÉ]/.test(next)) continue;
    const rest = key.slice(prefix.length);
    return rest.charAt(0).toLowerCase() + rest.slice(1);
  }
  return key;
}

function titleCasePhrase(lowerPhrase: string): string {
  const small = new Set(['e', 'ou', 'de', 'da', 'do', 'das', 'dos', 'em', 'na', 'no', 'a', 'o', 'com', 'por', 'para', 'versus']);
  return lowerPhrase
    .split(' ')
    .filter(Boolean)
    .map((word, i) => {
      if (!word) return word;
      if (i > 0 && small.has(word)) return word;
      return word.charAt(0).toUpperCase() + word.slice(1);
    })
    .join(' ');
}

/**
 * Traduz chave de subseção editorial (camelCase em inglês) para rótulo em português.
 */
export function translateEditorialSubsectionKey(key: string): string {
  const direct = FULL_KEY_LABELS[key];
  if (direct) return direct;

  const normalizedKey = stripEditorialSubsectionPrefix(key);
  const directNormalized = FULL_KEY_LABELS[normalizedKey];
  if (directNormalized) return directNormalized;

  const parts = splitCamelCaseKey(normalizedKey);
  if (parts.length === 0) return key;

  const mapped = parts
    .map((part) => {
      const low = part.toLowerCase();
      return CAMEL_PARTS_PT[low] ?? part;
    })
    .filter(Boolean);

  const lowerPhrase = mapped.join(' ');
  const looksUntranslated = mapped.every((w, i) => w === parts[i] || w.toLowerCase() === parts[i].toLowerCase());
  if (looksUntranslated && parts.join('') === normalizedKey.replace(/\s/g, '')) {
    return titleCasePhrase(parts.join(' ').toLowerCase());
  }

  return titleCasePhrase(lowerPhrase);
}

/** Nomes de sistema em inglês (conteúdo) → português para cartões de achados. */
const SYSTEM_TITLE_PT: Record<string, string> = {
  critical: 'Emergência crítica',
  neuromuscular: 'Neuromuscular',
  mammary: 'Mamário',
  neonatal: 'Neonatal',
  respiratory: 'Respiratório',
  cardiovascular: 'Cardiovascular',
  gastrointestinal: 'Gastrointestinal',
  neurologic: 'Neurológico',
  neurological: 'Neurológico',
  dermatologic: 'Dermatológico',
  dermatological: 'Dermatológico',
  renal: 'Renal',
  urinary: 'Urinário',
  hepatic: 'Hepático',
  ocular: 'Ocular',
  ophthalmic: 'Oftálmico',
  musculoskeletal: 'Músculo-esquelético',
  orthopedic: 'Ortopédico',
  orthopaedic: 'Ortopédico',
  reproductive: 'Reprodutivo',
  endocrine: 'Endócrino',
  hematologic: 'Hematológico',
  haematological: 'Hematológico',
  immunologic: 'Imunológico',
  immunological: 'Imunológico',
  lymphatic: 'Linfático',
  behavioral: 'Comportamental',
  behavioural: 'Comportamental',
  nutritional: 'Nutricional',
  metabolic: 'Metabólico',
  general: 'Geral',
  oral: 'Oral',
  dental: 'Odontológico',
  thoracic: 'Torácico',
  pulmonary: 'Pulmonar',
  abdominal: 'Abdominal',
  integumentary: 'Tegumentar',
  immune: 'Imune',
  multisystemic: 'Multissistêmico',
  multiSystemic: 'Multissistêmico',
  effusion: 'Efusão',
  biochemical: 'Bioquímico',
  oncologic: 'Oncológico',
  dog: 'Cão',
  cat: 'Gato',
  canine: 'Cão',
  feline: 'Gato',
};

function translateSystemToken(token: string): string {
  const t = token.trim();
  if (!t) return '';
  const key = t.toLowerCase().replace(/\s+/g, '');
  return SYSTEM_TITLE_PT[t] ?? SYSTEM_TITLE_PT[key] ?? SYSTEM_TITLE_PT[t.toLowerCase()] ?? t;
}

export function translateSystemGroupTitle(title: string): string {
  const t = title.trim();
  if (!t) return '';
  if (t.includes('/')) {
    return t
      .split('/')
      .map((part) => translateSystemToken(part))
      .filter(Boolean)
      .join(' · ');
  }
  return translateSystemToken(t);
}

const SUBSECTION_DESCRIPTIONS_PT: Record<string, string> = {
  tgAA: 'Marcador de tireoidite autoimune; não informa sozinho se a tireoide ainda funciona.',
  perfil: 'Faixa etária, espécie e contexto em que a doença aparece com maior frequência.',
  racas: 'Predisposições raciais e variações fisiológicas que alteram a interpretação dos exames.',
  felinos: 'O que muda na ocorrência, investigação e conduta quando o paciente é um gato.',
  primaria: 'Mecanismo que origina a doença diretamente no órgão ou tecido afetado.',
  secundaria: 'Condições externas ou doenças de base capazes de produzir o mesmo fenótipo.',
  rara: 'Causas incomuns que entram na investigação quando o quadro típico não se confirma.',
  eixo: 'Como o controle hormonal se altera e repercute nos diferentes sistemas do organismo.',
  ntis: 'Redução dos hormônios tireoidianos causada por outra doença, sem falência primária da tireoide.',
  transmissao: 'Esclarece se existe contágio e quais vias ou fatores familiares são relevantes.',
  principio: 'Regra central que organiza a escolha e a interpretação dos exames.',
  testes: 'O que cada exame responde, quando pedir e quais erros podem distorcer o resultado.',
  desempenho: 'Sensibilidade, especificidade e limitações observadas em estudos diagnósticos.',
  conceitosTestes: 'Definições que permitem interpretar resultados laboratoriais no contexto clínico.',
  tabelaDesempenho: 'Números publicados por teste e amostra — sempre integrar à suspeita clínica.',
  aplicacaoPratica: 'Cenários típicos em que VPP e VPN mudam a conduta.',
  valorPreditivoPositivo: 'Probabilidade de PIF quando o teste veio positivo.',
  valorPreditivoNegativo: 'Probabilidade de não-PIF quando o teste veio negativo.',
  probabilidadePreTeste: 'Quão provável é PIF antes de qualquer exame, com base em sinalmento e achados.',
  aaHaCategorias: 'Conduta prática conforme a combinação entre sinais clínicos e resultados hormonais.',
  interferentes: 'Situações que alteram os exames sem representar necessariamente a doença investigada.',
  imagem: 'Situações em que ultrassonografia, radiografia ou outro método realmente acrescenta informação.',
  levotiroxina: 'Como iniciar a reposição hormonal e manter uma administração consistente.',
  resposta: 'Prazo esperado de melhora e sinais que indicam necessidade de rever o diagnóstico.',
  monitoramento: 'O que acompanhar para medir eficácia, segurança e progressão da doença.',
  comaMixedematoso: 'Forma rara e grave que exige estabilização intensiva imediata.',
  genetica: 'Influência hereditária e limites dos testes genéticos disponíveis.',
  dieta: 'Quando a alimentação pode causar, agravar ou imitar a doença.',
  caes: 'Características clínicas e epidemiológicas mais importantes na espécie canina.',
  gatos: 'Características clínicas e epidemiológicas mais importantes na espécie felina.',
  prognostico: 'Achados associados a maior risco, progressão ou menor sobrevida.',
  cascata: 'Passo a passo que liga a causa às alterações clínicas observadas.',
  preclinica: 'Doença detectável antes do aparecimento de insuficiência cardíaca ou sinais evidentes.',
  aguda: 'Medidas prioritárias para estabilizar o paciente descompensado.',
  cronica: 'Estratégia domiciliar, ajustes de dose e acompanhamento após a estabilização.',
  hormonal: 'Como a exposição hormonal influencia o aparecimento e o comportamento da doença.',
  molecular: 'Alterações celulares que ajudam a explicar agressividade e resposta terapêutica.',
  exameClinico: 'Como registrar número, posição, tamanho, mobilidade e características de cada lesão.',
  citologia: 'Exame de triagem celular que ajuda no planejamento, mas pode não definir malignidade.',
  histopatologia: 'Avaliação da arquitetura do tecido, invasão, grau e margens após biópsia ou cirurgia.',
  estadiamentoTnm: 'Classificação pela massa primária, linfonodos regionais e metástases distantes.',
  linfonodoSentinela: 'Primeiro linfonodo que recebe drenagem do tumor e melhor representa a rota metastática.',
  padraoOuro: 'Método que oferece a confirmação diagnóstica mais confiável.',
  cirurgia: 'Como extensão da doença, espécie e drenagem linfática orientam a técnica.',
  quimioterapia: 'Quando considerar tratamento sistêmico e quais são os limites da evidência.',
  carcinomaInflamatorio: 'Forma agressiva com invasão linfática cutânea, edema, calor e prognóstico reservado.',
  novidades: 'Resultados recentes que podem mudar a investigação ou o tratamento.',
  agentes: 'Microrganismos mais associados ao quadro e sua importância para a escolha inicial.',
  culturaNormal: 'Por que uma cultura positiva isolada não confirma mastite.',
  periodo: 'Momento fisiológico em que vigilância e exame diário são mais importantes.',
  risco: 'Condições que favorecem estase, lesão do teto ou entrada de bactérias.',
  neonatos: 'Consequências da doença materna sobre ingestão, hidratação, temperatura e crescimento.',
  suporteLocal: 'Medidas para aliviar estase, favorecer drenagem e identificar tecido inviável.',
  analgesia: 'Como controlar a dor sem ignorar hidratação, perfusão e exposição dos filhotes.',
  lactacao: 'Decisão sobre mamada, suplementação e eventual supressão da produção de leite.',
  hipoteses: 'Explicações biologicamente plausíveis que ainda não estão completamente demonstradas.',
  classificacao: 'Como o padrão anatômico e funcional é nomeado e diferenciado de outros fenótipos.',
  mecanismo: 'Alterações de enchimento, pressão e fluxo que geram os sinais clínicos.',
  congestao: 'Como reconhecer e reduzir edema pulmonar ou derrame pleural sem comprometer perfusão.',
  trombose: 'Quando o risco de trombo justifica terapia antitrombótica.',
  arritmia: 'Quando frequência ou ritmo passam a piorar enchimento, débito e risco de morte súbita.',
  obstrucao: 'Estreitamento funcional que varia com frequência, contratilidade e volume circulante.',
  desfechos: 'Eventos clínicos que determinam gravidade e necessidade de monitoramento mais próximo.',
  prioridades: 'Ordem prática das intervenções conforme o risco imediato do paciente.',
  alertas: 'Situações em que uma conduta aparentemente útil pode causar dano.',
  rastreio: 'Quem deve ser examinado antes de desenvolver sinais e com qual método.',
  tutor: 'Sinais que devem ser observados em casa e quando procurar atendimento.',
  pontosChave: 'Conceitos que mudam a conduta se forem esquecidos na consulta.',
  dmvdCriteriosB2Tabela: 'Conjunto de medidas que define remodelação pré-clínica — não um valor isolado.',
  dmvdTosseCardiacaVsRespiratoria: 'Quando a tosse é congestão, compressão brônquica ou doença de via aérea.',
  historiaNatural: 'Como a doença costuma evoluir e o que acelera a descompensação.',
  errosComuns: 'Condutas frequentes que atrasam o diagnóstico ou pioram o paciente.',
};

export function getEditorialSubsectionDescription(key: string): string | undefined {
  return SUBSECTION_DESCRIPTIONS_PT[key];
}

const SYSTEM_DESCRIPTIONS_PT: Record<string, string> = {
  general: 'Alterações de energia, peso, temperatura e condição corporal.',
  dermatologic: 'Mudanças em pele, pelagem, barreira cutânea e infecções secundárias.',
  neuromuscular: 'Alterações de nervos periféricos, músculos, equilíbrio e força.',
  cardiovascular: 'Efeitos sobre frequência, ritmo, contratilidade, perfusão e congestão.',
  respiratory: 'Alterações de ventilação, esforço respiratório e oxigenação.',
  gastrointestinal: 'Sinais ligados ao apetite, digestão, absorção e motilidade.',
  neurologic: 'Alterações de consciência, comportamento, equilíbrio ou função neurológica.',
  renal: 'Efeitos sobre filtração, hidratação, eletrólitos e produção urinária.',
  urinary: 'Sinais relacionados à micção e ao trato urinário.',
  hematologic: 'Alterações em hemácias, leucócitos, plaquetas e perfil lipídico.',
  reproductive: 'Efeitos sobre fertilidade, gestação, puerpério e lactação.',
  endocrine: 'Alterações hormonais e suas repercussões sistêmicas.',
  critical: 'Complicações raras ou graves que exigem reconhecimento e estabilização imediatos.',
  mammary: 'Alterações locais das glândulas mamárias, do leite, da pele e dos tecidos adjacentes.',
  neonatal: 'Repercussões sobre ingestão, temperatura, hidratação e desenvolvimento dos filhotes.',
  lymphatic: 'Alterações de drenagem linfática, linfonodos regionais e disseminação tumoral.',
  ocular: 'Alterações visuais, vasculares ou inflamatórias dos olhos.',
  musculoskeletal: 'Dor, fraqueza ou limitação envolvendo músculos, ossos e articulações.',
  multisystemic: 'Conjunto de alterações simultâneas em diferentes órgãos.',
};

export function getSystemGroupDescription(system: string): string {
  return SYSTEM_DESCRIPTIONS_PT[system.trim().toLowerCase()] ?? 'Sinais agrupados pelo sistema afetado e explicados pelo mecanismo da doença.';
}
