/**
 * Tradução de chaves técnicas em inglês (JSON editorial) para títulos em português na interface.
 */

const FULL_KEY_LABELS: Record<string, string> = {
  visaoGeral: 'Visão geral',
  fatores: 'Fatores participantes',
  especiePrincipal: 'Espécie principal',
  notaFelinos: 'Nota sobre felinos',
  contextoGeografico: 'Contexto geográfico',
  patogenese: 'Patogênese',
  infiltrado: 'Infiltrado inflamatório',
  transmissao: 'Transmissão',
  ordemDePrioridade: 'Ordem de prioridade',
  monitoramento: 'Monitoramento',
  conceitoEixoHPA: 'Conceito: eixo HPA',
  formasNoCaes: 'Formas no cão',
  formasNosGatos: 'Formas no gato',
  especiesCaes: 'Cães',
  especiesGatos: 'Gatos',
  patogenesePDH: 'Patogênese — PDH',
  patogeneseADH: 'Patogênese — ADH',
  patogeneseIatrogenica: 'Patogênese — iatrogênica',
  decisaoInicial: 'Decisão: tratar, operar ou encaminhar',
  trilostanoNoCao: 'Trilostano (cão)',
  mitotanoNoCao: 'Mitotano (cão)',
  cetoconazolNoCao: 'Cetoconazol (cão)',
  cirurgiaEspecializada: 'Cirurgia e terapias especializadas',
  tratamentoFelino: 'Tratamento no gato',
  iatrogenicoManejo: 'Hiperadrenocorticismo iatrogênico',
  prognosticoResumo: 'Prognóstico',
  especiesNasAmericas: 'Espécies nas Américas',
  focoCaninoEgatos: 'Foco da diretriz e nota felina',
  distribuicaoAmericas: 'Distribuição nas Américas',
  magnitudesEVariacao: 'Magnitudes e variação regional',
  saudePublicaInterface: 'Saúde pública e One Health',
  cicloVetorEMacrófago: 'Ciclo no vetor e no hospedeiro',
  viasSecundariasTransmissao: 'Vias secundárias de transmissão',
  patogeneseParasitaEImunidade: 'Patogênese: parasita + imunidade',
  principiosFarmacologicosLCan: 'Classes terapêuticas (Brasileish)',
  objetivoTerapeuticoLCan: 'Objetivo terapêutico realista',
  miltefosina: 'Miltefosina',
  marbofloxacina: 'Marbofloxacina',
  alopurinol: 'Alopurinol',
  domperidona: 'Domperidona',
  estadiamentoClinicoBrasileish: 'Estadiamento clínico (I–VI)',
  terapiasInternacionaisComplemento: 'Acervo internacional (complemento)',
  teachingOverview: 'Visão didática',
  pathophysiologyExplanation: 'Entendendo a fisiopatologia',
  diagnosticReasoning: 'Raciocínio clínico',
  diagnosticPlanStepByStep: 'Plano diagnóstico passo a passo',
  diagnosticPlanIfLimitedResources: 'Conduta com recursos limitados',
  treatmentReasoning: 'Lógica do tratamento',
  treatmentByScenario: 'Tratamento por cenário',
  drugProtocolExamples: 'Protocolos medicamentosos',
  monitoringPlan: 'Plano de monitoramento',
  ownerGuidance: 'Orientação ao tutor',
  commonClinicalMistakesExpanded: 'Erros clínicos frequentes',
  causes: 'Principais causas',
  riskFactors: 'Fatores de risco',
  clinicalSuspicion: 'Quando suspeitar',
  firstLineTests: 'Exames mínimos',
  idealTests: 'Exames ideais',
  confirmatoryTests: 'Exames confirmatórios',
  mostSensitiveTests: 'Exames mais sensíveis',
  mostSpecificTests: 'Exames mais específicos',
  falsePositiveConsiderations: 'Falsos positivos',
  falseNegativeConsiderations: 'Falsos negativos',
  limitations: 'Limitações',
  interpretation: 'Interpretação prática',
  supportiveCare: 'Tratamento de suporte',
  emergencyCare: 'Tratamento emergencial',
  longTermCare: 'Tratamento de longo prazo',
  specificTherapy: 'Tratamento específico',
  description: 'Visão geral',
  outcomes: 'Desfechos esperados',
  tissueDamage: 'Lesão tecidual',
  immuneInteraction: 'Interação inflamatória',
  possibleSystemsAffected: 'Sistemas afetados',
  agePredisposition: 'Faixa etária mais afetada',
  populationFactors: 'Perfil do paciente',
  immunologicFactors: 'Fatores biológicos',
  environmentalFactors: 'Fatores ambientais',
  susceptibleGroups: 'Pacientes mais expostos',
  mainClinicalSigns: 'Principais sinais',
  summaryDifferentials: 'Diferenciais principais',
  affectedHosts: 'Espécies afetadas',
  overview: 'Visão geral',
  cause: 'Causa',
  causesCombined: 'Causas',
  infectiousRole: 'Papel das infecções',
  microbiotaAndDiet: 'Microbiota e alimentação',
  microbiota: 'Microbiota',
  dietAndNutrition: 'Dieta e nutrição',
  nutrition: 'Nutrição',
  immuneMediated: 'Mecanismo imunomediado',
  pathogenesis: 'Patogênese',
  mechanisms: 'Mecanismos',
  clinicalSpectrum: 'Espectro clínico',
  signalment: 'Sinal clínico inicial',
  breedPredisposition: 'Predisposição por raça',
  historyComplaints: 'Queixas no histórico',
  chiefComplaints: 'Queixa principal',
  respiratorySigns: 'Sinais respiratórios',
  digestiveSigns: 'Sinais digestivos',
  neurologicSigns: 'Sinais neurológicos',
  dermatologicSigns: 'Sinais dermatológicos',
  generalSigns: 'Sinais gerais',
  ocularSigns: 'Sinais oculares',
  systemicSigns: 'Sinais sistêmicos',
  urinarySigns: 'Sinais urinários',
  musculoskeletalSigns: 'Sinais músculo-esqueléticos',
  perianalSigns: 'Sinais perianais',
  onsetAndCourse: 'Início e evolução',
  advancedDisease: 'Quadro avançado',
  typicalSignalment: 'Perfil típico do paciente',
  defecationRelatedSigns: 'Sinais relacionados à defecação',
  analSacs: 'Sacos anais',
  palpation: 'Palpação',
  inspection: 'Inspeção',
  digitalRectalExam: 'Toque retal',
  abordagemDiagnostica: 'Abordagem e raciocínio diagnóstico',
  examesEConfirmacao: 'Exames e confirmação',
  examesLaboratoriais: 'Exames laboratoriais',
  examesDeImagem: 'Exames de imagem',
  respiratoryForm: 'Forma respiratória',
  cardiovascularForm: 'Forma cardiovascular',
  avoidMistakes: 'Erros a evitar',
  keyPoints: 'Pontos-chave',
  summary: 'Resumo',
  background: 'Contexto',
  definition: 'Definição',
  scope: 'Escopo',
  notes: 'Notas',
  commentary: 'Comentários',
  evidence: 'Evidências',
  controversies: 'Controvérsias',
  differentialConsiderations: 'Considerações diferenciais',
  staging: 'Estadiamento',
  classification: 'Classificação',
  prognosticFactors: 'Fatores prognósticos',
  qualityOfLife: 'Qualidade de vida',
  clientCommunication: 'Comunicação com o tutor',
  dischargeInstructions: 'Orientações de alta',
  hospitalizationCriteria: 'Critérios de internação',
  outpatientCare: 'Manejo ambulatorial',
  inpatientCare: 'Manejo hospitalar',
  surgicalOptions: 'Opções cirúrgicas',
  medicalManagement: 'Tratamento medicamentoso',
  adjunctTherapy: 'Terapia adjuvante',
  firstAid: 'Primeiros socorros',
  chronicManagement: 'Manejo crônico',
  acuteManagement: 'Manejo agudo',
  preventiveCare: 'Cuidados preventivos',
  vaccination: 'Vacinação',
  parasiteControl: 'Controle de parasitas',
  zoonoticConsiderations: 'Aspectos zoonóticos',
  publicHealth: 'Saúde pública',
  oneHealth: 'Uma só saúde',
  differentialDiagnosis: 'Diagnóstico diferencial',
  workup: 'Investigação complementar',
  therapeuticGoals: 'Objetivos terapêuticos',
  followUp: 'Seguimento',
  recurrence: 'Recidiva',
  relapse: 'Recaída',
  remission: 'Remissão',
  epidemiologicContext: 'Contexto epidemiológico',
  hostFactors: 'Fatores do hospedeiro',
  environmentalTriggers: 'Gatilhos ambientais',
  comorbidities: 'Comorbidades',
  predisposingFactors: 'Fatores predisponentes',
  clinicalCourse: 'Evolução clínica',
  naturalHistory: 'História natural',
  pathologicFindings: 'Achados anatomopatológicos',
  laboratoryFindings: 'Achados laboratoriais',
  imagingFindings: 'Achados de imagem',
  cytology: 'Citologia',
  histopathology: 'Histopatologia',
  microbiology: 'Microbiologia',
  serology: 'Sorologia',
  molecularTests: 'Testes moleculares',
  ancillaryTests: 'Exames auxiliares',
  monitoring: 'Monitoramento',
  reassessment: 'Reavaliação',
  prognosisFactors: 'Fatores de prognóstico',
  survival: 'Sobrevida',
  mortality: 'Mortalidade',
  morbidity: 'Morbidade',
  economicConsiderations: 'Considerações econômicas',
  ethicalConsiderations: 'Considerações éticas',
  legalConsiderations: 'Considerações legais',
  reporting: 'Notificação',
  biosecurity: 'Biossegurança',
  quarantine: 'Quarentena',
  disinfection: 'Desinfecção',
  vectorControl: 'Controle de vetores',
  reservoirHosts: 'Hospedeiros reservatório',
  transmissionRoutes: 'Vias de transmissão',
  incubationPeriod: 'Período de incubação',
  carrierState: 'Estado de portador',
  subclinical: 'Subclínico',
  clinicalManifestations: 'Manifestações clínicas',
  paraclinical: 'Paraclínico',
  definitiveDiagnosis: 'Diagnóstico definitivo',
  presumptiveDiagnosis: 'Diagnóstico presuntivo',
  ruleOuts: 'Exclusões',
  minimumDatabase: 'Banco mínimo de dados',
  advancedImaging: 'Imagem avançada',
  endoscopy: 'Endoscopia',
  biopsy: 'Biópsia',
  fineNeedleAspiration: 'Aspiração por agulha fina',
  culture: 'Cultura',
  sensitivityTesting: 'Teste de sensibilidade',
  antimicrobialStewardship: 'Uso racional de antimicrobianos',
  sourceControl: 'Controle do foco',
  fluidTherapy: 'Fluidoterapia',
  analgesia: 'Analgesia',
  anesthesiaConsiderations: 'Considerações anestésicas',
  perioperative: 'Perioperatório',
  postoperative: 'Pós-operatório',
  rehabilitation: 'Reabilitação',
  nutritionSupport: 'Suporte nutricional',
  transfusion: 'Transfusão',
  oxygenTherapy: 'Oxigenoterapia',
  mechanicalVentilation: 'Ventilação mecânica',
  euthanasiaConsiderations: 'Considerações sobre eutanásia',
  palliativeCare: 'Cuidados paliativos',
  homeCare: 'Cuidados domiciliares',
  nursingCare: 'Cuidados de enfermagem',
  woundManagement: 'Manejo de feridas',
  bandaging: 'Curativos',
  physicalTherapy: 'Fisioterapia',
  environmentalModification: 'Modificação ambiental',
  behavioralModification: 'Modificação comportamental',
  enrichment: 'Enriquecimento ambiental',
  exerciseRestriction: 'Restrição de exercício',
  dietaryModification: 'Modificação dietética',
  allergenAvoidance: 'Evitação de alérgenos',
  immunotherapy: 'Imunoterapia',
  desensitization: 'Dessensibilização',
  vaccineResponse: 'Resposta vacinal',
  maternalNeonatal: 'Matriz e neonatal',
  pediatricConsiderations: 'Considerações pediátricas',
  geriatricConsiderations: 'Considerações geriátricas',
  breedSpecific: 'Específico da raça',
  speciesSpecific: 'Específico da espécie',
  felineSpecific: 'Específico felino',
  canineSpecific: 'Específico canino',
  zoonosisRisk: 'Risco zoonótico',
  occupationalRisk: 'Risco ocupacional',
  outbreakManagement: 'Manejo de surtos',
  herdHealth: 'Saúde de rebanho',
  shelterMedicine: 'Medicina de abrigos',
  travelMedicine: 'Medicina de viagem',
  importExport: 'Importação e exportação',
  regulatory: 'Aspectos regulatórios',
  pharmacokinetics: 'Farmacocinética',
  pharmacodynamics: 'Farmacodinâmica',
  drugInteractions: 'Interações medicamentosas',
  adverseReactions: 'Reações adversas',
  overdose: 'Superdose',
  toxicity: 'Toxicidade',
  antidote: 'Antídoto',
  decontamination: 'Descontaminação',
  emesisInduction: 'Indução de êmese',
  activatedCharcoal: 'Carvão ativado',
  gastricLavage: 'Lavagem gástrica',
  anticonvulsants: 'Anticonvulsivantes',
  cardiovascularSupport: 'Suporte cardiovascular',
  renalSupport: 'Suporte renal',
  hepaticSupport: 'Suporte hepático',
  hematologicSupport: 'Suporte hematológico',
  coagulopathy: 'Coagulopatia',
  sepsisManagement: 'Manejo da sepse',
  shock: 'Choque',
  acidBase: 'Equilíbrio ácido-base',
  electrolytes: 'Eletrólitos',
  bloodGas: 'Gasometria',
  acidosis: 'Acidose',
  alkalosis: 'Alcalose',
  dehydration: 'Desidratação',
  hypovolemia: 'Hipovolemia',
  anemia: 'Anemia',
  polycythemia: 'Policitemia',
  thrombocytopenia: 'Trombocitopenia',
  leukogram: 'Leucograma',
  inflammatoryMarkers: 'Marcadores inflamatórios',
  acutePhaseProteins: 'Proteínas de fase aguda',
  biomarkers: 'Biomarcadores',
  geneticTesting: 'Testes genéticos',
  pedigreeRisk: 'Risco familiar',
  heritability: 'Hereditariedade',
  multifactorial: 'Multifatorial',
  idiopathic: 'Idiopático',
  iatrogenic: 'Iatrogênico',
  traumatic: 'Traumático',
  neoplastic: 'Neoplásico',
  degenerative: 'Degenerativo',
  developmental: 'Desenvolvimental',
  congenital: 'Congênito',
  acquired: 'Adquirido',
  primary: 'Primário',
  secondary: 'Secundário',
  tertiary: 'Terciário',
  localized: 'Localizado',
  generalized: 'Generalizado',
  focal: 'Focal',
  multifocal: 'Multifocal',
  diffuse: 'Difuso',
  chronic: 'Crônico',
  acute: 'Agudo',
  subacute: 'Subagudo',
  peracute: 'Peragudo',
  intermittent: 'Intermitente',
  recurrent: 'Recorrente',
  refractory: 'Refratário',
  responsive: 'Responsivo',
  partialResponse: 'Resposta parcial',
  completeResponse: 'Resposta completa',
  treatmentFailure: 'Falha terapêutica',
  resistance: 'Resistência',
  sensitivity: 'Sensibilidade',
  specificity: 'Especificidade',
  predictiveValue: 'Valor preditivo',
  likelihoodRatios: 'Razões de verossimilhança',
  bayesian: 'Abordagem bayesiana',
  clinicalDecision: 'Decisão clínica',
  algorithms: 'Algoritmos',
  flowcharts: 'Fluxogramas',
  checklists: 'Listas de verificação',
  redFlagsSection: 'Sinais de alerta',
  pearls: 'Pérolas clínicas',
  pitfalls: 'Armadilhas',
  mimics: 'Mimetizadores',
  lookAlike: 'Semelhantes',
  ruleIns: 'Critérios de inclusão',
  ruleOutsCriteria: 'Critérios de exclusão',
  goldStandard: 'Padrão ouro',
  screening: 'Rastreamento',
  confirmation: 'Confirmação',
  monitoringLabs: 'Laboratório de monitoramento',
  imagingFollowUp: 'Seguimento por imagem',
  clinicalScoring: 'Escores clínicos',
  severityScores: 'Escores de gravidade',
  stagingSystems: 'Sistemas de estadiamento',
  responseCriteria: 'Critérios de resposta',
  dischargeCriteria: 'Critérios de alta',
  readmission: 'Reinternação',
  complicationsWatch: 'Vigilância de complicações',
  longTermOutlook: 'Perspectiva em longo prazo',
  caregiverEducation: 'Educação do cuidador',
  compliance: 'Adesão',
  recheckIntervals: 'Intervalos de reavaliação',
  telemedicine: 'Telemedicina',
  referralCriteria: 'Critérios de encaminhamento',
  specialistConsult: 'Consulta especializada',
  multidisciplinary: 'Multidisciplinar',
  evidenceBased: 'Baseado em evidências',
  consensusStatements: 'Declarações de consenso',
  guidelines: 'Diretrizes',
  offLabel: 'Uso fora da bula',
  compassionateUse: 'Uso compassivo',
  clinicalTrials: 'Ensaios clínicos',
  emergingTherapies: 'Terapias emergentes',
  futureDirections: 'Direções futuras',
  knowledgeGaps: 'Lacunas de conhecimento',
  researchNeeds: 'Necessidades de pesquisa',
};

/** Partes de chaves camelCase em inglês → português (minúsculas, exceto nomes próprios). */
const CAMEL_PARTS_PT: Record<string, string> = {
  and: 'e',
  or: 'ou',
  of: 'de',
  in: 'em',
  for: 'para',
  with: 'com',
  without: 'sem',
  from: 'de',
  to: 'a',
  on: 'em',
  at: 'em',
  by: 'por',
  vs: 'versus',
  per: 'por',
  pre: 'pré',
  post: 'pós',
  non: 'não',
  anti: 'anti',
  co: 'co',
  sub: 'sub',
  over: 'super',
  under: 'sub',
  intra: 'intra',
  inter: 'inter',
  multi: 'multi',
  overview: 'visão geral',
  infectious: 'infeccioso',
  role: 'papel',
  microbiota: 'microbiota',
  diet: 'dieta',
  immune: 'imune',
  mediated: 'mediado',
  host: 'hospedeiro',
  vector: 'vetor',
  risk: 'risco',
  factor: 'fator',
  factors: 'fatores',
  clinical: 'clínico',
  presentation: 'apresentação',
  sign: 'sinal',
  signs: 'sinais',
  symptom: 'sintoma',
  symptoms: 'sintomas',
  history: 'história',
  physical: 'físico',
  exam: 'exame',
  diagnostic: 'diagnóstico',
  diagnostics: 'diagnósticos',
  differential: 'diferencial',
  treatment: 'tratamento',
  therapy: 'terapia',
  management: 'manejo',
  prognosis: 'prognóstico',
  prevention: 'prevenção',
  control: 'controle',
  transmission: 'transmissão',
  epidemiology: 'epidemiologia',
  etiology: 'etiologia',
  pathophysiology: 'fisiopatologia',
  pathology: 'patologia',
  laboratory: 'laboratorial',
  imaging: 'imagem',
  surgical: 'cirúrgico',
  medical: 'médico',
  emergency: 'emergência',
  chronic: 'crônico',
  acute: 'agudo',
  general: 'geral',
  specific: 'específico',
  common: 'comum',
  rare: 'raro',
  severe: 'grave',
  mild: 'leve',
  moderate: 'moderado',
  early: 'precoce',
  late: 'tardio',
  primary: 'primário',
  secondary: 'secundário',
  local: 'local',
  systemic: 'sistêmico',
  regional: 'regional',
  bilateral: 'bilateral',
  unilateral: 'unilateral',
  upper: 'superior',
  lower: 'inferior',
  distal: 'distal',
  proximal: 'proximal',
  respiratory: 'respiratório',
  cardiovascular: 'cardiovascular',
  gastrointestinal: 'gastrointestinal',
  neurologic: 'neurológico',
  neurological: 'neurológico',
  dermatologic: 'dermatológico',
  dermatological: 'dermatológico',
  renal: 'renal',
  hepatic: 'hepático',
  ocular: 'ocular',
  orthopedic: 'ortopédico',
  orthopaedic: 'ortopédico',
  musculoskeletal: 'músculo-esquelético',
  reproductive: 'reprodutivo',
  endocrine: 'endócrino',
  hematologic: 'hematológico',
  haematological: 'hematológico',
  immunologic: 'imunológico',
  immunological: 'imunológico',
  metabolic: 'metabólico',
  nutritional: 'nutricional',
  behavioral: 'comportamental',
  behavioural: 'comportamental',
  urinary: 'urinário',
  lymphatic: 'linfático',
  oral: 'oral',
  dental: 'dental',
  environmental: 'ambiental',
  genetic: 'genético',
  breed: 'raça',
  age: 'idade',
  sex: 'sexo',
  weight: 'peso',
  body: 'corpo',
  condition: 'condição',
  score: 'escore',
  scale: 'escala',
  stage: 'estágio',
  grade: 'grau',
  type: 'tipo',
  class: 'classe',
  category: 'categoria',
  form: 'forma',
  pattern: 'padrão',
  course: 'evolução',
  onset: 'início',
  duration: 'duração',
  frequency: 'frequência',
  severity: 'gravidade',
  outcome: 'desfecho',
  outcomes: 'desfechos',
  survival: 'sobrevida',
  mortality: 'mortalidade',
  morbidity: 'morbidade',
  incidence: 'incidência',
  prevalence: 'prevalência',
  exposure: 'exposição',
  vaccine: 'vacina',
  vaccination: 'vacinação',
  parasite: 'parasita',
  bacterial: 'bacteriano',
  viral: 'viral',
  fungal: 'fúngico',
  protozoal: 'protozoário',
  rickettsial: 'rickettsial',
  zoonotic: 'zoonótico',
  public: 'pública',
  health: 'saúde',
  safety: 'segurança',
  welfare: 'bem-estar',
  quality: 'qualidade',
  life: 'vida',
  pain: 'dor',
  distress: 'sofrimento',
  comfort: 'conforto',
  care: 'cuidado',
  nursing: 'enfermagem',
  owner: 'tutor',
  client: 'cliente',
  patient: 'paciente',
  animal: 'animal',
  canine: 'canino',
  feline: 'felino',
  dog: 'cão',
  cat: 'gato',
  puppy: 'filhote',
  kitten: 'filhote',
  adult: 'adulto',
  geriatric: 'geriátrico',
  pediatric: 'pediátrico',
  juvenile: 'juvenil',
  neonatal: 'neonatal',
  maternal: 'materno',
  fetal: 'fetal',
  placental: 'placentário',
  congenital: 'congênito',
  hereditary: 'hereditário',
  familial: 'familiar',
  idiopathic: 'idiopático',
  iatrogenic: 'iatrogênico',
  traumatic: 'traumático',
  toxic: 'tóxico',
  neoplastic: 'neoplásico',
  inflammatory: 'inflamatório',
  degenerative: 'degenerativo',
  developmental: 'desenvolvimental',
  metabolic: 'metabólico',
  endocrine: 'endócrino',
  autoimmune: 'autoimune',
  allergic: 'alérgico',
  hypersensitivity: 'hipersensibilidade',
  deficiency: 'deficiência',
  excess: 'excesso',
  imbalance: 'desequilíbrio',
  dysfunction: 'disfunção',
  failure: 'falência',
  insufficiency: 'insuficiência',
  obstruction: 'obstrução',
  stenosis: 'estenose',
  dilation: 'dilatação',
  rupture: 'ruptura',
  perforation: 'perfuração',
  ulcer: 'úlcera',
  erosion: 'erosão',
  necrosis: 'necrose',
  fibrosis: 'fibrose',
  edema: 'edema',
  hemorrhage: 'hemorragia',
  effusion: 'derrame',
  effusions: 'derrames',
  mass: 'massa',
  lesion: 'lesão',
  lesions: 'lesões',
  tumor: 'tumor',
  cyst: 'cisto',
  abscess: 'abscesso',
  granuloma: 'granuloma',
  plaque: 'placa',
  nodule: 'nódulo',
  papule: 'pápula',
  vesicle: 'vesícula',
  pustule: 'pústula',
  scale: 'escama',
  crust: 'crosta',
  alopecia: 'alopecia',
  pruritus: 'prurido',
  erythema: 'eritema',
  hyperpigmentation: 'hiperpigmentação',
  hypopigmentation: 'hipopigmentação',
  discharge: 'secreção',
  secretion: 'secreção',
  exudate: 'exsudato',
  drainage: 'drenagem',
  wound: 'ferida',
  trauma: 'trauma',
  injury: 'lesão',
  burn: 'queimadura',
  bite: 'mordedura',
  sting: 'picada',
  foreign: 'estranho',
  body: 'corpo',
  obstruction: 'obstrução',
  intussusception: 'intussuscepção',
  volvulus: 'vólvulo',
  torsion: 'torção',
  dilation: 'dilatação',
  distension: 'distensão',
  ileus: 'íleo',
  vomiting: 'vômito',
  diarrhea: 'diarreia',
  constipation: 'constipação',
  inappetence: 'inapetência',
  anorexia: 'anorexia',
  polyphagia: 'polifagia',
  polydipsia: 'polidipsia',
  polyuria: 'poliúria',
  oliguria: 'oligúria',
  anuria: 'anúria',
  dysuria: 'disúria',
  stranguria: 'estrangúria',
  hematuria: 'hematúria',
  proteinuria: 'proteinúria',
  glucosuria: 'glicosúria',
  ketonuria: 'cetonúria',
  bilirubinuria: 'bilirrubinúria',
  azotemia: 'azotemia',
  uremia: 'uremia',
  acidosis: 'acidose',
  alkalosis: 'alcalose',
  dehydration: 'desidratação',
  shock: 'choque',
  sepsis: 'sepse',
  fever: 'febre',
  hypothermia: 'hipotermia',
  hyperthermia: 'hipertermia',
  lethargy: 'letargia',
  weakness: 'fraqueza',
  collapse: 'colapso',
  syncope: 'síncope',
  seizure: 'convulsão',
  seizures: 'convulsões',
  tremor: 'tremor',
  ataxia: 'ataxia',
  paresis: 'paresia',
  paralysis: 'paralisia',
  pain: 'dor',
  lameness: 'claudicação',
  stiffness: 'rigidez',
  cough: 'tosse',
  sneeze: 'espirro',
  nasal: 'nasal',
  ocular: 'ocular',
  aural: 'auricular',
  oral: 'oral',
  dental: 'dental',
  gingival: 'gengival',
  periodontal: 'periodontal',
  stomatitis: 'estomatite',
  glossitis: 'glossite',
  esophageal: 'esofágico',
  gastric: 'gástrico',
  intestinal: 'intestinal',
  colonic: 'cólico',
  pancreatic: 'pancreático',
  biliary: 'biliar',
  hepatic: 'hepático',
  splenic: 'esplênico',
  renal: 'renal',
  ureteral: 'ureteral',
  bladder: 'bexiga',
  urethral: 'uretral',
  prostatic: 'prostático',
  uterine: 'uterino',
  ovarian: 'ovariano',
  testicular: 'testicular',
  mammary: 'mamário',
  thoracic: 'torácico',
  pulmonary: 'pulmonar',
  pleural: 'pleural',
  mediastinal: 'mediastinal',
  cardiac: 'cardíaco',
  pericardial: 'pericárdico',
  vascular: 'vascular',
  arterial: 'arterial',
  venous: 'venoso',
  lymph: 'linfático',
  node: 'linfonodo',
  bone: 'ósseo',
  joint: 'articular',
  muscle: 'muscular',
  tendon: 'tendíneo',
  ligament: 'ligamentar',
  cartilage: 'cartilaginoso',
  skin: 'pele',
  hair: 'pelo',
  coat: 'pelagem',
  nail: 'unha',
  claw: 'garra',
  pad: 'coixinha',
  foot: 'pata',
  limb: 'membro',
  spine: 'coluna',
  spinal: 'espinal',
  brain: 'encéfalo',
  peripheral: 'periférico',
  central: 'central',
  autonomic: 'autonômico',
  sensory: 'sensorial',
  motor: 'motor',
  reflex: 'reflexo',
  cognition: 'cognição',
  behavior: 'comportamento',
  aggression: 'agressividade',
  anxiety: 'ansiedade',
  fear: 'medo',
  stress: 'estresse',
  enrichment: 'enriquecimento',
  training: 'treinamento',
  medication: 'medicamento',
  drug: 'fármaco',
  dose: 'dose',
  dosing: 'posologia',
  route: 'via',
  frequency: 'frequência',
  duration: 'duração',
  taper: 'desmame',
  titration: 'titulação',
  loading: 'ataque',
  maintenance: 'manutenção',
  breakthrough: 'escape',
  rescue: 'resgate',
  adjunct: 'adjuvante',
  alternative: 'alternativa',
  first: 'primeira',
  line: 'linha',
  second: 'segunda',
  third: 'terceira',
  off: 'fora',
  label: 'bula',
  contraindication: 'contraindicação',
  precaution: 'precaução',
  warning: 'aviso',
  interaction: 'interação',
  adverse: 'adverso',
  effect: 'efeito',
  toxicity: 'toxicidade',
  overdose: 'superdose',
  withdrawal: 'suspensão',
  rebound: 'rebote',
  resistance: 'resistência',
  sensitivity: 'sensibilidade',
  culture: 'cultura',
  sensitivityTesting: 'teste de sensibilidade',
  gram: 'Gram',
  stain: 'coloração',
  cytology: 'citologia',
  histology: 'histologia',
  biopsy: 'biópsia',
  aspirate: 'aspirado',
  fluid: 'fluido',
  analysis: 'análise',
  chemistry: 'bioquímica',
  panel: 'painel',
  profile: 'perfil',
  count: 'contagem',
  smear: 'esfregaço',
  coagulation: 'coagulação',
  crossmatch: 'crossmatch',
  typing: 'tipagem',
  cross: 'cruzado',
  match: 'compatibilidade',
  transfusion: 'transfusão',
  whole: 'total',
  blood: 'sangue',
  plasma: 'plasma',
  platelet: 'plaqueta',
  erythrocyte: 'eritrócito',
  leukocyte: 'leucócito',
  radiograph: 'radiografia',
  radiography: 'radiografia',
  ultrasound: 'ultrassom',
  ct: 'tomografia',
  mri: 'ressonância',
  scan: 'exame',
  contrast: 'contraste',
  fluoroscopy: 'fluoroscopia',
  endoscopy: 'endoscopia',
  bronchoscopy: 'broncoscopia',
  rhinoscopy: 'rinoscopia',
  cystoscopy: 'cistoscopia',
  laparoscopy: 'laparoscopia',
  thoracoscopy: 'toracoscopia',
  arthroscopy: 'artroscopia',
  electrocardiogram: 'eletrocardiograma',
  echocardiogram: 'ecocardiograma',
  bloodPressure: 'pressão arterial',
  monitoring: 'monitorização',
  telemetry: 'telemetria',
  ambulatory: 'ambulatorial',
  holter: 'Holter',
  protocol: 'protocolo',
  guideline: 'diretriz',
  consensus: 'consenso',
  statement: 'declaração',
  recommendation: 'recomendação',
  grade: 'grau',
  level: 'nível',
  evidence: 'evidência',
  study: 'estudo',
  trial: 'ensaio',
  cohort: 'coorte',
  case: 'caso',
  series: 'série',
  report: 'relato',
  review: 'revisão',
  meta: 'meta',
  analysis: 'análise',
  systematic: 'sistemática',
  randomized: 'randomizado',
  controlled: 'controlado',
  blinded: 'cego',
  placebo: 'placebo',
  comparator: 'comparador',
  outcome: 'desfecho',
  endpoint: 'desfecho',
  surrogate: 'substituto',
  biomarker: 'biomarcador',
  validation: 'validação',
  reproducibility: 'reprodutibilidade',
  accuracy: 'acurácia',
  precision: 'precisão',
  bias: 'viés',
  confounding: 'confusão',
  limitation: 'limitação',
  caveat: 'ressalva',
  uncertainty: 'incerteza',
  gap: 'lacuna',
  need: 'necessidade',
  future: 'futuro',
  direction: 'direção',
  emerging: 'emergente',
  novel: 'novo',
  experimental: 'experimental',
  investigational: 'investigacional',
  compassionate: 'compassivo',
  use: 'uso',
  expanded: 'expandido',
  access: 'acesso',
  named: 'nomeado',
  patient: 'paciente',
  import: 'importação',
  export: 'exportação',
  regulatory: 'regulatório',
  approval: 'aprovação',
  registration: 'registro',
  withdrawal: 'retirada',
  recall: 'recall',
  adverse: 'adverso',
  event: 'evento',
  reporting: 'notificação',
  pharmacovigilance: 'farmacovigilância',
};

function splitCamelCaseKey(key: string): string[] {
  return key
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .split(/\s+/)
    .filter(Boolean);
}

function titleCasePhrase(lowerPhrase: string): string {
  const small = new Set(['e', 'ou', 'de', 'da', 'do', 'das', 'dos', 'em', 'na', 'no', 'a', 'o', 'com', 'por', 'para', 'versus']);
  return lowerPhrase
    .split(' ')
    .map((word, i) => {
      if (!word) return word;
      if (i > 0 && small.has(word)) return word;
      return word.charAt(0).toUpperCase() + word.slice(1);
    })
    .join(' ');
}

/**
 * Traduz chave de subseção editorial (camelCase em inglês) para rótulo em português.
 */
export function translateEditorialSubsectionKey(key: string): string {
  const direct = FULL_KEY_LABELS[key];
  if (direct) return direct;

  const parts = splitCamelCaseKey(key);
  if (parts.length === 0) return key;

  const mapped = parts.map((part) => {
    const low = part.toLowerCase();
    return CAMEL_PARTS_PT[low] ?? part;
  });

  const lowerPhrase = mapped.join(' ');
  const looksUntranslated = mapped.every((w, i) => w === parts[i] || w.toLowerCase() === parts[i].toLowerCase());
  if (looksUntranslated && parts.join('') === key.replace(/\s/g, '')) {
    return titleCasePhrase(parts.join(' ').toLowerCase());
  }

  return titleCasePhrase(lowerPhrase);
}

/** Nomes de sistema em inglês (conteúdo) → português para cartões de achados. */
const SYSTEM_TITLE_PT: Record<string, string> = {
  respiratory: 'Respiratório',
  cardiovascular: 'Cardiovascular',
  gastrointestinal: 'Gastrointestinal',
  neurologic: 'Neurológico',
  neurological: 'Neurológico',
  dermatologic: 'Dermatológico',
  dermatological: 'Dermatológico',
  renal: 'Renal',
  urinary: 'Urinário',
  hepatic: 'Hepático',
  ocular: 'Ocular',
  ophthalmic: 'Oftálmico',
  musculoskeletal: 'Músculo-esquelético',
  orthopedic: 'Ortopédico',
  orthopaedic: 'Ortopédico',
  reproductive: 'Reprodutivo',
  endocrine: 'Endócrino',
  hematologic: 'Hematológico',
  haematological: 'Hematológico',
  immunologic: 'Imunológico',
  immunological: 'Imunológico',
  lymphatic: 'Linfático',
  behavioral: 'Comportamental',
  behavioural: 'Comportamental',
  nutritional: 'Nutricional',
  metabolic: 'Metabólico',
  general: 'Geral',
  oral: 'Oral',
  dental: 'Odontológico',
  thoracic: 'Torácico',
  pulmonary: 'Pulmonar',
  abdominal: 'Abdominal',
  integumentary: 'Tegumentar',
  immune: 'Imune',
  multisystemic: 'Multissistêmico',
  multiSystemic: 'Multissistêmico',
};

export function translateSystemGroupTitle(title: string): string {
  const t = title.trim();
  const key = t.toLowerCase().replace(/\s+/g, '');
  const compact = SYSTEM_TITLE_PT[t] ?? SYSTEM_TITLE_PT[key] ?? SYSTEM_TITLE_PT[t.toLowerCase()];
  if (compact) return compact;
  return title;
}
