/** Compact editorial labels for the procedure chapter index; full headings stay in the reader. */
const PROCEDURE_CHAPTER_LABELS: Record<string, string> = {
  "1. O que é uma Sonda de Esofagostomia? (E-tube / O-tube)": "Definição",
  "2. Quando Indicar: O Limiar do Déficit Calórico": "Quando indicar",
  "3. Candidatos Clássicos e Indicações Frequentes": "Indicações frequentes",
  "4. Comparação Entre as Vias de Suporte Enteral": "Vias de alimentação",
  "5. Contraindicações e Quando NÃO Colocar": "Contraindicações",
  "6. Fluxograma de Decisão Clínica": "Decisão clínica",
  "7. Anatomia Cirúrgica Cervical: Relação Estrita com a Jugular 🧠": "Anatomia cervical",
  "8. Diferenças Entre Cães e Gatos": "Cães e gatos",
  "9. Seleção de Calibres French (Fr)": "Calibres",
  "10. Qual Sonda Usar no Brasil? 🇧🇷 (Dispositivos Comerciais)": "Tipos de sonda",
  "11. Checklist Completo de Materiais de Bancada": "Materiais",
  "12. Técnica Cirúrgica Passo a Passo (Técnica Retrógrada com Carmalt)": "Técnica com Carmalt",
  "15. Confirmação Radiográfica Obrigatória Antes de Alimentar 🩻": "Radiografia",
  "16. Radiografias comentadas": "Radiografias comentadas",
  "17. Fixação e curativo cervical": "Fixação e curativo",
  "18. Protocolo Alimentar: Quando e Como Iniciar": "Início da alimentação",
  "20. Cálculo Energético: Do RER ao Volume de Dieta": "RER e volume de dieta",
  "21. Síndrome de realimentação ⚠️": "Realimentação",
  "22. Balanço Hídrico das Lavagens e Medicamentos pela Sonda": "Água e medicamentos",
  "23. Inspeção Diária do Estoma: Saudável / Infecção": "Cuidados do estoma",
  "24. Obstrução da Sonda e a Física da Seringa 🔬": "Sonda obstruída",
  "25. Manejo Imediato de Deslocamentos, Vômitos e Intercorrências": "Intercorrências",
  "26. Técnicas Alternativas (Tunelizador MILA e Normógrada)": "Técnicas alternativas",
  "27. Quando e Como Remover a Sonda (Cicatrização por 2ª Intenção)": "Retirada da sonda",
  "28. Orientações de Alta Hospitalar e Treinamento do Tutor": "Alta e orientação",
  "29. Os 15 Erros Fatais Que o Veterinário Deve Evitar 🚨": "Erros a evitar",
  "30. Referências Bibliográficas e Diretrizes Clínicas Oficiais": "Referências",
  "1. O que é a biópsia incisional e conceito oncológico fundamental": "Conceito",
  "2. Comparação prática: PAAF, core, punch, incisional ou excisional?": "Tipos de biópsia",
  "3. Quando indicar biópsia incisional (Indicações fortes)": "Indicações",
  "4. Quando NÃO fazer uma biópsia incisional": "Contraindicações",
  "5. Algoritmo prático de decisão clínica no plantão": "Decisão clínica",
  "6. Antes da biópsia: planeje a cirurgia definitiva primeiro": "Planejamento cirúrgico",
  "7. O princípio sagrado dos compartimentos anatômicos": "Compartimentos",
  "8. Extensão cirúrgica em sarcomas: por que o trajeto precisa ser planejado": "Trajeto em sarcomas",
  "9. Imagem avançada: antes ou depois da biópsia?": "Imagem prévia",
  "10. Particularidades: Sarcomas em cães e gatos (FISS)": "Sarcomas e FISS",
  "11. Relato de caso demonstrativo: Ressecção vertebral com trajeto em bloco": "Caso clínico",
  "12. Materiais e montagem da bancada cirúrgica": "Materiais",
  "13. Sedação, anestesia e analgesia multimodal": "Anestesia e analgesia",
  "14. Passo 1 — Documentar a massa antes de interferir nela 🩺": "Documentar a massa",
  "15. Passo 2 — Preparo do campo e anestesia local perilesional": "Preparo do campo",
  "16. Passo 3 — Incisão cutânea e exposição cirúrgica mínima": "Incisão e exposição",
  "17. Passo 4 — Retirada da cunha com bisturi frio": "Retirada da cunha",
  "18. Passo 5 — O tecido normal deve entrar na amostra? (Nuance moderna)": "Tecido normal",
  "19. Passo 6 — Nunca esmague o fragmento (Manipulação delicada)": "Manuseio do fragmento",
  "20. Passo 7 — Eletrocautério: ótimo para hemostasia, ruim para a amostra": "Eletrocautério",
  "21. Passo 8 — Controle rigoroso de hemorragia e fechamento": "Hemostasia e fechamento",
  "22. Passo 9 — Marque o trajeto cirúrgico no prontuário 📸": "Registro do trajeto",
  "23. Particularidades críticas: Massas Orais e Melanoma Oral": "Massas orais",
  "24. Como escolher o ponto da amostra: fragmento representativo 🎯": "Escolha da amostra",
  "25. Heterogeneidade tumoral: lições do estudo prospectivo Ferraris et al. 2026": "Heterogeneidade tumoral",
  "26. Imprint citológico antes da formalina: técnica e cuidados": "Imprint citológico",
  "27. Fixação tecidual em formalina tamponada neutra a 10%": "Fixação em formalina",
  "28. Suspeita de doença infecciosa associada (Fungos profundos e bactérias)": "Suspeita de infecção",
  "29. O formulário enviado ao patologista faz parte da biópsia": "Pedido ao patologista",
  "30. Da sala cirúrgica ao patologista: como as margens são avaliadas": "Avaliação das margens",
  "31. O que esperar do laudo histopatológico e seus limites": "Laudo histopatológico",
  "32. Discordância entre patologistas e conduta diante de laudo discordante": "Laudo discordante",
  "33. Os 10 erros que mais prejudicam o paciente oncológico 🚨": "Erros a evitar",
  "34. Tabela completa de complicações cirúrgicas: mecanismo e prevenção": "Complicações",
  "35. Pós-operatório imediato e seguimento oncológico": "Pós-operatório",
  "36. Checklist de bolso interativo ✅ (Antes, Durante e Depois)": "Checklist",
  "37. O que precisa ser memorizado 🧠 (Os 8 pontos de ouro)": "Pontos essenciais",
  "38. Mapa das fontes do projeto e evidências científicas": "Fontes e evidências",
  "39. Bibliografia principal completa (Formato ABNT)": "Bibliografia",
  "A ideia mais importante": "Conceito",
  "Por que ele rompe e por que o exame funciona?": "Biomecânica",
  "1. Antes de pôr a mão no joelho: o que observar": "Avaliação inicial",
  "2. Anatomia mínima para “enxergar” com a mão": "Anatomia do joelho",
  "3. Teste de gaveta cranial: como fazer": "Gaveta cranial",
  "4. Como interpretar a gaveta cranial": "Interpretar a gaveta",
  "5. Teste de compressão tibial: como fazer": "Compressão tibial",
  "6. O que cada teste “prova” na biomecânica": "Comparação dos testes",
  "7. Quando o teste pode enganar": "Limitações dos testes",
  "8. Sequência prática completa (ordem sugerida)": "Sequência do exame",
  "9. Achados que aumentam a suspeita de LCCr": "Achados sugestivos",
  "10. O exame ortopédico sozinho “fecha” diagnóstico?": "Diagnóstico",
  "11. Pérolas clínicas": "Dicas clínicas",
  "Tabela de manobras (referência rápida)": "Tabela de manobras",
  "Segurança e limitações": "Segurança",
  "Figura de referência": "Figura",
  "Vídeos demonstrativos (YouTube)": "Vídeos",
  "Quando usar": "Indicações",
  "Materiais": "Materiais",
  "Passo a passo visual": "Passo a passo",
  "Como saber se ficou boa": "Qualidade da bandagem",
  "Monitoramento e retorno": "Monitoramento",
  "Erros comuns": "Erros comuns",
  "Fontes": "Referências",
  "1. Indicações Clínicas": "Indicações",
  "2. Preparação do Paciente e Anestesia": "Preparo e anestesia",
  "3. Equipamentos Necessários": "Materiais",
  "4. Técnica de Punção": "Técnica de punção",
  "5. Por que fazemos assim? (Fundamentação Anatômica & Fisiológica)": "Anatomia e fisiologia",
  "6. Fluxograma do Procedimento": "Fluxograma",
  "7. Manejo Pós-Tratamento": "Cuidados posteriores",
  "Definição e Objetivos": "Objetivos",
  "Onde Consultar Ilustrações nos Livros de Referência": "Figuras nos livros",
  "1. Quando fazer? (Indicações)": "Indicações",
  "2. Quando evitar ou tomar cuidado? (Contraindicações e Precauções)": "Contraindicações",
  "3. Materiais de Bolso (Checklist)": "Materiais",
  "4. Técnica Rápida — Escolha do Método": "Escolha da técnica",
  "5. Armadilhas Práticas no Plantão": "Armadilhas",
  "6. Lavagem Peritoneal Diagnóstica (LPD / DPL)": "Lavagem peritoneal",
  "7. O que solicitar na análise do líquido?": "Análise do líquido",
  "8. Interpretação Citológica de Emergência": "Citologia",
  "9. Algoritmo de Plantão": "Decisão clínica",
  "10. Complicações Possíveis": "Complicações",
  "1. Para que serve uma amostra arterial?": "Indicações",
  "2. Resumo Rápido — Cão vs. Gato": "Cães e gatos",
  "3. Antes de Conter o Paciente": "Preparo do paciente",
  "4. Sedar ou Não Sedar? & Paciente Dispneico": "Sedação e dispneia",
  "5. CÃO — Coleta pela Artéria Dorsal Pedal (1ª Escolha)": "Cão: dorsal pedal",
  "6. CÃO — Quando Usar a Artéria Femoral?": "Cão: femoral",
  "7. GATO — Coleta Arterial & Manejo Cat Friendly": "Gato: coleta arterial",
  "8. Como Confirmar se a Amostra é Realmente Arterial?": "Confirmar a amostra",
  "9. Manejo Crítico da Amostra (Os Primeiros 30 Segundos)": "Preservar a amostra",
  "10. Tabela Mestra de Erros Pré-Analíticos": "Erros pré-analíticos",
  "11. Complicações e Contraindicações": "Complicações e riscos",
  "12. Cuidados e Monitoramento Pós-Procedimento": "Cuidados posteriores",
  "13. Valores de Referência & Regras de Interpretação": "Valores e interpretação",
  "14. Cateter Arterial: Quando Indicar?": "Cateter arterial",
  "15. Fluxograma de Decisão na Coleta Arterial": "Decisão clínica",
  "16. Box de Bolso — Não Esquecer 🩸": "Checklist",
  "17. Referências Técnicas": "Referências",
  "1. O que Estamos Coletando? (AMO vs. BMO)": "Aspirado ou biópsia",
  "2. Fisiologia & Por que não podemos furar qualquer parte de qualquer osso?": "Fisiologia óssea",
  "3. Quando Pedir Medula Óssea? (Indicações Clínicas)": "Indicações",
  "4. Quando a Medula NÃO é Obrigatória em Citopenias": "Quando dispensar coleta",
  "5. Trombocitopenia Grave Contraindica a Punção?": "Trombocitopenia",
  "6. Contraindicações e Cuidados Locais": "Contraindicações",
  "7. Escolha do Local Anatômico 🦴": "Local de coleta",
  "8. Equipamentos e o Papel Vital do Estilete": "Instrumental e estilete",
  "9. Preparação dos Materiais ANTES de Anestesiar": "Preparo dos materiais",
  "10. Anticoagulante: Anticoagular NÃO é Diluir": "Anticoagulante",
  "11. Sedação, Anestesia & Analgesia Perióstea": "Anestesia e analgesia",
  "12. Técnica de Entrada no Espaço Medular": "Entrada na medula",
  "13. Passo a Passo por Sítio Anatômico": "Técnica por local",
  "14. Técnica de Aspiração e Controle de Volume": "Aspiração e volume",
  "15. \"Veio Sangue. Acertei?\" — O Reconhecimento das Espículas": "Reconhecer espículas",
  "16. O que Fazer Diante de um \"Dry Tap\" (Aspirado Seco)?": "Aspirado seco",
  "17. Manuseio Imediato & Preparo dos Esfregaços": "Preparo dos esfregaços",
  "18. Dicas de Ouro de Laboratório & Envio": "Envio ao laboratório",
  "19. Raciocínio Clínico na Interpretação do Mielograma": "Interpretar o mielograma",
  "20. Quando e Como Fazer a Biópsia Core (BMO)?": "Biópsia core",
  "21. Complicações & Cuidados Pós-Procedimento": "Complicações e cuidados",
  "22. Fluxograma de Decisão na Coleta de Medula": "Decisão clínica",
  "23. Box de Bolso — Antes de Puncionar Medula 🩸": "Checklist",
  "24. Referências Técnicas": "Referências",
  "1. A Ideia Central e Quando Sondar 🎯": "Indicações",
  "2. Anatomia Cirúrgico-Clínica Fundamental 🧠": "Anatomia",
  "3. Ilustração Técnica: Anatomia Sagital e Métodos de Sondagem 📸": "Esquema das técnicas",
  "4. Seleção de Materiais e Escolha do Cateter 🩺": "Materiais e cateter",
  "5. Regra de Ouro: Medição Prévia do Comprimento 📏": "Medir o comprimento",
  "6. Parte I — Cadela: Posicionamento e Preparo Asséptico 🐶": "Cadela: preparo",
  "7. Técnica Principal na Cadela: Palpação Digital (\"Dedo como Teto\") 👆": "Cadela: palpação digital",
  "8. Técnica Alternativa na Cadela: Visualização com Espéculo ou Otoscópio 🔦": "Cadela: visualização",
  "9. Cadela Pequena (<10 kg): A Técnica dos Dois Cateteres ⭐": "Cadela: dois cateteres",
  "10. Casos Complexos na Cadela: Técnica de Fio-Guia / Seldinger Modificado 🪢": "Cadela: fio-guia",
  "11. Parte II — Gata: Particularidades Anatômicas e Sedação 🐱": "Gata: preparo",
  "12. Técnica às Cegas na Gata (Passo a Passo) 🐾": "Gata: técnica às cegas",
  "13. Gata Difícil: Visualização com Cone de Otoscópio e Dois Cateteres 🔦": "Gata: visualização",
  "14. Confirmação do Posicionamento Vesical: O Que Fazer Quando a Urina Não Vem? 🧪": "Confirmar posição",
  "15. Balão de Retenção Foley: O Erro Crítico que Não Pode Ocorrer ⚠️": "Balão da Foley",
  "16. Ilustração Técnica: Montagem do Sistema Fechado e Prevenção de ITU 📸": "Esquema do circuito",
  "17. Montagem e Fixação do Sistema Fechado de Drenagem 🛡️": "Fixação e circuito",
  "18. Prevenção de ITU Hospitalar Associada ao Cateter (CAUTI) — Diretrizes ISCAID 2019 🔬": "Prevenção de ITU",
  "19. Quando Parar Imediatamente e Reavaliar 🚨": "Quando interromper",
  "20. Tabela de Troubleshooting Clínico Rápido ⚙️": "Intercorrências",
  "21. Fluxograma de Decisão Clínica para Sondagem em Fêmeas 🔄": "Decisão clínica",
  "22. Box de Bolso — Checklist de Ouro do Plantão 📋": "Checklist",
  "23. Referências Técnicas e Bibliográficas 📚": "Referências",
  "1. A Ideia Central e Anatomia do Espaço Subaracnoide 🧠": "Anatomia e conceito",
  "2. Quando Vale a Pena Coletar LCR? Indicações Clínicas 🎯": "Indicações",
  "3. A Pergunta Mais Importante: \"Este Paciente Pode Herniar?\" 🚨": "Risco de herniação",
  "4. Documentação de Imagem: Herniação de Tronco Encefálico Pós-Coleta 📸": "Imagem da herniação",
  "5. Contraindicações Formais à Punção Cisternal ⛔": "Contraindicações",
  "6. Alerta Crítico de Raça: Cavalier King Charles Spaniel 🐶": "Cavalier: cuidados",
  "7. Cisternal vs. Lombar: Qual Sítio Escolher? ⚖️": "Cisterna ou lombar",
  "8. Materiais e Equipamentos Obrigatórios 🩺": "Materiais",
  "9. Ilustração Técnica: Triângulo Atlanto-Occipital e Punção Sagital 📸": "Esquema anatômico",
  "10. Parte I — Punção Cisternal: Posicionamento Milimétrico 📐": "Cisterna: posição",
  "11. Delimitação do Triângulo Atlanto-Occipital 🔺": "Triângulo anatômico",
  "12. Inserção da Agulha Cisternal Passo a Passo 💉": "Cisterna: inserção",
  "13. Regra de Segurança Vital: Gotejamento Passivo e NUNCA Aspirar 🚫": "Gotejamento passivo",
  "14. Intercorrências na Cisternal: Contato Ósseo, Sangue e Limite de Tentativas ⚠️": "Cisterna: intercorrências",
  "15. Parte II — Punção Lombar: Diferenças Anatômicas Cão vs. Gato 🦴": "Lombar: anatomia",
  "16. Técnica do \"Trilho Ósseo\" na Punção Lombar 🪡": "Lombar: técnica",
  "17. Volume de Coleta e Fracionamento em Tubos 🧪": "Volume e fracionamento",
  "18. Corrida Contra o Relógio: Preservação da Amostra (30–60 min) ⏱️": "Preservar a amostra",
  "19. Valores de Referência e Avaliação Macroscópica 📊": "Valores de referência",
  "20. Padrões Citológicos e Interpretação Básica 🔬": "Interpretar a citologia",
  "21. Distinção: Hemorragia Verdadeira vs. Acidente de Punção 🩸": "Sangue na amostra",
  "22. Monitoramento Pós-Procedimento e Complicações 🚨": "Monitoramento e riscos",
  "23. Tabela de Troubleshooting Clínico Rápido ⚙️": "Intercorrências",
  "24. Fluxograma de Decisão Clínica para Coleta de LCR 🔄": "Decisão clínica",
  "25. Box de Bolso — Checklist de Ouro e \"Nunca Faça\" 📋": "Checklist",
  "26. Referências Técnicas e Bibliográficas 📚": "Referências",
  "1. O que Muda entre o Cão e o Gato? 🐱🐶": "Cães e gatos",
  "2. Fisiopatologia Sistêmica e o Perigo da Hipercalemia ⚡": "Hipercalemia",
  "3. Triagem de Emergência e Banco Mínimo Laboratorial 📋": "Triagem",
  "4. Estabilização Pré-Desobstrução e Controle da Hipercalemia 💉": "Estabilização",
  "5. Analgesia e Protocolo Anestésico / Sedativo 😴": "Anestesia e analgesia",
  "6. Cistocentese Descompressiva: Fazer ou Não? (iCatCare 2025) 🎯": "Cistocentese",
  "7. Ilustração Técnica: Desobstrução Uretral Felina 📸": "Esquema felino",
  "8. Materiais e Seleção do Cateter Felino 🩺": "Cateter felino",
  "9. Parte I — Gato: Técnica Passo a Passo de Desobstrução 🐾": "Gato: desobstrução",
  "10. Sonda de Demora e Circuito Fechado no Gato (24–36 Horas) 🛡️": "Gato: sonda de demora",
  "11. Vigilância da Diurese Pós-Obstrutiva (POD) 🌊": "Diurese pós-obstrutiva",
  "12. Antibiótico e Prazosina: Mudanças Cruciais de Prática (iCatCare 2025) 💊": "Antibiótico e prazosina",
  "13. O que Fazer Quando a Sonda Não Passa no Gato? 🚨": "Gato: falha de passagem",
  "14. Cistite Idiopática Felina (CIF / FIC): Manejo Multimodal (MEMO) 🐱": "Cistite idiopática",
  "15. Parte II — Cão com Obstrução Uretral: Mecânica vs. Funcional 🐶": "Cão: tipos de obstrução",
  "16. Diagnóstico por Imagem no Cão Obstruído 📸": "Cão: diagnóstico por imagem",
  "17. Ilustração Técnica: Retro-hidropropulsão Canina 📸": "Esquema canino",
  "18. Técnica de Retro-hidropropulsão no Cão Macho Passo a Passo 🪨": "Cão: retro-hidropropulsão",
  "19. Confirmação por Imagem e Documentação Radiográfica (Frontiers 2023) 📸": "Confirmação por imagem",
  "20. Destino Definitivo do Cálculo e Análise Mineral Quantitativa 🔬": "Destino do cálculo",
  "21. Falha de Desobstrução no Cão: Cistostomia Pigtail como Ponte 🪢": "Cistostomia de resgate",
  "22. Obstrução Uretral na Cadela: O que Pensar? 🐕": "Obstrução na cadela",
  "24. Fluxograma de Decisão Clínica na Obstrução Uretral 🔄": "Decisão clínica",
  "25. Box de Bolso — Checklist de Ouro e \"Erros Fatais\" 📋": "Checklist",
  "1. O Princípio Fundamental & Bases Técnicas 🩺": "Conceito",
  "2. Quando Sondar um Cão Macho? Indicações Clínicas e de UTI 🎯": "Indicações",
  "3. Quando NÃO Fazer uma Sondagem Rotineira (Contraindicações) 🚫": "Contraindicações",
  "4. Sondagem vs. Cistocentese: Cuidados Pré-Analíticos 🔬": "Cuidados pré-analíticos",
  "5. Anatomia Sagital da Uretra Canina: Os 3 Pontos de Resistência 🦴": "Anatomia da uretra",
  "6. O Truque Mais Importante da Técnica: A Manobra de Retificação Caudal 💡": "Retificação caudal",
  "7. Escolha do Cateter: Tipos, Calibres e Materiais 📏": "Escolha do cateter",
  "8. Mensuração Prévia Obrigatória: Como Evitar o Nó Intravesical 📏": "Medir o comprimento",
  "9. Lista de Materiais Necessários para o Procedimento 📦": "Materiais",
  "10. Sedação e Manejo do Paciente Obstruído 🚨": "Sedação e obstrução",
  "11. Posicionamento e Antissepsia Rigorosa 🧼": "Posição e antissepsia",
  "12. Técnica Passo a Passo da Sondagem Uretral 🐾": "Passo a passo",
  "13. A Regra da Resistência: O que Fazer Quando a Sonda Trava? 🚨": "Resistência à passagem",
  "14. Não Saiu Urina: Como Confirmar se a Sonda Está na Bexiga? 💧": "Confirmar posição",
  "15. Manejo Específico da Sonda Foley de Silicone 🎈": "Sonda Foley",
  "16. Fixação Externa Atraumática e Montagem do Circuito Fechado 🔒": "Fixação e circuito",
  "17. Prevenção de CAUTI (Diretrizes ISCAID 2019) 🦠": "Prevenção de ITU",
  "18. Abordagem do Cão Obstruído por Uretrólito: Não \"Empurre a Pedra\" 🛑": "Uretrólitos",
  "19. Recursos Avançados: O Uso do Fio-Guia Hidrofílico (0,035\") ⭐": "Fio-guia",
  "21. Fluxograma de Decisão Clínica na Sondagem Uretral Canina 🔄": "Decisão clínica",
  "22. Box de Bolso — Checklist de Ouro e \"NUNCA FAÇA\" 📋": "Checklist",
};

export function getProcedureChapterLabel(heading: string): string {
  const cleaned = heading.replace(/\*\*|==/g, '').trim();
  const number = cleaned.match(/^(\d+)\.\s+/)?.[1];
  const short = PROCEDURE_CHAPTER_LABELS[heading];
  if (short) return number ? `${number}. ${short}` : short;

  // Keep future headings compact until a specific editorial label is supplied.
  const base = cleaned.replace(/\([^)]*\)/g, '').split(/\s+[—–]\s+|:\s+/)[0].trim();
  if (base.length <= 38) return base;
  return `${base.slice(0, 37).replace(/\s+\S*$/, '').trim()}…`;
}
