import type { EvidenceReference } from './evidenceCatalog'
import { getComorbidityOptionById } from './comorbidityCatalog'
import { THERAPEUTIC_PROFILE_REGISTRY_VERSION } from './schemaVersion'
import type { CanonicalNutritionInput, CanonicalSpecies } from './types'

export type TherapeuticEnergyPolicy = 'no_direct_change' | 'select_target' | 'clinician_required'

export interface NutrientTargetRule {
  nutrientKey: string
  labelPt: string
  basis: 'dry_matter_pct' | 'mg_per_kg_dm' | 'per_1000_kcal' | 'percent_me' | 'g_day'
  type: 'minimum' | 'maximum' | 'range' | 'qualitative' | 'laboratory_driven'
  minimum?: number
  maximum?: number
  unit: string
  descriptionPtBr: string
  evidenceIds: string[]
  confidence: EvidenceReference['confidence']
}

export interface TherapeuticNutritionProfileV3 {
  id: string
  version: string
  species: Array<CanonicalSpecies>
  diagnosisCode: string
  displayNamePtBr: string
  requiredStage?: boolean
  requiredSubtype?: boolean
  energy: {
    policy: TherapeuticEnergyPolicy
    recommendationPtBr: string
    evidenceIds: string[]
  }
  nutrientTargets: NutrientTargetRule[]
  contraindications: string[]
  monitoring: string[]
  conflictProfileIds: string[]
  evidenceIds: string[]
  confidence: EvidenceReference['confidence']
}

export const THERAPEUTIC_NUTRITION_PROFILES_V3: TherapeuticNutritionProfileV3[] = [
  {
    id: 'ckd_dog_iris_1',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog'],
    diagnosisCode: 'chronic_kidney_disease',
    displayNamePtBr: 'DRC canina — IRIS estágio 1',
    requiredStage: true,
    energy: {
      policy: 'no_direct_change',
      recommendationPtBr: 'Manter energia suficiente para peso e EMC; não restringir calorias apenas por DRC.',
      evidenceIds: ['iris-ckd-2023'],
    },
    nutrientTargets: [
      {
        nutrientKey: 'phosphorusPct',
        labelPt: 'Fósforo dietético',
        basis: 'dry_matter_pct',
        type: 'laboratory_driven',
        descriptionPtBr: 'Estágio 1: monitorar fósforo sérico; restrição dietética não automática.',
        evidenceIds: ['iris-ckd-2023'],
        confidence: 'high',
        unit: '% MS',
      },
    ],
    contraindications: ['Restrição proteica automática'],
    monitoring: 'Creatinina/SDMA, fósforo, UPC, peso, EMC.',
    conflictProfileIds: ['hepatic_encephalopathy'],
    evidenceIds: ['iris-ckd-2023'],
    confidence: 'high',
  },
  {
    id: 'ckd_dog_iris_2',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog'],
    diagnosisCode: 'chronic_kidney_disease',
    displayNamePtBr: 'DRC canina — IRIS estágio 2',
    requiredStage: true,
    energy: { policy: 'no_direct_change', recommendationPtBr: 'Energia para manter peso; alta densidade se hiporexia.', evidenceIds: ['iris-ckd-2023'] },
    nutrientTargets: [
      {
        nutrientKey: 'phosphorusPct',
        labelPt: 'Fósforo dietético',
        basis: 'dry_matter_pct',
        type: 'maximum',
        maximum: 0.5,
        unit: '% MS',
        descriptionPtBr: 'Considerar dieta renal e fósforo moderado conforme fósforo sérico.',
        evidenceIds: ['iris-ckd-2023'],
        confidence: 'moderate',
      },
      {
        nutrientKey: 'crudeProteinPct',
        labelPt: 'Proteína',
        basis: 'dry_matter_pct',
        type: 'range',
        minimum: 14,
        maximum: 20,
        unit: '% MS',
        descriptionPtBr: 'Proteína moderada preservando massa muscular.',
        evidenceIds: ['iris-ckd-2023', 'applied-clinical-nutrition'],
        confidence: 'moderate',
      },
    ],
    contraindications: ['Proteína zero'],
    monitoring: 'Fósforo sérico alvo <4,6 mg/dL, UPC, peso, EMC.',
    conflictProfileIds: ['hepatic_encephalopathy', 'weight_loss_dog'],
    evidenceIds: ['iris-ckd-2023'],
    confidence: 'high',
  },
  {
    id: 'ckd_dog_iris_3',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog'],
    diagnosisCode: 'chronic_kidney_disease',
    displayNamePtBr: 'DRC canina — IRIS estágio 3',
    requiredStage: true,
    energy: { policy: 'no_direct_change', recommendationPtBr: 'Priorizar ingestão e densidade energética.', evidenceIds: ['iris-ckd-2023'] },
    nutrientTargets: [
      {
        nutrientKey: 'phosphorusPct',
        labelPt: 'Fósforo',
        basis: 'dry_matter_pct',
        type: 'maximum',
        maximum: 0.4,
        unit: '% MS',
        descriptionPtBr: 'Redução de fósforo dietético; meta sérica <5,0 mg/dL.',
        evidenceIds: ['iris-ckd-2023'],
        confidence: 'high',
      },
      {
        nutrientKey: 'crudeProteinPct',
        labelPt: 'Proteína',
        basis: 'dry_matter_pct',
        type: 'range',
        minimum: 12,
        maximum: 18,
        unit: '% MS',
        descriptionPtBr: 'Proteína de alta qualidade; ajuste conforme UPC e palatabilidade (IRIS estágio 3).',
        evidenceIds: ['iris-ckd-2023', 'applied-clinical-nutrition'],
        confidence: 'high',
      },
      {
        nutrientKey: 'sodiumPct',
        labelPt: 'Sódio',
        basis: 'dry_matter_pct',
        type: 'maximum',
        maximum: 0.25,
        unit: '% MS',
        descriptionPtBr: 'Moderação de sódio se hipertensão ou edema.',
        evidenceIds: ['iris-ckd-2023', 'applied-clinical-nutrition'],
        confidence: 'moderate',
      },
    ],
    contraindications: [],
    monitoring: 'Fósforo, potássio, peso, EMC, apetite.',
    conflictProfileIds: ['diabetes_dog'],
    evidenceIds: ['iris-ckd-2023'],
    confidence: 'high',
  },
  {
    id: 'ckd_cat_iris_2',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['cat'],
    diagnosisCode: 'chronic_kidney_disease',
    displayNamePtBr: 'DRC felina — IRIS estágio 2',
    requiredStage: true,
    energy: { policy: 'no_direct_change', recommendationPtBr: 'Manter peso e massa muscular.', evidenceIds: ['iris-ckd-2023'] },
    nutrientTargets: [
      {
        nutrientKey: 'phosphorusPct',
        labelPt: 'Fósforo',
        basis: 'dry_matter_pct',
        type: 'range',
        minimum: 0.3,
        maximum: 0.6,
        unit: '% MS',
        descriptionPtBr: 'Ajustar conforme fósforo sérico e palatabilidade.',
        evidenceIds: ['iris-ckd-2023'],
        confidence: 'moderate',
      },
      {
        nutrientKey: 'crudeProteinPct',
        labelPt: 'Proteína',
        basis: 'dry_matter_pct',
        type: 'range',
        minimum: 28,
        maximum: 35,
        unit: '% MS',
        descriptionPtBr: 'Evitar restrição proteica indiscriminada em gatos.',
        evidenceIds: ['iris-ckd-2023'],
        confidence: 'moderate',
      },
    ],
    contraindications: ['Taurina ausente'],
    monitoring: 'Fósforo, potássio, peso, BCS, MCS.',
    conflictProfileIds: ['diabetes_cat_insulin', 'diabetes_cat_sglt2'],
    evidenceIds: ['iris-ckd-2023'],
    confidence: 'high',
  },
  {
    id: 'diabetes_dog',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog'],
    diagnosisCode: 'diabetes_mellitus',
    displayNamePtBr: 'Diabetes mellitus canina',
    energy: {
      policy: 'select_target',
      recommendationPtBr: 'Energia conforme peso ideal/objetivo corporal; sem multiplicador de diabetes.',
      evidenceIds: ['aaha-2021-nutrition', 'applied-clinical-nutrition'],
    },
    nutrientTargets: [
      {
        nutrientKey: 'crudeProteinPct',
        labelPt: 'Proteína',
        basis: 'per_1000_kcal',
        type: 'minimum',
        minimum: 45,
        unit: 'g/1000 kcal',
        descriptionPtBr: 'Proteína de alta qualidade; horários de refeição consistentes (AAHA 2021).',
        evidenceIds: ['aaha-2021-nutrition', 'applied-clinical-nutrition'],
        confidence: 'moderate',
      },
      {
        nutrientKey: 'crudeFiberPct',
        labelPt: 'Fibra',
        basis: 'dry_matter_pct',
        type: 'range',
        minimum: 7,
        maximum: 15,
        unit: '% MS',
        descriptionPtBr: 'Fibra mista (solúvel + insolúvel) moderada a aumentada quando tolerada.',
        evidenceIds: ['applied-clinical-nutrition', 'aaha-2021-nutrition'],
        confidence: 'moderate',
      },
      {
        nutrientKey: 'carbohydrateMePct',
        labelPt: 'Carboidratos',
        basis: 'percent_me',
        type: 'maximum',
        maximum: 25,
        unit: '% ME',
        descriptionPtBr: 'Carboidrato complexo; evitar picos glicêmicos.',
        evidenceIds: ['applied-clinical-nutrition'],
        confidence: 'moderate',
      },
    ],
    contraindications: ['Açúcares simples', 'Horários irregulares'],
    monitoring: 'Peso, glicemia, apetite, adesão.',
    conflictProfileIds: ['pancreatitis_dog'],
    evidenceIds: ['aaha-2021-nutrition'],
    confidence: 'moderate',
  },
  {
    id: 'diabetes_cat_insulin',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['cat'],
    diagnosisCode: 'diabetes_mellitus',
    displayNamePtBr: 'Diabetes felina — insulina',
    requiredSubtype: true,
    energy: {
      policy: 'select_target',
      recommendationPtBr: 'Priorizar ingestão previsível; emagrecimento gradual se obeso.',
      evidenceIds: ['aaha-2026-cat-diabetes'],
    },
    nutrientTargets: [
      {
        nutrientKey: 'carbohydrateMePct',
        labelPt: 'Carboidratos',
        basis: 'percent_me',
        type: 'maximum',
        maximum: 12,
        unit: '% ME',
        descriptionPtBr: 'Baixo carboidrato, alta proteína quando compatível com comorbidades.',
        evidenceIds: ['aaha-2026-cat-diabetes'],
        confidence: 'moderate',
      },
    ],
    contraindications: ['Ingestão inconsistente'],
    monitoring: 'Glicemia, peso, apetite.',
    conflictProfileIds: ['ckd_cat_iris_2'],
    evidenceIds: ['aaha-2026-cat-diabetes'],
    confidence: 'high',
  },
  {
    id: 'diabetes_cat_sglt2',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['cat'],
    diagnosisCode: 'diabetes_mellitus',
    displayNamePtBr: 'Diabetes felina — SGLT2',
    requiredSubtype: true,
    energy: {
      policy: 'clinician_required',
      recommendationPtBr: 'Primeiras 2 semanas: manter dieta habitual; depois transição gradual se estável.',
      evidenceIds: ['aaha-2026-cat-diabetes'],
    },
    nutrientTargets: [],
    contraindications: [
      'Redução brusca de carboidratos nas primeiras 2 semanas',
      'Restrição calórica agressiva com hiporexia',
    ],
    monitoring: 'β-hidroxibutirato, peso, apetite, vômitos, desidratação.',
    conflictProfileIds: ['weight_loss_cat'],
    evidenceIds: ['aaha-2026-cat-diabetes'],
    confidence: 'high',
  },
  {
    id: 'urolith_struvite_dissolution',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog', 'cat'],
    diagnosisCode: 'urolithiasis',
    displayNamePtBr: 'Urolitíase — estruvita (dissolução)',
    requiredSubtype: true,
    energy: { policy: 'no_direct_change', recommendationPtBr: 'Sem alteração energética direta.', evidenceIds: ['acvim-urolith-2016'] },
    nutrientTargets: [
      {
        nutrientKey: 'urinaryPh',
        labelPt: 'pH urinário',
        basis: 'dry_matter_pct',
        type: 'qualitative',
        descriptionPtBr: 'Dieta de dissolução exclusiva; RSS estruvita baixa.',
        evidenceIds: ['acvim-urolith-2016'],
        confidence: 'moderate',
        unit: '—',
      },
    ],
    contraindications: ['Mistura com alimentos comuns'],
    monitoring: 'pH urinário, rechecagem radiográfica/ultra.',
    conflictProfileIds: ['urolith_calcium_oxalate_prevention'],
    evidenceIds: ['acvim-urolith-2016'],
    confidence: 'moderate',
  },
  {
    id: 'urolith_calcium_oxalate_prevention',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog', 'cat'],
    diagnosisCode: 'urolithiasis',
    displayNamePtBr: 'Urolitíase — oxalato de cálcio (prevenção)',
    requiredSubtype: true,
    energy: { policy: 'no_direct_change', recommendationPtBr: 'Aumentar água e diluição urinária.', evidenceIds: ['acvim-urolith-2016'] },
    nutrientTargets: [
      {
        nutrientKey: 'moisturePct',
        labelPt: 'Umidade',
        basis: 'dry_matter_pct',
        type: 'qualitative',
        descriptionPtBr: 'Priorizar alimento úmido e água adicionada.',
        evidenceIds: ['acvim-urolith-2016'],
        confidence: 'moderate',
        unit: '%',
      },
    ],
    contraindications: ['Acidificação excessiva', 'Suplemento de cálcio sem indicação'],
    monitoring: 'USG, recorrência, cálcio sérico.',
    conflictProfileIds: ['urolith_struvite_dissolution'],
    evidenceIds: ['acvim-urolith-2016'],
    confidence: 'moderate',
  },
  {
    id: 'obesity_dog',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog'],
    diagnosisCode: 'obesity',
    displayNamePtBr: 'Obesidade canina',
    energy: {
      policy: 'select_target',
      recommendationPtBr: 'AAHA sobre peso ideal; não usar MER do peso obeso.',
      evidenceIds: ['aaha-2021-nutrition'],
    },
    nutrientTargets: [
      {
        nutrientKey: 'crudeProteinPct',
        labelPt: 'Proteína',
        basis: 'g_day',
        type: 'minimum',
        minimum: 2.5,
        unit: 'g/kg peso ideal/dia',
        descriptionPtBr: 'Mínimo AAHA para preservar massa magra durante perda.',
        evidenceIds: ['aaha-2021-nutrition'],
        confidence: 'high',
      },
    ],
    contraindications: ['Restrição proteica indiscriminada'],
    monitoring: 'Peso semanal, EMC, adesão.',
    conflictProfileIds: ['critical_care_recovery'],
    evidenceIds: ['aaha-2021-nutrition'],
    confidence: 'high',
  },
  {
    id: 'pancreatitis_dog',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog'],
    diagnosisCode: 'pancreatitis',
    displayNamePtBr: 'Pancreatite canina',
    energy: { policy: 'select_target', recommendationPtBr: 'Ambulatorial: MER conforme ECC; hospital: RER e progressão.', evidenceIds: ['applied-clinical-nutrition'] },
    nutrientTargets: [
      {
        nutrientKey: 'etherExtractPct',
        labelPt: 'Gordura',
        basis: 'percent_me',
        type: 'maximum',
        maximum: 20,
        unit: '% ME',
        descriptionPtBr: 'Baixa gordura relativa; priorizar tolerância e ingestão.',
        evidenceIds: ['applied-clinical-nutrition'],
        confidence: 'low',
      },
    ],
    contraindications: ['Jejum prolongado rotineiro'],
    monitoring: 'Vômitos, dor, lipase, apetite.',
    conflictProfileIds: ['obesity_dog'],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'moderate',
  },
  {
    id: 'pancreatitis_cat',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['cat'],
    diagnosisCode: 'pancreatitis',
    displayNamePtBr: 'Pancreatite felina',
    energy: { policy: 'select_target', recommendationPtBr: 'Garantir energia e proteína; sem restrição universal de gordura.', evidenceIds: ['acvim-pancreatitis-cat-2021'] },
    nutrientTargets: [],
    contraindications: ['Copiar perfil canino automaticamente'],
    monitoring: ['Apetite', 'Cobalamina', 'Tríade felina'],
    conflictProfileIds: [],
    evidenceIds: ['acvim-pancreatitis-cat-2021', 'applied-clinical-nutrition'],
    confidence: 'moderate',
  },
  {
    id: 'ckd_cat_iris_1',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['cat'],
    diagnosisCode: 'chronic_kidney_disease',
    displayNamePtBr: 'DRC felina — IRIS estágio 1',
    requiredStage: true,
    energy: {
      policy: 'no_direct_change',
      recommendationPtBr: 'Manter energia; aumentar turnover hídrico com alimentos ≥70% umidade quando possível (AVCN cap. 15).',
      evidenceIds: ['applied-clinical-nutrition', 'iris-ckd-2023'],
    },
    nutrientTargets: [
      {
        nutrientKey: 'moisturePct',
        labelPt: 'Umidade dietética',
        basis: 'dry_matter_pct',
        type: 'qualitative',
        descriptionPtBr: 'Priorizar alimento úmido ou adicionar água para poliúria compensatória.',
        evidenceIds: ['applied-clinical-nutrition'],
        confidence: 'moderate',
        unit: '%',
      },
    ],
    contraindications: ['Restrição proteica automática'],
    monitoring: ['Peso', 'USG', 'Creatinina/SDMA', 'Apetite'],
    conflictProfileIds: ['diabetes_cat_insulin'],
    evidenceIds: ['applied-clinical-nutrition', 'iris-ckd-2023'],
    confidence: 'high',
  },
  {
    id: 'ckd_cat_iris_3',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['cat'],
    diagnosisCode: 'chronic_kidney_disease',
    displayNamePtBr: 'DRC felina — IRIS estágio 3–4',
    requiredStage: true,
    energy: {
      policy: 'no_direct_change',
      recommendationPtBr: 'Densidade energética elevada; evitar desnutrição em uremia (AVCN cap. 15).',
      evidenceIds: ['applied-clinical-nutrition', 'iris-ckd-2023'],
    },
    nutrientTargets: [
      {
        nutrientKey: 'phosphorusPct',
        labelPt: 'Fósforo',
        basis: 'dry_matter_pct',
        type: 'maximum',
        maximum: 0.5,
        unit: '% MS',
        descriptionPtBr: 'Restrição de fósforo; alvo sérico conforme IRIS.',
        evidenceIds: ['applied-clinical-nutrition', 'iris-ckd-2023'],
        confidence: 'high',
      },
      {
        nutrientKey: 'crudeProteinPct',
        labelPt: 'Proteína',
        basis: 'dry_matter_pct',
        type: 'range',
        minimum: 28,
        maximum: 40,
        unit: '% MS',
        descriptionPtBr: 'Proteína de alta qualidade; mínimo NRC ~40 g/Mcal para gatos.',
        evidenceIds: ['applied-clinical-nutrition', 'nrc-2006'],
        confidence: 'moderate',
      },
    ],
    contraindications: ['Taurina insuficiente'],
    monitoring: ['Fósforo', 'Potássio', 'BUN', 'Peso', 'MCS'],
    conflictProfileIds: ['hepatic_encephalopathy'],
    evidenceIds: ['applied-clinical-nutrition', 'iris-ckd-2023'],
    confidence: 'high',
  },
  {
    id: 'obesity_cat',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['cat'],
    diagnosisCode: 'obesity',
    displayNamePtBr: 'Obesidade felina',
    energy: {
      policy: 'select_target',
      recommendationPtBr: 'Perda gradual; preservar massa magra; alto risco de diabetes se obeso (AVCN cap. 9).',
      evidenceIds: ['applied-clinical-nutrition', 'aaha-2021-nutrition'],
    },
    nutrientTargets: [
      {
        nutrientKey: 'crudeProteinPct',
        labelPt: 'Proteína',
        basis: 'g_day',
        type: 'minimum',
        minimum: 5,
        unit: 'g/kg peso ideal/dia',
        descriptionPtBr: 'Proteína adequada durante restrição calórica.',
        evidenceIds: ['applied-clinical-nutrition'],
        confidence: 'moderate',
      },
    ],
    contraindications: ['Perda ponderal rápida em gatos'],
    monitoring: ['Peso semanal', 'Apetite', 'Glicemia'],
    conflictProfileIds: ['diabetes_cat_sglt2'],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'moderate',
  },
  {
    id: 'feline_idiopathic_cystitis',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['cat'],
    diagnosisCode: 'lower_urinary_tract_disease',
    displayNamePtBr: 'Cistite idiopática felina',
    energy: { policy: 'no_direct_change', recommendationPtBr: 'Aumentar ingestão hídrica; dieta úmida preferencial (AVCN cap. 16).', evidenceIds: ['applied-clinical-nutrition'] },
    nutrientTargets: [
      {
        nutrientKey: 'moisturePct',
        labelPt: 'Umidade',
        basis: 'dry_matter_pct',
        type: 'qualitative',
        descriptionPtBr: 'Alimento úmido e múltiplos pontos de água.',
        evidenceIds: ['applied-clinical-nutrition'],
        confidence: 'moderate',
        unit: '%',
      },
    ],
    contraindications: [],
    monitoring: ['Frequência urinária', 'Hematúria', 'Comportamento'],
    conflictProfileIds: [],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'moderate',
  },
  {
    id: 'urinary_tract_infection_support',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog', 'cat'],
    diagnosisCode: 'urinary_tract_infection',
    displayNamePtBr: 'Infecção do trato urinário',
    energy: { policy: 'no_direct_change', recommendationPtBr: 'Hidratação e dieta completa durante antibiótico.', evidenceIds: ['applied-clinical-nutrition'] },
    nutrientTargets: [],
    contraindications: ['Misturar dietas terapêuticas sem indicação'],
    monitoring: ['Urocultura', 'USG', 'Sintomas'],
    conflictProfileIds: [],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'low',
  },
  {
    id: 'hyperthyroid_cat',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['cat'],
    diagnosisCode: 'hyperthyroidism',
    displayNamePtBr: 'Hipertireoidismo felino',
    energy: {
      policy: 'select_target',
      recommendationPtBr: 'Suporte calórico-proteico; monitorar perda de peso e comorbidades renais (AVCN cap. 17).',
      evidenceIds: ['applied-clinical-nutrition'],
    },
    nutrientTargets: [],
    contraindications: ['Deficiência de nutrientes essenciais'],
    monitoring: ['T4', 'Peso', 'Função renal', 'Apetite'],
    conflictProfileIds: ['ckd_cat_iris_2'],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'moderate',
  },
  {
    id: 'hyperlipidemia_dog',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog', 'cat'],
    diagnosisCode: 'hyperlipidemia',
    displayNamePtBr: 'Hiperlipidemia',
    energy: { policy: 'select_target', recommendationPtBr: 'Controle de gordura dietética e peso corporal (AVCN cap. 17).', evidenceIds: ['applied-clinical-nutrition'] },
    nutrientTargets: [
      {
        nutrientKey: 'etherExtractPct',
        labelPt: 'Gordura',
        basis: 'percent_me',
        type: 'maximum',
        maximum: 25,
        unit: '% ME',
        descriptionPtBr: 'Moderar gordura; investigar causas secundárias.',
        evidenceIds: ['applied-clinical-nutrition'],
        confidence: 'low',
      },
    ],
    contraindications: [],
    monitoring: ['Perfil lipídico', 'Pancreatite', 'Peso'],
    conflictProfileIds: ['pancreatitis_dog'],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'low',
  },
  {
    id: 'gi_acute_gastroenteritis',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog', 'cat'],
    diagnosisCode: 'acute_gastroenteritis',
    displayNamePtBr: 'Gastroenterite aguda',
    energy: {
      policy: 'select_target',
      recommendationPtBr: 'Nutrição luminal precoce quando tolerada; evitar jejum prolongado (AVCN cap. 11).',
      evidenceIds: ['applied-clinical-nutrition', 'hospital-nutrition-small-animals'],
    },
    nutrientTargets: [],
    contraindications: ['Jejum prolongado rotineiro'],
    monitoring: ['Vômitos', 'Hidratação', 'Apetite'],
    conflictProfileIds: [],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'moderate',
  },
  {
    id: 'gi_chronic_enteropathy',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog', 'cat'],
    diagnosisCode: 'chronic_enteropathy',
    displayNamePtBr: 'Enteropatia crônica',
    energy: { policy: 'no_direct_change', recommendationPtBr: 'Proteína digestível; ajuste de gordura e prebióticos (AVCN cap. 11).', evidenceIds: ['applied-clinical-nutrition', 'microbiome-nutrition'] },
    nutrientTargets: [
      {
        nutrientKey: 'crudeProteinPct',
        labelPt: 'Proteína',
        basis: 'dry_matter_pct',
        type: 'qualitative',
        descriptionPtBr: 'Proteína altamente digestível; considerar dieta hipoalergênica.',
        evidenceIds: ['applied-clinical-nutrition'],
        confidence: 'moderate',
        unit: '% MS',
      },
    ],
    contraindications: [],
    monitoring: ['Peso', 'Fezes', 'Proteína sérica'],
    conflictProfileIds: [],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'moderate',
  },
  {
    id: 'gi_adverse_food_reaction',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog', 'cat'],
    diagnosisCode: 'adverse_food_reaction',
    displayNamePtBr: 'Reação adversa a alimento',
    energy: { policy: 'no_direct_change', recommendationPtBr: 'Dieta de eliminação 8–12 semanas; sem petiscos paralelos (AVCN cap. 11 e 14).', evidenceIds: ['applied-clinical-nutrition'] },
    nutrientTargets: [],
    contraindications: ['Petiscos fora da dieta de eliminação'],
    monitoring: ['Prurido', 'Fezes', 'Reintrodução alimentar'],
    conflictProfileIds: [],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'moderate',
  },
  {
    id: 'gi_colitis',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog', 'cat'],
    diagnosisCode: 'colitis',
    displayNamePtBr: 'Colite',
    energy: { policy: 'no_direct_change', recommendationPtBr: 'Fibras fermentáveis/moderadamente solúveis (AVCN cap. 11).', evidenceIds: ['applied-clinical-nutrition', 'microbiome-nutrition'] },
    nutrientTargets: [
      {
        nutrientKey: 'crudeFiberPct',
        labelPt: 'Fibra',
        basis: 'dry_matter_pct',
        type: 'qualitative',
        descriptionPtBr: 'Ajustar tipo de fibra conforme resposta clínica.',
        evidenceIds: ['applied-clinical-nutrition'],
        confidence: 'low',
        unit: '% MS',
      },
    ],
    contraindications: [],
    monitoring: ['Frequência defecatória', 'Muco/sangue', 'Peso'],
    conflictProfileIds: [],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'low',
  },
  {
    id: 'gi_constipation_cat',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['cat'],
    diagnosisCode: 'constipation',
    displayNamePtBr: 'Constipação / megacólon felino',
    energy: { policy: 'no_direct_change', recommendationPtBr: 'Fibras insolúveis e hidratação (AVCN cap. 11).', evidenceIds: ['applied-clinical-nutrition'] },
    nutrientTargets: [],
    contraindications: [],
    monitoring: ['Frequência defecatória', 'Dor', 'Hidratação'],
    conflictProfileIds: [],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'low',
  },
  {
    id: 'exocrine_pancreatic_insufficiency',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog', 'cat'],
    diagnosisCode: 'exocrine_pancreatic_insufficiency',
    displayNamePtBr: 'Insuficiência pancreática exócrina',
    energy: { policy: 'select_target', recommendationPtBr: 'Dieta digestível; enzimas e cobalamina (AVCN cap. 12).', evidenceIds: ['applied-clinical-nutrition'] },
    nutrientTargets: [],
    contraindications: ['Suspender suplementação enzimática'],
    monitoring: ['Peso', 'Fezes', 'Cobalamina'],
    conflictProfileIds: [],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'moderate',
  },
  {
    id: 'hepatic_lipidosis_cat',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['cat'],
    diagnosisCode: 'hepatic_lipidosis',
    displayNamePtBr: 'Lipidose hepática felina',
    energy: {
      policy: 'clinician_required',
      recommendationPtBr: 'Suporte calórico-proteico agressivo; arginina e cobalamina (AVCN cap. 13).',
      evidenceIds: ['applied-clinical-nutrition', 'hospital-nutrition-small-animals'],
    },
    nutrientTargets: [
      {
        nutrientKey: 'crudeProteinPct',
        labelPt: 'Proteína',
        basis: 'dry_matter_pct',
        type: 'minimum',
        minimum: 35,
        unit: '% MS',
        descriptionPtBr: 'Proteína de alta qualidade para evitar catabolismo.',
        evidenceIds: ['applied-clinical-nutrition'],
        confidence: 'moderate',
      },
    ],
    contraindications: ['Jejum prolongado'],
    monitoring: ['Bilirrubinas', 'Apetite', 'Potássio', 'Peso'],
    conflictProfileIds: ['hepatic_encephalopathy'],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'high',
  },
  {
    id: 'hepatic_encephalopathy',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog', 'cat'],
    diagnosisCode: 'hepatic_encephalopathy',
    displayNamePtBr: 'Encefalopatia hepática',
    energy: { policy: 'select_target', recommendationPtBr: 'Proteína modificada/vegetal; fibras e lactulose conforme caso (AVCN cap. 13).', evidenceIds: ['applied-clinical-nutrition'] },
    nutrientTargets: [],
    contraindications: ['Proteína excessiva sem controle'],
    monitoring: ['Ammonia', 'Neurologia', 'Peso'],
    conflictProfileIds: ['ckd_dog_iris_2', 'ckd_cat_iris_2'],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'moderate',
  },
  {
    id: 'hepatic_copper_dog',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog'],
    diagnosisCode: 'copper_associated_hepatopathy',
    displayNamePtBr: 'Hepatopatia associada ao cobre',
    energy: { policy: 'no_direct_change', recommendationPtBr: 'Restrição de cobre dietético; antioxidantes (AVCN cap. 13).', evidenceIds: ['applied-clinical-nutrition'] },
    nutrientTargets: [
      {
        nutrientKey: 'copperPct',
        labelPt: 'Cobre',
        basis: 'dry_matter_pct',
        type: 'maximum',
        maximum: 0.001,
        unit: '% MS',
        descriptionPtBr: 'Dieta com cobre restrito; confirmar histologia.',
        evidenceIds: ['applied-clinical-nutrition'],
        confidence: 'moderate',
      },
    ],
    contraindications: ['Suplementos com cobre'],
    monitoring: ['Enzimas hepáticas', 'Cobre sérico', 'Bilirrubinas'],
    conflictProfileIds: [],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'moderate',
  },
  {
    id: 'chronic_hepatitis',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog', 'cat'],
    diagnosisCode: 'chronic_hepatitis',
    displayNamePtBr: 'Hepatite crônica',
    energy: { policy: 'no_direct_change', recommendationPtBr: 'Evitar desnutrição; proteína de qualidade e antioxidantes.', evidenceIds: ['applied-clinical-nutrition'] },
    nutrientTargets: [],
    contraindications: [],
    monitoring: ['Albumina', 'Peso', 'Enzimas hepáticas'],
    conflictProfileIds: ['hepatic_encephalopathy'],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'low',
  },
  {
    id: 'cardiac_dog_stage_b',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog'],
    diagnosisCode: 'cardiovascular_disease',
    displayNamePtBr: 'Cardiopatia canina — estágio B',
    energy: { policy: 'no_direct_change', recommendationPtBr: 'Manutenção de peso; moderação de sódio (AVCN cap. 18).', evidenceIds: ['applied-clinical-nutrition'] },
    nutrientTargets: [],
    contraindications: [],
    monitoring: ['Peso', 'Tolerância ao exercício'],
    conflictProfileIds: [],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'moderate',
  },
  {
    id: 'cardiac_dog_stage_c',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog'],
    diagnosisCode: 'heart_failure',
    displayNamePtBr: 'Insuficiência cardíaca congestiva (cão)',
    energy: {
      policy: 'select_target',
      recommendationPtBr: 'Densidade energética; n-3 EPA/DHA; controle de sódio (AVCN cap. 18).',
      evidenceIds: ['applied-clinical-nutrition'],
    },
    nutrientTargets: [],
    contraindications: ['Desnutrição/cachexia cardíaca'],
    monitoring: ['Peso', 'Apetite', 'Edema', 'Medicações'],
    conflictProfileIds: [],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'moderate',
  },
  {
    id: 'cardiac_cat_hcm',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['cat'],
    diagnosisCode: 'cardiomyopathy',
    displayNamePtBr: 'Cardiopatia felina',
    energy: { policy: 'no_direct_change', recommendationPtBr: 'Manter peso; taurina e palatabilidade (AVCN cap. 18).', evidenceIds: ['applied-clinical-nutrition'] },
    nutrientTargets: [],
    contraindications: ['Taurina deficiente'],
    monitoring: ['Peso', 'ECO', 'Apetite'],
    conflictProfileIds: [],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'moderate',
  },
  {
    id: 'oncology_support',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog', 'cat'],
    diagnosisCode: 'neoplasia',
    displayNamePtBr: 'Neoplasia — suporte nutricional',
    energy: {
      policy: 'select_target',
      recommendationPtBr: 'Priorizar ingestão; densidade energética e proteína; n-3 quando tolerado (AVCN cap. 19).',
      evidenceIds: ['applied-clinical-nutrition'],
    },
    nutrientTargets: [],
    contraindications: ['Dietas fad sem evidência'],
    monitoring: ['Peso', 'MCS', 'Apetite', 'Efeitos da quimioterapia'],
    conflictProfileIds: [],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'moderate',
  },
  {
    id: 'orthopedic_osteoarthritis',
    version: THERAPEUTIC_PROFILE_REGISTRY_VERSION,
    species: ['dog', 'cat'],
    diagnosisCode: 'osteoarthritis',
    displayNamePtBr: 'Osteoartrite',
    energy: {
      policy: 'select_target',
      recommendationPtBr: 'Controle de peso; ácidos graxos n-3 (AVCN cap. 10).',
      evidenceIds: ['applied-clinical-nutrition'],
    },
    nutrientTargets: [],
    contraindications: [],
    monitoring: ['Peso', 'Mobilidade', 'Dor'],
    conflictProfileIds: ['obesity_dog', 'obesity_cat'],
    evidenceIds: ['applied-clinical-nutrition'],
    confidence: 'low',
  },
]

export function getTherapeuticProfileV3ById(id: string): TherapeuticNutritionProfileV3 | undefined {
  return THERAPEUTIC_NUTRITION_PROFILES_V3.find((profile) => profile.id === id)
}

/** Resolve IDs de perfis terapêuticos a partir das comorbidades selecionadas. */
export function resolveProfileIdsFromComorbidities(
  species: CanonicalSpecies,
  comorbidityIds: string[],
): string[] {
  const ids = new Set<string>()

  for (const comorbidityId of comorbidityIds) {
    const option = getComorbidityOptionById(comorbidityId)
    if (!option || !option.species.includes(species)) continue
    for (const profileId of option.therapeuticProfileIds) {
      const profile = getTherapeuticProfileV3ById(profileId)
      if (profile?.species.includes(species)) ids.add(profileId)
    }
  }

  return Array.from(ids)
}

export function resolveTherapeuticProfilesV3(input: CanonicalNutritionInput): TherapeuticNutritionProfileV3[] {
  const species = input.patient.species
  const ids = new Set<string>(
    resolveProfileIdsFromComorbidities(species, input.clinical.comorbidityIds ?? []),
  )

  for (const diagnosis of input.clinical.diagnoses) {
    if (!diagnosis.active) continue
    if (diagnosis.diagnosisId.startsWith('ckd_')) ids.add(diagnosis.diagnosisId)
    if (diagnosis.diagnosisId.startsWith('urolith_')) ids.add(diagnosis.diagnosisId)
    if (diagnosis.diagnosisId.startsWith('diabetes_')) ids.add(diagnosis.diagnosisId)
  }

  const bcs = input.patient.bodyConditionScore?.value ?? 5
  if (bcs >= 8) {
    ids.add(species === 'cat' ? 'obesity_cat' : 'obesity_dog')
  }

  return Array.from(ids)
    .map((id) => getTherapeuticProfileV3ById(id))
    .filter((profile): profile is TherapeuticNutritionProfileV3 => Boolean(profile))
    .filter((profile) => profile.species.includes(species))
}
