import { RxTemplateStyle } from './rxDb'

export const DEFAULT_NOVA_RECEITA_TEMPLATE_ID = 'rx_br_v1_modern_dark'

export const BUILTIN_TEMPLATES: RxTemplateStyle[] = [
    {
        id: 'rx_classic_vertical_v1',
        name: 'Receita clássica vertical',
        documentKindTarget: 'standard',
        layoutVariant: 'classic-vertical',
        fontFamily: 'Georgia, "Times New Roman", serif',
        fontSizePt: 12,
        headingSizePt: 16,
        lineHeight: 1.55,
        accentColor: '#111827',
        textColor: '#111827',
        paperBg: '#ffffff',
        paperSize: 'A4',
        showLetterhead: true,
        showSignature: true,
        showMapaSignature: false,
        showTimestamp: true,
        extraNotes: '',
        zoneStyles: {
            header: {
                fontSizePt: 13,
                fontWeight: 'bold',
                textColor: '#111827',
            },
            body: {
                textColor: '#111827',
            },
        },
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'rx_br_v1_clean',
        name: 'Padrão Clínico',
        documentKindTarget: 'standard',
        layoutVariant: 'default',
        fontFamily: 'Manrope, Arial, sans-serif',
        fontSizePt: 12,
        headingSizePt: 18,
        lineHeight: 1.5,
        accentColor: '#1d4ed8',
        textColor: '#1f2937',
        paperBg: '#ffffff',
        paperSize: 'A4',
        showLetterhead: true,
        showSignature: true,
        showMapaSignature: false,
        showTimestamp: true,
        extraNotes: '',
        zoneStyles: {
            header: {
                fontSizePt: 14,
                fontWeight: 'bold',
                textColor: '#1d4ed8',
            },
        },
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'rx_br_v1_modern_dark',
        name: 'Moderno Dark',
        documentKindTarget: 'standard',
        layoutVariant: 'default',
        fontFamily: 'Inter, Arial, sans-serif',
        fontSizePt: 11,
        headingSizePt: 22,
        lineHeight: 1.6,
        accentColor: '#16a34a',
        textColor: '#111827',
        paperBg: '#f9fafb',
        paperSize: 'A4',
        showLetterhead: true,
        showSignature: true,
        showMapaSignature: false,
        showTimestamp: true,
        extraNotes: '',
        zoneStyles: {
            header: {
                fontSizePt: 16,
                fontWeight: 'bold',
                textColor: '#1a2e40',
            },
        },
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'rx_br_v1_minimal_green',
        name: 'Verde Clínico',
        documentKindTarget: 'standard',
        layoutVariant: 'default',
        fontFamily: 'Roboto, Arial, sans-serif',
        fontSizePt: 12,
        headingSizePt: 18,
        lineHeight: 1.45,
        accentColor: '#059669',
        textColor: '#064e3b',
        paperBg: '#f0fdf4',
        paperSize: 'A4',
        showLetterhead: true,
        showSignature: true,
        showMapaSignature: false,
        showTimestamp: true,
        extraNotes: '',
        zoneStyles: {
            header: {
                textColor: '#065f46',
                fontWeight: 'bold',
            },
            body: {
                accentColor: '#10b981',
            },
        },
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'rx_br_v1_classico',
        name: 'Clássico Formal',
        documentKindTarget: 'standard',
        layoutVariant: 'default',
        fontFamily: 'Georgia, "Times New Roman", serif',
        fontSizePt: 12,
        headingSizePt: 16,
        lineHeight: 1.6,
        accentColor: '#78350f',
        textColor: '#1c1917',
        paperBg: '#fffbeb',
        paperSize: 'A4',
        showLetterhead: true,
        showSignature: true,
        showMapaSignature: false,
        showTimestamp: true,
        extraNotes: '',
        zoneStyles: {
            header: {
                fontSizePt: 14,
                fontWeight: 'bold',
                textColor: '#92400e',
                underline: true,
            },
        },
        updatedAt: new Date().toISOString(),
    },
    {
        id: 'rx_br_v1_compact_a5',
        name: 'Compacto A5',
        documentKindTarget: 'standard',
        layoutVariant: 'default',
        fontFamily: 'Inter, Arial, sans-serif',
        fontSizePt: 10,
        headingSizePt: 14,
        lineHeight: 1.35,
        accentColor: '#7c3aed',
        textColor: '#1e1b4b',
        paperBg: '#ffffff',
        paperSize: 'A5',
        showLetterhead: true,
        showSignature: true,
        showMapaSignature: false,
        showTimestamp: false,
        extraNotes: '',
        zoneStyles: {
            header: {
                fontSizePt: 12,
                fontWeight: 'bold',
                textColor: '#5b21b6',
            },
        },
        updatedAt: new Date().toISOString(),
    },
]