// Protocol to Prescription Mapper
// Converts ProtocolMedicationItem to PrescriptionItem compatible with Nova Receita 2.0 and rxRenderer

import { ProtocolMedicationItem, ProtocolRecommendation } from '../../src/lib/protocols/protocolsRepo'
import { PrescriptionItem as RxPrescriptionItem, RouteGroup } from './rxTypes'
import { createDefaultItem } from './rxDefaults'

// Local PrescriptionItem interface from NovaReceita2Page.tsx
export interface PrescriptionItem {
    id: string
    type: 'medication' | 'hygiene' | 'other'

    // Medication-specific
    medication_id?: string
    presentation_id?: string

    // Common fields
    name: string
    presentation_label?: string
    dose?: string
    frequency?: string
    route?: string
    duration?: string
    instructions?: string
}

/**
 * Map a protocol medication item to a rxTypes PrescriptionItem (for rxRenderer)
 */
export function mapProtocolMedicationToRxPrescriptionItem(
    protocolMed: ProtocolMedicationItem
): RxPrescriptionItem {
    // Determine route group from protocol route
    const routeGroup = mapRouteToRouteGroup(protocolMed.route)

    // Create default item with proper route
    const item = createDefaultItem('medication', routeGroup)

    // Set basic information
    item.name = protocolMed.medication_name || protocolMed.manual_medication_name || 'Medicamento'
    item.presentation = protocolMed.manual_presentation_label || ''
    item.concentration = protocolMed.concentration_value
        ? `${protocolMed.concentration_value} ${protocolMed.concentration_unit || ''}`.trim()
        : protocolMed.concentration_unit || ''

    // Set dose information if available
    if (protocolMed.dose_value !== null && protocolMed.dose_value !== undefined) {
        item.doseValue = protocolMed.dose_value.toString()
    }
    if (protocolMed.dose_unit) {
        item.doseUnit = protocolMed.dose_unit
    }

    // Set frequency information
    if (protocolMed.frequency_type === 'times_per_day' && protocolMed.times_per_day) {
        item.frequencyType = 'timesPerDay'
        item.timesPerDay = protocolMed.times_per_day.toString()
        // Map common frequencies to tokens
        if (protocolMed.times_per_day === 1) item.frequencyToken = 'SID'
        else if (protocolMed.times_per_day === 2) item.frequencyToken = 'BID'
        else if (protocolMed.times_per_day === 3) item.frequencyToken = 'TID'
        else if (protocolMed.times_per_day === 4) item.frequencyToken = 'QID'
    } else if (protocolMed.frequency_type === 'interval_hours' && protocolMed.interval_hours) {
        item.frequencyType = 'everyHours'
        item.everyHours = protocolMed.interval_hours.toString()
    } else if (protocolMed.frequency_type === 'once_daily') {
        item.frequencyType = 'timesPerDay'
        item.timesPerDay = '1'
        item.frequencyToken = 'SID'
    } else if (protocolMed.frequency_type === 'as_needed') {
        item.frequencyType = 'timesPerDay'
        item.timesPerDay = '1'
        item.instruction = 'Administrar conforme necessidade.'
        item.autoInstruction = false
        item.manualEdited = true
    }

    // Set duration
    if (protocolMed.duration_days) {
        item.durationDays = protocolMed.duration_days.toString()
    }

    // Auto instruction will be generated by rxRenderer based on dose/frequency/duration
    // NOTE: `instructions` column does NOT exist in protocol_medications DB table
    item.autoInstruction = true
    item.manualEdited = false

    // Set status based on completeness
    item.id = `protocol-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`

    return item
}

/**
 * Map a protocol medication item to a NovaReceita2Page PrescriptionItem
 */
export function mapProtocolMedicationToPrescriptionItem(
    protocolMed: ProtocolMedicationItem
): PrescriptionItem {
    // NOTE: `instructions` does NOT exist in DB — build instruction text dynamically
    let instructions = ''
    {
        // Create simple instruction from protocol data
        const parts: string[] = []
        if (protocolMed.dose_value !== null && protocolMed.dose_value !== undefined && protocolMed.dose_unit) {
            parts.push(`${protocolMed.dose_value} ${protocolMed.dose_unit}`)
        }
        if (protocolMed.frequency_type === 'times_per_day' && protocolMed.times_per_day) {
            parts.push(`${protocolMed.times_per_day}x ao dia`)
        } else if (protocolMed.frequency_type === 'interval_hours' && protocolMed.interval_hours) {
            parts.push(`a cada ${protocolMed.interval_hours} horas`)
        } else if (protocolMed.frequency_type === 'once_daily') {
            parts.push('1x ao dia')
        } else if (protocolMed.frequency_type === 'as_needed') {
            parts.push('conforme necessidade')
        }
        if (protocolMed.duration_days) {
            parts.push(`por ${protocolMed.duration_days} dias`)
        }
        if (protocolMed.route) {
            parts.push(`via ${protocolMed.route}`)
        }

        instructions = parts.join(', ') + '.'
    }

    // Build dose string
    let dose = ''
    if (protocolMed.dose_value !== null && protocolMed.dose_value !== undefined) {
        dose = protocolMed.dose_value.toString()
        if (protocolMed.dose_unit) {
            dose += ` ${protocolMed.dose_unit}`
        }
    }

    // Build frequency string
    let frequency = ''
    if (protocolMed.frequency_type === 'times_per_day' && protocolMed.times_per_day) {
        frequency = `${protocolMed.times_per_day}x ao dia`
    } else if (protocolMed.frequency_type === 'interval_hours' && protocolMed.interval_hours) {
        frequency = `a cada ${protocolMed.interval_hours} horas`
    } else if (protocolMed.frequency_type === 'once_daily') {
        frequency = '1x ao dia'
    } else if (protocolMed.frequency_type === 'as_needed') {
        frequency = 'conforme necessidade'
    }

    return {
        id: `protocol-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`,
        type: 'medication',
        medication_id: protocolMed.medication_id || undefined,
        presentation_id: protocolMed.presentation_id || undefined,
        name: protocolMed.medication_name || protocolMed.manual_medication_name || 'Medicamento',
        presentation_label: protocolMed.manual_presentation_label || '',
        dose: dose || undefined,
        frequency: frequency || undefined,
        route: protocolMed.route || undefined,
        duration: protocolMed.duration_days ? `${protocolMed.duration_days} dias` : undefined,
        instructions: instructions,
    }
}

/**
 * Map route string to RouteGroup enum
 */
function mapRouteToRouteGroup(route: string | null): RouteGroup {
    if (!route) return 'ORAL'

    const routeLower = route.toLowerCase().trim()

    if (routeLower.includes('oral') || routeLower.includes('oral')) return 'ORAL'
    if (routeLower.includes('otológico') || routeLower.includes('otico')) return 'OTOLOGICO'
    if (routeLower.includes('oftálmico') || routeLower.includes('oftalmico')) return 'OFTALMICO'
    if (routeLower.includes('tópico') || routeLower.includes('topico')) return 'TOPICO'
    if (routeLower.includes('intranasal')) return 'INTRANASAL'
    if (routeLower.includes('retal')) return 'RETAL'
    if (routeLower.includes('subcutâneo') || routeLower.includes('sc') || routeLower.includes('subcutaneo')) return 'SC'
    if (routeLower.includes('intramuscular') || routeLower.includes('im')) return 'IM'
    if (routeLower.includes('intravenoso') || routeLower.includes('iv')) return 'IV'
    if (routeLower.includes('inalatório') || routeLower.includes('inalatorio')) return 'INALATORIO'
    if (routeLower.includes('transdérmico') || routeLower.includes('transdermico')) return 'TRANSDERMICO'

    return 'OUTROS'
}

/**
 * Convert protocol recommendations to a single string for Nova Receita 2.0
 */
export function mapProtocolRecommendationsToString(
    recommendations: ProtocolRecommendation[]
): string {
    return recommendations
        .map(rec => rec.text.trim())
        .filter(text => text.length > 0)
        .join('\n\n')
}

/**
 * Check if a prescription item is complete (has name, route, and instructions)
 */
export function isPrescriptionItemComplete(item: PrescriptionItem): boolean {
    return !!item.name.trim() && !!item.route && !!item.instructions?.trim()
}

/**
 * Check if a rx prescription item is complete
 */
export function isRxPrescriptionItemComplete(item: RxPrescriptionItem): boolean {
    return !!item.name.trim() && !!item.routeGroup && !!item.instruction.trim()
}