import { Species } from './rxTypes'

export const DOG_BREEDS_BR: string[] = [
  'Labrador Retriever',
  'Golden Retriever',
  'Poodle',
  'Shih Tzu',
  'Yorkshire Terrier',
  'Bulldog Francês',
  'Spitz Alemão',
  'Rottweiler',
  'Pastor Alemão',
  'Beagle',
  'Pinscher',
  'Dachshund',
  'Border Collie',
  'Maltês',
  'Pug',
  'Bulldog Inglês',
  'American Bully',
  'Chihuahua',
  'Lhasa Apso',
  'Cocker Spaniel Inglês',
  'SRD (Vira-lata)',
  'Boxer',
  'Dobermann',
  'Husky Siberiano',
  'Akita Inu',
  'Schnauzer Miniatura',
  'Australian Shepherd',
  'Weimaraner',
  'Jack Russell Terrier',
  'Pit Bull Terrier Americano',
  'Boston Terrier',
  'Samoieda',
  'Cane Corso',
  'Collie',
  'Basset Hound',
]

export const CAT_BREEDS_BR: string[] = [
  'SRD (Sem raça definida)',
  'Siamês',
  'Persa',
  'Maine Coon',
  'Angorá',
  'Bengal',
  'Sphynx',
  'Ragdoll',
  'British Shorthair',
  'Scottish Fold',
  'Birmanês',
  'Himalaio',
  'Abissínio',
  'Oriental Shorthair',
  'Exótico',
  'Devon Rex',
  'Russian Blue',
  'Norueguês da Floresta',
  'Burmese',
  'Savannah',
]

export const DOG_COATS_50: string[] = [
  'Preto',
  'Branco',
  'Marrom',
  'Caramelo',
  'Dourado',
  'Cinza',
  'Azul',
  'Bege',
  'Creme',
  'Chocolate',
  'Amarelo',
  'Vermelho',
  'Canela',
  'Fulvo',
  'Tricolor',
  'Bicolor',
  'Preto e branco',
  'Preto e caramelo',
  'Marrom e branco',
  'Cinza e branco',
  'Dourado e branco',
  'Tigrado',
  'Merle azul',
  'Merle vermelho',
  'Arlequim',
  'Malhado',
  'Mosqueado',
  'Ruão',
  'Sable',
  'Sable claro',
  'Sable escuro',
  'Lobo cinza',
  'Prateado',
  'Champanhe',
  'Isabela',
  'Lilás',
  'Canela e branco',
  'Preto e cinza',
  'Preto e dourado',
  'Branco e caramelo',
  'Branco e marrom',
  'Branco, preto e caramelo',
  'Castanho',
  'Castanho escuro',
  'Marfim',
  'Pérola',
  'Ferrugem',
  'Sal e pimenta',
  'Preto carvão',
  'Creme rosado',
]

export const CAT_COATS_50: string[] = [
  'Preto',
  'Branco',
  'Cinza',
  'Azul',
  'Marrom',
  'Chocolate',
  'Canela',
  'Creme',
  'Caramelo',
  'Dourado',
  'Prateado',
  'Lilás',
  'Fawn',
  'Vermelho',
  'Preto e branco',
  'Cinza e branco',
  'Creme e branco',
  'Tigrado cinza',
  'Tigrado marrom',
  'Tigrado laranja',
  'Tigrado prata',
  'Tigrado azul',
  'Rajado clássico',
  'Rajado mackerel',
  'Rajado spotted',
  'Tricolor',
  'Calico',
  'Escama de tartaruga',
  'Escama diluída',
  'Colorpoint seal',
  'Colorpoint blue',
  'Colorpoint lilac',
  'Colorpoint chocolate',
  'Mink',
  'Sepia',
  'Smoke preto',
  'Smoke azul',
  'Chinchila prateada',
  'Chinchila dourada',
  'Shaded prata',
  'Shaded dourado',
  'Van',
  'Arlequim',
  'Lilás e branco',
  'Azul e branco',
  'Chocolate e branco',
  'Champanhe',
  'Pêssego',
  'Marfim',
  'Silver tabby',
]

function sortPtBr(values: string[]): string[] {
  return [...values].sort((a, b) => a.localeCompare(b, 'pt-BR', { sensitivity: 'base' }))
}

export function breedOptionsForSpecies(species: Species): string[] {
  return species === 'Felina' ? sortPtBr(CAT_BREEDS_BR) : sortPtBr(DOG_BREEDS_BR)
}

export function coatOptionsForSpecies(species: Species): string[] {
  return species === 'Felina' ? sortPtBr(CAT_COATS_50) : sortPtBr(DOG_COATS_50)
}
