export type DiseaseRow = {
  id: string;
  category_id: string | null;
  slug: string;
  title: string;
  synonyms: string[] | null;
  species: string[] | null;
  tags: string[] | null;
  quick_summary: string;
  thirty_second_view: string[] | null;
  do_not_forget: string[] | null;
  when_to_suspect: string[] | null;
  initial_conduct: string[] | null;
  high_yield_tests: string[] | null;
  dog_vs_cat_differences: string[] | null;
  common_mistakes: string[] | null;
  red_flags: string[] | null;
  clinical_pearls: string[] | null;
  introduction: unknown;
  etiology: unknown;
  transmission: unknown;
  pathophysiology: unknown;
  epidemiology: unknown;
  clinical_presentation: unknown;
  physical_exam: unknown;
  differential_diagnoses: unknown;
  diagnostics: unknown;
  diagnostic_approach: unknown;
  treatment: unknown;
  prognosis: unknown;
  complications: unknown;
  prevention: unknown;
  references: unknown;
  is_published: boolean;
  created_at: string;
  updated_at: string;
};
