import * as fs from 'fs';
import * as path from 'path';

interface ComplicationData {
  principais: string[];
  prognostico: string;
}

const complicationsMap: Record<string, ComplicationData> = {
  'diseases.erlichia.seed.ts': {
    principais: [
      'Hipoplasia/Aplasia Medular Crônica e Pancitopenia Irreversível (Fase Crônica Grave): Ocorre supressão imunomediada e toxicidade estromal da medula óssea decorrente da ativação crônica e desregulada de linfócitos T citotóxicos e plasmócitos. Esse processo destrói as células-tronco pluripotentes hematopoiéticas e a microarquitetura estromal, culminando em anemia aplásica arregenerativa profunda (hematócrito frequentemente < 15%), trombocitopenia severa (< 20.000/µL) e leucopenia/neutropenia absoluta (< 1.500/µL). Nessa fase crônica mielotísica, o paciente torna-se frequentemente refratário à doxiciclina e o prognóstico é infausto a gravíssimo.',
      'Diatése Hemorrágica Grave, Trombocitopatia e Hemorragias Fatais: A combinação sinérgica entre trombocitopenia por consumo periférico/destruição imunomediada, vasculite necrosante imunomediada e disfunção funcional plaquetária (trombocitopatia secundária à hipergamaglobulinemia monoclonal ou oligoclonal que recobre as plaquetas e impede a agregação) pode desencadear diátese hemorrágica severa. Manifesta-se como epistaxe profusa bilateral de difícil hemostasia com choque hipovolêmico agudo, hemorragia pulmonar difusa, melena/hematoquezia maciça e hematomas intracranianos (subdurais ou subaracnóideos) súbitos e fatais.',
      'Glomerulonefrite Imunomediada por Imunocomplexos (GNIC) e Síndrome Nefrótica: A persistência de antígenos de Ehrlichia canis induz produção massiva e crônica de imunoglobulinas (IgG e IgM), formando imunocomplexos circulantes solúveis que se depositam na membrana basal dos capilares glomerulares e no mesângio. Esse depósito ativa a via clássica do complemento, recrutando neutrófilos e provocando lesão da barreira de filtração com proteinúria maciça (RPCU > 2,0 a 5,0), hipoalbuminemia severa, edema subcutâneo em declive, ascite e rápida progressão para Doença Renal Crônica (DRC) avançada com hipertensão arterial sistêmica.',
      'Lesões Oculares Graves e Amaurose (Cegueira) Bilateral Aguda: Vasculite imunomediada dos vasos ciliares e coroideos associada à deposição de imunocomplexos no trato uveal anterior e posterior. Manifesta-se com uveíte anterior com hipópio ou hifema espontâneo extenso, edema de córnea em vidro fosco, infiltrados perivasculares retinianos, hemorragias e descolamento de retina seroso/exsudativo bilateral, glaucoma secundário doloroso e perda visual irreversível e permanente.',
      'Meningoencefalomielite Linfoplasmocitária e Vasculite do SNC: Infiltração perivascular densa de monócitos e plasmócitos nas leptomeninges e no parênquima cerebral e medular, associada a microinfartos isquêmicos e hemorrágicos vasculíticos. O quadro clínico inclui crises epilépticas focais ou generalizadas, ataxia proprioceptiva, déficits de nervos cranianos, hiperestesia espinhal cervical ou toracolombar severa, paraparesia/tetraparesia e depressão sensorial profunda (estupor/coma).',
      'Poliartrite Imunomediada Não Erosiva Bilateral: A deposição contínua de complexos antígeno-anticorpo na membrana sinovial articular de múltiplas articulações apendiculares (carpos, tarsos, joelhos) desencadeia sinovite inflamatória intensa, com claudicação migratória intermitente, efusão sinovial estéril bilateral, dor articular excruciante à flexão e extensão e episódios de pirexia recorrente.',
    ],
    prognostico:
      'Excelente na fase aguda quando o paciente é diagnosticado precocemente e submetido ao tratamento padrão com doxiciclina (10 mg/kg a cada 24h por 28 dias consecutivos), apresentando melhora clínica e hematológica em 24 a 72 horas. Bom a reservado na fase subclínica prolongada, na qual títulos de anticorpos e PCR podem demorar a negativar e há risco de reativação sob estresse ou imunossupressão. Infausto a gravíssimo na fase crônica severa associada à hipoplasia medular pancitopênica, glomerulonefrite proteinúrica avançada (DRC IRIS 3-4), hemorragias intracranianas ou choque séptico secundário à neutropenia profunda.',
  },

  'diseases.tumores-mamarios.seed.ts': {
    principais: [
      'Disseminação Metastática Hematógena e Linfática Maciça: Em cadelas com carcinomas de alto grau histológico (> 3 cm ou invasão vascular) e em mais de 85% a 90% dos tumores mamários felinos (quase invariavelmente adenocarcinomas de altíssima agressividade biológica), as células neoplásicas embolizam a rede linfática regional (linfonodos axilares, torácicos internos e inguinais superficiais/ilíacos mediais) e atingem a circulação hematógena. As metástases pulmonares difusas ("padrão micronodular em tempestade de neve" ou macrofocos consolidados) deflagram efusão pleural neoplásica massiva, insuficiência respiratória restritiva com hipoxemia e tosse crônica refratária. Metástases viscerais (hepáticas, esplênicas, renais) e ósseas com dor e fraturas patológicas também ocorrem.',
      'Carcinoma Inflamatório Mamário (CIM / Carcinomatose Inflamatória): Forma hiperaguda, extremamente dolorosa e letal de neoplasia mamária em cadelas, decorrente da embolização neoplásica maciça difusa dos vasos linfáticos da derme superficial e do tecido subcutâneo por células carcinomatosas altamente agressivas. Apresenta-se com eritema violáceo generalizado, calor local intenso, consistência lenhosa difusa, edema cutâneo pronunciado em casca de laranja (peau d\'orange), dor excruciante e alto risco de Coagulação Intravascular Disseminada (CIVD) secundária. A ressecção cirúrgica é formalmente contraindicada pelo risco de disseminação hiperaguda e óbito peroperatório, conferindo sobrevida mediana de poucas semanas com manejo exclusivamente paliativo multimodal.',
      'Ulceração Cutânea Extensa, Necrose Isquêmica Tumoral e Sepse Secundária: O crescimento tumoral expansivo acelerado ultrapassa a capacidade de neoangiogênese tecidual, levando a áreas centrais de isquemia transmural, infarto e liquefação necrótica com ruptura da barreira epidérmica. Segue-se colonização bacteriana secundária mista fétida (Staphylococcus spp., Streptococcus spp., coliformes entéricos e anaeróbios estritos), exsudato purulento-hemorrágico profuso, atração de miíases secundárias e risco iminente de bacteremia, síndrome da resposta inflamatória sistêmica (SIRS) e choque séptico.',
      'Linfoedema Obstrutivo Grave de Membros Pélvicos e Região Perineal: A compressão tumoral extrínseca, infiltração neoplásica carcinomatosa intraluminal ou ressecção cirúrgica agressiva radical com linfadenectomia de linfonodos inguinais/ilíacos interrompem o fluxo de drenagem linfática efeituada pelos canais linfáticos dos membros pélvicos. Resulta em edema crônico frio, endurecido e sem fóvea ("elefantíase") acometendo um ou ambos os membros pélvicos e períneo, comprometendo gravemente a locomoção, o bem-estar e predispondo a celulite secundária recorrente e deiscência de ferida.',
      'Síndrome de Caquexia Neoplásica e Síndromes Paraneoplásicas: A liberação sustentada e desregulada de mediadores inflamatórios e citocinas catabólicas tumorais (TNF-alfa, IL-1, IL-6 e IFN-gama) desvia o metabolismo intermediário do paciente, provocando proteólise acelerada da musculatura esquelética, lipólise refratária e perda ponderal progressiva e involuntária apesar de ingestão calórica preservada. Raras síndromes paraneoplásicas incluem hipercalcemia humoral da malignidade (secreção de PTHrP por carcinomas agressivos) e trombocitopenia de consumo secundária.',
    ],
    prognostico:
      'Cadelas: altamente variável de acordo com estadiamento clínico TNM, tamanho do tumor (< 3 cm vs 3–5 cm vs > 5 cm), subtipo histopatológico e grau de diferenciação (escala de Nottingham/Elston-Ellis), invasão vascular/linfática e status de margens cirúrgicas. Tumores benignos e carcinomas bem diferenciados < 3 cm com excisão ampla apresentam excelente sobrevida a longo prazo (taxas de cura > 85-90%). Carcinomas > 5 cm, com comprometimento linfonodal ou metástase a distância, e carcinomas anaplásicos apresentam prognóstico reservado a desfavorável. Carcinomas inflamatórios apresentam prognóstico infausto (sobrevida média de 25 a 60 dias). Gatas: predominantemente reservado a desfavorável, pois > 85% das neoplasias mamárias felinas são adenocarcinomas de comportamento biológico invasivo agressivo e rápida disseminação metastática; tumores < 2 cm ressecados precocemente por mastectomia radical em cadeia bilateral estagiada conferem sobrevida mediana de ~3 anos, tumores entre 2 e 3 cm apresentam mediana de 1 a 2 anos, e tumores > 3 cm apresentam sobrevida mediana inferior a 6 meses.',
  },

  'diseases.leucemia-viral-felina.seed.ts': {
    principais: [
      'Linfomas Malignos FeLV-Associados e Neoplasias Hematopoéticas: A inserção do DNA proviral do FeLV no genoma dos linfócitos do hospedeiro causa mutagênese insercional e ativação oncogênica desregulada de proto-oncogenes celulares (ex.: c-myc), multiplicando o risco de desenvolvimento de linfoma em até 60 vezes. As formas mais prevalentes incluem o Linfoma Mediastinal/Tímico em gatos jovens (cursando com efusão pleural neoplásica rica em linfoblastos atípicos, síndrome restritiva com dispneia severa e síndrome de veia cava cranial); Linfoma Espinhal Epidural provocando ataxia proprioceptiva e paraplegia súbita; Linfoma Multicêntrico e Formas Extranodais (renal, cutâneo, ocular, neurológico central); além de Leucemia Linfoide Aguda e Neoplasias Mieloproliferativas com infiltração maciça de blastos na circulação periférica.',
      'Síndromes Mielossupressivas e Aplasia Pura de Série Vermelha (PRCA): A replicação do vírus nos precursores hematopoiéticos da medula óssea causa mieloftise, atipia citológica e colapso clonal: a Aplasia Pura de Série Vermelha (Pure Red Cell Aplasia - PRCA), causada prioritariamente pelo subgrupo recombinante FeLV-C que interage com o receptor FLVCR1 (exportador de heme) nos eritroblastos primitivos, desencadeando apoptose prematura das células eritroides sem afetar granulócitos ou megacariócitos. Manifesta-se como anemia arregenerativa profunda normocítica normocrômica (hematócrito < 10% a 12%, reticulócitos absolutos < 10.000/µL), tornando o paciente dependente de transfusões sanguíneas regulares. Síndromes mielodisplásicas (SMD) e pancitopenia aplásica generalizada também ocorrem com alta frequência.',
      'Imunodeficiência Grave Adquirida e Infecções Oportunistas Fatais: A destruição de linfócitos T CD4+ auxiliares associada às propriedades imunossupressoras da proteína de envelope viral p15E induz anergia celular adaptativa profunda. O felino desenvolve vulnerabilidade extrema a infecções secundárias por patógenos intracelulares e saprófitas: hemoplasmose crônica por Mycoplasma haemofelis desencadeando crises hemolíticas fatais; mutação e replicação descontrolada do Coronavírus Felino levando à Peritonite Infecciosa Felina (PIF); infecções fúngicas profundas sistêmicas (Criptococose, Histoplasmose); reativação de Toxoplasma gondii; estomatite ulcerativa refratária e pneumonias bacterianas recorrentes.',
      'Enteropatia FeLV-Induzida (Síndrome Panleucopenia-Like): Infecção viral citopática direta do epitélio das criptas intestinais do duodeno e jejuno, mimetizando a ação do parvovírus felino (FPV). Cursa com atrofia acentuada de vilosidades intestinais, vômitos incoercíveis, diarreia profusa aquosa com perda proteica maciça, colapso hidroeletrolítico, neutropenia extrema concomitante e choque séptico distributivo secundário à translocação de bactérias entéricas.',
      'Neuropatias Centrais e Periféricas Primárias ("FeLV-Associated Myelopathy"): Neurotropismo direto do vírus com infiltração linfoplasmocitária perivascular e degeneração espongiforme da substância branca medular nos cornos dorsais e ventrais. Produz déficits neurológicos não compressivos como anisocoria persistente (pupilas assimétricas), síndrome de Horner unilateral ou bilateral, paresia espástica de membros pélvicos, hiperestesia lombossacra, perda de controle de esfíncter vesical e alterações comportamentais crônicas.',
      'Glomerulonefrite por Imunocomplexos e Insuficiência Renal Crônica Acelerada: Deposição glomerular crônica de complexos solúveis de antígenos do core viral (proteína p27) ligados a anticorpos circulantes nos tufos glomerulares. Desencadeia glomerulonefrite membranoproliferativa com proteinúria patológica persistente, perda de antitrombina III com risco trombótico, hipertensão arterial secundária e evolução precoce para DRC terminal.',
    ],
    prognostico:
      'Estritamente dependente do padrão da resposta imune e do curso da infecção: gatos em infecção abortiva (eliminam o vírus sem antígeno ou provírus detectável) ou infecção regressiva (DNA proviral integrado na medula, mas antigenemia p27 negativa e ausência de viremia) apresentam excelente expectativa e qualidade de vida normal, sem desenvolver neoplasias ou imunossupressão. Gatos em infecção progressiva persistente (antigenemia p27 positiva em múltiplos testes com viremia contínua) apresentam prognóstico a longo prazo reservado a desfavorável: aproximadamente 80% a 85% dos felinos em viremia persistente vão a óbito dentro de 3 a 4 anos após o diagnóstico inicial em decorrência de linfoma maligno, aplasia pura de série vermelha, infecções oportunistas fulminantes ou mielodisplasias refratárias.',
  },

  'diseases.peritonite-infecciosa-felina.seed.ts': {
    principais: [
      'Insuficiência Respiratória Restritiva Aguda por Efusão Pleural Massiva (Forma Efusiva Torácica): Vasculite imunomediada mediada por ativação de complemento e liberação massiva de citocinas inflamatórias (TNF-alfa, IL-1, IL-6) pelas linhagens de monócitos/macrófagos infectados com o vírus mutado (FIPV). Resulta em transudação e exsudação contínua de líquido amarelo-palha viscoso, rico em proteínas (> 3,5 g/dL) e fibrina para a cavidade pleural, comprimindo mecanicamente os lobos pulmonares e provocando atelectasia compressiva, dispneia restritiva severa com padrão respiratório paradoxal superficial e rápido, cianose, acidose respiratória e risco imediato de óbito sem toracocentese evacuativa de emergência.',
      'Hipertensão Abdominal, Icterícia e Falência Multiorgânica (Forma Efusiva Abdominal): O acúmulo de grande volume de exsudato peritoneal viscoso distende gravemente a parede abdominal, elevando a pressão intra-abdominal, restringindo a mobilidade diafragmática e comprimindo a veia cava caudal com redução do retorno venoso sistêmico. O processo piogranulomatoso disseminado atinge o parênquima hepático e a árvore biliar, deflagrando colangio-hepatite piogranulomatosa destrutiva, hiperbilirrubinemia mista grave, esteatose, pancreatite necrotizante e hipoalbuminemia extrema decorrente da perda transmural de proteínas.',
      'Meningoencefalomielite Piogranulomatosa e Hidrocefalia Obstrutiva (Forma Neurológica): Infiltração piogranulomatosa perivascular severa nas leptomeninges, plexos coroideos do quarto ventrículo e epêndima ventricular. A proliferação inflamatória oclui o aqueduto mesencefálico, gerando hidrocefalia obstrutiva hipertensiva secundária aguda com aumento vertiginoso da pressão intracraniana. Os sinais clínicos incluem ataxia vestibular central, tetraparesia proprioceptiva assimétrica, nistagmo vertical ou posicional, crises convulsivas refratárias, cegueira de origem central, hiperestesia espinhal excruciante e rápida deterioração para estupor e coma.',
      'Uveíte Piogranulomatosa, Hifema e Descolamento Retiniano com Amaurose (Forma Ocular): Vasculite inflamatória intensa nos vasos ciliares, coroideos e retinais. Produz exsudação rica em fibrina na câmara anterior (precipitados ceráticos volumosos em "gordura de carneiro" no endotélio corneano posterior), hifema espontâneo recorrente, rubeosis iridis, miose espástica dolorosa, coriorretinite com manguitos perivasculares exsudativos e descolamento seroso total da retina com perda completa e permanente da visão.',
      'Massas Piogranulomatosas Mesentéricas e Obstrução Intestinal Íleo-Ceco-Cólica (Pseudotumor de PIF): Na forma não efusiva (seca), a agregação de múltiplos macrófagos, neutrófilos e plasmócitos forma grandes massas piogranulomatosas teciduais murais ou linfadenopatia mesentérica tumefativa, localizadas frequentemente na junção ileocecocólica. Essas lesões podem mimetizar clínica e ultrassonograficamente um linfoma ou adenocarcinoma intestinal, provocando estenose luminal intestinal com obstrução gastrointestinal mecânica parcial ou total, vômitos crônicos, dor abdominal aguda e má absorção severa.',
      'Coagulopatia Intravascular Disseminada (CIVD) e Vasculite Necrosante Sistêmica: A agressão endotelial generalizada provocada pelos imunocomplexos circulantes e a liberação de fator tecidual pelos macrófagos ativados deflagram a ativação sistêmica descontrolada da cascata de coagulação. Ocorre trombose microvascular capilar difusa em múltiplos órgãos nobres, consumo exaustivo de plaquetas e fatores de coagulação, diátese hemorrágica com petéquias/equimozes e choque distributivo irreversível.',
    ],
    prognostico:
      'Historicamente a PIF era considerada uma doença invariavelmente fatal em praticamente 100% dos felinos diagnosticados. Com o advento e a consolidação dos protocolos antivirais baseados em análogos de nucleosídeos (GS-441524 por via oral ou injetável e Remdesivir), as taxas de resposta clínica favorável e remissão completa a longo prazo (cura clínica) alcançam entre 80% e 90% dos gatos tratados com protocolo ininterrupto de 84 dias consecutivos com dosagens adequadas. O prognóstico permanece reservado nos felinos com manifestações neurológicas centrais graves e hidrocefalia obstrutiva (que requerem doses significativamente maiores de GS-441524 para ultrapassar a barreira hematoencefálica: 10 a 15 mg/kg), nos casos de mutações virais secundárias de resistência ao antiviral e naqueles admitidos em choque séptico avançado com falência de múltiplos órgãos.',
  },

  'diseases.imunodeficiencia-felina-fiv.seed.ts': {
    principais: [
      'Síndrome de Imunodeficiência Felina Terminal (Inversão CD4+/CD8+ e Falência da Imunidade Celular): A destruição progressiva, persistente e cumulativa de linfócitos T auxiliares CD4+ pelos mecanismos de apoptose mediada pelo vírus resulta na inversão dramática da razão CD4:CD8 (de níveis fisiológicos normais > 1,5 a 2,0 para níveis < 0,5 ou até < 0,1 na fase final). Essa depleção celular suprime a imunidade adaptativa do hospedeiro, privando o animal da capacidade de montar respostas clonais eficientes contra antígenos bacterianos, parasitários e fúngicos oportunistas.',
      'Infecções Oportunistas Múltiplas, Recorrentes e Graves: Devido ao colapso imunológico mediado por células, organismos oportunistas ou de baixa patogenicidade causam quadros clínicos devastadores e refratários: infecções fúngicas invasivas profundas (Criptococose com destruição do plano nasal e invasão do SNC, Histoplasmose sistêmica, Aspergilose sinonasal); hemoplasmose severa por Mycoplasma haemofelis com crises hemolíticas refratárias; toxoplasmose disseminada com pneumonite necrosante e coriorretinite; além de rinites bacterianas crônicas proliferativas com lise de conchas nasais e broncopneumonias recorrentes.',
      'Gengivite e Estomatite Crônica Fauciana Severa e Refratária (FCGS): Inflamação e ulceração transmural exuberantíssima dos arcos glossopalatinos, mucosa jugal e gengiva livre, desencadeada por hiper-reatividade imune anômala a antígenos da placa dentária e coinfecção crônica por Calicivírus Felino (FCV). Causa dor orofacial excruciante intratável, sialorreia filamentosa fétida com sangue, incapacidade mecânica de apreender e mastigar alimentos, perda ponderal progressiva e resposta frequentemente inferior à exodontia subtotal em comparação com gatos não portadores de retrovirose.',
      'Neoplasias Secundárias de Alta Malignidade: O risco de desenvolvimento de neoplasias em gatos FIV-positivos é 5 a 6 vezes superior ao de gatos negativos, primariamente decorrente da perda da vigilância imune antitumoral por linfócitos T e células NK, associada à estimulação policlonal contínua de linfócitos B: destacam-se os Linfomas Extranodais de Células B (ocular, nasal, renal, do sistema nervoso central e multicêntrico), o Carcinoma de Células Escamosas (CCE) cutâneo e oral com comportamento biológico significativamente mais agressivo, osteossarcomas e leucemias.',
      'Nefropatia Imunomediada e Aceleração da Doença Renal Crônica (DRC): A estimulação policlonal contínua de linfócitos B gera hipergamaglobulinemia crônica, com formação contínua de complexos antígeno-anticorpo solúveis que se depositam nos glomérulos renais. Provoca glomerulonefrite proliferativa membranosa crônica com proteinúria patológica persistente (RPCU > 0,4 a 1,0), glomeruloesclerose acelerada e rápida perda de néfrons funcionais, adiantando o surgimento de DRC terminal com azotemia severa e hipertensão arterial.',
      'Complexo Demência-FIV e Neuropatias Primárias: A invasão direta do parênquima cerebral por monócitos/macrófagos infectados e a infecção crônica de células microgliais induzem neuroinflamação crônica com liberação local de óxido nítrico, glutamato e citocinas neurotóxicas. Clinicamente manifesta-se por alterações de personalidade e comportamento (agressividade súbita, perda de hábitos de higiene na caixa de areia, miados compulsivos noturnos, desorientação espacial), ataxia proprioceptiva progressiva, dismetria e crises convulsivas focais ou generalizadas.',
    ],
    prognostico:
      'Muito bom a excelente durante a longa fase de infecção assintomática crônica (fase subclínica), que pode se estender por muitos anos ou por toda a expectativa de vida natural do felino, desde que ele seja mantido estritamente confinado em ambiente intradomiciliar, sob excelente suporte nutricional, manejo vacinal e profilático contra ecto e endoparasitas e com consultas clínicas e exames laboratoriais semestrais. O prognóstico torna-se reservado a desfavorável quando o gato progride para a fase clínica avançada (síndrome de imunodeficiência adquirida felina terminal), caracterizada por perda de peso intratável, citopenias medulares graves, neoplasias secundárias ou infecções oportunistas sistêmicas invasivas refratárias.',
  },

  'diseases.insuficiencia-pancreatica-exocrina-caes-gatos.seed.ts': {
    principais: [
      'Síndrome de Má Digestão e Má Absorção Severa com Caquexia Extrema: A destruição de mais de 90% da capacidade funcional secretória das células acinares pancreáticas elimina a secreção intraluminal de lipase, tripsina, quimiotripsina e amilase pancreáticas. Sem essas enzimas essenciais, os macronutrientes da dieta não são hidrolisados na luz duodenal, permanecendo na luz intestinal como partículas osmoticamente ativas. Ocorre esteatorreia volumosa, perda fecal maciça de lipídios e proteínas, atrofia muscular esquelética difusa progressiva com emaciação caquética profunda, fraqueza severa e polifagia voraz compensatória.',
      'Deficiência Severa de Cobalamina (Vitamina B12) e Atrofia das Vilosidades: O Fator Intrínseco — glicoproteína carreadora indispensável para a absorção ileal ativa mediada por receptor da cobalamina — é sintetizado quase que com exclusividade pelo pâncreas exócrino em gatos (100%) e em cães (> 95%). A perda do tecido acinar leva invariavelmente a hipocobalaminemia severa (< 150 ng/L), que compromete a renovação celular entérica da mucosa, deflagrando atrofia das vilosidades intestinais, enteropatia difusa com perda de borda em escova, neuropatia periférica, anemia macrocítica arregenerativa e falha terapêutica completa à reposição enzimática se a cobalamina não for suplementada por via parenteral.',
      'Disbiose Intestinal e Supercrescimento Bacteriano no Intestino Delgado (SIBO / ARD): O suco pancreático exerce ação antibacteriana fisiológica indispensável que modula a densidade microbiana do lúmen entérico. Na IPE, a ausência dessas enzimas somada à presença abundante e contínua de nutrientes indigeridos favorece a proliferação bacteriana descontrolada no jejuno e íleo (especialmente coliformes e anaeróbios estritos). As bactérias desconjugam os sais biliares (impedindo a formação de micelas e agravando a má absorção de gorduras), metabolizam carboidratos produzindo gases e ácidos graxos de cadeia curta irritantes, gerando meteorismo fétido, dor tipo cólica e enterite crônica bacteriana secundária.',
      'Coagulopatia e Hipovitaminoses Lipossolúveis (Vitaminas K, A, D e E): A ineficácia na digestão e solubilização de lipídios compromete criticamente a absorção ileal das quatro vitaminas lipossolúveis. A deficiência de Vitamina K impede a gama-carboxilação pós-traducional hepática dos fatores de coagulação vitamina K-dependentes (II, VII, IX e X), provocando prolongamento marcante dos tempos de coagulação (TP e TTPA) e risco de sangramentos espontâneos fatais (hematomas, hematoquezia, epistaxe), complicação particularmente grave e comum em felinos com IPE.',
      'Diabetes Mellitus Concomitante por Destruição Pancreática Mista: Nos casos de IPE secundária à pancreatite crônica recorrente necrosante fibrótica (frequente em gatos e em raças caninas como o Schnauzer Miniatura), o processo inflamatório-destrutivo crônico aniquila simultaneamente as células acinares exócrinas e as ilhotas de Langerhans endócrinas (células beta produtoras de insulina). O paciente desenvolve Diabetes Mellitus insulino-dependente associado, cujo controle glicêmico é extremamente complexo devido à absorção intestinal errática e instável de carboidratos.',
      'Dermatopatias por Deficiência de Ácidos Graxos Essenciais e Zinco: A privação crônica de absorção de lipídios e micronutrientes debilita a síntese lipídica do estrato córneo epidérmico. Causa pelagem seca, quebradiça e sem brilho, hipotricose/alopecia difusa, dermatite descamativa seborreica severa e dermatite perianal/perineal intensamente eritematosa e ulcerada pela passagem constante de fezes esteatorreicas ácidas e irritantes.',
    ],
    prognostico:
      'Excelente a muito bom na imensa maioria dos cães tratados adequadamente com terapia de reposição enzimática pancreática (PERT) regular e contínua adicionada às refeições, associada à correção parenteral da hipocobalaminemia, propiciando ganho de peso progressivo e recuperação plena da qualidade e expectativa de vida. O prognóstico torna-se mais reservado nos casos com recusa alimentar crônica das enzimas em pó, em gatos e cães com enteropatia inflamatória crônica (IBD) subjacente refratária, na presença de hipocobalaminemia persistente não responsiva ou quando há associação com Diabetes Mellitus secundário a pancreatite crônica terminal.',
  },

  'diseases.giardiase-caes-gatos.seed.ts': {
    principais: [
      'Desidratação Severa, Desequilíbrio Hidroeletrolítico e Choque Hipovolêmico: Em animais jovens (filhotes recém-desmamados e em idade de creche/canil), idosos ou imunocomprometidos, a adesão e o encravamento massivo de milhares de trofozoítos de Giardia duodenalis aos enterócitos pelo disco ventral adesivo deflagram necrose e apoptose de enterócitos com atrofia difusa das vilosidades. Isso acarreta diarreia osmótica e secretória aguda grave e volumosa, perda massiva de água, sódio, potássio e bicarbonato, evoluindo rapidamente para hipocalemia severa, acidose metabólica, choque hipovolêmico distributivo e óbito rápido sem terapia fluida intensiva.',
      'Enteropatia Crônica com Perda Proteica (PLE) e Caquexia por Má Absorção: A disrupção mecânica contínua da barreira mucosal e o afrouxamento das junções intercelulares de oclusão (zonula occludens) provocam o extravasamento paracelular de macromoléculas e proteínas plasmáticas para a luz intestinal. Concomitantemente, a inibição das dissacaridases da borda em escova (maltase, sacarase, lactase) impede a clivagem e absorção de nutrientes, gerando esteatorreia crônica, hipoalbuminemia patológica, ascite em casos graves e retardo permanente do crescimento e desenvolvimento ósseo e muscular em filhotes.',
      'Disbiose Intestinal Crônica e Síndrome do Intestino Irritável Pós-Infecciosa: Mesmo após a eliminação parasitológica completa dos protozoários mediante tratamento antiparasitário adequado com fenbendazol ou metronidazol, a agressão epitelial prolongada associada à infiltração linfoplasmocitária da lâmina própria e à desestruturação da microbiota comensal do jejuno pode perpetuar um estado de hipersensibilidade mucosal sustentada. Manifesta-se como diarreia crônica intermitente, intolerância alimentar secundária a proteínas comuns, fezes pastosas com muco e dismotilidade entérica por semanas a meses pós-cura parasitológica.',
      'Intussuscepção Intestinal Aguda por Hiperperistaltismo: O tônus inflamatório hiper-reativo com peristaltismo espasmódico e descoordenado secundário à enterite aguda pode deflagrar a invaginação de um segmento do intestino proximal em uma alça adjacente distal (intussuscepção jejuno-jejunal ou ileocólica). Constitui abdômen agudo cirúrgico de emergência absoluta, cursando com dor abdominal intensa, vômitos em jato, obstrução luminal mecânica completa e risco de necrose isquêmica transmural, perfuração entérica e peritonite séptica fulminante se não submetido à enterectomia precoce.',
      'Coinfecções Sinérgicas Fatais: A quebra da barreira mucosal e imunológica intestinal promovida por Giardia duodenalis facilita e potencializa infecções entéricas concomitantes por Cryptosporidium spp., Cystoisospora spp., Coronavírus Entérico Canino e Parvovírus Canino (CPV-2) ou Panleucopenia Felina (FPV), elevando dramaticamente o índice de mortalidade em ninhadas e abrigos de animais.',
      'Zoonose e Potencial de Reinfecção Ambiental Recorrente: Os cistos de Giardia eliminados nas fezes já são imediatamente infectantes e extremamente resistentes a fatores climáticos adversos no meio ambiente úmido. A ausência de medidas higiênicas rigorosas no ambiente e a retenção de cistos na pelagem perianal do próprio paciente deflagram ciclos frustrantes de reinfecção autóloga. Além disso, embora os genótipos específicos de cão (assemblages C e D) e de gato (assemblage F) predominem, os genótipos zoonóticos cosmopolitas (assemblages A e B) podem infectar seres humanos contactantes vulneráveis, especialmente crianças e imunossuprimidos.',
    ],
    prognostico:
      'Excelente na grande maioria dos cães e gatos adultos imunocompetentes submetidos a protocolo antiparasitário adequado associado a rigoroso manejo higiênico ambiental (desinfecção com amônia quaternária ou vapor quente) e banho do paciente com xampu clorexidina no último dia do tratamento para remoção de cistos da pelagem. Reservado a grave em neonatos e filhotes com desidratação hiperaguda descompensada (> 8% a 10%), em pacientes que desenvolvam intussuscepção intestinal secundária ou em casos com coinfecções virais entéricas agressivas concomitantes (ex.: parvovirose).',
  },

  'diseases.coccidiose-caes-gatos.seed.ts': {
    principais: [
      'Enterite Hemorrágica Necrosante com Choque Hipovolêmico e Séptico: A replicação assexuada intracelular maciça e repetida (esquizogonia) seguida de fase sexuada (gametogonia) de Cystoisospora canis, C. ohioensis (cães) ou C. felis, C. rivolta (gatos) ocorre no interior dos enterócitos maduros do íleo e ceco. A maturação e liberação dos oocistos promovem a lise celular simultânea de milhares de células epiteliais, desnudando extensas áreas da mucosa e submucosa intestinal. Resulta em enterorrogia severa com diarreia mucossanguinolenta ou hemorrágica escura fétida, hipotermia, acidose metabólica láctica, perda volêmica crítica e translocação massiva de coliformes intestinais para a circulação, culminando em choque séptico distributivo em filhotes jovens.',
      'Desidratação Grave, Hipoglicemia e Colapso Circulatório Pediátrico: Filhotes com menos de 4 a 6 meses de vida possuem reservas de glicogênio hepático limitadas e uma taxa metabólica elevada com extrema sensibilidade ao estresse osmótico e volêmico. A combinação entre perdas intestinais profusas por diarreia aquosa sanguinolenta, êmese e anorexia prolongada deflagra desidratação hiperaguda, hipotermia e hipoglicemia severa (< 40 mg/dL), culminando em fraqueza extrema, fasciculações, crises convulsivas hipoglicêmicas, estupor e colapso circulatório fatal em questão de poucas horas sem suporte hidroterápico parenteral intensivo.',
      'Má Absorção e Retardo Severo do Crescimento (Nanismo Funcional Pediátrico): A destruição extensa da arquitetura das criptas e vilosidades intestinais e o processo de regeneração mucosal anômalo com deposição de tecido fibrótico cicatricial colapsam a superfície funcional absortiva do intestino delgado. O animal afetado desenvolve má absorção crônica grave de aminoácidos, lipídios e micronutrientes essenciais durante o pico de crescimento esquelético e muscular, resultando em emaciação, atrofia corporal difusa, raquitismo funcional e déficit ponderal de crescimento frequentemente irreversível.',
      'Intussuscepção Intestinal e Íleo Paralítico: O processo inflamatório transmural intenso com espasmos peristálticos desordenados no íleo distal e junção cecocólica pode precipitar invaginação intestinal (intussuscepção ileocólica ou jejuno-jejunal), constituindo emergência cirúrgica aguda de alto risco anestésico em filhotes debilitados. Alternativamente, a agressão toxêmica neuromuscular pode deflagrar íleo paralítico funcional com dilatação gasosa extrema de alças entéricas e dor tipo cólica excruciante.',
      'Coinfecções Sinérgicas Fatais: A destruição do epitélio mucosal provocada por Cystoisospora remove a barreira mecânica e enzimática primordial do trato digestivo, atuando como porta de entrada e amplificador biológico devastador para outros agentes infecciosos concomitantes, tais como o Parvovírus Canino (CPV-2), Vírus da Panleucopenia Felina (FPV), Giardia duodenalis, Campylobacter jejuni e Clostridium perfringens, multiplicando exponencialmente o risco de mortalidade pediátrica em canis e gatis.',
    ],
    prognostico:
      'Excelente em animais com mais de 3 a 4 meses de idade, imunocompetentes e bem nutridos que recebem diagnóstico precoce e terapia antiprotozoária direcionada eficaz (toltrazuril ou ponazuril em dose única/repetida, ou sulfadimetoxina por 10 a 14 dias), apresentando resolução clínica completa em poucos dias. Reservado a grave em neonatos e filhotes com menos de 8 a 10 semanas de idade em condições precárias de manejo, com desidratação severa descompensada (> 8% a 10%), hipotermia, hematoquezia volumosa profunda ou coinfecção com parvovirose canina/panleucopenia felina.',
  },

  'diseases.hiperparatireoidismo-caes-gatos.seed.ts': {
    principais: [
      'Crise Hipercalcêmica Aguda e Colapso Cardiovascular: No hiperparatireoidismo primário (adenoma paratireóideo funcionante) ou na hipercalcemia paraneoplásica grave, a elevação descontrolada e marcante do cálcio ionizado sérico (> 1,8 mmol/L ou cálcio sérico total > 15 a 18 mg/dL) altera o potencial de repouso e a refratariedade miocárdica. Ocorre encurtamento patológico do intervalo QT, prolongamento do intervalo PR, bloqueios atrioventriculares de alto grau, bradiarritmias refratárias, risco iminente de parada cardíaca em sístole, vasoconstrição arteriolar sistêmica severa e encefalopatia metabólica grave com estupor e coma.',
      'Nefrocalcinose, Insuficiência Renal Aguda (IRA) e Progressão para DRC: A hipercalcemia sustentada promove vasoconstrição reflexa da arteríola aferente renal com redução drástica da taxa de filtração glomerular. Quando o produto cálcio x fósforo (Ca x P) ultrapassa o limiar crítico de 55 a 60 mg²/dL², ocorre precipitação mineral metastática heterotópica insolúvel de cristais de fosfato de cálcio na membrana basal tubular renal e no interstício renal (nefrocalcinose irreversível). Esse processo deflagra necrose tubular aguda isquêmica, inflamação intersticial crônica, glomeruloesclerose e rápida progressão para Doença Renal Crônica (DRC) terminal.',
      'Urolitíase Recorrente por Oxalato de Cálcio e Fosfato de Cálcio: A hipercalcemia eleva a carga de cálcio filtrada pelos glomérulos além da capacidade fisiológica de reabsorção tubular na alça de Henle e túbulo distal (hipercalciúria crônica). Essa supersaturação urinária persistente deflagra a precipitação e crescimento de urólitos radiopacos de oxalato de cálcio e apatita na bexiga e nos rins/ureteres. As complicações incluem cistite hemorrágica recorrente, nefrite obstrutiva, obstrução ureteral unilateral ou bilateral com hidronefrose, perda de néfrons e uremia pós-renal aguda de emergência cirúrgica.',
      'Osteodistrofia Fibrosa Severa e Fraturas Patológicas: No hiperparatireoidismo secundário nutricional (dietas exclusivamente cárneas com deficiência de cálcio ou relação Ca:P invertida) ou renal (retenção crônica de fosfato e perda da hidroxilação de calcitriol na DRC), a secreção compensatória excessiva de PTH promove reabsorção osteoclástica óssea descontrolada e difusa. A matriz mineral e osteoide é destruída e substituída por tecido conjuntivo fibroso vascularizado proliferativo. Isso provoca osteopenia generalizada, "mandíbula de borracha" (rubber jaw) com mobilidade e perda dentária espontânea, deformidades vertebrais cifoescolióticas com colapso do canal vertebral, estenose do canal pélvico e fraturas patológicas espontâneas em ossos longos sob cargas mecânicas triviais.',
      'Hipocalcemia Pós-Operatória Crítica (Síndrome do Osso Faminto / "Hungry Bone Syndrome"): Imediatamente após a paratireoidectomia cirúrgica curativa ou ablação guiada por imagem do adenoma paratireóideo autônomo no hiperparatireoidismo primário, o tecido paratireóideo normal contralateral remanescente encontra-se profundamente atrófico devido ao feedback negativo crônico por hipercalcemia. Ocorre queda abrupta e precipitosa das concentrações séricas de PTH e de cálcio ionizado dentro de 24 a 72 horas pós-operatórias, enquanto o esqueleto desmineralizado absorve vorazmente cálcio e fósforo da circulação. Manifesta-se com hipocalcemia tetânica crítica: ansiedade motora, prurido facial compulsivo (patadas na face), rigidez em cavalete dos membros, fasciculações musculares difusas, laringoespasmo e crises convulsivas tetânicas potencialmente fatais sem monitorização rigorosa de Ca ionizado e infusão imediata de gluconato de cálcio a 10%.',
      'Úlceras Gastrointestinais e Pancreatite Aguda Necrotizante: O cálcio ionizado elevado atua como agonista direto nos receptores de gastrina das células parietais gástricas, hiperestimulando a secreção de ácido clorídrico e predispondo a gastrite erosiva severa e úlceras pépticas perfurantes. Além disso, a hipercalcemia desestabiliza as membranas dos zimogênios pancreáticos e ativa precocemente o tripsinogênio dentro dos ácinos pancreáticos, deflagrando pancreatite aguda necrotizante fulminante.',
    ],
    prognostico:
      'Hiperparatireoidismo Primário: excelente na maioria esmagadora dos cães submetidos à paratireoidectomia cirúrgica eletiva ou ablação percutânea por calor/etanol por ultrassonografia, alcançando taxa de cura superior a 90% a 95%, desde que o manejo e a monitorização rigorosa da hipocalcemia pós-operatória nas primeiras 48 a 96 horas sejam conduzidos meticulosamente e não haja nefrocalcinose com falência renal crônica irreversível pré-instalada. Hiperparatireoidismo Secundário Nutricional: excelente se diagnosticado precocemente e instituída correção nutricional balanceada com dietas comerciais completas (ou suplementação equilibrada de carbonato de cálcio), antes que deformidades anatômicas permanentes (como compressão de canal pélvico ou desvios de coluna vertebral) estejam consolidadas. Hiperparatireoidismo Secundário Renal: reservado a desfavorável, uma vez que espelha Doença Renal Crônica avançada (IRIS Estágios 3 e 4), exigindo uso contínuo de quelantes de fósforo entéricos, controle dietético estrito de fósforo e calcitriol em microdoses quando estritamente indicado e monitorizado.',
  },

  'diseases.prostatite-caes-gatos.seed.ts': {
    principais: [
      'Abscesso Prostático Volumoso e Risco de Ruptura com Peritonite Séptica Fulminante: Na prostatite bacteriana aguda grave, a proliferação destrutiva bacteriana e a confluência de microabscessos necróticos intraparenquimatosos coalescem formando coleções purulentas cavitárias gigantescas encapsuladas (abscesso prostático). A parede dessas cápsulas teciduais é friável e propensa à ruptura espontânea ou iatrogênica (por palpação transretal vigorosa ou tentativa inadvertida de punção cistocêntica). A ruptura extravasa pus repleto de coliformes, estafilococos ou anaeróbios para o retroperitônio e cavidade peritoneal livre, deflagrando peritonite séptica hiperaguda, choque distributivo séptico e mortalidade cirúrgica superior a 40% a 50%.',
      'Choque Séptico e Falência de Múltiplos Órgãos por Bacteremia Sistêmica: A exuberante vascularização arteriovenosa prostática e o colapso da integridade da barreira vascular inflamatória facilitam a translocação de microrganismos patogênicos (como Escherichia coli uropatogênica, Proteus mirabilis, Klebsiella spp. e Pseudomonas aeruginosa) para o leito vascular sistêmico. Essa bacteremia sustentada desencadeia a Síndrome da Resposta Inflamatória Sistêmica (SIRS), microtrombose por ativação endotelial, coagulopatia intravascular disseminada (CIVD) e choque séptico distributivo com hipotensão refratária.',
      'Pielonefrite Aguda Ascendente e Insuficiência Renal Aguda: A contaminação do lúmen uretral prostático associada à cistite bacteriana secundária e à alteração funcional inflamatória dos óstios ureterais no trígono vesical permite a ascensão retrógrada de uropatógenos ao longo dos ureteres até a pelve renal e parênquima medular. Provoca pielonefrite necrosante uni ou bilateral com dor lombar aguda severa, necrose papilar renal, falência renal aguda isquêmico-inflamatória e risco de perda funcional de néfrons a longo prazo.',
      'Obstrução Urinária e Retenção Urinária Aguda com Hidronefrose Pós-Renal: O aumento de volume acentuado da glândula prostática por edema e infiltração celular associado ao espasmo esfincteriano reflexo induzido por dor periuretral severa comprime concentricamente a uretra prostática. Desenvolve-se retenção urinária aguda com distensão vesical extrema dolorosa em bexiga de cólica, risco iminente de ruptura vesical, hidroureter e hidronefrose obstrutiva pós-renal com azotemia aguda e hipercalemia ameaçadora à vida.',
      'Prostatite Bacteriana Crônica Recorrente e Cistite Refratária: Devido à presença da barreira hemato-prostática lipídica intacta na fase crônica, muitos antibióticos hidrossolúveis de uso comum (como penicilinas simples, aminoglicosídeos e cefalosporinas de primeira geração) não conseguem penetrar nem atingir concentrações terapêuticas mínimas inibitórias (CIM) no interior do ácino e estroma prostático. A glândula atua como foco infeccioso crônico sequestrado que continuamente inocula bactérias na urina vesical, produzindo infecções urinárias recorrentes frustrantes e prostatólitos (cálculos prostáticos infectados) de difícil erradicação sem castração e antibioticoterapia lipofílica prolongada (ex.: fluoroquinolonas ou trimetoprima-sulfa por 4 a 6 semanas).',
      'Disquezia Crônica, Obstipação e Tenesmo com Megacólon Funcional Secundário: A expansão simétrica ou assimétrica do parênquima prostático aumentada projeta a glândula dorsalmente contra a face ventral do canal pélvico e reto. Essa compressão mecânica impede a passagem do bolo fecal normal, gerando disquezia crônica severa, tenesmo fecal persistente, fezes aplanadas em fita e impactação fecal crônica que pode culminar em dilatação atônica do cólon descendente com megacólon secundário.',
    ],
    prognostico:
      'Prostatite bacteriana aguda não complicada em cães: bom a excelente quando instituída antibioticoterapia lipofílica direcionada com alta penetração prostática (fluoroquinolonas como enrofloxacina/marbofloxacina ou trimetoprima-sulfa) por 4 a 6 semanas ininterruptas, acompanhada de orquiectomia eletiva (castração) após a estabilização do quadro para induzir atrofia do parênquima glandular. Abscesso prostático e cistos infectados: reservado a grave, exigindo intervenção cirúrgica meticulosa (drenagem com omentalização prostática) associada a orquiectomia; prognóstico altamente desfavorável se houver ruptura prévia com peritonite séptica generalizada. Prostatite felina: extremamente rara na espécie, apresentando prognóstico reservado a desfavorável, pois habitualmente está associada a neoplasias prostáticas primárias malignas altamente agressivas (adenocarcinomas ou carcinomas indiferenciados) ou abscesso complexo.',
  },

  'diseases.gengivoestomatite-cronica-felina.seed.ts': {
    principais: [
      'Dor Orofacial Excruciante Incapacitante e Síndrome de Dor Neuropática Crônica: A inflamação proliferativa e ulcerativa transmural crônica e exuberante da mucosa oral e dos arcos palatoglossos mantém uma estimulação nociceptiva ininterrupta dos ramos sensitivos periféricos do nervo trigêmeo. Ocorre sensibilização periférica e central profunda ("wind-up"), gerando alodinia mecânica e hiperalgesia orofacial intratável. O gato manifesta vocalizações lancinantes na tentativa de apreensão alimentar, patadas frenéticas na boca (pawing at mouth), bruxismo (ranger de dentes doloroso) e comportamento de evitação alimentar absoluto (fobia à comida).',
      'Lipidose Hepática Secundária por Anorexia Prolongada: Devido à dor orofacial excruciante, o paciente recusa completamente a ingestão hídrica e alimentar por dias consecutivos (> 3 a 5 dias). O estresse catabólico do jejum prolongado em felinos desencadeia lipólise periférica descontrolada com mobilização maciça de ácidos graxos livres ao fígado, que ultrapassa a capacidade dos hepatócitos de sintetizar apolipoproteínas e exportar triglicerídeos como VLDL. Ocorre esteatose hepática intracelular maciça, colestase intra-hepática severa, hiperbilirrubinemia, coagulopatia e insuficiência hepática aguda fulminante com alta taxa de mortalidade se não houver rápida intervenção com tubo de esofagostomia para alimentação enteral forçada.',
      'Estenose Faucial Cicatricial e Disfagia Faringiana Mecânica: O processo inflamatório contínuo com deposição aberrante de tecido de granulação e subsequente retração fibrótica cicatricial nos arcos glossopalatinos (fauce caudal) resulta em estreitamento estenótico do orifício orofaríngeo. Provoca disfagia mecânica grave, engasgos, tosse reflexa dolorosa durante a deglutição, regurgitação, risco permanente de pneumonia aspirativa e incapacidade anatômica de deglutir alimentos de consistência sólida ou pastosa.',
      'Perda Dentária Extensa e Lesões de Reabsorção Dentária Felina (FORL / TR) Associadas: A infiltração linfoplasmocitária contínua da lâmina própria gengival e do ligamento periodontal ativa odontoclastos e osteoclastos locais, que destroem o cemento radicular, a dentina e o osso alveolar. Desenvolvem-se lesões reabsortivas de colo dentário intensamente dolorosas com exposição da câmara pulpar, mobilidade de dentes pré-molares e molares, abscessos periapicais crônicos e perda dentária progressiva espontânea.',
      'Desnutrição Proteico-Calórica Severa, Caquexia e Imunodepressão Secundária: A incapacidade crônica de manutenção do consumo energético basal consome as reservas de glicogênio e deflagra proteólise da musculatura temporal, massetérica e da musculatura epaxial dorsal. O estado catabólico profundo deprime a função imunológica do felino, predispondo a infecções bacterianas oportunistas e exacerbações clínicas de infecções virais latentes crônicas como o Calicivírus Felino (FCV) e o Herpesvírus Felino tipo 1 (FHV-1).',
      'Efeitos Adversos Iatrogênicos da Imunossupressão Farmacológica Prolongada: O uso paliativo continuado de corticosteroides sistêmicos (prednisolona em doses anti-inflamatórias ou imunossupressivas) induz resistência insulínica e diabetes mellitus esteroide-induzido em felinos, infecções assintomáticas do trato urinário e precipitação de insuficiência cardíaca congestiva aguda por retenção hídrica em animais com cardiomiopatia hipertrófica subclínica. O uso de ciclosporina pode induzir náuseas, vômitos, anorexia inicial e aumentar o risco de reativação de toxoplasmose latente.',
    ],
    prognostico:
      'Favorável a bom em cerca de 70% a 80% dos gatos submetidos precocemente à exodontia cirúrgica total ou subtotal (remoção completa de todos os dentes pré-molares e molares com ou sem caninos e incisivos), desde que realizada com confirmação radiográfica transoperatória estrita da remoção integral de todas as raízes e alisamento das cristas ósseas alveolares, propiciando resolução completa ou remissão clínica satisfatória e duradoura. Reservado nos cerca de 20% a 30% de casos classificados como "refratários pós-extração", que necessitam de manejo médico imunomodulador multimodal vitalício (ciclosporina, terapia celular com células-tronco mesenquimais, interferon ômega felino) associado a controle analgésico rigoroso com neuromoduladores (gabapentina) e opioides (buprenorfina) para manter a dignidade e a qualidade de vida do paciente.',
  },

  'diseases.doenca-periodontal-caes.seed.ts': {
    principais: [
      'Fístula Oronasal Crônica com Rinite Secundária e Sinusite: Na periodontite avançada (Estágio IV da AVDC), a perda óssea alveolar profunda atinge a face palatina da raiz do canino superior ou as raízes mediais e distais do quarto pré-molar superior (PM4). Ocorre a destruição osteoclástica completa da delgada lâmina óssea maxilar que separa o alvéolo dentário da fossa nasal ventral, estabelecendo uma comunicação permanente entre a cavidade oral e o meato nasal ventral. Restos alimentares, saliva e bactérias da placa penetram na cavidade nasal, deflagrando rinite purulenta crônica unilateral grave, espirros violentos pós-prandiais, secreção nasal mucossanguinolenta ou epistaxe intermitente e sinusite maxilar refratária.',
      'Fratura Patológica de Mandíbula por Osteomielite Periodontal: É uma complicação frequente e devastadora em cães de raças pequenas e toy (Poodle Toy, Yorkshire Terrier, Maltês, Spitz Alemão, Pinscher, Dachshund), nos quais a proporção do primeiro dente molar inferior (M1) em relação à espessura do corpo da mandíbula é desproporcionalmente grande (a raiz de M1 pode ocupar até 70% a 80% da altura óssea mandibular vertical). A perda óssea alveolar marginal e periapical associada à osteomielite bacteriana anaeróbia destrói a cortical óssea residual. Uma força mastigatória mínima, a apreensão de um brinquedo rígido ou o estresse mecânico de uma extração dentária inadequada deflagram a fratura patológica espontânea da mandíbula, cuja cicatrização óssea é extremamente complexa devido à infecção anaeróbia e à ausência de leito ósseo suficiente.',
      'Abscesso Retrobulbar e Celulite Orbitária: A extensão infecciosa e necrótica periapical a partir dos ápices radiculares do quarto pré-molar superior (PM4) ou dos primeiros e segundos molares superiores (M1 e M2) — cujos ápices repousam em íntima contiguidade anatômica com o assoalho da órbita óssea do cão — penetra no espaço periorbitário e retrobulbar. Manifesta-se agudamente com celulite orbitária purulenta e abscesso retrobulbar, cursando com exoftalmia unilateral extremamente dolorosa, protusão da terceira pálpebra, quemose conjuntival acentuada, dor excruciante à tentativa de abertura da boca e risco de amaurose permanente por neuropatia óptica compressiva isquêmica.',
      'Endocardite Bacteriana Infecciosa e Microêmbolos Sépticos Cardíacos: A mastigação repetida sobre tecidos gengivais cronicamente inflamados, ulcerados e colonizados por biofilme bacteriano denso provoca bacteremias transitórias frequentes e cumulativas por estreptococos e patógenos anaeróbios orais. As bactérias circulantes aderem às superfícies endoteliais com microlesões nas valvas cardíacas (primariamente as valvas mitral e aórtica), deflagrando vegetações sépticas valvares, endocardite infecciosa aguda com insuficiência valvar hiperaguda, colapso hemodinâmico, arritmias cardíacas ventriculares graves e disseminação de êmbolos sépticos sistêmicos.',
      'Nefropatia e Hepatopatia Inflamatória por Imunocomplexos e Microtrombose Séptica: A liberação contínua de endotoxinas bacterianas (LPS) e antígenos da placa periodontal na circulação sistêmica deflagra a formação contínua de complexos antígeno-anticorpo que se depositam no mesângio e membrana basal glomerular renal, provocando glomerulonefrite crônica com microalbuminúria persistente e rápida progressão para Doença Renal Crônica (DRC). No fígado, as bactérias e citocinas orais carreadas pela circulação venosa geram infiltrados inflamatórios periportais crônicos, colangio-hepatite reativa e elevação persistente de enzimas hepáticas (ALT e Fosfatase Alcalina).',
      'Osteomielite Crônica Mandibular e Maxilar com Sequestro Ósseo e Fístula Cutânea Facial: A invasão bacteriana profunda nos canais medulares do osso esponjoso e cortical acarreta trombose séptica dos vasos intraósseos, isquemia focal e necrose de fragmentos ósseos corticais que se desprendem formando sequestros ósseos avasculares. Clinicamente manifesta-se com abscesso dentário fistulizado que drena exsudato purulento fétido crônico através da pele da face (fístula infraorbitária na altura do canto medial do olho) ou na margem ventral do ramo mandibular.',
    ],
    prognostico:
      'Gengivite e Periodontite Precoce (Estágios I e II da AVDC): excelente a muito bom, com reversibilidade total do processo inflamatório ou estabilização anatômica mediante profilaxia periodontal profissional sob anestesia geral inalatória com ultrassom e polimento coronário, associada à instituição rigorosa de higiene oral mecânica domiciliar diária com escovação dentária. Periodontite Moderada a Grave (Estágios III e IV da AVDC): desfavorável quanto à manutenção dos dentes gravemente afetados, exigindo extrações cirúrgicas abertas com odontosecção e fechamento primário por retalhos mucoperiósticos sem tensão; o prognóstico global para o paciente torna-se excelente assim que todas as fontes ativas de dor, osteomielite e infecção bacteriana crônica são completamente extirpadas do arco dentário.',
  },

  'diseases.doenca-periodontal-gatos.seed.ts': {
    principais: [
      'Lesões de Reabsorção Dentária Felina (FORL / TR) Secundárias e Concomitantes: A inflamação crônica do sulco gengival e do ligamento periodontal deflagra o recrutamento e a ativação desregulada de odontoclastos a partir das células progenitoras periodontais. Os odontoclastos degradam progressivamente o cemento radicular e a dentina ao nível da junção cemento-esmalte (colo do dente) e das raízes, penetrando na câmara pulpar. A exposição da polpa e dos túbulos dentinários expostos ao meio bucal deflagra dor odontogênica excruciante ("chattering" ou tremor espasmódico mandibular à palpação ou mastigação), fratura espontânea da coroa dentária com retenção de raízes necróticas subgengivais e necessidade imperiosa de extração dentária completa ou amputação coronária (em casos de anquilose e substituição óssea do Tipo 2 confirmados por radiografia intraoral).',
      'Fístula Oronasal e Fraturas Mandibulares e Maxilares Felinas: Pela delicadeza e espessura milimétrica do esqueleto crânio-facial dos gatos, a reabsorção osteoclástica periapical induzida pela infecção do canino superior ou do primeiro molar inferior (M1) perfura com rapidez a fina lâmina palatina, estabelecendo fístula oronasal crônica com espirros e rinite unilateral purulenta. Na mandíbula, a destruição óssea periapical em torno da raiz volumosa de M1 pode reduzir a cortical mandibular a uma casca óssea extremamente delgada, deflagrando fratura patológica espontânea da mandíbula durante mastigação comum de ração seca.',
      'Abscesso Retrobulbar Felino e Celulite Orbitária: A proximidade espacial extrema entre os ápices dos pré-molares superiores e do primeiro molar superior felino com a cavidade orbitária permite a migração direta de infecções periapicais para o tecido retrobulbar. O felino apresenta protrusão unilateral aguda do globo ocular (exoftalmia), protusão da terceira pálpebra, dor intensa que impede a abertura da boca, anorexia hiperaguda e risco iminente de neurite óptica isquêmica compressiva com amaurose unilateral irreversível.',
      'Anorexia Induzida por Dor Oral com Risco Iminente de Lipidose Hepática Felina: A dor aguda excruciante provocada pelo contato de partículas alimentares com o tecido gengival ulcerado e as superfícies dentinárias expostas leva o felino a interromper completamente a ingestão alimentar. O estresse de jejum sustentado (> 48 a 72 horas) em gatos, em particular aqueles sobrepesados ou obesos, deflagra rápida lipólise periférica descontrolada com mobilização massiva de ácidos graxos para o fígado, culminando em lipidose hepática fulminante com icterícia, colestase intra-hepática e alta mortalidade sem intervenção precoce.',
      'Disseminação Sistêmica Séptica e Sobrecarga Renal Crônica (Aceleração da DRC): A bacteremia crônica de baixo grau associada à mastigação em gengivas cronicamente inflamadas induz a circulação diária de lipopolissacarídeos (LPS) e antígenos bacterianos. Esses fatores estimulam a liberação sustentada de mediadores inflamatórios sistêmicos e a deposição crônica de imunocomplexos no mesângio glomerular. Em uma espécie onde a prevalência de Doença Renal Crônica (DRC) já ultrapassa 30% a 50% nos animais idosos, a periodontite crônica não tratada atua como um potente acelerador da perda progressiva de néfrons funcionais, microalbuminúria e hipertensão arterial secundária.',
      'Retenção de Fragmentos Radiculares Necróticos e Osteíte Alveolar Esclerosante: Coroas dentárias fragilizadas que sofrem fratura patológica espontânea deixam raízes dentárias necróticas sepultadas no osso alveolar sob mucosa gengival aparentemente intacta. Essas raízes funcionam como corpos estranhos cronicamente infectados, perpetuando osteomielite focal, dor orofacial persistente ("dor fantasma"), hiporexia crônica e granulomas periapicais que somente são diagnosticados através de exame radiográfico intraoral odontológico sistemático e resolvidos por exodontia cirúrgica meticulosa.',
    ],
    prognostico:
      'Estágio I (Gengivite): excelente, com reversibilidade anatômica completa mediante higienização ultrassônica supragengival e subgengival sob anestesia geral e instituição de cuidados domiciliares com produtos com selo VOHC. Periodontite Moderada a Avançada (Estágios III e IV) ou Lesões Reabsortivas (FORL) avançadas: excelente quanto ao alívio dos sinais clínicos e recuperação do bem-estar geral após exodontia cirúrgica cuidadosa dos dentes afetados com retalhos mucoperiósticos sem tensão e curetagem do alvéolo, promovendo a eliminação definitiva de todos os focos álgicos e sépticos da cavidade oral.',
  },
};

const seedDir = path.resolve('modules/consulta-vet/data/seed');

let successCount = 0;

for (const [filename, compData] of Object.entries(complicationsMap)) {
  const filePath = path.join(seedDir, filename);
  if (!fs.existsSync(filePath)) {
    console.error(`File not found: ${filePath}`);
    continue;
  }

  let content = fs.readFileSync(filePath, 'utf8');

  // Check if complications already exists
  if (/^\s*complications:\s*\{/m.test(content)) {
    console.log(`[SKIP] ${filename} already has complications.`);
    continue;
  }

  // Find prevention
  const preventionRegex = /((\r?\n)([ \t]*)prevention:\s*\{?)/;
  const match = content.match(preventionRegex);
  if (!match) {
    console.error(`[ERROR] Could not find prevention in ${filename}`);
    continue;
  }

  const nl = match[2];
  const indent = match[3];

  // Format complications block
  const formatArray = (arr: string[]) => {
    return arr
      .map(item => `${indent}    ${JSON.stringify(item)},`)
      .join(nl);
  };

  const complicationsBlock = `${indent}complications: {${nl}` +
    `${indent}  principais: [${nl}` +
    `${formatArray(compData.principais)}${nl}` +
    `${indent}  ],${nl}` +
    `${indent}  prognostico:${nl}` +
    `${indent}    ${JSON.stringify(compData.prognostico)},${nl}` +
    `${indent}},${nl}${nl}`;

  // Insert complications right before prevention
  const replaced = content.replace(preventionRegex, `${complicationsBlock}$1`);
  fs.writeFileSync(filePath, replaced, 'utf8');
  console.log(`[SUCCESS] Added complications to ${filename}`);
  successCount++;
}

console.log(`\nFinished: successfully updated ${successCount} files.`);
