import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Textarea } from '@/components/ui/Textarea';
import { FileText, Sparkles, Wand2, CheckCircle2, AlertTriangle, ArrowRight } from 'lucide-react';
import { usePatientStore } from '@/store/patientStore';

export function SmartImport() {
  const [rawText, setRawText] = useState('');
  const [isProcessing, setIsProcessing] = useState(false);
  const [isSuccess, setIsSuccess] = useState(false);
  const navigate = useNavigate();
  const addPatient = usePatientStore(state => state.addPatient);

  const handleImport = () => {
    if (!rawText.trim()) return;
    
    setIsProcessing(true);
    
    // Simulate AI processing delay
    setTimeout(() => {
      setIsProcessing(false);
      setIsSuccess(true);
      
      // Add a mock patient based on the "import"
      const newPatient = {
        id: Math.random().toString(36).substr(2, 9),
        patientMasterId: '', // Will be generated by store
        name: 'Bidu',
        species: 'Canina' as const,
        breed: 'Poodle',
        age: '10 anos',
        weight: '8 kg',
        tutor: 'João Silva',
        mainDiagnosis: 'Insuficiência Cardíaca Congestiva',
        status: 'OBSERVAÇÃO' as const,
        badges: ['CARDIOPATA', 'EXAME PENDENTE'],
        summary: 'Paciente com tosse crônica e cansaço. Ecocardiograma sugere ICC. Iniciado tratamento com Pimobendan e Furosemida.',
        definingPhrase: 'Cardiopata descompensado, monitorar FR.',
        problems: [
          { id: 'p1', name: 'Tosse', status: 'ativo' as const, priority: 'média' as const, notes: 'Piora à noite' },
          { id: 'p2', name: 'Edema Pulmonar', status: 'melhorando' as const, priority: 'alta' as const, notes: 'Furosemida em curso' }
        ],
        tasks: [
          { id: 't1', shiftPatientId: '', title: 'Aferir FR', time: '14:00', category: 'monitoramento' as const, priority: 'alta' as const, completed: false },
          { id: 't2', shiftPatientId: '', title: 'Pimobendan 0.25mg/kg', time: '20:00', category: 'medicação' as const, priority: 'alta' as const, completed: false }
        ]
      };
      
      addPatient(newPatient);
      
      // Navigate to the new patient after a short delay
      setTimeout(() => {
        navigate(`/paciente/${newPatient.id}`);
      }, 1500);
      
    }, 3000);
  };

  const handleUseExample = () => {
    setRawText(`Paciente: Bidu, Canino, Poodle, 10 anos, 8kg. Tutor: João Silva.
Motivo da consulta: Tosse seca há 2 semanas, piora à noite, cansaço fácil.
Histórico: Nega vômitos ou diarreia. Apetite preservado.
Exame físico: Mucosas normocoradas, TPC 2s, FC 140bpm, FR 40bpm. Ausculta cardíaca com sopro sistólico grau IV/VI em foco mitral. Ausculta pulmonar com crepitações em lobos caudais.
Suspeita: Insuficiência Cardíaca Congestiva (ICC) secundária a DMVM.
Conduta: Solicito Ecocardiograma e Radiografia de tórax.
Prescrição inicial: Furosemida 2mg/kg BID, Pimobendan 0.25mg/kg BID.
Observações: Manter em repouso, monitorar frequência respiratória (FR) em casa.`);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8 pb-12">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-[var(--text-main)] flex items-center gap-3">
          <Sparkles className="w-8 h-8 text-[var(--primary)]" />
          Prontuário Inteligente
        </h1>
        <p className="text-[var(--text-muted)] mt-2 text-lg">
          Cole o texto bruto da ficha do paciente. O sistema irá organizar automaticamente as informações nas seções corretas do PlantãoVET.
        </p>
      </div>

      <Card className="border-[var(--primary)]/20 shadow-lg overflow-hidden relative">
        {/* Decorative background element */}
        <div className="absolute top-0 right-0 w-64 h-64 bg-gradient-to-br from-[var(--primary)]/10 to-[var(--accent-purple)]/10 blur-3xl rounded-full -translate-y-1/2 translate-x-1/2 pointer-events-none" />
        
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-[var(--primary)]" />
            Texto Bruto do Prontuário
          </CardTitle>
          <CardDescription>
            Copie e cole todo o histórico, evolução, exames e prescrições. Nossa IA fará o trabalho pesado de estruturar os dados.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6 relative z-10">
          <div className="relative">
            <Textarea 
              value={rawText}
              onChange={(e) => setRawText(e.target.value)}
              placeholder="Cole aqui o texto do prontuário..."
              className="min-h-[300px] text-base resize-y font-mono bg-[var(--surface-hover)]/50 focus:bg-[var(--surface)] transition-colors"
              disabled={isProcessing || isSuccess}
            />
            
            <AnimatePresence>
              {isProcessing && (
                <motion.div 
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="absolute inset-0 bg-[var(--surface)]/80 backdrop-blur-sm flex flex-col items-center justify-center rounded-md border border-[var(--border)]"
                >
                  <div className="w-16 h-16 relative mb-4">
                    <div className="absolute inset-0 border-4 border-[var(--primary)]/30 rounded-full" />
                    <div className="absolute inset-0 border-4 border-[var(--primary)] rounded-full border-t-transparent animate-spin" />
                    <Wand2 className="absolute inset-0 m-auto w-6 h-6 text-[var(--primary)] animate-pulse" />
                  </div>
                  <h3 className="text-lg font-semibold text-[var(--text-main)]">Analisando Prontuário...</h3>
                  <p className="text-sm text-[var(--text-muted)] mt-2">Extraindo parâmetros, problemas ativos e medicações</p>
                </motion.div>
              )}
              
              {isSuccess && (
                <motion.div 
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  className="absolute inset-0 bg-[var(--surface)]/90 backdrop-blur-md flex flex-col items-center justify-center rounded-md border border-[var(--accent-green)]/50"
                >
                  <motion.div 
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    transition={{ type: "spring", bounce: 0.5 }}
                    className="w-16 h-16 bg-[var(--accent-green)]/20 rounded-full flex items-center justify-center mb-4"
                  >
                    <CheckCircle2 className="w-8 h-8 text-[var(--accent-green)]" />
                  </motion.div>
                  <h3 className="text-xl font-bold text-[var(--text-main)]">Prontuário Estruturado!</h3>
                  <p className="text-[var(--text-muted)] mt-2">Redirecionando para a ficha do paciente...</p>
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
            <div className="flex gap-3 w-full sm:w-auto">
              <Button 
                variant="outline" 
                onClick={() => setRawText('')}
                disabled={isProcessing || isSuccess || !rawText}
                className="w-full sm:w-auto"
              >
                Limpar
              </Button>
              <Button 
                variant="secondary" 
                onClick={handleUseExample}
                disabled={isProcessing || isSuccess || rawText.length > 0}
                className="w-full sm:w-auto"
              >
                Usar Exemplo
              </Button>
            </div>
            
            <Button 
              size="lg" 
              onClick={handleImport}
              disabled={isProcessing || isSuccess || !rawText.trim()}
              className="w-full sm:w-auto bg-gradient-to-r from-[var(--primary)] to-[var(--accent-purple)] hover:opacity-90 transition-opacity shadow-lg shadow-[var(--primary)]/20"
            >
              {isProcessing ? 'Organizando...' : 'Organizar Prontuário'}
              {!isProcessing && <ArrowRight className="w-5 h-5 ml-2" />}
            </Button>
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="flex gap-4 items-start p-4 rounded-xl bg-[var(--surface-hover)] border border-[var(--border)]">
          <div className="p-2 bg-[var(--primary)]/10 rounded-lg text-[var(--primary)] shrink-0">
            <Sparkles className="w-5 h-5" />
          </div>
          <div>
            <h4 className="font-medium text-[var(--text-main)]">Estruturação Automática</h4>
            <p className="text-sm text-[var(--text-muted)] mt-1">O sistema identifica problemas ativos, parâmetros e medicações, distribuindo nas abas corretas.</p>
          </div>
        </div>
        <div className="flex gap-4 items-start p-4 rounded-xl bg-[var(--surface-hover)] border border-[var(--border)]">
          <div className="p-2 bg-[var(--accent-yellow)]/10 rounded-lg text-[var(--accent-yellow)] shrink-0">
            <AlertTriangle className="w-5 h-5" />
          </div>
          <div>
            <h4 className="font-medium text-[var(--text-main)]">Revisão Necessária</h4>
            <p className="text-sm text-[var(--text-muted)] mt-1">A IA organiza os dados, mas não substitui seu julgamento clínico. Revise sempre antes de salvar.</p>
          </div>
        </div>
        <div className="flex gap-4 items-start p-4 rounded-xl bg-[var(--surface-hover)] border border-[var(--border)]">
          <div className="p-2 bg-[var(--accent-green)]/10 rounded-lg text-[var(--accent-green)] shrink-0">
            <FileText className="w-5 h-5" />
          </div>
          <div>
            <h4 className="font-medium text-[var(--text-main)]">Boletins Facilitados</h4>
            <p className="text-sm text-[var(--text-muted)] mt-1">Com o prontuário estruturado, gerar boletins técnicos e para tutores leva apenas um clique.</p>
          </div>
        </div>
      </div>
    </div>
  );
}
