alter table public.consulta_vet_medications
  add column if not exists official_site_url text,
  add column if not exists leaflet_url text,
  add column if not exists image_url text;

insert into public.consulta_vet_categories (slug, title, description, sort_order, is_published)
values (
  'infectologia',
  'Infectologia',
  'Doenças infecciosas, antimicrobianos e stewardship em pequenos animais.',
  10,
  true
)
on conflict (slug) do update
set
  title = excluded.title,
  description = excluded.description,
  is_published = true,
  updated_at = now();

with category as (
  select id from public.consulta_vet_categories where slug = 'infectologia' limit 1
),
records as (
  select *
  from jsonb_to_recordset($records$
[
  {
    "slug": "synulox-comprimidos-palataveis",
    "title": "Synulox Comprimidos Palatáveis",
    "active_ingredient": "Amoxicilina + clavulanato de potássio",
    "trade_names": ["Synulox 50 mg", "Synulox 250 mg"],
    "pharmacologic_class": "Aminopenicilina + inibidor de beta-lactamase",
    "species": ["dog", "cat"],
    "tags": ["antibiótico", "amoxicilina", "clavulanato", "tecidos moles", "stewardship"],
    "mechanism_of_action": "A amoxicilina inibe a síntese da parede bacteriana; o clavulanato inibe beta-lactamases e amplia a utilidade contra bactérias produtoras dessas enzimas.",
    "indications": ["Abscessos, mordeduras, feridas infectadas, doença periodontal e tecidos moles quando há suspeita de beta-lactamase.", "Algumas infecções respiratórias, urinárias ou gastrintestinais sensíveis, sempre conforme foco e avaliação clínica."],
    "contraindications": ["Hipersensibilidade a penicilinas, cefalosporinas ou beta-lactâmicos."],
    "cautions": ["Não usar automaticamente como primeira linha para cistite simples sem justificativa.", "Solicitar cultura/antibiograma em recorrência, falha terapêutica, infecção profunda ou suspeita de resistência."],
    "adverse_effects": ["Vômito, diarreia, hiporexia e reações de hipersensibilidade."],
    "interactions": ["Antibióticos bacteriostáticos podem antagonizar beta-lactâmicos em algumas situações clínicas."],
    "routes": ["VO"],
    "doses": [{"id":"synulox-both-125-q12","species":"both","indication":"Infecções bacterianas sensíveis com indicação para amoxicilina + clavulanato","doseMin":12.5,"doseMax":25,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q12h","duration":"Conforme foco; reavaliar resposta e duração.","notes":"Dose em mg/kg da associação. A bula cita 10 mg/kg de amoxicilina + 2,5 mg/kg de ácido clavulânico q12h.","calculatorEnabled":true}],
    "presentations": [{"id":"synulox-50","label":"Synulox 50 mg","form":"comprimido palatável","concentrationValue":50,"concentrationUnit":"mg","packInfo":"comprimidos palatáveis","route":"VO","scoringInfo":"fracionamento conforme bula/avaliação","channel":"veterinary"},{"id":"synulox-250","label":"Synulox 250 mg","form":"comprimido palatável","concentrationValue":250,"concentrationUnit":"mg","packInfo":"comprimidos palatáveis","route":"VO","scoringInfo":"fracionamento conforme bula/avaliação","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Antibiótico útil quando beta-lactamase é plausível, mas não deve substituir diagnóstico, foco provável e stewardship. Em infecções recorrentes, profundas, hospitalares ou com falha terapêutica, cultura e antibiograma são mandatórios.</p>",
    "references": [{"citationText":"Zoetis Brasil. Synulox Comprimidos Palatáveis.","sourceType":"site oficial","url":"https://www.zoetis.com.br/especies/animais-de-companhia/synulox-comprimidos-palataveis.aspx","notes":"Página oficial com indicação, apresentação e posologia."},{"citationText":"Zoetis Brasil. Bula Synulox Comprimidos Palatáveis.","sourceType":"bula","url":"https://www.zoetis.com.br/global-assets/private/synulox-comprimidos-palataveis.pdf","notes":"Bula do produto."},{"citationText":"Plumb's Veterinary Drug Handbook, 10ª ed. Dose de amoxicilina + clavulanato.","sourceType":"dose Plumb/literatura","url":null,"notes":"Resumo informado na pesquisa textual anexada: 12,5–25 mg/kg da associação VO q8–12h; uso conforme foco."}],
    "official_site_url": "https://www.zoetis.com.br/especies/animais-de-companhia/synulox-comprimidos-palataveis.aspx",
    "leaflet_url": "https://www.zoetis.com.br/global-assets/private/synulox-comprimidos-palataveis.pdf",
    "image_url": "https://www.zoetis.com.br/_locale-assets/img/animais-de-companhia/fotos-produtos/synulox-pack-zoetis.jpg"
  },
  {
    "slug": "agemoxi-cl",
    "title": "Agemoxi CL",
    "active_ingredient": "Amoxicilina tri-hidratada + clavulanato de potássio",
    "trade_names": ["Agemoxi CL 50 mg", "Agemoxi CL 250 mg"],
    "pharmacologic_class": "Aminopenicilina + inibidor de beta-lactamase",
    "species": ["dog", "cat"],
    "tags": ["antibiótico", "amoxicilina", "clavulanato", "tecidos moles", "oral"],
    "mechanism_of_action": "Beta-lactâmico bactericida tempo-dependente associado a inibidor de beta-lactamase.",
    "indications": ["Infecções sensíveis em cães e gatos quando há justificativa para cobertura de beta-lactamase.", "Abscessos, mordeduras, tecidos moles e infecções orais conforme avaliação veterinária."],
    "contraindications": ["Hipersensibilidade a beta-lactâmicos."],
    "cautions": ["Não usar como reflexo automático em UTI simples.", "Reavaliar se não houver resposta clínica no intervalo esperado."],
    "adverse_effects": ["Sinais gastrointestinais e hipersensibilidade."],
    "interactions": ["Evitar associação sem critério com bacteriostáticos quando o objetivo for ação bactericida tempo-dependente."],
    "routes": ["VO"],
    "doses": [{"id":"agemoxi-cl-both-125-q12","species":"both","indication":"Infecções bacterianas sensíveis","doseMin":12.5,"doseMax":25,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q12h","duration":"Conforme foco e resposta clínica.","notes":"Dose em mg/kg da associação. Bula: 50 mg para 4 kg ou 250 mg para 20 kg q12h.","calculatorEnabled":true}],
    "presentations": [{"id":"agemoxi-cl-50","label":"Agemoxi CL 50 mg","form":"comprimido","concentrationValue":50,"concentrationUnit":"mg","packInfo":"caixa com comprimidos","route":"VO","scoringInfo":"avaliar fracionamento conforme bula","channel":"veterinary"},{"id":"agemoxi-cl-250","label":"Agemoxi CL 250 mg","form":"comprimido","concentrationValue":250,"concentrationUnit":"mg","packInfo":"caixa com comprimidos","route":"VO","scoringInfo":"avaliar fracionamento conforme bula","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Produto comercial veterinário de amoxicilina + clavulanato. Use como opção com indicação clara para beta-lactamase, tecidos moles, abscessos ou foco compatível.</p>",
    "references": [{"citationText":"Agener União. Agemoxi CL.","sourceType":"site oficial","url":"https://agener.com.br/produtos/pequenos-animais/antimicrobianos-pt/agemoxi-cl/","notes":"Página oficial com posologia e apresentações."},{"citationText":"Agener União. Bula Agemoxi CL.","sourceType":"bula","url":"https://agener.com.br/wp-content/uploads/2020/01/4019264-Agemoxi-CL.pdf","notes":"Bula do produto."},{"citationText":"Plumb's Veterinary Drug Handbook, 10ª ed. Dose de amoxicilina + clavulanato.","sourceType":"dose Plumb/literatura","url":null,"notes":"Resumo informado na pesquisa textual anexada: 12,5–25 mg/kg da associação VO q8–12h."}],
    "official_site_url": "https://agener.com.br/produtos/pequenos-animais/antimicrobianos-pt/agemoxi-cl/",
    "leaflet_url": "https://agener.com.br/wp-content/uploads/2020/01/4019264-Agemoxi-CL.pdf",
    "image_url": "https://agener.com.br/wp-content/uploads/2020/01/agemoxi2.jpg"
  },
  {
    "slug": "clavaseptin-p",
    "title": "Clavaseptin P",
    "active_ingredient": "Amoxicilina + ácido clavulânico",
    "trade_names": ["Clavaseptin P 62,5 mg", "Clavaseptin P 250 mg", "Clavaseptin P 500 mg"],
    "pharmacologic_class": "Aminopenicilina + inibidor de beta-lactamase",
    "species": ["dog", "cat"],
    "tags": ["antibiótico", "amoxicilina", "clavulanato", "palatável", "stewardship"],
    "mechanism_of_action": "A amoxicilina bloqueia a síntese da parede celular bacteriana; o ácido clavulânico inibe beta-lactamases.",
    "indications": ["Infecções cutâneas, tecidos moles, feridas, abscessos e focos sensíveis quando amoxi-clav é apropriado."],
    "contraindications": ["Hipersensibilidade a penicilinas ou cefalosporinas."],
    "cautions": ["Usar cultura/antibiograma em infecção recorrente, profunda ou falha terapêutica.", "Evitar escalonamento sem foco bacteriano provável."],
    "adverse_effects": ["Vômito, diarreia, hiporexia e reações alérgicas."],
    "interactions": [],
    "routes": ["VO"],
    "doses": [{"id":"clavaseptin-both-125-q12","species":"both","indication":"Infecções bacterianas sensíveis","doseMin":12.5,"doseMax":25,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q12h","duration":"Conforme foco e reavaliação.","notes":"Dose em mg/kg da associação. Bula: 10 mg/kg de amoxicilina + 2,5 mg/kg de ácido clavulânico q12h.","calculatorEnabled":true}],
    "presentations": [{"id":"clavaseptin-625","label":"Clavaseptin P 62,5 mg","form":"comprimido palatável","concentrationValue":62.5,"concentrationUnit":"mg","packInfo":"10 ou 100 comprimidos","route":"VO","scoringInfo":"avaliar fracionamento conforme bula","channel":"veterinary"},{"id":"clavaseptin-250","label":"Clavaseptin P 250 mg","form":"comprimido palatável","concentrationValue":250,"concentrationUnit":"mg","packInfo":"10 ou 100 comprimidos","route":"VO","scoringInfo":"avaliar fracionamento conforme bula","channel":"veterinary"},{"id":"clavaseptin-500","label":"Clavaseptin P 500 mg","form":"comprimido palatável","concentrationValue":500,"concentrationUnit":"mg","packInfo":"10 ou 100 comprimidos","route":"VO","scoringInfo":"avaliar fracionamento conforme bula","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Boa opção quando a apresentação palatável ajuda adesão, mas o app mantém alerta de stewardship: amoxi-clav não deve ser escolhido só por comodidade.</p>",
    "references": [{"citationText":"Vetoquinol Brasil. Clavaseptin P.","sourceType":"site oficial","url":"https://www.vetoquinol.com.br/products/clavaseptinr-p","notes":"Página oficial do produto."},{"citationText":"Vetoquinol Brasil. Bula Clavaseptin P.","sourceType":"bula","url":"https://www.vetoquinol.com.br/sites/brcountry/files/clavaseptin_p_bula.pdf","notes":"Bula do produto."},{"citationText":"Plumb's Veterinary Drug Handbook, 10ª ed. Dose de amoxicilina + clavulanato.","sourceType":"dose Plumb/literatura","url":null,"notes":"Resumo informado na pesquisa textual anexada: 12,5–25 mg/kg da associação VO q8–12h."}],
    "official_site_url": "https://www.vetoquinol.com.br/products/clavaseptinr-p",
    "leaflet_url": "https://www.vetoquinol.com.br/sites/brcountry/files/clavaseptin_p_bula.pdf",
    "image_url": "https://www.vetoquinol.com.br/sites/brcountry/files/styles/product_detail__photo_popup/public/2025-02/clavaseptin2024_embalagem_mockup_todas_juntas.png?itok=RjtlT6kL"
  },
  {
    "slug": "doxifin-tabs",
    "title": "Doxifin Tabs",
    "active_ingredient": "Doxiciclina",
    "trade_names": ["Doxifin Tabs 50 mg", "Doxifin Tabs 100 mg", "Doxifin Tabs 200 mg"],
    "pharmacologic_class": "Tetraciclina bacteriostática",
    "species": ["dog", "cat"],
    "tags": ["doxiciclina", "rickettsioses", "erliquiose", "hemoplasmas", "gatos"],
    "mechanism_of_action": "Inibe síntese proteica bacteriana por ligação à subunidade ribossomal 30S; útil contra bactérias intracelulares e agentes transmitidos por vetores.",
    "indications": ["Erliquiose, anaplasmose e rickettsioses.", "Bordetella, Chlamydia felis, Mycoplasma spp. e outros focos sensíveis."],
    "contraindications": ["Hipersensibilidade a tetraciclinas."],
    "cautions": ["Em gatos, nunca administrar comprimido seco; oferecer água/alimento após.", "Cautela em gestação e animais jovens por classe tetraciclina."],
    "adverse_effects": ["Vômito, diarreia, náusea, esofagite/estenose esofágica em gatos se administrado seco."],
    "interactions": ["Cátions e antiácidos podem reduzir absorção oral."],
    "routes": ["VO"],
    "doses": [{"id":"doxifin-both-5-q12","species":"both","indication":"Infecções sensíveis à doxiciclina","doseMin":5,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q12h","duration":"Conforme foco; erliquiose frequentemente curso prolongado.","notes":"Alternativa de regime descrita em literatura clínica.","calculatorEnabled":true},{"id":"doxifin-both-10-q24","species":"both","indication":"Infecções sensíveis / regime SID","doseMin":10,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q24h","duration":"Bula: 7 dias; erliquiose pode requerer 28 dias conforme protocolo.","notes":"Em gatos, administrar com água/alimento após o comprimido.","calculatorEnabled":true}],
    "presentations": [{"id":"doxifin-50","label":"Doxifin Tabs 50 mg","form":"comprimido palatável","concentrationValue":50,"concentrationUnit":"mg","packInfo":"comprimidos palatáveis","route":"VO","scoringInfo":"avaliar fracionamento conforme bula","channel":"veterinary"},{"id":"doxifin-100","label":"Doxifin Tabs 100 mg","form":"comprimido palatável","concentrationValue":100,"concentrationUnit":"mg","packInfo":"comprimidos palatáveis","route":"VO","scoringInfo":"avaliar fracionamento conforme bula","channel":"veterinary"},{"id":"doxifin-200","label":"Doxifin Tabs 200 mg","form":"comprimido palatável","concentrationValue":200,"concentrationUnit":"mg","packInfo":"comprimidos palatáveis","route":"VO","scoringInfo":"avaliar fracionamento conforme bula","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Doxiciclina é opção central para hemoparasitoses e rickettsioses. Em felinos, a orientação de administração com água ou alimento não é detalhe: reduz risco de esofagite e estenose.</p>",
    "references": [{"citationText":"Ourofino Pet. Doxifin Tabs.","sourceType":"site oficial","url":"https://www.ourofinopet.com/produtos/medicamentos/doxifin-tabs/","notes":"Página oficial do produto."},{"citationText":"Bula Doxifin Tabs.","sourceType":"bula","url":"https://consultaremedios.com.br/doxifin-tabs-ourofino-para-caes-e-gatos/bula","notes":"Bula consultável publicamente."},{"citationText":"Plumb's Veterinary Drug Handbook, 10ª ed. Dose de doxiciclina.","sourceType":"dose Plumb/literatura","url":null,"notes":"Resumo informado na pesquisa textual anexada: 5 mg/kg q12h ou 10 mg/kg q24h em cães e gatos."}],
    "official_site_url": "https://www.ourofinopet.com/produtos/medicamentos/doxifin-tabs/",
    "leaflet_url": "https://consultaremedios.com.br/doxifin-tabs-ourofino-para-caes-e-gatos/bula",
    "image_url": "https://www.ourofinopet.com/media/uploads/produtos/apresentacao/2023/20231026084158.png"
  },
  {
    "slug": "doxitec",
    "title": "Doxitec",
    "active_ingredient": "Hiclato de doxiciclina",
    "trade_names": ["Doxitec 50 mg", "Doxitec 100 mg", "Doxitec 200 mg"],
    "pharmacologic_class": "Tetraciclina bacteriostática",
    "species": ["dog", "cat"],
    "tags": ["doxiciclina", "erliquiose", "respiratório", "gatos"],
    "mechanism_of_action": "Tetraciclina que inibe síntese proteica bacteriana por ação na subunidade ribossomal 30S.",
    "indications": ["Infecções respiratórias, gastrintestinais, geniturinárias, pele/anexos em cães e gatos.", "Erliquiose canina e agentes intracelulares sensíveis."],
    "contraindications": ["Hipersensibilidade a tetraciclinas."],
    "cautions": ["Em gatos, administrar com água/alimento após a dose.", "Evitar misturar regimes de cão e gato quando bula diferencia posologia."],
    "adverse_effects": ["Sinais gastrointestinais, esofagite em gatos, hipersensibilidade rara."],
    "interactions": ["Cátions, antiácidos e alimentos muito ricos em minerais podem reduzir absorção."],
    "routes": ["VO"],
    "doses": [{"id":"doxitec-dog-5-q12","species":"dog","indication":"Infecções gerais sensíveis","doseMin":5,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q12h","duration":"7 dias conforme bula; ajustar por foco.","notes":"Para erliquiose canina, bula cita 21 dias.","calculatorEnabled":true},{"id":"doxitec-cat-10-q24","species":"cat","indication":"Infecções gerais sensíveis","doseMin":10,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q24h","duration":"7 dias conforme bula; ajustar por foco.","notes":"Administrar com água/alimento após a dose.","calculatorEnabled":true}],
    "presentations": [{"id":"doxitec-50","label":"Doxitec 50 mg","form":"comprimido palatável","concentrationValue":50,"concentrationUnit":"mg","packInfo":"cartucho com blisters","route":"VO","scoringInfo":"sulcado; fracionar conforme bula","channel":"veterinary"},{"id":"doxitec-100","label":"Doxitec 100 mg","form":"comprimido palatável","concentrationValue":100,"concentrationUnit":"mg","packInfo":"cartucho com blisters","route":"VO","scoringInfo":"sulcado; fracionar conforme bula","channel":"veterinary"},{"id":"doxitec-200","label":"Doxitec 200 mg","form":"comprimido palatável","concentrationValue":200,"concentrationUnit":"mg","packInfo":"cartucho com blisters","route":"VO","scoringInfo":"sulcado; fracionar conforme bula","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Regimes foram separados por espécie porque a própria bula diferencia cão e gato. Isso evita linhas ambíguas e melhora a calculadora.</p>",
    "references": [{"citationText":"Syntec. Doxitec.","sourceType":"site oficial","url":"https://syntec.com.br/produtos/doxitec-doxiciclina-syntec","notes":"Página oficial com indicações, posologia e apresentação."},{"citationText":"Syntec. Bula Doxitec.","sourceType":"bula","url":"https://syntec.com.br/storage/produtos/bulas/bula-site-doxitec-v5pdf-630368764.pdf","notes":"Bula do produto."},{"citationText":"Plumb's Veterinary Drug Handbook, 10ª ed. Dose de doxiciclina.","sourceType":"dose Plumb/literatura","url":null,"notes":"Resumo informado na pesquisa textual anexada: 5 mg/kg q12h ou 10 mg/kg q24h em cães e gatos."}],
    "official_site_url": "https://syntec.com.br/produtos/doxitec-doxiciclina-syntec",
    "leaflet_url": "https://syntec.com.br/storage/produtos/bulas/bula-site-doxitec-v5pdf-630368764.pdf",
    "image_url": "https://syntec.com.br/storage/produtos/Doxitec-apresenta%C3%A7%C3%A3o-50100-e-200-15-14-55.webp"
  },
  {
    "slug": "trissulfin-sid",
    "title": "Trissulfin SID",
    "active_ingredient": "Sulfadimetoxina + ormetoprim",
    "trade_names": ["Trissulfin SID 400 mg", "Trissulfin SID 1600 mg"],
    "pharmacologic_class": "Sulfonamida potencializada",
    "species": ["dog", "cat"],
    "tags": ["sulfa", "ormetoprim", "isosporose", "stewardship"],
    "mechanism_of_action": "Bloqueio sequencial da síntese de folato bacteriano/protozoário pela associação de sulfonamida com ormetoprim.",
    "indications": ["Infecções bacterianas sensíveis conforme bula.", "Isosporose conforme bula."],
    "contraindications": ["Hipersensibilidade a sulfonamidas."],
    "cautions": ["Não cadastrar como sulfametoxazol + trimetoprim; é sulfadimetoxina + ormetoprim.", "Monitorar efeitos idiossincráticos de sulfas e hidratação."],
    "adverse_effects": ["KCS, hepatotoxicidade, trombocitopenia, anemia, poliartropatia, cristalúria, vômitos e hiporexia."],
    "interactions": ["Cautela com fármacos potencialmente mielotóxicos ou hepatotóxicos."],
    "routes": ["VO"],
    "doses": [{"id":"trissulfin-both-bacterial-loading","species":"both","indication":"Infecções bacterianas - primeiro dia","doseMin":160,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q24h","duration":"1º dia","notes":"Dose em mg/kg do produto conforme bula.","calculatorEnabled":true},{"id":"trissulfin-both-bacterial-maintenance","species":"both","indication":"Infecções bacterianas - manutenção","doseMin":80,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q24h","duration":"Mínimo 3 dias e continuar 2 dias após remissão; máximo 21 dias.","notes":"Dose em mg/kg do produto conforme bula.","calculatorEnabled":true},{"id":"trissulfin-both-isosporose","species":"both","indication":"Isosporose","doseMin":200,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q24h","duration":"Mínimo 5 dias; máximo 14 dias.","notes":"Dose em mg/kg do produto conforme bula.","calculatorEnabled":true}],
    "presentations": [{"id":"trissulfin-400","label":"Trissulfin SID 400 mg","form":"comprimido","concentrationValue":400,"concentrationUnit":"mg","packInfo":"comprimidos","route":"VO","scoringInfo":"avaliar fracionamento conforme bula","channel":"veterinary"},{"id":"trissulfin-1600","label":"Trissulfin SID 1600 mg","form":"comprimido","concentrationValue":1600,"concentrationUnit":"mg","packInfo":"comprimidos","route":"VO","scoringInfo":"avaliar fracionamento conforme bula","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Produto de sulfa potencializada distinto de TMP-SMX. A calculadora usa mg/kg do produto conforme bula, não conversão de dose de trimetoprim-sulfa humana.</p>",
    "references": [{"citationText":"Ourofino Pet. Trissulfin SID.","sourceType":"site oficial","url":"https://www.ourofinopet.com/produtos/medicamentos/trissulfin-sid/","notes":"Página oficial do produto."},{"citationText":"Bula Trissulfin SID.","sourceType":"bula","url":"https://uploads.consultaremedios.com.br/drug_leaflet/Bula-Trissulfin-SID-para-Caes-e-Gatos-Consulta-Remedios.pdf","notes":"Bula consultável publicamente."},{"citationText":"Literatura clínica de sulfonamidas potencializadas.","sourceType":"dose Plumb/literatura","url":null,"notes":"A pesquisa anexada alerta que doses de outras sulfas não devem ser convertidas automaticamente para este produto brasileiro."}],
    "official_site_url": "https://www.ourofinopet.com/produtos/medicamentos/trissulfin-sid/",
    "leaflet_url": "https://uploads.consultaremedios.com.br/drug_leaflet/Bula-Trissulfin-SID-para-Caes-e-Gatos-Consulta-Remedios.pdf",
    "image_url": "https://www.ourofinopet.com/media/uploads/produtos/apresentacao/2023/20231030115609.png"
  },
  {
    "slug": "sulfaprim-comprimidos",
    "title": "Sulfaprim Comprimidos",
    "active_ingredient": "Sulfametoxazol + trimetoprim",
    "trade_names": ["Sulfaprim Comprimidos"],
    "pharmacologic_class": "Sulfonamida + diaminopirimidina",
    "species": ["dog", "cat"],
    "tags": ["sulfametoxazol", "trimetoprim", "TMP-SMX", "UTI", "stewardship"],
    "mechanism_of_action": "Bloqueio sequencial da via do folato por sulfametoxazol e trimetoprim.",
    "indications": ["Infecções bacterianas sensíveis em trato urinário, respiratório, tecido mole ou próstata conforme cultura/contexto.", "Uso criterioso em cães e gatos, com atenção à tolerabilidade."],
    "contraindications": ["Hipersensibilidade a sulfonamidas.", "Cautela extrema em pacientes com histórico de reação idiossincrática a sulfas."],
    "cautions": ["Monitorar uso prolongado; orientar hidratação.", "Em gatos, observar anorexia, cristalúria, hematúria, leucopenia e anemia."],
    "adverse_effects": ["KCS, hepatotoxicidade, citopenias, cristalúria, poliartropatia, sinais gastrointestinais."],
    "interactions": ["Cautela com fármacos mielotóxicos, hepatotóxicos e anticoagulantes."],
    "routes": ["VO"],
    "doses": [{"id":"sulfaprim-both-15-q12","species":"both","indication":"Infecções bacterianas sensíveis","doseMin":15,"doseMax":30,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q12h","duration":"Conforme foco, cultura e resposta clínica.","notes":"Dose em mg/kg da associação. Conferir tabela da bula antes de automação em pacientes pequenos, pois o comprimido tem 600 mg totais.","calculatorEnabled":true}],
    "presentations": [{"id":"sulfaprim-600","label":"Sulfaprim Comprimidos 600 mg","form":"comprimido","concentrationValue":600,"concentrationUnit":"mg","packInfo":"500 mg sulfametoxazol + 100 mg trimetoprim","route":"VO","scoringInfo":"fracionamento deve respeitar bula e segurança do paciente","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Cadastro com trava editorial de cálculo: a apresentação de 600 mg pode gerar frações impraticáveis em animais pequenos. Conferir sempre foco, cultura e tolerabilidade antes de prescrever sulfas.</p>",
    "references": [{"citationText":"Bravet/Fourvet. Sulfaprim Comprimidos.","sourceType":"site oficial","url":"https://www.bravet.com.br/sulfaprim-comprimidos","notes":"Página oficial com composição."},{"citationText":"Bravet/Fourvet. Bula Sulfaprim Comprimidos.","sourceType":"bula","url":"https://www.bravet.com.br/files/product/leaflet/30/Sulfaprim%20Comprimidos%20-%20GG1%20%E2%80%93%20Fourvet.pdf","notes":"Bula do produto."},{"citationText":"Plumb's Veterinary Drug Handbook, 10ª ed. Dose de trimetoprim-sulfa.","sourceType":"dose Plumb/literatura","url":null,"notes":"Resumo informado na pesquisa textual anexada: 15 mg/kg da associação VO q12h; algumas fontes 15–30 mg/kg q12h."}],
    "official_site_url": "https://www.bravet.com.br/sulfaprim-comprimidos",
    "leaflet_url": "https://www.bravet.com.br/files/product/leaflet/30/Sulfaprim%20Comprimidos%20-%20GG1%20%E2%80%93%20Fourvet.pdf",
    "image_url": "https://www.bravet.com.br/files/product/photo/30/SULFAPRIM_COMPRIMIDO_660_.png"
  },
  {
    "slug": "cefex",
    "title": "Cefex",
    "active_ingredient": "Cefalexina",
    "trade_names": ["Cefex 500 mg", "Cefex 1 g", "Cefex suspensão 50 mg/mL"],
    "pharmacologic_class": "Cefalosporina de 1ª geração",
    "species": ["dog", "cat"],
    "tags": ["cefalexina", "pele", "UTI", "cefalosporina", "enterococcus-resistente"],
    "mechanism_of_action": "Cefalosporina beta-lactâmica bactericida que inibe síntese de parede bacteriana.",
    "indications": ["Piodermite e infecções cutâneas por Staphylococcus sensível.", "Algumas infecções urinárias, respiratórias, ósseas, digestivas e geniturinárias por bactérias sensíveis."],
    "contraindications": ["Hipersensibilidade a cefalosporinas ou penicilinas."],
    "cautions": ["Enterococcus é resistente; não usar quando cultura indicar Enterococcus.", "Cultura em piodermite recorrente, profunda ou falha terapêutica."],
    "adverse_effects": ["Vômito, diarreia, hiporexia, hipersensibilidade."],
    "interactions": [],
    "routes": ["VO"],
    "doses": [{"id":"cefex-both-10-30-q8-12","species":"both","indication":"Infecções sensíveis à cefalexina","doseMin":10,"doseMax":30,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q8-12h","duration":"Conforme foco; piodermite pode exigir curso mais longo.","notes":"Literatura clínica; para UTI, faixas de 12–25 mg/kg q12h são citadas.","calculatorEnabled":true}],
    "presentations": [{"id":"cefex-500","label":"Cefex 500 mg","form":"comprimido","concentrationValue":500,"concentrationUnit":"mg","packInfo":"comprimidos","route":"VO","scoringInfo":"avaliar fracionamento conforme bula","channel":"veterinary"},{"id":"cefex-1000","label":"Cefex 1 g","form":"comprimido","concentrationValue":1000,"concentrationUnit":"mg","packInfo":"comprimidos","route":"VO","scoringInfo":"avaliar fracionamento conforme bula","channel":"veterinary"},{"id":"cefex-susp-50","label":"Cefex suspensão 50 mg/mL","form":"suspensão oral","concentrationValue":50,"concentrationUnit":"mg/mL","packInfo":"suspensão 50 mg/mL","route":"VO","scoringInfo":"calcular em mL após reconstituição correta","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Cefalexina continua útil para pele e alguns focos urinários sensíveis, mas falha se o alvo for Enterococcus. Em recorrência, cultura muda conduta.</p>",
    "references": [{"citationText":"CEPAV. Cefex.","sourceType":"site oficial","url":"https://cepav.com.br/produtos/cefex/","notes":"Página oficial do produto."},{"citationText":"CEPAV. Bula Cefex.","sourceType":"bula","url":"https://cepav.com.br/wp-content/uploads/2018/03/CEFEX-.pdf","notes":"Bula do produto."},{"citationText":"Plumb's Veterinary Drug Handbook, 10ª ed. Dose de cefalexina.","sourceType":"dose Plumb/literatura","url":null,"notes":"Resumo informado na pesquisa textual anexada: 10–30 mg/kg VO q8–12h; UTI 12–25 mg/kg q12h."}],
    "official_site_url": "https://cepav.com.br/produtos/cefex/",
    "leaflet_url": "https://cepav.com.br/wp-content/uploads/2018/03/CEFEX-.pdf",
    "image_url": "https://cepav.com.br/wp-content/uploads/2021/02/Cefex-e1615838923677.png"
  },
  {
    "slug": "ceftrat",
    "title": "Ceftrat",
    "active_ingredient": "Cefpodoxima proxetil",
    "trade_names": ["Ceftrat 100 mg", "Ceftrat 200 mg"],
    "pharmacologic_class": "Cefalosporina oral de 3ª geração",
    "species": ["dog"],
    "tags": ["cefpodoxima", "cães", "cefalosporina", "segunda linha", "cultura"],
    "mechanism_of_action": "Cefalosporina beta-lactâmica bactericida com ação por inibição de síntese da parede bacteriana.",
    "indications": ["Infecções causadas por cepas sensíveis em cães, especialmente pele/tecidos moles quando há justificativa.", "Usar de forma criteriosa e preferencialmente guiada por cultura em recorrência ou falha."],
    "contraindications": ["Hipersensibilidade a cefalosporinas ou beta-lactâmicos."],
    "cautions": ["Cadastrar como cães apenas.", "Cefalosporina de geração mais alta; evitar uso empírico sem justificativa."],
    "adverse_effects": ["Sinais gastrointestinais e hipersensibilidade."],
    "interactions": [],
    "routes": ["VO"],
    "doses": [{"id":"ceftrat-dog-5-10-q24","species":"dog","indication":"Infecções sensíveis em cães","doseMin":5,"doseMax":10,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q24h","duration":"Conforme foco e resposta clínica.","notes":"Dose de bula e literatura para cães. Não cadastrar automaticamente para gatos.","calculatorEnabled":true}],
    "presentations": [{"id":"ceftrat-100","label":"Ceftrat 100 mg","form":"comprimido palatável bissulcado","concentrationValue":100,"concentrationUnit":"mg","packInfo":"cartucho com comprimidos","route":"VO","scoringInfo":"bissulcado; fracionar conforme bula","channel":"veterinary"},{"id":"ceftrat-200","label":"Ceftrat 200 mg","form":"comprimido palatável bissulcado","concentrationValue":200,"concentrationUnit":"mg","packInfo":"cartucho com comprimidos","route":"VO","scoringInfo":"bissulcado; fracionar conforme bula","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Cefpodoxima deve ser tratada como opção de escalonamento. A ficha restringe a cães porque a fonte oficial do produto está direcionada a essa espécie.</p>",
    "references": [{"citationText":"Agener União. Ceftrat 100 mg.","sourceType":"site oficial","url":"https://agener.com.br/produtos/pequenos-animais/antimicrobianos-pt/ceftrat-100mg/","notes":"Página oficial com posologia."},{"citationText":"União Química. Bula Ceftrat.","sourceType":"bula","url":"https://www.uniaoquimica.com.br/wp-content/uploads/2023/01/4028415-BU-CEFTRAT-COM.pdf","notes":"Bula do produto."},{"citationText":"Plumb's Veterinary Drug Handbook, 10ª ed. Dose de cefpodoxima.","sourceType":"dose Plumb/literatura","url":null,"notes":"Resumo informado na pesquisa textual anexada: cães 5–10 mg/kg VO q24h."}],
    "official_site_url": "https://agener.com.br/produtos/pequenos-animais/antimicrobianos-pt/ceftrat-100mg/",
    "leaflet_url": "https://www.uniaoquimica.com.br/wp-content/uploads/2023/01/4028415-BU-CEFTRAT-COM.pdf",
    "image_url": "https://agener.com.br/wp-content/uploads/2023/01/8463B_AGE22_Pack-3D_Ceftrat-100mg.png"
  },
  {
    "slug": "convenia",
    "title": "Convenia",
    "active_ingredient": "Cefovecina sódica",
    "trade_names": ["Convenia"],
    "pharmacologic_class": "Cefalosporina de 3ª geração de longa ação",
    "species": ["dog", "cat"],
    "tags": ["cefovecina", "injetável", "longa ação", "adesão", "stewardship"],
    "mechanism_of_action": "Cefalosporina beta-lactâmica de longa ação que inibe síntese de parede bacteriana.",
    "indications": ["Infecções de pele e trato urinário em cães e gatos quando a indicação é compatível.", "Situações em que adesão oral é inviável e o uso de longa ação é justificado."],
    "contraindications": ["Hipersensibilidade a cefalosporinas ou penicilinas."],
    "cautions": ["Antibiótico de longa ação; após aplicar, não é possível retirar o fármaco.", "Evitar por conveniência em infecção leve sem justificativa/cultura."],
    "adverse_effects": ["Vômito, diarreia, letargia, reações no local de aplicação e hipersensibilidade."],
    "interactions": [],
    "routes": ["SC"],
    "doses": [{"id":"convenia-both-8-sc","species":"both","indication":"Infecções compatíveis com cefovecina","doseMin":8,"doseUnit":"mg","perWeightUnit":"kg","route":"SC","frequency":"dose única; repetir apenas se indicado","duration":"Longa ação; reavaliação conforme bula/foco.","notes":"Equivale a 1 mL/10 kg após reconstituição a 80 mg/mL.","calculatorEnabled":true}],
    "presentations": [{"id":"convenia-80","label":"Convenia 80 mg/mL","form":"solução injetável após reconstituição","concentrationValue":80,"concentrationUnit":"mg/mL","packInfo":"frascos 4 mL ou 10 mL","route":"SC","scoringInfo":"uso médico-veterinário; calcular em mL","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Convenia precisa de justificativa clínica explícita. É útil quando VO é inviável, mas stewardship é crítico porque a exposição antimicrobiana persiste por tempo prolongado.</p>",
    "references": [{"citationText":"Zoetis Brasil. Convenia.","sourceType":"site oficial","url":"https://www.zoetis.com.br/especies/animais-de-companhia/convenia.aspx","notes":"Página oficial com indicações e posologia."},{"citationText":"Zoetis Brasil. Bula Convenia.","sourceType":"bula","url":"https://www.zoetis.com.br/_locale-assets/arquivos/animais-de-companhia/bula-convenia.pdf","notes":"Bula do produto."},{"citationText":"Plumb's Veterinary Drug Handbook, 10ª ed. Dose de cefovecina.","sourceType":"dose Plumb/literatura","url":null,"notes":"Resumo informado na pesquisa textual anexada: cães/gatos 8 mg/kg SC."}],
    "official_site_url": "https://www.zoetis.com.br/especies/animais-de-companhia/convenia.aspx",
    "leaflet_url": "https://www.zoetis.com.br/_locale-assets/arquivos/animais-de-companhia/bula-convenia.pdf",
    "image_url": "https://www.zoetis.com.br/_locale-assets/img/animais-de-companhia/fotos-produtos/convenia-zoetis.jpg"
  },
  {
    "slug": "baytril-flavour",
    "title": "Baytril Flavour",
    "active_ingredient": "Enrofloxacino",
    "trade_names": ["Baytril Flavour 15 mg", "Baytril Flavour 50 mg", "Baytril Flavour 150 mg"],
    "pharmacologic_class": "Fluoroquinolona",
    "species": ["dog", "cat"],
    "tags": ["enrofloxacino", "fluoroquinolona", "gram-negativos", "gatos", "segunda linha"],
    "mechanism_of_action": "Fluoroquinolona bactericida concentração-dependente que inibe DNA girase e topoisomerase IV.",
    "indications": ["Infecções por Gram-negativos/resistentes, prostatite, pielonefrite ou ITU complicada quando cultura/contexto justificam.", "Não usar como primeira escolha automática em infecções simples."],
    "contraindications": ["Hipersensibilidade a fluoroquinolonas.", "Evitar em animais em crescimento quando risco articular for relevante."],
    "cautions": ["Em gatos, não exceder 5 mg/kg/dia por risco de retinopatia/cegueira.", "Cautela em pacientes com convulsões ou distúrbios neurológicos."],
    "adverse_effects": ["Sinais gastrointestinais, excitação/convulsões em predispostos, artropatia em crescimento, retinopatia em gatos com doses altas."],
    "interactions": ["Cátions e antiácidos reduzem absorção; cautela com teofilina e fármacos pró-convulsivantes."],
    "routes": ["VO"],
    "doses": [{"id":"baytril-dog-5-20-q24","species":"dog","indication":"Infecções sensíveis justificadas em cães","doseMin":5,"doseMax":20,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q24h","duration":"Conforme foco, cultura e resposta clínica.","notes":"Faixa de literatura; usar dose e duração com stewardship.","calculatorEnabled":true},{"id":"baytril-cat-5-q24","species":"cat","indication":"Infecções sensíveis justificadas em gatos","doseMin":5,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q24h","duration":"Conforme foco e resposta clínica.","notes":"Não exceder 5 mg/kg/dia em gatos.","calculatorEnabled":true}],
    "presentations": [{"id":"baytril-15","label":"Baytril Flavour 15 mg","form":"comprimido palatável","concentrationValue":15,"concentrationUnit":"mg","packInfo":"comprimidos","route":"VO","scoringInfo":"avaliar fracionamento conforme bula","channel":"veterinary"},{"id":"baytril-50","label":"Baytril Flavour 50 mg","form":"comprimido palatável","concentrationValue":50,"concentrationUnit":"mg","packInfo":"comprimidos","route":"VO","scoringInfo":"avaliar fracionamento conforme bula","channel":"veterinary"},{"id":"baytril-150","label":"Baytril Flavour 150 mg","form":"comprimido palatável","concentrationValue":150,"concentrationUnit":"mg","packInfo":"comprimidos","route":"VO","scoringInfo":"avaliar fracionamento conforme bula","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Fluoroquinolona deve ser vista como segunda linha/reservada. Em felinos, o limite de dose é regra de segurança, não sugestão.</p>",
    "references": [{"citationText":"Elanco. Baytril.","sourceType":"site oficial","url":"https://vet.elanco.com/br/produtos/baytril","notes":"Página oficial do produto."},{"citationText":"Bula Baytril Flavour.","sourceType":"bula","url":"https://products-info-public.s3-sa-east-1.amazonaws.com/bulas/bayer/81347298_V3_Leaflet_BAYTRIL%2BFLAVOUR%2B15%2BMG_Aprovado_bula-SAC.pdf","notes":"Bula do produto."},{"citationText":"Plumb's Veterinary Drug Handbook, 10ª ed. Dose de enrofloxacina.","sourceType":"dose Plumb/literatura","url":null,"notes":"Resumo informado na pesquisa textual anexada: cães 5–20 mg/kg q24h; gatos 5 mg/kg q24h, não exceder."}],
    "official_site_url": "https://vet.elanco.com/br/produtos/baytril",
    "leaflet_url": "https://products-info-public.s3-sa-east-1.amazonaws.com/bulas/bayer/81347298_V3_Leaflet_BAYTRIL%2BFLAVOUR%2B15%2BMG_Aprovado_bula-SAC.pdf",
    "image_url": "https://assets.elanco.com/0cec44ed-3eaa-0009-2029-666567e7e4de/a52962b3-7964-4ce3-82e2-bf89774ba3f5/Packshot_Baytril.png?auto=format&q=75&w=828"
  },
  {
    "slug": "enrotrat-tabs",
    "title": "Enrotrat Tabs",
    "active_ingredient": "Enrofloxacina",
    "trade_names": ["Enrotrat Tabs 25 mg", "Enrotrat Tabs 100 mg", "Enrotrat Tabs 200 mg"],
    "pharmacologic_class": "Fluoroquinolona",
    "species": ["dog", "cat"],
    "tags": ["enrofloxacina", "fluoroquinolona", "stewardship", "gatos"],
    "mechanism_of_action": "Fluoroquinolona bactericida concentração-dependente com ação sobre DNA girase/topoisomerase.",
    "indications": ["Infecções sensíveis em cães e gatos quando a fluoroquinolona é justificável.", "Reservar para cenários com suspeita de resistência ou cultura compatível."],
    "contraindications": ["Hipersensibilidade a fluoroquinolonas.", "Evitar em crescimento quando risco articular for relevante."],
    "cautions": ["Gatos: manter limite de 5 mg/kg/dia.", "Cautela em animais com histórico neurológico."],
    "adverse_effects": ["Gastrointestinais, neurológicos em predispostos, artropatia em jovens, retinopatia felina em doses altas."],
    "interactions": ["Cátions/antiácidos reduzem absorção."],
    "routes": ["VO"],
    "doses": [{"id":"enrotrat-dog-5-20-q24","species":"dog","indication":"Infecções sensíveis justificadas em cães","doseMin":5,"doseMax":20,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q24h","duration":"Bula 3–5 dias; ajustar por foco/cultura.","notes":"Usar com stewardship.","calculatorEnabled":true},{"id":"enrotrat-cat-5-q24","species":"cat","indication":"Infecções sensíveis justificadas em gatos","doseMin":5,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q24h","duration":"Conforme foco; não exceder dose diária.","notes":"Não exceder 5 mg/kg/dia em gatos.","calculatorEnabled":true}],
    "presentations": [{"id":"enrotrat-25","label":"Enrotrat Tabs 25 mg","form":"comprimido","concentrationValue":25,"concentrationUnit":"mg","packInfo":"comprimidos","route":"VO","scoringInfo":"avaliar fracionamento conforme bula","channel":"veterinary"},{"id":"enrotrat-100","label":"Enrotrat Tabs 100 mg","form":"comprimido","concentrationValue":100,"concentrationUnit":"mg","packInfo":"comprimidos","route":"VO","scoringInfo":"avaliar fracionamento conforme bula","channel":"veterinary"},{"id":"enrotrat-200","label":"Enrotrat Tabs 200 mg","form":"comprimido","concentrationValue":200,"concentrationUnit":"mg","packInfo":"comprimidos","route":"VO","scoringInfo":"avaliar fracionamento conforme bula","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Mesmo raciocínio de Baytril: fluoroquinolona é fármaco de reserva relativa. A ficha separa cão e gato para impedir extrapolação insegura de dose felina.</p>",
    "references": [{"citationText":"Ourofino Pet. Enrotrat Tabs.","sourceType":"site oficial","url":"https://www.ourofinopet.com/produtos/medicamentos/enrotrat-tabs/","notes":"Página oficial do produto."},{"citationText":"Bula Enrotrat Tabs.","sourceType":"bula","url":"https://uploads.consultaremedios.com.br/drug_leaflet/Bula-Enrotrat-Tabs-Uso-Veterinario-Paciente-Consulta-Remedios.pdf","notes":"Bula consultável publicamente."},{"citationText":"Plumb's Veterinary Drug Handbook, 10ª ed. Dose de enrofloxacina.","sourceType":"dose Plumb/literatura","url":null,"notes":"Resumo informado na pesquisa textual anexada: cães 5–20 mg/kg q24h; gatos 5 mg/kg q24h."}],
    "official_site_url": "https://www.ourofinopet.com/produtos/medicamentos/enrotrat-tabs/",
    "leaflet_url": "https://uploads.consultaremedios.com.br/drug_leaflet/Bula-Enrotrat-Tabs-Uso-Veterinario-Paciente-Consulta-Remedios.pdf",
    "image_url": "https://www.ourofinopet.com/media/uploads/produtos/apresentacao/2023/20231026085157_CtBZrJ2.png"
  },
  {
    "slug": "marbocyl-p",
    "title": "Marbocyl P",
    "active_ingredient": "Marbofloxacina",
    "trade_names": ["Marbocyl P 5 mg", "Marbocyl P 20 mg", "Marbocyl P 80 mg"],
    "pharmacologic_class": "Fluoroquinolona",
    "species": ["dog", "cat"],
    "tags": ["marbofloxacina", "fluoroquinolona", "pele", "ITU", "respiratório"],
    "mechanism_of_action": "Fluoroquinolona bactericida com ação concentração-dependente por inibição de DNA girase/topoisomerase.",
    "indications": ["Cães: piodermite superficial/profunda, infecções urinárias e respiratórias.", "Gatos: pele/subcutâneo e trato respiratório superior conforme bula."],
    "contraindications": ["Hipersensibilidade a fluoroquinolonas."],
    "cautions": ["Uso reservado; considerar cultura em recorrência, falha ou suspeita de resistência.", "Cautela em animais jovens e pacientes com histórico neurológico."],
    "adverse_effects": ["Sinais gastrointestinais e neurológicos em predispostos; cautela de classe em crescimento."],
    "interactions": ["Cátions e antiácidos reduzem absorção."],
    "routes": ["VO"],
    "doses": [{"id":"marbocyl-both-2-q24","species":"both","indication":"Infecções sensíveis conforme bula","doseMin":2,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q24h","duration":"Conforme foco; bula cita até 40 dias em indicações específicas.","notes":"Bula: 2 mg/kg/dia; literatura cita 2–5,5 mg/kg conforme foco.","calculatorEnabled":true},{"id":"marbocyl-both-2-55-q24-lit","species":"both","indication":"Faixa de literatura para foco selecionado","doseMin":2,"doseMax":5.5,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q24h","duration":"Individualizar por cultura/foco.","notes":"Usar dose alta apenas com justificativa clínica e segurança.","calculatorEnabled":true}],
    "presentations": [{"id":"marbocyl-5","label":"Marbocyl P 5 mg","form":"comprimido palatável sulcado","concentrationValue":5,"concentrationUnit":"mg","packInfo":"blister com comprimidos","route":"VO","scoringInfo":"sulcado; 1 cp/2,5 kg na posologia de bula","channel":"veterinary"},{"id":"marbocyl-20","label":"Marbocyl P 20 mg","form":"comprimido palatável sulcado","concentrationValue":20,"concentrationUnit":"mg","packInfo":"blister com comprimidos","route":"VO","scoringInfo":"sulcado; 1 cp/10 kg na posologia de bula","channel":"veterinary"},{"id":"marbocyl-80","label":"Marbocyl P 80 mg","form":"comprimido palatável sulcado","concentrationValue":80,"concentrationUnit":"mg","packInfo":"blister com comprimidos","route":"VO","scoringInfo":"sulcado; 1 cp/40 kg na posologia de bula","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Marbofloxacina pode ter nichos úteis, mas segue sendo fluoroquinolona. A página mantém a lógica de segunda linha e cultura quando há recorrência ou falha.</p>",
    "references": [{"citationText":"Vetoquinol Brasil. Marbocyl P.","sourceType":"site oficial","url":"https://www.vetoquinol.com.br/products/marbocylr-p","notes":"Página oficial com composição, indicação e dose."},{"citationText":"Bula Marbocyl P.","sourceType":"bula","url":"https://consultaremedios.com.br/marbocyl-p-para-caes-e-gatos-vetoquinol/bula","notes":"Bula consultável publicamente."},{"citationText":"Plumb's Veterinary Drug Handbook, 10ª ed. Dose de marbofloxacina.","sourceType":"dose Plumb/literatura","url":null,"notes":"Resumo informado na pesquisa textual anexada: 2–5,5 mg/kg VO q24h."}],
    "official_site_url": "https://www.vetoquinol.com.br/products/marbocylr-p",
    "leaflet_url": "https://consultaremedios.com.br/marbocyl-p-para-caes-e-gatos-vetoquinol/bula",
    "image_url": "https://www.vetoquinol.com.br/sites/brcountry/files/styles/product_detail__photo_popup/public/11.02.png?itok=vqWTTIdj"
  },
  {
    "slug": "marbopet",
    "title": "Marbopet",
    "active_ingredient": "Marbofloxacina",
    "trade_names": ["Marbopet 27,5 mg", "Marbopet 82,5 mg"],
    "pharmacologic_class": "Fluoroquinolona",
    "species": ["dog"],
    "tags": ["marbofloxacina", "cães", "fluoroquinolona", "segunda linha"],
    "mechanism_of_action": "Fluoroquinolona bactericida com ação concentração-dependente por inibição de DNA girase/topoisomerase.",
    "indications": ["Infecções de pele/anexos, urinárias, gastrointestinais e respiratórias em cães por bactérias sensíveis."],
    "contraindications": ["Hipersensibilidade a fluoroquinolonas."],
    "cautions": ["Cadastrar como cães apenas.", "Uso reservado; cultura em recorrência, falha ou suspeita de resistência."],
    "adverse_effects": ["Sinais gastrointestinais, neurológicos em predispostos e cautelas de classe em crescimento."],
    "interactions": ["Cátions e antiácidos podem reduzir absorção."],
    "routes": ["VO"],
    "doses": [{"id":"marbopet-dog-275-q24","species":"dog","indication":"Infecções sensíveis em cães","doseMin":2.75,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q24h","duration":"Conforme foco e bula.","notes":"Bula: 27,5 mg = 1 comprimido/10 kg; 82,5 mg = 1 comprimido/30 kg.","calculatorEnabled":true}],
    "presentations": [{"id":"marbopet-275","label":"Marbopet 27,5 mg","form":"comprimido","concentrationValue":27.5,"concentrationUnit":"mg","packInfo":"comprimidos","route":"VO","scoringInfo":"1 cp/10 kg na posologia de bula","channel":"veterinary"},{"id":"marbopet-825","label":"Marbopet 82,5 mg","form":"comprimido","concentrationValue":82.5,"concentrationUnit":"mg","packInfo":"comprimidos","route":"VO","scoringInfo":"1 cp/30 kg na posologia de bula","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Produto de marbofloxacina direcionado a cães. Não extrapolar automaticamente para gatos.</p>",
    "references": [{"citationText":"Ceva Brasil. Produtos para animais de companhia - Marbopet.","sourceType":"site oficial","url":"https://www.ceva.com.br/solucoes-e-inovacoes/animais-de-companhia/nossos-produtos-para-animais-de-companhia","notes":"Página oficial de produtos Ceva."},{"citationText":"Ceva Brasil. Bula Marbopet.","sourceType":"bula","url":"https://www.ceva.com.br/content/download/2852/file/Bula%20-%20Marbopet.pdf?version=1","notes":"Bula do produto."},{"citationText":"Plumb's Veterinary Drug Handbook, 10ª ed. Dose de marbofloxacina.","sourceType":"dose Plumb/literatura","url":null,"notes":"Resumo informado na pesquisa textual anexada: 2–5,5 mg/kg VO q24h; bula Marbopet usa 2,75 mg/kg."}],
    "official_site_url": "https://www.ceva.com.br/solucoes-e-inovacoes/animais-de-companhia/nossos-produtos-para-animais-de-companhia",
    "leaflet_url": "https://www.ceva.com.br/content/download/2852/file/Bula%20-%20Marbopet.pdf?version=1",
    "image_url": "https://www.ceva.com.br/var/site/storage/images/_aliases/large/7/7/0/7/57077-1-por-BR/e22ef171118e-Captura-de-tela-2026-04-13-172254.webp"
  }
]$records$::jsonb) as r(
    slug text,
    title text,
    active_ingredient text,
    trade_names jsonb,
    pharmacologic_class text,
    species jsonb,
    tags jsonb,
    mechanism_of_action text,
    indications jsonb,
    contraindications jsonb,
    cautions jsonb,
    adverse_effects jsonb,
    interactions jsonb,
    routes jsonb,
    doses jsonb,
    presentations jsonb,
    clinical_notes_rich_text text,
    "references" jsonb,
    official_site_url text,
    leaflet_url text,
    image_url text
  )
)
insert into public.consulta_vet_medications (
  category_id,
  slug,
  title,
  active_ingredient,
  trade_names,
  pharmacologic_class,
  species,
  tags,
  mechanism_of_action,
  indications,
  contraindications,
  cautions,
  adverse_effects,
  interactions,
  routes,
  doses,
  presentations,
  clinical_notes_rich_text,
  admin_notes_text,
  "references",
  official_site_url,
  leaflet_url,
  image_url,
  is_published
)
select
  category.id,
  records.slug,
  records.title,
  records.active_ingredient,
  array(select jsonb_array_elements_text(records.trade_names)),
  records.pharmacologic_class,
  array(select jsonb_array_elements_text(records.species)),
  array(select jsonb_array_elements_text(records.tags)),
  records.mechanism_of_action,
  array(select jsonb_array_elements_text(records.indications)),
  array(select jsonb_array_elements_text(records.contraindications)),
  array(select jsonb_array_elements_text(records.cautions)),
  array(select jsonb_array_elements_text(records.adverse_effects)),
  array(select jsonb_array_elements_text(records.interactions)),
  array(select jsonb_array_elements_text(records.routes)),
  records.doses,
  records.presentations,
  records.clinical_notes_rich_text,
  'Seed editorial de antibióticos comerciais BR importado da pesquisa textual de 24/06/2026. Produtos incompletos do documento não foram importados automaticamente.',
  records."references",
  records.official_site_url,
  records.leaflet_url,
  records.image_url,
  true
from records
cross join category
on conflict (slug) do update
set
  category_id = excluded.category_id,
  title = excluded.title,
  active_ingredient = excluded.active_ingredient,
  trade_names = excluded.trade_names,
  pharmacologic_class = excluded.pharmacologic_class,
  species = excluded.species,
  tags = excluded.tags,
  mechanism_of_action = excluded.mechanism_of_action,
  indications = excluded.indications,
  contraindications = excluded.contraindications,
  cautions = excluded.cautions,
  adverse_effects = excluded.adverse_effects,
  interactions = excluded.interactions,
  routes = excluded.routes,
  doses = excluded.doses,
  presentations = excluded.presentations,
  clinical_notes_rich_text = excluded.clinical_notes_rich_text,
  admin_notes_text = excluded.admin_notes_text,
  "references" = excluded."references",
  official_site_url = excluded.official_site_url,
  leaflet_url = excluded.leaflet_url,
  image_url = excluded.image_url,
  is_published = true,
  updated_at = now();
