-- Coleção renal e do trato urinário do ConsultaVet.
-- O consenso ACVIM de hipertensão sistêmica já existe na coleção endócrina
-- e é reutilizado como referência interdisciplinar, sem duplicação.

insert into public.consensus_documents (
  slug,
  title,
  description,
  organization,
  year,
  category,
  species,
  file_path,
  file_url,
  is_published,
  related_disease_slugs,
  related_medication_slugs
)
values
  (
    'iris-drc-2023',
    'Doença renal crônica em cães e gatos',
    'Guideline IRIS 2026 para estadiamento e tratamento da doença renal crônica em cães e gatos, com creatinina/SDMA, UPC, pressão arterial e manejo por estágio.',
    'IRIS',
    2026,
    'nefrologia-urologia',
    'both',
    'external/iris-drc-2026',
    'https://www.iris-kidney.com/iris-guidelines-1',
    true,
    '["doenca-renal-cronica-caes-gatos"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'iris-lra-2026',
    'Graduação da lesão renal aguda em cães e gatos',
    'Guideline IRIS 2026 para reconhecer e graduar lesão renal aguda em cães e gatos por creatinina, evolução clínica e produção urinária.',
    'IRIS',
    2026,
    'nefrologia-urologia',
    'both',
    'external/iris-lra-2026',
    'https://www.iris-kidney.com/iris-guidelines-1',
    true,
    '[]'::jsonb,
    '[]'::jsonb
  ),
  (
    'icatcare-dtuif-felina-2025',
    'Doenças do trato urinário inferior em gatos',
    'Consenso iCatCare 2025 para abordagem por causa, cistite idiopática felina, urolitíase, ITU, obstrução uretral e manejo ambiental.',
    'iCatCare',
    2025,
    'nefrologia-urologia',
    'cat',
    'external/icatcare-dtuif-felina-2025',
    'https://journals.sagepub.com/doi/10.1177/1098612X241309176',
    true,
    '["doencas-trato-urinario-inferior-felino-dtuif"]'::jsonb,
    '["amoxicilina-clavulanato","sulfametoxazol-trimetoprima","pregabalina","maropitant"]'::jsonb
  ),
  (
    'iscaid-itu-caes-gatos-2019',
    'Infecções bacterianas do trato urinário em cães e gatos',
    'Guideline ISCAID 2019 para diagnóstico e uso responsável de antimicrobianos na cistite bacteriana, pielonefrite e bacteriúria subclínica.',
    'ISCAID',
    2019,
    'nefrologia-urologia',
    'both',
    'external/iscaid-itu-caes-gatos-2019',
    'https://www.iscaid.org/guidelines',
    true,
    '[]'::jsonb,
    '["amoxicilina-clavulanato","sulfametoxazol-trimetoprima"]'::jsonb
  ),
  (
    'acvim-urolitiase-caes-gatos-2016',
    'Tratamento e prevenção de urólitos em cães e gatos',
    'Consenso ACVIM 2016 para tratamento minimamente invasivo, dissolução e prevenção de urólitos em cães e gatos.',
    'ACVIM',
    2016,
    'nefrologia-urologia',
    'both',
    'external/acvim-urolitiase-caes-gatos-2016',
    'https://academic.oup.com/jvim/article/30/5/1564/8417232',
    true,
    '[]'::jsonb,
    '[]'::jsonb
  ),
  (
    'acvim-incontinencia-urinaria-canina-2024',
    'Incontinência urinária em cães',
    'Consenso ACVIM 2024 para classificação, investigação e tratamento da incontinência urinária em cães.',
    'ACVIM',
    2024,
    'nefrologia-urologia',
    'dog',
    'external/acvim-incontinencia-urinaria-canina-2024',
    'https://academic.oup.com/jvim/article/38/2/878/8448883',
    true,
    '[]'::jsonb,
    '[]'::jsonb
  ),
  (
    'iris-doenca-glomerular-canina-2013',
    'Doença glomerular em cães',
    'Série de consenso IRIS/ACVIM 2013 para reconhecimento, diagnóstico, tratamento e monitorização da doença glomerular canina.',
    'IRIS / ACVIM',
    2013,
    'nefrologia-urologia',
    'dog',
    'external/iris-doenca-glomerular-canina-2013',
    'https://academic.oup.com/jvim/issue/27/Supplement_S1',
    true,
    '["doenca-renal-cronica-caes-gatos"]'::jsonb,
    '["benazepril"]'::jsonb
  ),
  (
    'isfm-drc-felina-2016',
    'Diagnóstico e manejo da doença renal crônica felina',
    'Diretriz clínica ISFM 2016 para diagnóstico, estadiamento e manejo prático da doença renal crônica em gatos.',
    'ISFM',
    2016,
    'nefrologia-urologia',
    'cat',
    'external/isfm-drc-felina-2016',
    'https://pubmed.ncbi.nlm.nih.gov/26936494/',
    true,
    '["doenca-renal-cronica-caes-gatos"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'terminologia-infeccoes-urinarias-2026',
    'Terminologia das infecções do trato urinário em cães e gatos',
    'Consenso internacional de 2026 que padroniza 29 termos usados nas infecções urinárias de cães e gatos.',
    'JSAP / painel internacional',
    2026,
    'nefrologia-urologia',
    'both',
    'external/terminologia-infeccoes-urinarias-2026',
    'https://onlinelibrary.wiley.com/doi/10.1111/jsap.70127',
    true,
    '[]'::jsonb,
    '[]'::jsonb
  ),
  (
    'acvim-proteinuria-caes-gatos-2005',
    'Avaliação e manejo da proteinúria em cães e gatos',
    'Consenso histórico ACVIM sobre detecção, confirmação, localização e monitorização da proteinúria em cães e gatos.',
    'ACVIM',
    2005,
    'nefrologia-urologia',
    'both',
    'external/acvim-proteinuria-caes-gatos-2005',
    'https://pubmed.ncbi.nlm.nih.gov/15954557/',
    true,
    '["doenca-renal-cronica-caes-gatos"]'::jsonb,
    '["benazepril"]'::jsonb
  )
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  organization = excluded.organization,
  year = excluded.year,
  category = excluded.category,
  species = excluded.species,
  file_path = excluded.file_path,
  file_url = excluded.file_url,
  is_published = excluded.is_published,
  related_disease_slugs = excluded.related_disease_slugs,
  related_medication_slugs = excluded.related_medication_slugs;
