-- Coleção cardiológica do ConsultaVet.
-- O consenso de hipertensão sistêmica já foi cadastrado pela coleção endócrina
-- e é reutilizado, sem duplicação, como documento cardiológico vigente.

insert into public.consensus_documents (
  slug,
  title,
  description,
  organization,
  year,
  category,
  species,
  file_path,
  file_url,
  is_published,
  related_disease_slugs,
  related_medication_slugs
)
values
  (
    'acvim-mmvd-canina-2019',
    'Doença valvar mitral mixomatosa canina',
    'Consenso ACVIM 2019 para diagnóstico, estadiamento A–D e tratamento da doença valvar mitral mixomatosa em cães.',
    'ACVIM',
    2019,
    'cardiologia',
    'dog',
    'external/acvim-mmvd-canina-2019',
    'https://academic.oup.com/jvim/article/33/3/1127/8448111',
    true,
    '["doenca-valvar-mitral-degenerativa-caes"]'::jsonb,
    '["pimobendan","benazepril"]'::jsonb
  ),
  (
    'acvim-cardiomiopatias-felinas-2020',
    'Cardiomiopatias felinas',
    'Consenso ACVIM 2020 para classificação fenotípica, diagnóstico, estadiamento e manejo das cardiomiopatias em gatos.',
    'ACVIM',
    2020,
    'cardiologia',
    'cat',
    'external/acvim-cardiomiopatias-felinas-2020',
    'https://academic.oup.com/jvim/article/34/3/1062/8448248',
    true,
    '["cardiomiopatia-hipertrofica-caes-gatos","cardiomiopatia-restritiva-felina","cardiomiopatia-dilatada-caes-gatos"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'acvim-hipertensao-pulmonar-canina-2020',
    'Hipertensão pulmonar em cães',
    'Consenso ACVIM 2020 para probabilidade ecocardiográfica, classificação etiológica, tratamento e monitorização da hipertensão pulmonar canina.',
    'ACVIM',
    2020,
    'cardiologia',
    'dog',
    'external/acvim-hipertensao-pulmonar-canina-2020',
    'https://academic.oup.com/jvim/article/34/2/549/8448421',
    true,
    '[]'::jsonb,
    '[]'::jsonb
  ),
  (
    'esvc-dcm-canina-2003',
    'Diagnóstico da cardiomiopatia dilatada canina',
    'Documento fundador da ESVC para diagnóstico da cardiomiopatia dilatada idiopática canina e identificação da fase pré-clínica.',
    'ESVC',
    2003,
    'cardiologia',
    'dog',
    'external/esvc-dcm-canina-2003',
    'https://www.esvcardio.org/disease-guidelines.pml',
    true,
    '["cardiomiopatia-dilatada-caes-gatos"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'esvc-dcm-dobermann-2017',
    'Rastreamento de DCM em Dobermann',
    'Guideline ESVC específico para rastreamento longitudinal da fase oculta da cardiomiopatia dilatada em Dobermann.',
    'ESVC',
    2017,
    'cardiologia',
    'dog',
    'external/esvc-dcm-dobermann-2017',
    'https://livrepository.liverpool.ac.uk/3020158/',
    true,
    '["cardiomiopatia-dilatada-caes-gatos"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'dcm-screening-caes-2022',
    'Rastreamento de cardiomiopatia dilatada em cães',
    'Revisão prática de 2022 que atualiza métodos e recomendações de rastreamento de DCM em raças caninas predispostas.',
    'Journal of Veterinary Cardiology',
    2022,
    'cardiologia',
    'dog',
    'external/dcm-screening-caes-2022',
    'https://doi.org/10.1016/j.jvc.2021.09.004',
    true,
    '["cardiomiopatia-dilatada-caes-gatos"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'curative-risco-trombotico-2022',
    'CURATIVE — populações sob risco de trombose',
    'Atualização CURATIVE 2022 para classificar populações e intervenções associadas a risco trombótico em cães e gatos.',
    'ACVECC CURATIVE',
    2022,
    'cardiologia',
    'both',
    'external/curative-risco-trombotico-2022',
    'https://escholarship.org/uc/item/0ss8j8dd',
    true,
    '["cardiomiopatia-hipertrofica-caes-gatos","cardiomiopatia-restritiva-felina"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'curative-antitromboticos-2019',
    'CURATIVE — protocolos antitrombóticos',
    'Consenso CURATIVE 2019 sobre escolha e protocolos de antiplaquetários e anticoagulantes em cães e gatos sob risco de trombose.',
    'ACVECC CURATIVE',
    2019,
    'cardiologia',
    'both',
    'external/curative-antitromboticos-2019',
    'https://doi.org/10.1111/vec.12795',
    true,
    '["cardiomiopatia-hipertrofica-caes-gatos","cardiomiopatia-restritiva-felina"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'consenso-cardiorrenal-2015',
    'Distúrbios do eixo cardiovascular–renal',
    'Consenso veterinário sobre definição, classificação, diagnóstico e manejo das interações entre sistema cardiovascular e rins em cães e gatos.',
    'CRS Consensus Group',
    2015,
    'cardiologia',
    'both',
    'external/consenso-cardiorrenal-2015',
    'https://onlinelibrary.wiley.com/doi/10.1111/jsap.12387',
    true,
    '["doenca-renal-cronica","hipertensao-arterial-sistemica-caes-gatos","doenca-valvar-mitral-degenerativa-caes"]'::jsonb,
    '["benazepril"]'::jsonb
  ),
  (
    'acvim-valvular-canina-2009',
    'Doença valvar crônica canina',
    'Consenso histórico ACVIM 2009 sobre doença valvar crônica canina, preservado para rastreabilidade e substituído pelo ACVIM 2019.',
    'ACVIM',
    2009,
    'cardiologia',
    'dog',
    'external/acvim-valvular-canina-2009',
    'https://doi.org/10.1111/j.1939-1676.2009.0392.x',
    true,
    '["doenca-valvar-mitral-degenerativa-caes"]'::jsonb,
    '[]'::jsonb
  )
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  organization = excluded.organization,
  year = excluded.year,
  category = excluded.category,
  species = excluded.species,
  file_path = excluded.file_path,
  file_url = excluded.file_url,
  is_published = excluded.is_published,
  related_disease_slugs = excluded.related_disease_slugs,
  related_medication_slugs = excluded.related_medication_slugs;
