-- Coleção endócrina do ConsultaVet.
-- Metadados e fontes primárias; os detalhes clínicos possuem fallback editorial
-- versionado no app até serem personalizados no painel editorial.

insert into public.consensus_documents (
  slug,
  title,
  description,
  organization,
  year,
  category,
  species,
  file_path,
  file_url,
  is_published,
  related_disease_slugs,
  related_medication_slugs
)
values
  (
    'aaha-diabetes-felino-2026',
    'Diabetes mellitus felino',
    'Guideline AAHA 2026 para diagnóstico, seleção entre insulina e inibidor de SGLT2, monitorização, remissão e manejo de CAD euglicêmica em gatos.',
    'AAHA',
    2026,
    'endocrinologia',
    'cat',
    'external/aaha-diabetes-felino-2026',
    'https://www.aaha.org/resources/2026-aaha-diabetes-management-guidelines-for-cats/',
    true,
    '["diabetes-mellitus-felina"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'icatcare-diabetes-felino-2025',
    'Diabetes mellitus felino — casos simples e complexos',
    'Consenso iCatCare 2025 aprofundado sobre fisiopatologia, insulinorresistência, hipersomatotropismo, tratamento, monitorização, remissão e recaída do diabetes felino.',
    'iCatCare',
    2025,
    'endocrinologia',
    'cat',
    'external/icatcare-diabetes-felino-2025',
    'https://doi.org/10.1177/1098612X251399103',
    true,
    '["diabetes-mellitus-felina"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'aaha-endocrinopatias-caes-gatos-2023',
    'Endocrinopatias selecionadas de cães e gatos',
    'Guideline AAHA 2023 com algoritmos para hipotireoidismo, hipercortisolismo e hipoadrenocorticismo caninos e hipertireoidismo felino, além de endocrinopatias felinas menos comuns.',
    'AAHA',
    2023,
    'endocrinologia',
    'both',
    'external/aaha-selected-endocrinopathies-2023.pdf',
    'https://www.aaha.org/wp-content/uploads/globalassets/02-guidelines/2023-aaha-selected-endocrinopathies-of-dogs-and-cats-guidelines/resources/aaha-selected-endocrinopathies-of-dogs-and-cats-guidelines.pdf',
    true,
    '["hipotireoidismo-adquirido-caes-gatos","hipotireoidismo-congenito-caes-gatos","sindrome-cushing-caes","sindrome-cushing-gatos","hipoadrenocorticismo-addison","hipertireoidismo-felino"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'aaha-diabetes-caes-gatos-2018-2022',
    'Diabetes mellitus em cães e gatos',
    'Guideline AAHA 2018 atualizado em 2022, ainda central para diabetes canino e mantido como referência histórica/complementar para gatos.',
    'AAHA',
    2022,
    'endocrinologia',
    'both',
    'external/2018-aaha-diabetes-management-guidelines-2022-update.pdf',
    'https://www.aaha.org/wp-content/uploads/globalassets/02-guidelines/diabetes/2018-aaha-diabetes-management-guidelines-2022-update.pdf',
    true,
    '["diabetes-mellitus-canina","diabetes-mellitus-felina"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'aafp-hipertireoidismo-felino-2016',
    'Hipertireoidismo felino',
    'Guideline AAFP 2016 que classifica gatos suspeitos em seis grupos clínico-laboratoriais e compara as modalidades terapêuticas.',
    'AAFP / FelineVMA',
    2016,
    'endocrinologia',
    'cat',
    'external/aafp-hipertireoidismo-felino-2016',
    'https://doi.org/10.1177/1098612X16643252',
    true,
    '["hipertireoidismo-felino"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'acvim-hipercortisolismo-canino-2012',
    'Diagnóstico do hipercortisolismo canino espontâneo',
    'Consenso ACVIM focado na indicação e interpretação dos testes para hipercortisolismo canino espontâneo e na diferenciação de origem após confirmação.',
    'ACVIM',
    2012,
    'endocrinologia',
    'dog',
    'external/acvim-hipercortisolismo-canino-2012',
    'https://doi.org/10.1111/jvim.12192',
    true,
    '["sindrome-cushing-caes","sindrome-cushing-gatos"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'alive-diabetes-cycle-1-2022',
    'ALIVE Cycle 1 — terminologia do diabetes mellitus',
    'Consenso ALIVE Cycle 1 que padroniza definições, critérios diagnósticos e caracterização do diabetes mellitus em cães e gatos.',
    'ESVE / SCE',
    2022,
    'endocrinologia',
    'both',
    'external/alive-diabetes-cycle-1-2022',
    'https://doi.org/10.1016/j.tvjl.2022.105910',
    true,
    '["diabetes-mellitus-canina","diabetes-mellitus-felina"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'alive-adrenais-cycle-2-2025',
    'ALIVE Cycle 2 — Cushing e hipoadrenocorticismo',
    'Consenso ALIVE Cycle 2 que padroniza 35 conceitos de síndrome de Cushing, hipercortisolismo, hipoadrenocorticismo e crise adrenal.',
    'ESVE / SCE',
    2025,
    'endocrinologia',
    'both',
    'external/alive-adrenais-cycle-2-2025',
    'https://doi.org/10.3390/vetsci12080761',
    true,
    '["sindrome-cushing-caes","sindrome-cushing-gatos","hipoadrenocorticismo-addison"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'alive-tireoide-cycle-3-2026',
    'ALIVE Cycle 3 — tireoide, cetose/CAD e remissão',
    'Consenso ALIVE Cycle 3 com 78 definições tireoidianas e atualizações para cetose diabética, CAD, CAD euglicêmica e remissão.',
    'ESVE / SCE',
    2026,
    'endocrinologia',
    'both',
    'external/alive-tireoide-cycle-3-2026',
    'https://doi.org/10.3390/vetsci13010035',
    true,
    '["hipotireoidismo-adquirido-caes-gatos","hipotireoidismo-congenito-caes-gatos","hipertireoidismo-felino","diabetes-mellitus-canina","diabetes-mellitus-felina"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'hipertensao-sistemica',
    'Hipertensão sistêmica em cães e gatos',
    'Consenso ACVIM 2018 para mensuração, classificação de risco, pesquisa de lesão em órgão-alvo e manejo da hipertensão em cães e gatos.',
    'ACVIM',
    2018,
    'cardiologia',
    'both',
    'external/acvim-hipertensao-sistemica-2018',
    'https://doi.org/10.1111/jvim.15331',
    true,
    '["hipertensao-arterial-sistemica-caes-gatos","hipertireoidismo-felino","sindrome-cushing-caes","sindrome-cushing-gatos"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'isfm-diabetes-felino-2015',
    'Manejo prático do diabetes mellitus felino',
    'Consenso histórico ISFM 2015 sobre manejo prático do diabetes felino, preservado para rastreabilidade e não como primeira referência terapêutica.',
    'ISFM / iCatCare',
    2015,
    'endocrinologia',
    'cat',
    'external/isfm-diabetes-felino-2015',
    'https://doi.org/10.1177/1098612X15571880',
    true,
    '["diabetes-mellitus-felina"]'::jsonb,
    '[]'::jsonb
  )
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  organization = excluded.organization,
  year = excluded.year,
  category = excluded.category,
  species = excluded.species,
  file_path = excluded.file_path,
  file_url = excluded.file_url,
  is_published = excluded.is_published,
  related_disease_slugs = excluded.related_disease_slugs,
  related_medication_slugs = excluded.related_medication_slugs;
