insert into public.consulta_vet_medications (
  category_id,
  slug,
  title,
  active_ingredient,
  trade_names,
  pharmacologic_class,
  species,
  tags,
  mechanism_of_action,
  indications,
  contraindications,
  cautions,
  adverse_effects,
  interactions,
  routes,
  doses,
  presentations,
  clinical_notes_rich_text,
  admin_notes_text,
  "references",
  is_published
)
values (
  (select id from public.consulta_vet_categories where slug = 'neurologia'),
  'pregabalina',
  'Pregabalina',
  'Pregabalina',
  array['Lyrica', 'Genericos']::text[],
  'Anticonvulsivante / modulador de dor neuropatica',
  array['dog', 'cat']::text[],
  array['Neuropatica', 'Ansiolise', 'Anticonvulsivante', 'VO']::text[],
  'Liga-se a subunidade alfa-2-delta de canais de calcio voltagem-dependentes, reduzindo liberacao de neurotransmissores excitatorios e modulando dor neuropatica e excitabilidade neuronal.',
  array['Dor neuropatica em caes.', 'Adjuvante anticonvulsivante em caes selecionados.', 'Ansiolise pre-transporte em gatos.']::text[],
  array['Hipersensibilidade conhecida ao farmaco.', 'Uso sem ajuste clinico em paciente com sedacao excessiva relevante.']::text[],
  array['Titulacao e desmame devem ser graduais em uso continuo.', 'Monitorar sedacao, ataxia e resposta funcional nos primeiros dias.', 'Separar claramente regimes de dose unica e manutencao.']::text[],
  array['Sedacao.', 'Ataxia.', 'Hiporexia ou desconforto gastrointestinal leve em alguns pacientes.']::text[],
  array['Pode potencializar sedacao com opioides, gabapentinoides ou outros depressores do SNC.']::text[],
  array['VO']::text[],
  '[{"id":"dose-pregabalina-dog-neuropatica","species":"dog","indication":"Dor neuropatica em caes","doseMin":2,"doseMax":4,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q8-12h","duration":"Conforme resposta clinica","notes":"Regime de manutencao. Reavaliar sedacao e conforto nas primeiras 72 horas.","calculatorEnabled":true},{"id":"dose-pregabalina-dog-anticonvulsivante","species":"dog","indication":"Adjuvante anticonvulsivante em caes","doseMin":3,"doseMax":4,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q8-12h","duration":"Uso continuo com reavaliacao periodica","notes":"Nao misturar com protocolo de dose unica.","calculatorEnabled":true},{"id":"dose-pregabalina-cat-transporte","species":"cat","indication":"Ansiolise pre-transporte em gatos","doseMin":4,"doseMax":4,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"dose unica","duration":"Administrar 90 min antes do transporte","notes":"Entrada separada para evitar fusao com regimes de manutencao.","calculatorEnabled":true}]'::jsonb,
  '[{"id":"pres-pregabalina-solucao-20","label":"Solucao oral 20 mg/mL","form":"Solucao oral","concentrationValue":20,"concentrationUnit":"mg/mL","route":"VO","packInfo":"Frasco"},{"id":"pres-pregabalina-caps-25","label":"Capsula 25 mg","form":"Capsula","concentrationValue":25,"concentrationUnit":"mg/capsula","route":"VO","packInfo":"Blister"},{"id":"pres-pregabalina-caps-50","label":"Capsula 50 mg","form":"Capsula","concentrationValue":50,"concentrationUnit":"mg/capsula","route":"VO","packInfo":"Blister"},{"id":"pres-pregabalina-caps-75","label":"Capsula 75 mg","form":"Capsula","concentrationValue":75,"concentrationUnit":"mg/capsula","route":"VO","packInfo":"Blister"},{"id":"pres-pregabalina-caps-100","label":"Capsula 100 mg","form":"Capsula","concentrationValue":100,"concentrationUnit":"mg/capsula","route":"VO","packInfo":"Blister"}]'::jsonb,
  '<p>Na pratica, a pregabalina exige regime clinico bem delimitado. Ansiolise pre-transporte em gatos nao deve ser fundida com protocolos de manutencao para dor neuropatica ou uso anticonvulsivante em caes.</p><p>Quando a apresentacao escolhida nao permite conversao segura para comprimidos ou capsulas, mantenha a decisao em mg e ajuste a apresentacao no editorial.</p>',
  'Caso de teste da sprint: doses separadas por especie, regimes separados por indicacao e apresentacoes individuais para calculo.',
  '[{"citationText":"Plumb''s Veterinary Drugs. Pregabalin.","sourceType":"Livro","url":"","notes":"Base para posologia clinica e cautelas de uso veterinario."},{"citationText":"Gruen ME et al. Use of pregabalin in veterinary patients.","sourceType":"Artigo","url":"","notes":"Contexto de dor neuropatica e sedacao em pequenos animais."}]'::jsonb,
  true
)
on conflict (slug) do update set
  category_id = excluded.category_id,
  title = excluded.title,
  active_ingredient = excluded.active_ingredient,
  trade_names = excluded.trade_names,
  pharmacologic_class = excluded.pharmacologic_class,
  species = excluded.species,
  tags = excluded.tags,
  mechanism_of_action = excluded.mechanism_of_action,
  indications = excluded.indications,
  contraindications = excluded.contraindications,
  cautions = excluded.cautions,
  adverse_effects = excluded.adverse_effects,
  interactions = excluded.interactions,
  routes = excluded.routes,
  doses = excluded.doses,
  presentations = excluded.presentations,
  clinical_notes_rich_text = excluded.clinical_notes_rich_text,
  admin_notes_text = excluded.admin_notes_text,
  "references" = excluded."references",
  is_published = excluded.is_published;
