insert into public.consulta_vet_categories (slug, title, description, sort_order, is_published)
values
  ('odontologia', 'Odontologia', 'Infecções orais, periodontais e suporte odontológico.', 65, true),
  ('oftalmologia', 'Oftalmologia', 'Produtos e condutas para afecções oculares.', 75, true),
  ('dermatologia', 'Dermatologia', 'Pele, ouvido externo e anexos.', 80, true),
  ('gastroenterologia', 'Gastroenterologia', 'Trato gastrointestinal, fígado, pâncreas e enteropatógenos.', 90, true),
  ('infectologia', 'Infectologia', 'Doenças infecciosas, antimicrobianos e stewardship em pequenos animais.', 10, true)
on conflict (slug) do update
set
  title = excluded.title,
  description = excluded.description,
  is_published = true,
  updated_at = now();

with records as (
  select *
  from jsonb_to_recordset($records$
[
  {
    "category_slug": "infectologia",
    "slug": "clinbacter",
    "title": "Clinbacter",
    "active_ingredient": "Cloridrato de clindamicina",
    "trade_names": ["Clinbacter 75 mg", "Clinbacter 150 mg"],
    "pharmacologic_class": "Lincosamida",
    "species": ["dog", "cat"],
    "tags": ["clindamicina", "lincosamida", "oral", "abscessos", "anaeróbios"],
    "mechanism_of_action": "Lincosamida que inibe a síntese proteica bacteriana por ligação à subunidade 50S, com boa penetração em tecidos moles, cavidade oral, abscessos e alguns focos ósseos.",
    "indications": ["Infecções orais/periodontais, feridas profundas, abscessos, tecidos moles e anaeróbios sensíveis.", "Pode ser considerada em osteomielite e alguns protocolos para toxoplasmose/neosporose conforme diagnóstico."],
    "contraindications": ["Hipersensibilidade a lincosamidas.", "Evitar associação com macrolídeos ou cloranfenicol por antagonismo potencial."],
    "cautions": ["Em gatos, administrar comprimido com água/alimento para reduzir risco de esofagite.", "Cautela em hepatopatia ou nefropatia grave; não substitui drenagem, limpeza periodontal ou controle do foco."],
    "adverse_effects": ["Vômito, diarreia, hiporexia, salivação, colite e reação de hipersensibilidade."],
    "interactions": ["Não associar rotineiramente a macrolídeos ou cloranfenicol.", "Pode potencializar bloqueadores neuromusculares."],
    "routes": ["VO"],
    "doses": [{"id":"clinbacter-both-label-10-q12","species":"both","indication":"Infecções orais, tecidos moles e anaeróbios sensíveis","doseMin":10,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q12h","duration":"Conforme foco e reavaliação.","notes":"Dose de bula Clinbacter; literatura também cita 5,5 mg/kg q12h ou 11 mg/kg q24h em alguns cenários.","calculatorEnabled":true},{"id":"clinbacter-both-plumbs-55-q12","species":"both","indication":"Faixa de literatura clínica para infecções sensíveis","doseMin":5.5,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q12h","duration":"Conforme foco.","notes":"Resumo Plumb's/BSAVA informado no anexo.","calculatorEnabled":true}],
    "presentations": [{"id":"clinbacter-75","label":"Clinbacter 75 mg","form":"comprimido palatável bissulcado","concentrationValue":75,"concentrationUnit":"mg","packInfo":"cartucho com 14 comprimidos","route":"VO","scoringInfo":"bissulcado; fracionar conforme bula","channel":"veterinary"},{"id":"clinbacter-150","label":"Clinbacter 150 mg","form":"comprimido palatável bissulcado","concentrationValue":150,"concentrationUnit":"mg","packInfo":"cartucho com 14 comprimidos","route":"VO","scoringInfo":"bissulcado; fracionar conforme bula","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Clindamicina é útil para anaeróbios, boca, abscessos e tecidos moles, mas antibiótico não substitui drenagem, limpeza periodontal, extração dentária ou controle de foco. Em felinos, evitar comprimido seco.</p>",
    "references": [{"citationText":"Agener União. Clinbacter.","sourceType":"site oficial","url":"https://agener.com.br/produtos/pequenos-animais/antimicrobianos-pt/clinbacter/","notes":"Página oficial com fórmula, espécies, dose e apresentações."},{"citationText":"Agener União. Bula Clinbacter.","sourceType":"bula","url":"https://agener.com.br/wp-content/uploads/2020/05/4020676-Clinbacter-1.pdf","notes":"Bula do produto."},{"citationText":"Plumb's Veterinary Drug Handbook / BSAVA. Dose de clindamicina.","sourceType":"dose Plumb/literatura","url":null,"notes":"Resumo do anexo: 5,5 mg/kg q12h ou 11 mg/kg q24h; infecção grave até 11 mg/kg q12h."}],
    "official_site_url": "https://agener.com.br/produtos/pequenos-animais/antimicrobianos-pt/clinbacter/",
    "leaflet_url": "https://agener.com.br/wp-content/uploads/2020/05/4020676-Clinbacter-1.pdf",
    "image_url": "https://agener.com.br/wp-content/uploads/2020/05/clinbacter_foto.png"
  },
  {
    "category_slug": "odontologia",
    "slug": "oralguard-clindamicina",
    "title": "Oralguard",
    "active_ingredient": "Clindamicina",
    "trade_names": ["Oralguard 50 mg", "Oralguard 150 mg"],
    "pharmacologic_class": "Lincosamida",
    "species": ["dog", "cat"],
    "tags": ["clindamicina", "odontologia", "osteomielite", "abscessos", "anaeróbios"],
    "mechanism_of_action": "Clindamicina inibe a síntese proteica bacteriana na subunidade 50S e alcança boa concentração em tecidos moles, ossos e cavidade oral.",
    "indications": ["Infecções dentárias, osteomielites, feridas profundas e abscessos por bactérias aeróbicas e anaeróbicas sensíveis."],
    "contraindications": ["Hipersensibilidade a lincosamidas.", "Não associar sem critério a macrolídeos ou cloranfenicol."],
    "cautions": ["Antibiótico odontológico não substitui tratamento periodontal mecânico/cirúrgico.", "Em gatos, orientar água/alimento após comprimido."],
    "adverse_effects": ["Vômito, diarreia, hiporexia e irritação esofágica se comprimido seco em gatos."],
    "interactions": ["Macrolídeos/cloranfenicol podem antagonizar ação em 50S.", "Cautela com bloqueadores neuromusculares."],
    "routes": ["VO"],
    "doses": [{"id":"oralguard-dog-dental-5-q12","species":"dog","indication":"Infecções dentárias/tecidos moles em cães","doseMin":5,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q12h","duration":"7-14 dias conforme bula e controle do foco.","notes":"Para osteomielite, bula cita 10 mg/kg q12h por período prolongado.","calculatorEnabled":true},{"id":"oralguard-cat-dental-10-20-q24","species":"cat","indication":"Infecções dentárias, feridas e abscessos em gatos","doseMin":10,"doseMax":20,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q24h","duration":"Máximo 14 dias conforme bula localizada.","notes":"Usar Oralguard 50 mg; administrar com água/alimento.","calculatorEnabled":true}],
    "presentations": [{"id":"oralguard-50","label":"Oralguard 50 mg","form":"comprimido","concentrationValue":50,"concentrationUnit":"mg","packInfo":"blister com 14 comprimidos","route":"VO","scoringInfo":"fracionar conforme bula","channel":"veterinary"},{"id":"oralguard-150","label":"Oralguard 150 mg","form":"comprimido","concentrationValue":150,"concentrationUnit":"mg","packInfo":"blister com 14 comprimidos","route":"VO","scoringInfo":"fracionar conforme bula","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Fármaco útil em odontologia, mas o app deve reforçar que antibiótico não resolve cálculo dentário, bolsa periodontal, raiz comprometida ou abscesso sem manejo local.</p>",
    "references": [{"citationText":"CEPAV. Oralguard.","sourceType":"site oficial","url":"https://cepav.com.br/produtos/oralguard/","notes":"Página oficial com descrição, indicações e apresentações."},{"citationText":"CEPAV. Bula Oralguard 50 mg.","sourceType":"bula","url":"https://cepav.com.br/wp-content/uploads/2018/03/ORALGUARD-50-MG-logonovo12_20180222_SGF_1127.pdf","notes":"Bula do produto."},{"citationText":"Plumb's Veterinary Drug Handbook / BSAVA. Dose de clindamicina.","sourceType":"dose Plumb/literatura","url":null,"notes":"Resumo do anexo: 5,5 mg/kg q12h ou 11 mg/kg q24h; grave até 11 mg/kg q12h."}],
    "official_site_url": "https://cepav.com.br/produtos/oralguard/",
    "leaflet_url": "https://cepav.com.br/wp-content/uploads/2018/03/ORALGUARD-50-MG-logonovo12_20180222_SGF_1127.pdf",
    "image_url": "https://cepav.com.br/wp-content/uploads/2021/02/Oralguard-e1615841063653.png"
  },
  {
    "category_slug": "odontologia",
    "slug": "stomorgyl",
    "title": "Stomorgyl",
    "active_ingredient": "Espiramicina + metronidazol",
    "trade_names": ["Stomorgyl 2", "Stomorgyl 10", "Stomorgyl 20"],
    "pharmacologic_class": "Macrolídeo + nitroimidazol",
    "species": ["dog", "cat"],
    "tags": ["odontologia", "metronidazol", "anaeróbios", "periodontal"],
    "mechanism_of_action": "Associação de espiramicina, macrolídeo com ação em síntese proteica, e metronidazol, nitroimidazol ativo contra anaeróbios e protozoários.",
    "indications": ["Estomatites, gengivites, glossites, periodontites e piorreias quando há indicação antimicrobiana."],
    "contraindications": ["Hipersensibilidade a macrolídeos ou nitroimidazóis."],
    "cautions": ["Não substitui profilaxia odontológica, radiografia, extração, drenagem ou tratamento da causa periodontal.", "Cautela neurológica/hepática por metronidazol."],
    "adverse_effects": ["Vômito, diarreia, hiporexia, salivação e sinais neurológicos em dose alta/uso prolongado de metronidazol."],
    "interactions": ["Cautela com fármacos que prolongam QT ou reduzem limiar convulsivo.", "Metronidazol pode interagir com anticoagulantes cumarínicos."],
    "routes": ["VO"],
    "doses": [{"id":"stomorgyl-both-label-q24","species":"both","indication":"Afecções bucodentárias sensíveis","doseMin":12.5,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q24h","duration":"5-10 dias; manter 48 h após melhora conforme bula.","notes":"Dose em mg/kg de metronidazol, associada a 75.000 UI/kg de espiramicina. Equivalência prática: Stomorgyl 2 = 1 drágea/2 kg; 10 = 1/10 kg; 20 = 1/20 kg.","calculatorEnabled":true}],
    "presentations": [{"id":"stomorgyl-2","label":"Stomorgyl 2","form":"drágea","concentrationValue":2,"concentrationUnit":"kg por drágea","packInfo":"equivalência 1 drágea/2 kg","route":"VO","scoringInfo":"não converter como mg simples sem conferir bula","channel":"veterinary"},{"id":"stomorgyl-10","label":"Stomorgyl 10","form":"drágea","concentrationValue":10,"concentrationUnit":"kg por drágea","packInfo":"equivalência 1 drágea/10 kg","route":"VO","scoringInfo":"não converter como mg simples sem conferir bula","channel":"veterinary"},{"id":"stomorgyl-20","label":"Stomorgyl 20","form":"drágea","concentrationValue":20,"concentrationUnit":"kg por drágea","packInfo":"equivalência 1 drágea/20 kg","route":"VO","scoringInfo":"não converter como mg simples sem conferir bula","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Cadastro odontológico: usar quando há foco oral/periodontal compatível. A apresentação usa equivalência por peso; a calculadora não deve inventar conversão em mg quando a composição por drágea não estiver modelada.</p>",
    "references": [{"citationText":"Boehringer Ingelheim Brasil. Stomorgyl.","sourceType":"site oficial","url":"https://www.boehringer-ingelheim.com/br/saude-animal/produtos/stomorgyl-1","notes":"Página oficial do produto."},{"citationText":"Bula Stomorgyl.","sourceType":"bula","url":"https://uploads.consultaremedios.com.br/drug_leaflet/Bula-Stomorgyl-Paciente-Consulta-Remedios.pdf","notes":"Bula consultável publicamente."},{"citationText":"DGAMV. Stomorgyl 10 RCM.","sourceType":"bula técnica","url":"https://medvet.dgav.pt/medvet_dgav/static/RCM/Stomorgyl_10%2C_750_000.pdf","notes":"Referência técnica com equivalência por peso."}],
    "official_site_url": "https://www.boehringer-ingelheim.com/br/saude-animal/produtos/stomorgyl-1",
    "leaflet_url": "https://uploads.consultaremedios.com.br/drug_leaflet/Bula-Stomorgyl-Paciente-Consulta-Remedios.pdf",
    "image_url": "https://cdn.awsli.com.br/800x800/1999/1999267/produto/114740848/3dcc2181f7.jpg"
  },
  {
    "category_slug": "gastroenterologia",
    "slug": "giardicid",
    "title": "Giardicid",
    "active_ingredient": "Metronidazol + sulfadimetoxina",
    "trade_names": ["Giardicid suspensão", "Giardicid 50", "Giardicid 500"],
    "pharmacologic_class": "Nitroimidazol + sulfonamida",
    "species": ["dog", "cat"],
    "tags": ["giardíase", "coccidiose", "metronidazol", "sulfa", "protozoários"],
    "mechanism_of_action": "Associação de metronidazol, ativo contra anaeróbios/protozoários, e sulfadimetoxina, sulfonamida que interfere na via do folato.",
    "indications": ["Giardíase, coccidiose, tricomoníase, amebíase e infecções entéricas por microrganismos sensíveis."],
    "contraindications": ["Hipersensibilidade a nitroimidazóis ou sulfonamidas."],
    "cautions": ["Não usar automaticamente para toda diarreia.", "Cautela em hepatopatia, pacientes neurológicos, filhotes jovens e uso prolongado."],
    "adverse_effects": ["Vômito, anorexia, diarreia, letargia, ataxia, tremores, nistagmo, cristalúria e reações idiossincráticas de sulfas."],
    "interactions": ["Cautela com fármacos hepatotóxicos, anticoagulantes e outros neurotóxicos."],
    "routes": ["VO"],
    "doses": [{"id":"giardicid-both-125-25-q12","species":"both","indication":"Giardíase/protozoários conforme diagnóstico","doseMin":12.5,"doseMax":25,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q12h","duration":"5 dias conforme bula/fonte.","notes":"Dose por ativo em comprimidos. Suspensão exige cálculo próprio por mL conforme apresentação.","calculatorEnabled":true}],
    "presentations": [{"id":"giardicid-susp","label":"Giardicid suspensão","form":"suspensão oral","concentrationValue":50,"concentrationUnit":"mg/mL de cada ativo","packInfo":"50 mL; 50 mg/mL metronidazol + 50 mg/mL sulfadimetoxina","route":"VO","scoringInfo":"calcular em mL conforme bula","channel":"veterinary"},{"id":"giardicid-50","label":"Giardicid 50","form":"comprimido","concentrationValue":50,"concentrationUnit":"mg","packInfo":"comprimidos","route":"VO","scoringInfo":"conferir composição antes de fracionar","channel":"veterinary"},{"id":"giardicid-500","label":"Giardicid 500","form":"comprimido","concentrationValue":500,"concentrationUnit":"mg","packInfo":"comprimidos","route":"VO","scoringInfo":"atenção a animais pequenos","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Giardicid não é antidiarreico genérico. Use com diagnóstico, coproparasitológico/antígeno quando possível e controle ambiental. Metronidazol em dose alta/prolongada exige alerta neurológico.</p>",
    "references": [{"citationText":"CEPAV. Giardicid.","sourceType":"site oficial","url":"https://cepav.com.br/produtos/giardicid/","notes":"Página oficial com composição da suspensão e indicações."},{"citationText":"CEPAV. Bula Giardicid.","sourceType":"bula","url":"https://cepav.com.br/wp-content/uploads/2017/07/GIARDICID.pdf","notes":"Bula do produto."},{"citationText":"Plumb's Veterinary Drug Handbook / literatura. Dose de metronidazol.","sourceType":"dose Plumb/literatura","url":null,"notes":"Resumo do anexo: metronidazol 10–15 mg/kg VO q8–12h; evitar uso indiscriminado."}],
    "official_site_url": "https://cepav.com.br/produtos/giardicid/",
    "leaflet_url": "https://cepav.com.br/wp-content/uploads/2017/07/GIARDICID.pdf",
    "image_url": "https://images.tcdn.com.br/img/img_prod/1087789/giardicid_suspensao_50ml_71_2_13642f5a6f1b02fa5d45a5edbdf77bbf.jpg"
  },
  {
    "category_slug": "infectologia",
    "slug": "doxitrat",
    "title": "Doxitrat",
    "active_ingredient": "Hiclato de doxiciclina",
    "trade_names": ["Doxitrat 50 mg", "Doxitrat 80 mg", "Doxitrat 200 mg"],
    "pharmacologic_class": "Tetraciclina bacteriostática",
    "species": ["dog", "cat"],
    "tags": ["doxiciclina", "rickettsioses", "doença do carrapato", "gatos"],
    "mechanism_of_action": "Tetraciclina que inibe síntese proteica bacteriana por ação na subunidade 30S, útil contra agentes intracelulares e transmitidos por vetores.",
    "indications": ["Rickettsioses, doença do carrapato, infecções respiratórias, geniturinárias, tecidos moles e agentes sensíveis à doxiciclina."],
    "contraindications": ["Hipersensibilidade a tetraciclinas."],
    "cautions": ["Em gatos, administrar com água/alimento após o comprimido.", "Separar de sucralfato, ferro, zinco, cálcio, magnésio e alumínio."],
    "adverse_effects": ["Vômito, diarreia, náusea, esofagite/estenose em gatos se comprimido seco."],
    "interactions": ["Cátions, antiácidos e sucralfato reduzem absorção."],
    "routes": ["VO"],
    "doses": [{"id":"doxitrat-both-5-q12","species":"both","indication":"Infecções sensíveis à doxiciclina","doseMin":5,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q12h","duration":"Conforme foco.","notes":"Regime de literatura e bula por equivalência de apresentação.","calculatorEnabled":true},{"id":"doxitrat-both-10-q24","species":"both","indication":"Regime SID para infecções sensíveis","doseMin":10,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q24h","duration":"Conforme foco.","notes":"Em gatos, administrar com água/alimento.","calculatorEnabled":true}],
    "presentations": [{"id":"doxitrat-50","label":"Doxitrat 50 mg","form":"comprimido","concentrationValue":50,"concentrationUnit":"mg","packInfo":"comprimidos","route":"VO","scoringInfo":"1 cp/5 kg q24h ou 1 cp/10 kg q12h conforme bula","channel":"veterinary"},{"id":"doxitrat-80","label":"Doxitrat 80 mg","form":"comprimido","concentrationValue":80,"concentrationUnit":"mg","packInfo":"comprimidos","route":"VO","scoringInfo":"1 cp/8 kg q24h ou 1 cp/16 kg q12h conforme bula","channel":"veterinary"},{"id":"doxitrat-200","label":"Doxitrat 200 mg","form":"comprimido","concentrationValue":200,"concentrationUnit":"mg","packInfo":"comprimidos","route":"VO","scoringInfo":"1 cp/20 kg q24h ou 1 cp/40 kg q12h conforme bula","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Mesmo cuidado de outras doxiciclinas: não administrar comprimido seco em gatos e separar de quelantes. Evitar regimes confusos; cada protocolo deve ficar em linha própria.</p>",
    "references": [{"citationText":"Agener União. Doxitrat.","sourceType":"site oficial","url":"https://agener.com.br/produtos/pequenos-animais/antimicrobianos-pt/doxitrat/","notes":"Página oficial com apresentações e equivalências de dose."},{"citationText":"Agener União. Bula Doxitrat 80/200 mg.","sourceType":"bula","url":"https://agener.com.br/wp-content/uploads/2020/01/BU-DOXITRAT-80MG-E-200MG.pdf","notes":"Bula do produto."},{"citationText":"Plumb's Veterinary Drug Handbook. Dose de doxiciclina.","sourceType":"dose Plumb/literatura","url":null,"notes":"Resumo do anexo: 5 mg/kg q12h ou 10 mg/kg q24h."}],
    "official_site_url": "https://agener.com.br/produtos/pequenos-animais/antimicrobianos-pt/doxitrat/",
    "leaflet_url": "https://agener.com.br/wp-content/uploads/2020/01/BU-DOXITRAT-80MG-E-200MG.pdf",
    "image_url": "https://agener.com.br/wp-content/uploads/2020/01/novo-doxi-1-3.jpg"
  },
  {
    "category_slug": "infectologia",
    "slug": "zelotril",
    "title": "Zelotril",
    "active_ingredient": "Enrofloxacina",
    "trade_names": ["Zelotril 50 mg", "Zelotril 150 mg"],
    "pharmacologic_class": "Fluoroquinolona",
    "species": ["dog", "cat"],
    "tags": ["enrofloxacina", "fluoroquinolona", "gatos", "stewardship"],
    "mechanism_of_action": "Fluoroquinolona bactericida concentração-dependente por inibição de DNA girase/topoisomerase.",
    "indications": ["Infecções resistentes/complicadas, piodermites Gram-negativas, prostatite, pielonefrite/ITU complicada guiada por cultura."],
    "contraindications": ["Hipersensibilidade a fluoroquinolonas.", "Evitar em animais em crescimento quando risco articular for relevante."],
    "cautions": ["Gatos: não exceder 5 mg/kg/dia.", "Reservar para uso criterioso; cautela em epilepsia, tremores e doença neurológica."],
    "adverse_effects": ["Gastrointestinais, neurológicos, artropatia em crescimento e retinopatia felina em doses altas."],
    "interactions": ["Cátions e sucralfato reduzem absorção."],
    "routes": ["VO"],
    "doses": [{"id":"zelotril-dog-5-20-q24","species":"dog","indication":"Infecções sensíveis justificadas em cães","doseMin":5,"doseMax":20,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q24h","duration":"Conforme foco/cultura.","notes":"Bula Zelotril: 50 mg = 1 cp/10 kg q24h; 150 mg = 1 cp/30 kg q24h.","calculatorEnabled":true},{"id":"zelotril-cat-5-q24","species":"cat","indication":"Infecções sensíveis justificadas em gatos","doseMin":5,"doseUnit":"mg","perWeightUnit":"kg","route":"VO","frequency":"q24h","duration":"Conforme foco; não exceder dose diária.","notes":"Não exceder 5 mg/kg/dia em gatos.","calculatorEnabled":true}],
    "presentations": [{"id":"zelotril-50","label":"Zelotril 50 mg","form":"comprimido","concentrationValue":50,"concentrationUnit":"mg","packInfo":"comprimidos","route":"VO","scoringInfo":"1 cp/10 kg na dose de bula","channel":"veterinary"},{"id":"zelotril-150","label":"Zelotril 150 mg","form":"comprimido","concentrationValue":150,"concentrationUnit":"mg","packInfo":"comprimidos","route":"VO","scoringInfo":"1 cp/30 kg na dose de bula","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Fluoroquinolona reservada. O registro separa cão e gato para impedir extrapolação insegura, especialmente porque gatos têm limite máximo diário.</p>",
    "references": [{"citationText":"Agener União. Zelotril.","sourceType":"site oficial","url":"https://agener.com.br/produtos/pequenos-animais/antimicrobianos-pt/zelotril/","notes":"Página oficial com apresentações e posologia."},{"citationText":"Agener União. Bula Zelotril 50 mg.","sourceType":"bula","url":"https://agener.com.br/wp-content/uploads/2020/03/4007874-Zelotril-50-mg.pdf","notes":"Bula do produto."},{"citationText":"Plumb's Veterinary Drug Handbook. Dose de enrofloxacina.","sourceType":"dose Plumb/literatura","url":null,"notes":"Resumo do anexo: cães 5–20 mg/kg q24h; gatos 5 mg/kg q24h, não exceder."}],
    "official_site_url": "https://agener.com.br/produtos/pequenos-animais/antimicrobianos-pt/zelotril/",
    "leaflet_url": "https://agener.com.br/wp-content/uploads/2020/03/4007874-Zelotril-50-mg.pdf",
    "image_url": "https://agener.com.br/wp-content/uploads/2020/01/img_pet_antimicrobianos_zelotril.jpg"
  },
  {
    "category_slug": "oftalmologia",
    "slug": "tobrasyn",
    "title": "Tobrasyn",
    "active_ingredient": "Sulfato de tobramicina 0,3%",
    "trade_names": ["Tobrasyn colírio"],
    "pharmacologic_class": "Aminoglicosídeo oftálmico",
    "species": ["dog", "cat"],
    "tags": ["oftálmico", "tobramicina", "colírio", "aminoglicosídeo"],
    "mechanism_of_action": "Aminoglicosídeo bactericida que se liga de forma irreversível à subunidade 30S bacteriana, interrompendo síntese proteica.",
    "indications": ["Infecções oculares bacterianas em cães e gatos por microrganismos sensíveis à tobramicina."],
    "contraindications": ["Hipersensibilidade a aminoglicosídeos."],
    "cautions": ["Não usar olho doloroso sem exame oftálmico/fluoresceína.", "Úlcera profunda, corpo estranho ou perfuração exigem avaliação imediata."],
    "adverse_effects": ["Irritação ocular, hiperemia, desconforto local e hipersensibilidade."],
    "interactions": [],
    "routes": ["Oftálmica"],
    "doses": [{"id":"tobrasyn-both-eye-1drop","species":"both","indication":"Infecção ocular superficial sensível","doseMin":1,"doseUnit":"gota","perWeightUnit":"olho afetado","route":"Oftálmica","frequency":"4-6x/dia","duration":"Conforme gravidade e reavaliação oftálmica.","notes":"Casos graves podem exigir frequência maior sob monitoramento; não calcular por kg.","calculatorEnabled":false}],
    "presentations": [{"id":"tobrasyn-5ml","label":"Tobrasyn colírio 5 mL","form":"solução oftálmica","concentrationValue":3,"concentrationUnit":"mg/mL","packInfo":"frasco conta-gotas 5 mL","route":"Oftálmica","scoringInfo":"não se aplica","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Cadastro oftálmico, não antibiótico sistêmico. Dor ocular, blefaroespasmo, úlcera profunda ou secreção purulenta exigem exame e reavaliação rápida.</p>",
    "references": [{"citationText":"Syntec. Tobrasyn.","sourceType":"site oficial","url":"https://syntec.com.br/produtos/tobrasyn-tobramicina-syntec","notes":"Página oficial com descrição, espécies e concentração."},{"citationText":"Syntec. Bula Tobrasyn.","sourceType":"bula","url":"https://syntec.com.br/storage/produtos/bulas/bula-site-tobrasyn-v5pdf-1506943621.pdf","notes":"Bula do produto."},{"citationText":"Plumb's Veterinary Drug Handbook. Tobramicina oftálmica.","sourceType":"dose Plumb/literatura","url":null,"notes":"Resumo local: 1 gota 4–6x/dia, ajustando por gravidade."}],
    "official_site_url": "https://syntec.com.br/produtos/tobrasyn-tobramicina-syntec",
    "leaflet_url": "https://syntec.com.br/storage/produtos/bulas/bula-site-tobrasyn-v5pdf-1506943621.pdf",
    "image_url": "https://syntec.com.br/storage/produtos/Tobrasyn-5-mL-15-53-26.webp"
  },
  {
    "category_slug": "dermatologia",
    "slug": "auritop",
    "title": "Auritop",
    "active_ingredient": "Ciprofloxacina + cetoconazol + fluocinolona + lidocaína",
    "trade_names": ["Auritop"],
    "pharmacologic_class": "Otológico com quinolona tópica, antifúngico, corticoide e anestésico",
    "species": ["dog", "cat"],
    "tags": ["otite", "ciprofloxacina", "cetoconazol", "corticoide", "otológico"],
    "mechanism_of_action": "Associação tópica otológica com quinolona antibacteriana, azólico antifúngico, corticoide anti-inflamatório e anestésico local.",
    "indications": ["Otites agudas ou crônicas por bactérias/fungos sensíveis em cães e gatos."],
    "contraindications": ["Não usar se suspeita de ruptura timpânica sem avaliação.", "Hipersensibilidade aos componentes."],
    "cautions": ["Exigir otoscopia/citologia sempre que possível.", "Não usar se otite média/interna, head tilt, nistagmo, dor intensa ou perda auditiva sem avaliação."],
    "adverse_effects": ["Irritação local, desconforto, hipersensibilidade e potenciais efeitos de corticoide tópico."],
    "interactions": [],
    "routes": ["Otológica"],
    "doses": [{"id":"auritop-dog-small","species":"dog","indication":"Otite externa - cão <15 kg","doseMin":4,"doseUnit":"gotas","perWeightUnit":"ouvido afetado","route":"Otológica","frequency":"q12h","duration":"7-10 dias","notes":"Cães >15 kg: 8 gotas q12h.","calculatorEnabled":false},{"id":"auritop-cat","species":"cat","indication":"Otite externa - gato","doseMin":3,"doseUnit":"gotas","perWeightUnit":"ouvido afetado","route":"Otológica","frequency":"q12h","duration":"7-10 dias","notes":"Usar somente com avaliação otológica.","calculatorEnabled":false}],
    "presentations": [{"id":"auritop-15g","label":"Auritop","form":"solução/gel otológico","concentrationValue":15,"concentrationUnit":"g","packInfo":"frasco/bisnaga 15 g","route":"Otológica","scoringInfo":"não se aplica","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Produto otológico. Não usar como atalho sem citologia/otoscopia, principalmente em otite crônica, bastonetes, dor intensa ou tímpano incerto.</p>",
    "references": [{"citationText":"Ourofino Pet. Auritop.","sourceType":"site oficial","url":"https://www.ourofinopet.com/produtos/medicamentos/auritop/","notes":"Página oficial do produto."},{"citationText":"Ourofino. Bula Auritop.","sourceType":"bula","url":"https://products-info-public.s3-sa-east-1.amazonaws.com/bulas/ouro-fino/AURITOP_BULA.pdf","notes":"Bula do produto."}],
    "official_site_url": "https://www.ourofinopet.com/produtos/medicamentos/auritop/",
    "leaflet_url": "https://products-info-public.s3-sa-east-1.amazonaws.com/bulas/ouro-fino/AURITOP_BULA.pdf",
    "image_url": "https://www.ourofinopet.com/media/uploads/produtos/apresentacao/2024/20240614085709_eVJhBYz.png"
  },
  {
    "category_slug": "dermatologia",
    "slug": "aurigen",
    "title": "Aurigen",
    "active_ingredient": "Gentamicina + miconazol + betametasona",
    "trade_names": ["Aurigen"],
    "pharmacologic_class": "Otológico com aminoglicosídeo, antifúngico e corticoide",
    "species": ["dog"],
    "tags": ["otite", "gentamicina", "miconazol", "cães", "otológico"],
    "mechanism_of_action": "Associação de gentamicina antibacteriana, miconazol antifúngico e betametasona anti-inflamatória para uso otológico.",
    "indications": ["Otites agudas ou crônicas por bactérias e/ou fungos em cães."],
    "contraindications": ["Não usar em gatos.", "Não usar se suspeita de ruptura timpânica sem avaliação."],
    "cautions": ["Somente cães.", "Exigir tímpano íntegro; gentamicina tem risco oto/vestibular se ouvido médio for exposto."],
    "adverse_effects": ["Irritação local, hipersensibilidade e eventos ototóxicos se usado com tímpano comprometido."],
    "interactions": [],
    "routes": ["Otológica"],
    "doses": [{"id":"aurigen-dog-small","species":"dog","indication":"Otite externa - cão até 15 kg","doseMin":4,"doseUnit":"gotas","perWeightUnit":"ouvido afetado","route":"Otológica","frequency":"q12h","duration":"7-9 dias","notes":"Cães >=15 kg: 8 gotas q12h.","calculatorEnabled":false}],
    "presentations": [{"id":"aurigen-15g","label":"Aurigen","form":"pomada/solução otológica","concentrationValue":15,"concentrationUnit":"g","packInfo":"bisnaga 15 g com cânula","route":"Otológica","scoringInfo":"não se aplica","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Aurigen é registro otológico canino. Não cadastrar para gatos sem indicação oficial. Sempre avaliar tímpano, dor, sinais vestibulares e citologia.</p>",
    "references": [{"citationText":"Ourofino Pet. Aurigen.","sourceType":"site oficial","url":"https://www.ourofinopet.com/produtos/medicamentos/aurigen/","notes":"Página oficial do produto."},{"citationText":"Ourofino. Bula Aurigen.","sourceType":"bula","url":"https://ourofino.com/wp-content/uploads/2024/07/BUL_50006472_0724_OF00_AURIGEN-VD-1.pdf","notes":"Bula do produto."}],
    "official_site_url": "https://www.ourofinopet.com/produtos/medicamentos/aurigen/",
    "leaflet_url": "https://ourofino.com/wp-content/uploads/2024/07/BUL_50006472_0724_OF00_AURIGEN-VD-1.pdf",
    "image_url": "https://www.ourofinopet.com/media/uploads/produtos/apresentacao/2023/20231025164726.png"
  },
  {
    "category_slug": "dermatologia",
    "slug": "otomax",
    "title": "Otomax",
    "active_ingredient": "Gentamicina + clotrimazol + betametasona",
    "trade_names": ["Otomax"],
    "pharmacologic_class": "Otológico com aminoglicosídeo, antifúngico e corticoide",
    "species": ["dog"],
    "tags": ["otite", "gentamicina", "clotrimazol", "cães", "otológico"],
    "mechanism_of_action": "Associação otológica de gentamicina, clotrimazol e betametasona para bactérias/fungos sensíveis e inflamação do conduto.",
    "indications": ["Otite externa aguda e crônica de cães por fungos e bactérias sensíveis."],
    "contraindications": ["Não usar em gatos.", "Não usar se suspeita de ruptura timpânica sem avaliação."],
    "cautions": ["Somente cães.", "Exigir tímpano íntegro; avaliar sinais vestibulares, dor intensa e perda auditiva."],
    "adverse_effects": ["Irritação local, hipersensibilidade e risco de ototoxicidade se ouvido médio estiver exposto."],
    "interactions": [],
    "routes": ["Otológica"],
    "doses": [{"id":"otomax-dog-small","species":"dog","indication":"Otite externa - cão <15 kg","doseMin":4,"doseUnit":"gotas","perWeightUnit":"ouvido afetado","route":"Otológica","frequency":"q12h","duration":"7 dias","notes":"Cães >=15 kg: 8 gotas q12h.","calculatorEnabled":false}],
    "presentations": [{"id":"otomax-otic","label":"Otomax","form":"produto otológico","concentrationValue":15,"concentrationUnit":"g","packInfo":"12,5 g/14 mL ou 15 g conforme fornecedor","route":"Otológica","scoringInfo":"não se aplica","channel":"veterinary"}],
    "clinical_notes_rich_text": "<p>Otomax é otológico canino. Não usar em gatos. Evitar repetição empírica em otite recorrente sem citologia/cultura e avaliação da membrana timpânica.</p>",
    "references": [{"citationText":"MSD Saúde Animal Brasil. Otomax.","sourceType":"site oficial","url":"https://www.msd-saude-animal.com.br/produto/otomax/","notes":"Página oficial do produto."},{"citationText":"Vetsmart. Otomax.","sourceType":"fonte técnica","url":"https://vetsmart.com.br/cg/produto/149/otomax","notes":"Fonte técnica complementar quando bula PDF oficial não foi localizada no anexo."}],
    "official_site_url": "https://www.msd-saude-animal.com.br/produto/otomax/",
    "leaflet_url": "https://vetsmart.com.br/cg/produto/149/otomax",
    "image_url": "https://www.msd-saude-animal.com.br/wp-content/uploads/sites/55/2020/07/otomax-e1594207637831.png"
  }
]$records$::jsonb) as r(
    category_slug text,
    slug text,
    title text,
    active_ingredient text,
    trade_names jsonb,
    pharmacologic_class text,
    species jsonb,
    tags jsonb,
    mechanism_of_action text,
    indications jsonb,
    contraindications jsonb,
    cautions jsonb,
    adverse_effects jsonb,
    interactions jsonb,
    routes jsonb,
    doses jsonb,
    presentations jsonb,
    clinical_notes_rich_text text,
    "references" jsonb,
    official_site_url text,
    leaflet_url text,
    image_url text
  )
)
insert into public.consulta_vet_medications (
  category_id,
  slug,
  title,
  active_ingredient,
  trade_names,
  pharmacologic_class,
  species,
  tags,
  mechanism_of_action,
  indications,
  contraindications,
  cautions,
  adverse_effects,
  interactions,
  routes,
  doses,
  presentations,
  clinical_notes_rich_text,
  admin_notes_text,
  "references",
  official_site_url,
  leaflet_url,
  image_url,
  is_published
)
select
  c.id,
  r.slug,
  r.title,
  r.active_ingredient,
  array(select jsonb_array_elements_text(r.trade_names)),
  r.pharmacologic_class,
  array(select jsonb_array_elements_text(r.species)),
  array(select jsonb_array_elements_text(r.tags)),
  r.mechanism_of_action,
  array(select jsonb_array_elements_text(r.indications)),
  array(select jsonb_array_elements_text(r.contraindications)),
  array(select jsonb_array_elements_text(r.cautions)),
  array(select jsonb_array_elements_text(r.adverse_effects)),
  array(select jsonb_array_elements_text(r.interactions)),
  array(select jsonb_array_elements_text(r.routes)),
  r.doses,
  r.presentations,
  r.clinical_notes_rich_text,
  'Seed editorial de antibióticos comerciais BR - lote 2. Produtos sem imagem/bula/site seguros no anexo não foram importados automaticamente.',
  r."references",
  r.official_site_url,
  r.leaflet_url,
  r.image_url,
  true
from records r
join public.consulta_vet_categories c on c.slug = r.category_slug
on conflict (slug) do update
set
  category_id = excluded.category_id,
  title = excluded.title,
  active_ingredient = excluded.active_ingredient,
  trade_names = excluded.trade_names,
  pharmacologic_class = excluded.pharmacologic_class,
  species = excluded.species,
  tags = excluded.tags,
  mechanism_of_action = excluded.mechanism_of_action,
  indications = excluded.indications,
  contraindications = excluded.contraindications,
  cautions = excluded.cautions,
  adverse_effects = excluded.adverse_effects,
  interactions = excluded.interactions,
  routes = excluded.routes,
  doses = excluded.doses,
  presentations = excluded.presentations,
  clinical_notes_rich_text = excluded.clinical_notes_rich_text,
  admin_notes_text = excluded.admin_notes_text,
  "references" = excluded."references",
  official_site_url = excluded.official_site_url,
  leaflet_url = excluded.leaflet_url,
  image_url = excluded.image_url,
  is_published = true,
  updated_at = now();
