import { Drug } from '../../shared/types/drug';

export const dexmedetomidine: Drug = {
  id: 'dexmedetomidine',
  namePt: 'Dexmedetomidina',
  nameEn: 'Dexmedetomidine',
  synonyms: [
    'Dexdomitor',
    'Dexmedesed',
    'Dexmedetomidine hydrochloride',
    'Alpha-2 agonist',
    'Agonista alfa-2',
  ],
  category: 'sedativos_tranquilizantes',
  pharmacologicalClass: 'Agonista Alfa-2 Adrenérgico Altamente Seletivo',
  clinicalSummary:
    'Agonista alfa-2 potente com efeitos sedativos, ansiolíticos, miorrelaxantes e analgésicos adjuvantes. Essencial para sedação procedimental, premedicação e controle de disforia/emergence delirium. Requer monitorização cardiovascular rigorosa devido ao impacto no débito cardíaco.',
  physiology:
    'Atua em receptores alfa-2 centrais e periféricos. Causa vasoconstrição periférica inicial (aumento de PA) seguido de bradicardia reflexa e simpatólise central. Reduz drasticamente a liberação de noradrenalina, levando a sedação profunda e estabilização do plano anestésico.',
  indications: [
    'Sedação procedimental e contenção química',
    'Pré-medicação anestésica',
    'Sedação perioperatória e "rouseable sedation"',
    'Analgesia adjuvante multimodal (ex: DMLK)',
    'Manejo de disforia e excitação na emergência anestésica',
    'Sedação em pacientes ventilados mecanicamente',
  ],
  contraindications: [
    'Cardiopatias (especialmente insuficiência cardíaca e arritmias)',
    'Choque, hipovolemia ou instabilidade hemodinâmica severa',
    'Bradicardia pré-existente significante',
    'Doença respiratória severa em gatos',
    'Insuficiência hepática ou renal relevante',
    'Diabetes Mellitus (causa hiperglicemia transitória)',
    'Obstrução urinária (devido ao efeito diurético)',
    'Gestação',
  ],
  supportedSpecies: ['dog', 'cat'],
  allowedRegimes: ['CRI', 'bolus', 'bolus_maintenance'],
  highAlert: true,
  advantages: [
    'Sedação de excelente qualidade e previsibilidade',
    'Totalmente reversível com atipamezol',
    'Forte efeito poupador de inalatórios (MAC-sparing)',
    'Excelente para ajuste fino de recuperação anestésica (microdose)',
    'Analgesia adjuvante real por cerca de 1h com dose de 5 mcg/kg',
  ],
  limitations: [
    'Forte impacto cardiovascular (redução de até 50% do débito cardíaco)',
    'Vômito muito comum, especialmente em gatos',
    'Pode causar despertar súbito com estímulos sonoros/táteis',
    'Causa diurese e pode alterar a glicemia',
    'Não deve ser o analgésico único em dor severa',
  ],
  commonProblems: [
    'Bradicardia reflexa confundida com bradicardia patológica (evitar tratar com atropina se a PA estiver alta)',
    'Uso em animais em choque, agravando a má perfusão periférica',
  ],
  usageErrors: [
    'Administrar bolus IV rápido (aumenta risco de vômito e arritmias)',
    'Não lubrificar os olhos de gatos sedados (redução do reflexo de piscar)',
    'Usar em pacientes com obstrução uretral sem monitorização da diurese',
  ],
  doses: {
    dog: {
      min: 0.25,
      max: 3,
      unit: 'mcg/kg/h',
      observations: 'UTI/Sedação rousable: 0.25-1 mcg/kg/h. Intra-op: 1-3 mcg/kg/h.',
    },
    cat: {
      min: 0.25,
      max: 2,
      unit: 'mcg/kg/h',
      observations: 'CRI pós-op: 0.5-1 mcg/kg/h. Intra-op: até 2-3 mcg/kg/h.',
    },
  },
  bolusDoses: {
    dog: {
      min: 1,
      max: 10,
      unit: 'mcg/kg',
      observations: 'Premedicação: 2-5 mcg/kg (com opioide). Disforia: 0.25-1 mcg/kg IV.',
    },
    cat: {
      min: 5,
      max: 40,
      unit: 'mcg/kg',
      observations: 'Sedação leve: 5-15. Moderada: 20-30. Profunda: 40 mcg/kg IM.',
    },
  },
  preferredUnit: 'mcg/kg/h',
  allowedUnits: ['mcg/kg/h', 'mcg/kg', 'mcg/m2', 'mcg/m2/h'],
  presentations: [
    {
      id: 'dexmedetomidine_0_5mgml_10ml',
      description: 'Dexmedetomidina 0,5 mg/mL (500 mcg/mL) – 10 mL',
      concentration: 500,
      concentrationUnit: 'mcg/mL',
      volume: 10,
    },
    {
      id: 'dexmedetomidine_100mcgml_2ml',
      description: 'Cloridrato de Dexmedetomidina 100 mcg/mL – 2 mL',
      concentration: 100,
      concentrationUnit: 'mcg/mL',
      volume: 2,
    },
    {
      id: 'dexmedetomidine_gel_0_1mgml',
      description: 'Dexmedetomidina Gel Oromucosal 0,1 mg/mL (Apenas Cão)',
      concentration: 100,
      concentrationUnit: 'mcg/mL',
      volume: 3,
    },
  ],
  safetyMetadata: {
    preferredDiluent: 'NaCl 0.9%',
    allowedDiluents: ['NaCl 0.9%', 'Ringer Lactato'],
    notRecommendedDiluents: [],
    centralAccessRequired: false,
    centralAccessPreferred: false,
    peripheralAllowed: true,
    syringePumpRequired: true,
    dedicatedLineRequired: false,
    photosensitive: false,
    stabilityAfterDilution: '24 horas em temperatura ambiente.',
    incompatibilities: ['Anfotericina B', 'Diazepam', 'Soluções alcalinas'],
    recommendedMonitoring: ['ECG contínuo (avaliação de BAV)', 'PA não invasiva', 'Temperatura', 'Oximetria'],
  },
  alerts: [
    {
      id: 'v-dex-cardio',
      condition: (p) => p.comorbidities.includes('cardiopath') || p.comorbidities.includes('shock') || p.comorbidities.includes('hypovolemia'),
      message: 'ALERTA CRÍTICO: Contraindicado em cardiopatas, choque ou hipovolemia. Alto risco de queda fatal no débito cardíaco.',
      level: 'danger',
    },
    {
      id: 'v-dex-vomit',
      condition: (p) => p.comorbidities.includes('respiratory_disease') || p.comorbidities.includes('urinary_obstruction'),
      message: 'A dexmedetomidina causa vômito frequentemente. Evite se houver risco de aspiração ou em obstruções uretrais (aumenta diurese).',
      level: 'warning',
    },
    {
      id: 'v-dex-antichol',
      condition: () => true,
      message: 'NÃO use anticolinérgicos (atropina) para tratar a bradicardia reflexa se a PA estiver normal/alta. Risco de hipertensão severa.',
      level: 'warning',
    },
    {
      id: 'v-dex-cat-resp',
      condition: (p) => p.species === 'cat' && p.comorbidities.includes('respiratory_disease'),
      message: 'Gatos com doença respiratória: Risco raro de edema pulmonar agudo. Use apenas se essencial e com monitorização estreita.',
      level: 'danger',
    },
    {
      id: 'v-dex-glucose',
      condition: (p) => p.comorbidities.includes('endocrinopath'),
      message: 'Atenção em Diabéticos: Reduz secreção de insulina e pode causar hiperglicemia transitória.',
      level: 'warning',
    },
    {
      id: 'v-dex-eye',
      condition: (p) => p.species === 'cat',
      message: 'Lembre-se de lubrificar os olhos: o reflexo de piscar é reduzido significativamente durante a sedação.',
      level: 'info',
    },
    {
      id: 'v-dex-bsa',
      condition: (_p, _d, unit) => unit.includes('m2'),
      message: 'Dose em BSA (m2): O app calcula automaticamente com base no peso. Verifique se a dose em mcg/m2 condiz com o rótulo.',
      level: 'info',
    },
    {
      id: 'v-dex-rescue',
      condition: () => true,
      message: 'Se precisar de múltiplos bolus para disforia, migre para CRI (0.25-1 mcg/kg/h) para maior estabilidade.',
      level: 'warning',
    },
  ],
  adverseEffects: ['Bradicardia reflexa', 'Bloqueios AV', 'Hipertensão inicial', 'Hipotensão tardia', 'Vômito', 'Hiperglicemia', 'Diurese'],
  detailedInfo: {
    mechanismOfAction: 'Agonista alfa-2 seletivo. Atua no locus coeruleus (SNC) e nervos periféricos.',
    metabolism: 'Hepático (glicuronidação e oxidação).',
    excretion: 'Urinária (metabólitos).',
    onsetOfAction: '3-5 min (IV), 10-15 min (IM).',
    durationOfAction: 'Dose dependente (1-3h bolus). Analgesia adjuvante dura ~1h.',
    speciesDifferences: 'Gatos são mais propensos a vômito e respondem bem a doses em mcg/kg. Cães usam dose em BSA oficial.',
    administrationGuidelines: 'Bolus IV sempre lento. Utilize pré-diluição para pacientes pequenos para facilitar a titulação.',
    maximumUsageTime: 'Pode ser usada em CRI prolongada, mas requer desmame gradual se usada por dias.',
    extraClinicalNotes: [
      'MACETE PRÉ-DILUIÇÃO: 1 mL (500mcg) + 9 mL SF = 50 mcg/mL. Facilita muito o preparo de microdoses.',
      'O atipamezole reverte integralmente a sedação E a analgesia. Esteja pronto para tratar a dor com outros agentes.',
      'Em animais muito agitados/estressados, o teto de eficácia cai devido à alta descarga de catecolaminas endógenas.',
    ],
  },
  references: [
    "Plumb's Veterinary Drug Handbook, 10th ed. monografia Dexmedetomidine",
    'BSAVA Small Animal Formulary, 10th ed.',
    'Textbook of Small Animal Emergency Medicine, pp. 240, 1245',
    'BSAVA Manual of ECC, capítulos de sedação e analgesia.',
  ],
  doseGuides: [
    {
      id: 'dex-sed-std',
      regimen: 'bolus',
      title: 'Sedação / Premedicação',
      indication: 'Pacientes hígidos (ASA I/II)',
      doseText: '2 – 5 mcg/kg IV ou IM (combinada com opioide)',
      rationale: 'Sedação segura e reversível para procedimentos.',
    },
    {
      id: 'dex-cri-ana',
      regimen: 'CRI',
      title: 'Analgesia / Sedação Pós-op',
      indication: 'Manejo hospitalar e UTI',
      doseText: '0.5 – 1.5 mcg/kg/h',
      rationale: 'Estabiliza o plano analgésico e permite "rouseable sedation".',
    },
    {
      id: 'dex-dysphoria',
      regimen: 'bolus',
      title: 'Microdose para Disforia',
      indication: 'Recovery agitado / Emergence excitement',
      doseText: '0.25 – 0.5 mcg/kg IV lento',
      rationale: 'Recuperação anestésica suave sem prolongar demais a sedação.',
    },
    {
      id: 'dex-dmlk',
      regimen: 'CRI',
      title: 'Protocolo DMLK',
      indication: 'Dor crítica intensiva',
      doseText: '0.5 mcg/kg/h (Dex) + ...',
      rationale: 'Adjuvante em protocolo multimodal de alta performance.',
    },
  ],
  diluentGuidance: [
    {
      id: 'dex-dil-50',
      title: 'Pré-diluição 50 mcg/mL',
      recommendation: '1 mL estoque (500 mcg) + 9 mL diluente.',
      rationale: 'Fundamental para pacientes < 10kg ou doses em CRI muito baixas.',
      tone: 'success',
    },
    {
      id: 'dex-dil-10',
      title: 'Pré-diluição 10 mcg/mL',
      recommendation: '1 mL estoque (500 mcg) + 49 mL diluente ou 0.2 mL estoque + 9.8 mL diluente.',
      rationale: 'Ideal para titulação milimétrica em gatos e neonatos.',
      tone: 'info',
    },
  ],
};
