import { Drug } from '../../shared/types/drug';

export const ketamine: Drug = {
  id: 'ketamine',
  namePt: 'Cetamina',
  nameEn: 'Ketamine',
  synonyms: [
    'Ketamina',
    'Ketamine hydrochloride',
    'Ketamine HCl',
    'Anestésico dissociativo',
    'Antagonista NMDA',
  ],
  category: 'anestesicos_analgesicos',
  pharmacologicalClass: 'Anestésico dissociativo / Antagonista NMDA',
  clinicalSummary:
    'Anestésico dissociativo com papel fundamental como analgésico adjuvante, agindo via bloqueio de receptores NMDA para reduzir a sensibilização central e o fenômeno de wind-up. É extremamente útil em protocolos multimodais (como MLK/FLK) para dor inflamatória, visceral e neuropática.',
  physiology:
    'Bloqueia receptores NMDA no corno dorsal da medula, combatendo a amplificação medular da dor. Interage com sistemas opioides e monoaminérgicos. Em doses analgésicas subanestésicas, modula a percepção de dor sem causar dissociação profunda. Pode causar estímulo simpático (aumento de FC e PA) em animais hígidos, mas pode causar depressão cardiovascular em pacientes críticos exauridos de catecolaminas.',
  indications: [
    'Analgesia adjuvante perioperatória',
    'Prevenção e tratamento de sensibilização central e wind-up',
    'Dor inflamatória (ex: pancreatite)',
    'Protocolos multimodais (MLK/FLK/DMLK)',
    'Redução da necessidade de opioides e anestésicos inalatórios (MAC-sparing)',
    'Dor neuropática ou refratária',
  ],
  contraindications: [
    'Não usar como analgésico isolado para dor moderada a severa',
    'Glaucoma ou risco de perfuração ocular (aumenta PIO)',
    'Pressão intracraniana (PIC) elevada não controlada',
    'Hipertensão severa ou aneurismas',
    'Cardiomiopatia hipertrófica obstrutiva',
    'Hipertireoidismo não controlado',
    'Epilepsia ou histórico de convulsões (cautela)',
    'Insuficiência hepática ou renal severa (eliminação renal importante em gatos)',
  ],
  supportedSpecies: ['dog', 'cat'],
  allowedRegimes: ['CRI', 'bolus', 'bolus_maintenance'],
  highAlert: true,
  advantages: [
    'Excelente modulador de dor e anti-wind-up',
    'Efeito poupador de opioides e inalatórios',
    'Preserva reflexos protetores e função respiratória em doses baixas',
    'Muito útil em dor visceral inflamatória (pancreatite)',
    'Custo acessível e ampla disponibilidade',
  ],
  limitations: [
    'Efeito analgésico inconsistente se usada isoladamente',
    'Pode causar disforia e recuperação agitada',
    'Provoca hipersalivação e hipertonia muscular em doses mais altas',
    'Acúmulo em infusões prolongadas (especialmente em gatos)',
    'Exige monitorização rigorosa em cardiopatas',
  ],
  commonProblems: [
    'Confundir mcg/kg/min com mg/kg/h (0.6 mg/kg/h = 10 mcg/kg/min)',
    'Uso como analgésico único em procedimentos muito invasivos',
  ],
  usageErrors: [
    'Preparar soluções muito diluídas com volumes imprecisos',
    'Não realizar o loading antes da CRI, demorando para atingir nível terapêutico',
  ],
  doses: {
    dog: {
      min: 2,
      max: 20,
      unit: 'mcg/kg/min',
      observations: 'Intra-operatório: 10-20 mcg/kg/min. Pós-operatório: 2-10 mcg/kg/min.',
    },
    cat: {
      min: 2,
      max: 20,
      unit: 'mcg/kg/min',
      observations: 'Mesma faixa dos cães. Cautela extra na recuperação e em renais.',
    },
  },
  bolusDoses: {
    dog: {
      min: 0.25,
      max: 0.5,
      unit: 'mg/kg',
      observations: 'Ataque (loading) antes da CRI: 0.25-0.5 mg/kg IV lento.',
    },
    cat: {
      min: 0.25,
      max: 0.5,
      unit: 'mg/kg',
      observations: 'Ataque (loading) antes da CRI: 0.25-0.5 mg/kg IV lento.',
    },
  },
  preferredUnit: 'mcg/kg/min',
  allowedUnits: ['mcg/kg/min', 'mcg/kg/h', 'mg/kg/h'],
  presentations: [
    {
      id: 'ketamine_100mgml_10ml_vet',
      description: 'Cetamina 100 mg/mL – 10 mL (Veterinária)',
      concentration: 100,
      concentrationUnit: 'mg/mL',
      volume: 10,
    },
    {
      id: 'ketamine_50mgml_10ml_human',
      description: 'Cetamina 50 mg/mL – 10 mL (Humana)',
      concentration: 50,
      concentrationUnit: 'mg/mL',
      volume: 10,
    },
    {
      id: 'ketamine_10mgml_20ml_human',
      description: 'Cetamina 10 mg/mL – 20 mL (Humana)',
      concentration: 10,
      concentrationUnit: 'mg/mL',
      volume: 20,
    },
  ],
  safetyMetadata: {
    preferredDiluent: 'NaCl 0.9%',
    allowedDiluents: ['NaCl 0.9%', 'Ringer Lactato', 'Glicose 5%'],
    notRecommendedDiluents: [],
    centralAccessRequired: false,
    centralAccessPreferred: false,
    peripheralAllowed: true,
    syringePumpRequired: false,
    dedicatedLineRequired: false,
    photosensitive: false,
    stabilityAfterDilution: '24 horas em temperatura ambiente, protegida de contaminação.',
    incompatibilities: ['Soluções alcalinas', 'Metais pesados', 'Diazepam (em mistura direta)'],
    recommendedMonitoring: ['FC e ECG', 'Pressão Arterial', 'Nível de sedação/disforia', 'Padrão respiratório'],
  },
  alerts: [
    {
      id: 'v-ket-unit',
      condition: (_p, _d, unit) => unit === 'mg/kg/h' || unit === 'mcg/kg/min',
      message: 'Atenção: 0.6 mg/kg/h equivale a 10 mcg/kg/min. Garanta que a unidade selecionada no app corresponde à sua prescrição.',
      level: 'info',
    },
    {
      id: 'v-ket-sole',
      condition: () => true,
      message: 'Cetamina não deve ser usada como analgésico único. Funciona melhor em abordagem multimodal (opioide/lidocaína).',
      level: 'warning',
    },
    {
      id: 'v-ket-visceral',
      condition: () => true,
      message: 'Analgésico adjuvante para dor visceral (pancreatite). O efeito principal é a modulação NMDA (anti-wind-up).',
      level: 'info',
    },
    {
      id: 'v-ket-cardio',
      condition: (p) => p.comorbidities.includes('cardiopath') || p.comorbidities.includes('hypertension') || p.comorbidities.includes('shock'),
      message: 'Cautela em cardiopatas e hipertensos: pode elevar FC e PA. Em pacientes em choque severo, pode causar depressão miocárdica.',
      level: 'warning',
    },
    {
      id: 'v-ket-ocular',
      condition: () => true,
      message: 'Evite em casos de glaucoma, úlcera profunda ou risco de perfuração ocular devido ao aumento da PIO.',
      level: 'warning',
    },
    {
      id: 'v-ket-dysphoria',
      condition: (_p, d, unit) => (unit === 'mcg/kg/min' && d > 10) || (unit === 'mg/kg/h' && d > 0.6),
      message: 'Doses altas ou uso prolongado aumentam o risco de disforia, vocalização e recuperação errática.',
      level: 'warning',
    },
    {
      id: 'v-ket-cat-renal',
      condition: (p) => p.species === 'cat' && p.comorbidities.includes('renopath'),
      message: 'Gatos renais: a eliminação é majoritariamente renal. Use doses menores e espere recuperação prolongada.',
      level: 'danger',
    },
    {
      id: 'v-ket-rescue-freq',
      condition: () => true,
      message: 'Se o paciente precisa de muitos bolus de resgate, migre para CRI e escalone a terapia multimodal.',
      level: 'warning',
    },
  ],
  adverseEffects: ['Disforia', 'Hipersalivação', 'Hipertonia', 'Taquicardia', 'Hipertensão', 'Recuperação agitada'],
  detailedInfo: {
    mechanismOfAction: 'Antagonista não competitivo de receptores NMDA no corno dorsal medular.',
    metabolism: 'Hepático (N-desmetilação para norketamina).',
    excretion: 'Renal (especialmente importante em gatos).',
    onsetOfAction: '1-5 minutos (IV).',
    durationOfAction: 'Bolus dura 20-30 min para analgesia. Meia-vida curta requer CRI para efeito constante.',
    speciesDifferences: 'Gatos eliminam droga ativa via renal; cães dependem mais do metabolismo hepático.',
    administrationGuidelines: 'Bolus sempre lento IV. Em CRI, utilizar bomba para precisão.',
    maximumUsageTime: 'Pode acumular se usada por >24h, prolongando a recuperação.',
    extraClinicalNotes: [
      'MACETE: 120 mg de cetamina em 1L de cristaloide a 10 mL/kg/h entrega exatamente 10 mcg/kg/min.',
      'A dose de 4 mg/kg IV (com fentanil) é reservada para RESGATE DE ALTA INTENSIDADE, não rotina.',
      'Se houver múltiplos resgates, o problema é a analgesia de base. Reavalie.',
    ],
  },
  references: [
    "Plumb's Veterinary Drug Handbook, 10th ed. pp. 717-721",
    'BSAVA Small Animal Formulary, 10th ed. pp. 217-219',
    'Lumb and Jones Veterinary Anesthesia, 6th ed. p. 1014',
    'Textbook of Small Animal Emergency Medicine, p. 1247',
  ],
  doseGuides: [
    {
      id: 'ket-ana-cri',
      regimen: 'CRI',
      title: 'Analgesia Adjuvante (Wind-up)',
      indication: 'Modulação de dor e poupador de opioide',
      doseText: '2 – 10 mcg/kg/min (0.12 - 0.6 mg/kg/h)',
      rationale: 'Faixa clássica para pós-operatório e dor hospitalar crônica/inflamatória.',
    },
    {
      id: 'ket-intra-cri',
      regimen: 'CRI',
      title: 'Intra-operatório Intenso',
      indication: 'Cirurgias invasivas / Mastectomia / Ortopedia',
      doseText: '10 – 20 mcg/kg/min',
      rationale: 'Dose para bloqueio NMDA profundo em estímulo nociceptivo agudo.',
    },
    {
      id: 'ket-visceral',
      regimen: 'CRI',
      title: 'Pancreatite / Dor Visceral',
      indication: 'Analgesia abdominal inflamatória',
      doseText: '2 – 10 mcg/kg/min (Iniciar com loading 0.25 mg/kg)',
      rationale: 'Útil como adjuvante para preservar motilidade GI e poupar opioide.',
    },
    {
      id: 'ket-rescue-high',
      regimen: 'bolus',
      title: 'Resgate de Alta Intensidade',
      indication: 'Dor emergencial severa (ex: trauma grave)',
      doseText: '4 mg/kg IV bolus (associado a fentanil)',
      rationale: 'Dose agressiva para cenários críticos. Risco de disforia elevado.',
    },
  ],
  diluentGuidance: [
    {
      id: 'ket-std-mix',
      title: 'Mistura Padrão (Fácil)',
      recommendation: 'Adicione 120 mg de Cetamina a 1.000 mL de SF 0.9%.',
      rationale: 'Taxa de 10 mL/kg/h entregará exatamente 10 mcg/kg/min.',
      tone: 'success',
    },
    {
      id: 'ket-mlk-dog',
      title: 'Protocolo MLK (Cães)',
      recommendation: 'Em 500 mL SF: 50mg Morfina + 50mg Cetamina + 500mg Lidocaína (Sem Adr).',
      rationale: 'Taxa: 1-2 mL/kg/h. Analgesia multimodal clássica para dor intensa.',
      tone: 'info',
    },
  ],
};
